Sources/Datadog/DatadogCore/DatadogCore.swift
Sources/Datadog/DatadogCore/Storage/DataBlock.swift
Sources/Datadog/DatadogCore/Storage/Files/File.swift
Sources/Datadog/DatadogCore/Storage/Reading/FileReader.swift
Sources/Datadog/DatadogCore/Upload/FeatureUpload.swift
Tests/DatadogTests/Datadog/Core/Persistence/DataBlockTests.swift

Details in #1091 
This leads me to 3 possibilities:
1) Datadog is generating a huge buffer.
2) Datadog buffers are being leaked somehow (or just need more tight autorelease)
3) Something in my application is using a lot of memory and Datadog is the last straw that is being hit.
NOTE: Just realized we didn't start seeing this until after 1.12.0 upgrade.
Yeah, after digging into the 1.12.0 changes, I'm realizing that a bug causing the first possibility is the most likely. The data is already in memory at this point, and it's just being copied into a buffer. The crash is occurring during that buffer creation. It's likely that the length being provided is incorrect.
I address these:
1) Add a 10MB safety check (elsewhere it looks like file size should be limited to 4MB), currently the only …

Improve DataBlock memory consumption and validation

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/DatadogInternal/Concurrency/Concurrency.swift
Sources/Datadog/DatadogInternal/Concurrency/ReadWriteLock.swift
Sources/Datadog/Logging/RemoteLogger.swift
Sources/Datadog/Tracing/Integrations/TracingWithRUMIntegration.swift
Tests/DatadogTests/Datadog/DatadogInternal/ConcurrencyTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogInternal/DatadogCoreMock.swift
Tests/DatadogTests/Datadog/Mocks/DatadogInternal/PassthroughCoreMock.swift

With the asynchronous aspect of the event write context, logs entries' attributes and tags can become inconsistent. Here an example:
```swift
logger.add(tag: "tag1")
logger.info("info message 1") // This log entry won't include tag1 because the EWC is async
logger.remove(tag: "tag1")
```
We need to capture tags and attributes before opening the EWC.
In this proposal, I replace the remote logger queue with read-write locks around the attributes and tags. Managing the lock is abstracted behind a `@_pthread_rwlock` property-wrapper. The tags and attributes property are captured on the caller thread before jumping on the EWC.
The POSIX lock has been preferred over `DispatchQueue/barrier` as it's slightly faster on read operation.
This issue wasn't catch by unit tests because we rely on the …

RUMM-2795 Fix Logs Tags & Attributes Consistency

---

Tests/DatadogTests/Datadog/Logging/LoggingMessageReceiverTests.swift

🧯 Fixes the nightly tests ran on Xcode 13.4.x, macOS 12.4 (Monterey):
```
❌  /Users/vagrant/git/Tests/DatadogTests/Datadog/Logging/LoggingMessageReceiverTests.swift:252:13: protocol 'Encodable' as a type cannot conform to the protocol itself
try AssertEncodedRepresentationsEqual(received, AnyEncodable(expectedWebLogEvent))
^
```
Xcode 13.4.x is unable to understand `Encodable` value passed as `Encodable` parameter. For that reason, we need to wrap it into new `AnyEncodable`.
Tested on both Xcode `13.4.1` and `14.2` - it works 👍.

Fix tests compilation issue on Xcode 13.x

---

Makefile

Update to version 2.2.0-rc.7 of testing framework
Reenable tvOS testing now that the issues with tvOS are fixed
Changed version and configuration in the Makefile

Update to version 2.2.0-rc.7 of testing framework

---

CHANGELOG.md
Sources/Datadog/DatadogCore/DatadogCore.swift
Sources/Datadog/DatadogCore/Storage/DataBlock.swift
Sources/Datadog/DatadogCore/Storage/Files/File.swift
Sources/Datadog/DatadogCore/Storage/FilesOrchestrator.swift
Sources/Datadog/DatadogCore/Storage/Reading/FileReader.swift
Sources/Datadog/DatadogCore/Storage/Writing/FileWriter.swift
Sources/Datadog/DatadogCore/Upload/FeatureUpload.swift
Tests/DatadogTests/Datadog/Core/Persistence/DataBlockTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Files/FileTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Writing/FileWriterTests.swift
Tests/DatadogTests/Datadog/Logging/LogOutputs/LogFileOutputTests.swift
Tests/DatadogTests/Datadog/RUM/RUMEventOutputs/RUMEventFileOutputTests.swift

Follow up of #1089
Inject object size limit to TLV to protect from 'Could not allocate memory` crash when a TLV gets corrupted.

RUMM-2819 TLV Lenght Limit

---

DatadogSDKSessionReplay.podspec
DatadogSDKSessionReplay.podspec.src
DatadogSessionReplay/README.md
Makefile
dependency-manager-tests/cocoapods/App/ViewController.swift
dependency-manager-tests/cocoapods/Podfile.src

📦 This PR adds `DatadogSDKSessionReplay.podspec` so Session Replay can be installed through Cocoapods.
This is to enable early beta of SR. We will be providing this `.podspec` through separate `session-replay-beta` branch, without yet pushing it to `pod trunk` (we want to keep regular SDK releases separate from SR beta updates).
* added `.podspec`
* updated `dependency-manager-tests/cocoapods` project to run smoke tests for SR installation with Cocoapods

RUMM-2902 [SR] Add `DatadogSDKSessionReplay.podspec`

---

Tests/DatadogBenchmarkTests/BenchmarkMocks.swift

Removes redundant protocol conformance from `DatadogBenchmarkTests`. They are now coming from `TestUtilities`.

Fix develop build issues

---

DatadogSDK.podspec
DatadogSDKAlamofireExtension.podspec
DatadogSDKCrashReporting.podspec
DatadogSDKObjc.podspec
DatadogSDKSessionReplay.podspec
Makefile
Sources/Datadog/Versioning.swift
Tests/DatadogBenchmarkTests/BenchmarkMocks.swift

📦 Prepare Session Replay for private `-beta1`.
This PR targets `session-replay-beta` branch - the one that will be used for shipping updates in private beta. To avoid mistakes in managing this branch, I made it protected on the same rules as `develop`.
Even though it is not necessary, this PR bumps the version in `.podspecs` and `__sdkVersion` in code for versioning clarity:
```diff
- internal let __sdkVersion = "1.14.0"
+ internal let __sdkVersion = "1.14.0-sr-beta1"
```
This will let us distinguish telemetry and data sent from SR private beta.
⚠️ It is expected to run into git conflicts when regular SDK release is made from `develop` branch (and parallel `make bump` is done). However, it will be limited to only version number so its resolution will be easy. I don't think this requires …

RUMM-2902 [SR] Bump version to `1.14.0-sr-beta1`

---

Package.swift
TestUtilities/Package.swift

📦 Fixing the problem revealed in recent nightly tests failure:
```
xcodebuild: error: Could not resolve package dependencies:
package 'testutilities' is using Swift tools version 5.7.0 but the installed version is 5.6.0
```
Following [this post from Apple](https://developer.apple.com/news/?id=2t1chhp3):
> Starting April 25, 2022, iOS, iPadOS, and watchOS apps submitted to the App Store must be built with Xcode 13 (...)
it makes sense to align all our packages with:
```swift
// swift-tools-version: 5.5
```

Align `swift-tools-version` across all packages

---

Sources/Datadog/RUM/Integrations/CrashReportReceiver.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/Utils/RUMViewUpdatesThrottler.swift
Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift
Tests/DatadogTests/Datadog/RUM/Integrations/CrashReportReceiverTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/Utils/RUMViewUpdatesThrottlerTests.swift

Better handle cross-platform crashes to make sure:
- the view events are sent after the error
- the native crash, that is a "duplicate" from the js crash, is not sent as we limit the amount of crashes per view to 1.
Result 🎉:
The event is sent by modifying the `viewEventThrottler` to always accept events when the crash count is 1 - this is my favorite implementation as we keep close to the source of the issue, but I don't know if there will also be side effects if potential events come after that - there should not be so many in any case.
We don't send the duplicate by checking the last view does not contain a crash already.
A nice benefit to this implementation is that if js crash reporting is not enabled but native crash reporting is, we'll get the native crash 👍
If a user adds a crash …

RUMM-2516 Remove React Native duplicate crashes

---

Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift

Use no crash count in view event mock.

Fix RUM Crash Receiver Flakiness

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/DatadogInternal/Codable/AnyDecoder.swift
Sources/Datadog/DatadogInternal/Codable/AnyEncoder.swift
Sources/Datadog/DatadogInternal/Codable/DynamicCodingKey.swift
Tests/DatadogTests/Datadog/DatadogInternal/Codable/AnyCoderTests.swift

Introduce implementation of `AnyEncoder` and `AnyDecoder` which will allow defragmenting data-types for transfer on the message-bus.
In the following example, a CrashContext is transmitted from the CrashReporting Feature to RUM through the message-bus: 
This implementation will also be useful for the Flutter SDK to replace the dependency to [DictionaryCoder](https://github.com/almazrafi/DictionaryCoder). cc @fuzzybinary 
Usage on the `FeatureBaggage` is done in #1113.
The `AnyEncoder` implements the [`Encoder` protocol](https://developer.apple.com/documentation/swift/encoder) and is capable of encoding an `Encodable` object to a `Any`, `[Any?]`, or `[String: Any?]` representation.
It will result in the same `object` as the following snippet, but without having to serialize to `Data`. …

RUMM-2786 Create AnyEncoder and AnyDecoder

---

Datadog/Datadog.xcodeproj/project.pbxproj

💊 Fixing E2E tests build:
```
❌  /Users/vagrant/git/TestUtilities/Sources/TestUtilities/Mocks/DatadogContextMock.swift:90:34: referencing static method 'mockRandom()' on 'Dictionary' requires that 'FeatureBaggage' conform to 'RandomMockable'
featuresAttributes: .mockRandom()
^
```
Fixed by including `FeatureBaggageMock` in `E2ETests` target.

Fix E2ETests build

---

Sources/Datadog/Logging/RemoteLogger.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/RUM/Integrations/ErrorMessageReceiverTests.swift

When logs started going through the message bus, we accidentally started dropping the additional log attributes. This fixes it so we send the attributes properly. 
Additionally, we need to decode certain values specifically from the cross platform SDKs to ensure they're being set on the RUMErrorModel properly (sourceType and isCrash)
For now, we're doing "decoding" through a `decode` extension method on AttributeValue. This checks to see if the value is actually `DDAnyCodable` and casts its wrapped value the proper type if it is. Otherwise, it just returns the proper value or nil.

RUMM-2950 Fix log attribute forwarding to RUM

---

Sources/Datadog/RUM/Integrations/CrashReportReceiver.swift
Tests/DatadogTests/Datadog/RUM/Integrations/CrashReportReceiverTests.swift

Following a crash, when updating a view with the crash count increase we should also increase the error count. 

Increase error count by 1 on the view update event following a crash

---

Datadog/Example/Scenarios/RUM/RUMScenarios.swift
Sources/Datadog/RUM/Instrumentation/Views/RUMViewsHandler.swift
Sources/Datadog/RUM/Instrumentation/Views/UIKit/UIKitRUMViewsPredicate.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMModalViewsScenarioTests.swift
Tests/DatadogTests/Datadog/RUM/Instrumentation/Views/RUMViewsHandlerTests.swift

This allows modal views to be "untracked" (not call startView / stopView) when using automatic view tracking. The view disappearing under the modal will still call `stopView`, and will restart when the modal is dismissed.  This is useful for  when a user wants to manually track a view controller that is presented modally, or when a framework (such as Flutter or React Native) wants to take over view reporting.
Pre iOS 13, users will need to set `isUntrackedModal` on the view they return from the predicate. This will push the view onto the `RUMViewsHandler` stack, but this view will not be started or stopped by the `RUMViewsHandler`.
On iOS 13+, views that are marked with `isModalInPresentation`, but return null from the `rumViewPredicate` are automatically considered to be untracked …

RUMM-2889 Support untracked modals

---

Datadog/Example/Scenarios/RUM/ManualInstrumentation/SendRUMFixture2ViewController.swift
Sources/Datadog/DDRUMMonitor.swift
Sources/Datadog/RUM/RUMMonitor/DDNoopRUMMonitor.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMManualInstrumentationScenarioTests.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

Add a method to report the result of evaluating a feature flag to a RUM view. These feature flags are subsequently sent on view updates and error updates.
Feature flags are set on view scope, and are discarded when a new view starts.

RUMM-2884 Add `addFeatureFlagEvaluation` method

---

Sources/Datadog/Logging/LoggingV2Configuration.swift

There was an issue caught by integration test. It was caused by existence of optional field if the dictionary.
This PR fixes the type casting to include optional strings. Way to go is to refactor the communication to always use Codable model that describes the contract. Created a ticket to tackle that next week `RUMM-3023`.

Fix a bug caught by integration test

---

DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/Fixtures.swift
DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/InputElements.storyboard
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests.xcodeproj/project.pbxproj
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/SRSnapshotTests.swift
DatadogSessionReplay/Sources/Processor/SRDataModelsBuilder/WireframesBuilder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeIDGenerator.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISliderRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISwitchRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotBuilder.swift
DatadogSessionReplay/Sources/Utilities/CGRectExtensions.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeIDGeneratorTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISliderRecorderTests.swift
DatadogSessionReplay/Tests/Utilities/CGRectExtensionsTests.swift

📦 With this PR we're adding support to `UISlider` elements in session replay.
Regular use of SR framework:
* added `UISliderRecorder` with `UISliderWireframesBuilder`
* added "Sliders" fixture in snapshot tests project.
The slider is constructed with 3 or 4 wireframes:
* 2 wireframes for "min track" and "max track"
* 1 wireframe for the "thumb" element
* 1 optional wireframe if the slider's `UIView` defines visible background
This is the first element that produces more than 2 wireframes, so I had to update the logic of generating `NodeID` (wireframe IDs) for views. Now, the `NodeIDGenerator` can create variadic number of IDs (instead of one or two before).

RUMM-2965 [SR] Support `UISlider` elements in session replay

---

DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/Fixtures.swift
DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/InputElements.storyboard
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests.xcodeproj/project.pbxproj
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/SRSnapshotTests.swift
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/Utils/ImageRendering.swift
DatadogSessionReplay/Sources/Processor/SRDataModelsBuilder/WireframesBuilder.swift
DatadogSessionReplay/Sources/Recorder/Utilities/SystemColors.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISegmentRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISliderRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotBuilder.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISegmentRecorderTests.swift

📦 With this PR we're adding support to `UISegmentedControl` elements in session replay.
- added `UISegmentRecorder` with `UISegmentWireframesBuilder`
- added "Segments" fixture and snapshot tests
The slider is constructed with 1 to many wireframes:
- one _shape_ wireframe for drawing the background of entire control
- separate _text_ wireframes for drawing segment labels
- one more _shape_ wireframe to highlight selected segment.
If privacy mode `.maskAll` is enabled, we obfuscate text and do not build selection wireframe:
I also enhanced the way we deal with system colors by introducing `SystemColors` construct. It acts as a collection of system colors, which are UI mode dependant (return different values for light- and dark-mode on iOS 13+). 
Here, an example of segments in dark mode:

RUMM-2972 [SR] Support `UISegmentedControl` elements in session replay

---

Makefile
bitrise.yml
dependency-manager-tests/.gitignore
dependency-manager-tests/xcframeworks/App/AppDelegate.swift
dependency-manager-tests/xcframeworks/App/Info.plist
dependency-manager-tests/xcframeworks/App/SceneDelegate.swift
dependency-manager-tests/xcframeworks/App/ViewController.swift
dependency-manager-tests/xcframeworks/AppTests/AppTests.swift
dependency-manager-tests/xcframeworks/AppTests/Info.plist
dependency-manager-tests/xcframeworks/AppUITests/AppUITests.swift
dependency-manager-tests/xcframeworks/AppUITests/Info.plist
dependency-manager-tests/xcframeworks/Makefile
dependency-manager-tests/xcframeworks/XCProject.xcodeproj/project.pbxproj
dependency-manager-tests/xcframeworks/XCProject.xcodeproj/project.xcworkspace/contents.xcworkspacedata
dependency-manager-tests/xcframeworks/XCProject.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
dependency-manager-tests/xcframeworks/XCProject.xcodeproj/xcshareddata/xcschemes/App iOS.xcscheme
dependency-manager-tests/xcframeworks/XCProject.xcodeproj/xcshareddata/xcschemes/App tvOS.xcscheme
tools/distribution/build-xcframework.sh

Datadog class conflicts with module name and Swift emits invalid module interface
cf. https://github.com/apple/swift/issues/56573
Therefore, we cannot provide ABI stability, we have to supply `-allow-internal-distribution`.
The `xcframeworks` smoke test is added to `dependency-manager-tests`, it checkouts and build the xcframeworks and try to compile for iOS and tvOS.
Fix #1167

RUMM-3065 Fix invalid module interface

---

DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/Fixtures.swift
DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/InputElements.storyboard
DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/InputViewControllers.swift
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests.xcodeproj/project.pbxproj
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/SRSnapshotTests.swift
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/Utils/ImageRendering.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UILabelRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIPickerViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshot.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotBuilder.swift
DatadogSessionReplay/Tests/Processor/ProcessorTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIPickerViewRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIViewRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeRecorderTests.swift

📦 This PR enhances the look of `UIPickerView` elements in session replay. Now we approximate their look by only capturing the text from "selected row" and ignoring all other values on the wheel. To further meet SR goals, if content masking is enabled we erase the values by replacing them with fixed-width `"xxx"` mask.
<table>
<tr><td>With no masking:</td><td>With masking:</td></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/2358722/221533190-f65c7f7d-a86f-426a-895c-4c8046b713f6.png" /></td>
<td><img src="https://user-images.githubusercontent.com/2358722/221533979-28e65cee-076f-43d9-b582-eb256c8b997d.png" /></td></tr>
</table>
This implementation leverages `NodeSubtreeStrategy` concept introduced in #1175. The `UIPickerViewRecorder` uses its own `ViewTreeRecorder` to …

RUMM-2964 [SR] Support `UIPickerView` elements in session replay

---

DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/Fixtures.swift
DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/InputElements.storyboard
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/SRSnapshotTests.swift
DatadogSessionReplay/Sources/Recorder/Utilities/SystemColors.swift
DatadogSessionReplay/Sources/Recorder/Utilities/UIKitExtensions.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISwitchRecorder.swift
DatadogSessionReplay/Tests/Recorder/Utilties/UIKitExtensionsTests.swift

📦 This PR enhances the recording of `UISwitch` elements in session replay. Its preliminary support was introduced earlier, but here we solve remaining glitches and adjust the values properly for light and dark mode.
<table>
<tr><td>With no masking:</td><td>With masking:</td></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/2358722/221648946-0144a182-b807-42a8-a057-b40c1f63dd1c.png" /></td>
<td><img src="https://user-images.githubusercontent.com/2358722/221648957-6dba34c6-604d-4d18-88e0-dbf7a7153775.png" /></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/2358722/221648962-8281c9ea-490a-456f-af97-97a20c8b31b1.png" /></td>
<td><img src="https://user-images.githubusercontent.com/2358722/221648966-dbda0b8d-e40f-4c84-a54f-8edf7682eb8c.png" /></td>
</tr> …

REPLAY-1340 Support `UISwitch` elements in session replay

---

Sources/Datadog/RUM/RUMVitals/VitalCPUReader.swift
Sources/Datadog/RUM/RUMVitals/VitalInfoSampler.swift
Tests/DatadogTests/Datadog/RUM/RUMVitals/VitalInfoSamplerTests.swift

Seeing this crash after upgrading from 1.12.1 to 1.15.0:
```
Crashed: com.datadoghq.rum-monitor
0  MyApp                          0x24da04 VitalCPUReader.readVitalData() + 29 (VitalCPUReader.swift:29)
1  MyApp                          0x24db04 protocol witness for SamplingBasedVitalReader.readVitalData() in conformance VitalCPUReader + 4366867204 (<compiler-generated>:4366867204)
2  MyApp                          0x24df7c VitalInfoSampler.takeSample() + 86 (VitalInfoSampler.swift:86)
3  MyApp                          0x20982c specialized VitalInfoSampler.init(cpuReader:memoryReader:refreshRateReader:frequency:maximumRefreshRate:) + 4366587948 (<compiler-generated>:4366587948)
4  MyApp                          0x224808 specialized …
```

Remove data race caused by doing sample on rum thread

---

DatadogSessionReplay/Sources/Recorder/Utilities/ImageDataProvider.swift
DatadogSessionReplay/Sources/Utilities/Cache.swift
DatadogSessionReplay/Tests/Recorder/Utilties/ImageDataProviderTests.swift
DatadogSessionReplay/Tests/Utilities/CacheTests.swift

Image capture algorithm started to behave funky. It's memory consumption went through the roof.
Reasons:
- md5 for jpegs generate different values (probably apple's [pngData()](https://developer.apple.com/documentation/uikit/uiimage/1624096-pngdata) is optimised in a way where it doesn't always produce the same bitmap).
- for such image it was running into recursion loading the data each time
- since there was no autorelease pool - memory was never freed in such a loop
Fixes:
- Added cache's max cost (in bytes)
- Removed md5 hash for the time being (we can revisit when needed)
- Added autorelease pool on the `contentBase64String()` to make sure it always frees the memory (even when run in a loop or recursively).
After these changes we are back to stable:

Fix memory usage issues in image capture

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogInternal/Sources/Codable/AnyEncoder.swift
DatadogInternal/Sources/MessageBus/FeatureBaggage.swift
DatadogInternal/Tests/MessageBus/FeatureBaggageTests.swift
DatadogInternal/Tests/MessageBus/FeatureMessageReceiverTests.swift

The `URLSessionInstrumentation` will require sharing `Foundation` types that are not `Codable` on the message-bus: `HTTPRequest`, `URLResponse`, `Error`, etc ...
The current implementation of `FeatureBaggage` only allow `Codable` which is too restrictive, we need more flexibility to share more types between Features.
Enable setting and getting `Any` types on the `FeatureBaggage`.

Allow `Any` Feature Baggage

---

Sources/Datadog/Tracer.swift
Sources/Datadog/Tracing/DDSpan.swift
Sources/Datadog/Tracing/DDSpanContext.swift
Sources/Datadog/Tracing/Propagation/OpenTelemetry/OTelHTTPHeadersReader.swift
Sources/Datadog/Tracing/Propagation/OpenTracing/HTTPHeadersReader.swift
Sources/Datadog/Tracing/Propagation/TracePropagationHeadersExtractor.swift
Sources/Datadog/Tracing/Propagation/W3C/W3CHTTPHeadersReader.swift
Tests/DatadogTests/Datadog/Mocks/TracingFeatureMocks.swift
Tests/DatadogTests/Datadog/Tracing/DDSpanContextTests.swift
Tests/DatadogTests/Datadog/Tracing/DDSpanTests.swift
Tests/DatadogTests/Datadog/Tracing/Propagation/OTelHTTPHeadersReaderTests.swift
Tests/DatadogTests/Datadog/Tracing/Propagation/W3CHTTPHeadersReaderTests.swift

Use lock on `BaggageItems` for thread safety to simplify usage of our various `TracePropagationHeadersExtractor` implementation. This will ease usage of shared trace propagation in the v2 modular architecture.
Replace the Span `BaggageItems` synchronisation queue with a read-write lock.

Remove span baggage queue

---

DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/Fixtures.swift
DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/InputElements.storyboard
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/SRSnapshotTests.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIStepperRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotBuilder.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIStepperRecorderTests.swift

📦 This PR enhances the recording of `UIStepper` elements in session replay. Its preliminary support was introduced earlier, but here we solve remaining glitches and send frames instead of images for button + and - button icons.
By adding new recorder for `UIStepper` element that checks it's frame and creates matching wireframes.

REPLAY-1448 Add support for UIStepper

---

DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIStepperRecorder.swift

📦 This PR enhances masking behaviour for `UIStepper` elements when `.maskAll` policy is set. Now, the MIN and MAX values cannot be inferred as we no longer grey-out their buttons:
Easy 😎.

REPLAY-1460 Enhance `UIStepper` element masking

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/Scenarios/RUM/ManualInstrumentation/RUMManualInstrumentationScenario.storyboard
Datadog/Example/Scenarios/RUM/RUMScenarios.swift
Datadog/Example/Scenarios/RUM/StopSessionScenario/KioskSendEventsViewController.swift
Datadog/Example/Scenarios/RUM/StopSessionScenario/KioskSendInterruptedEventsViewController.swift
Datadog/Example/Scenarios/RUM/StopSessionScenario/KioskViewController.swift
Datadog/Example/Scenarios/RUM/StopSessionScenario/RUMStopSessionScenario.storyboard
Sources/Datadog/DDRUMMonitor.swift
Sources/Datadog/RUM/DataModels/RUMDataModels.swift
Sources/Datadog/RUM/Debugging/RUMDebugging.swift
Sources/Datadog/RUM/Integrations/CrashReportReceiver.swift
Sources/Datadog/RUM/RUMContext/RUMContext.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUMMonitor.swift
Sources/DatadogObjc/RUM/RUMDataModels+objc.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMCommonAsserts.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMStopSessionScenarioTests.swift
Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift

This adds a method to manually end a RUM session with `stopRumSession`.  This immediately stops the active view and sets the current session to inactive. A new session starts automatically when a user action is sent (`startView` or `addUserAction`).
First, may RUM events now have a new property: `session.isActive`. This can be null, and is only currently set in RUMViewEvents. The state of this member is pulled from the parent session context.
Second, I've modified `RUMApplicationScope` to support holding multiple `RUMSessionScope`s in a similar way to how Sessions can handle multiple Views until all of their events have been processed.
When a `RUMStopSession` event is received, the Application Scope forwards it to the Session, which marks itself as inactive, then forwards the event to the …

Allow users to manually end a RUM session

---

DatadogSessionReplay/Sources/Processor/SRDataModelsBuilder/WireframesBuilder.swift

📦 Our fonts support in SR is still very limited. No matter of the font configured for certain text elements, we always use single hardcoded value. This PR changes that value to better one according to results observed in the player:
```diff
- static let fontFamily = "-apple-system, Roboto, Helvetica, Arial"
+ static let fontFamily = "-apple-system, BlinkMacSystemFont, 'Roboto', sans-serif"
```
Just changing the hardcoded value in `WireframesBuilder`.
It doesn't update any tests, because `WireframesBuilder` logic is covered by snapshot tests and snapshots are yet not part of our git workflow (coming soon).

REPLAY-1421 Use better fallback value for fonts

---

DatadogSessionReplay/Sources/Recorder/Utilities/ImageDataProvider.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewRecorder.swift
DatadogSessionReplay/Sources/Utilities/UIImage+Scaling.swift
DatadogSessionReplay/Tests/Recorder/Utilties/ImageDataProviderTests.swift
DatadogSessionReplay/Tests/Utilities/UIImage+ScalingTests.swift

Adds algorithm for scaling images before generating base64 for session replay.
Algorithm make initial scale percentage calculation based on desiredSize/ActualSize and after that it performs fixed number of iterations decreasing the size by 10%. It must be done this way due to PNG compression (loss-less) - we can't guarantee that scaled image will be small enough byte size.
As a fallback if scaled image doesn't have smaller byte size than the original image, we will generate base64 of original image (this can happen for very small images).

REPLAY-1345 Image Scaling Optimisation

---

DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/Images.storyboard
DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/ImagesViewControllers.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewRecorder.swift

Adds support for image backgrounds for UIButton.
As extra we provided similar solution for any image background that's coming from `UIImageView` which is direct child 
of `_UIBarBackground` which covers scenarios for `UINavigationBar`, `UITabBar` and `UIToolbar`.
Other considered solution was involving separate recorders, but this would introduce way more complexity.
Once we find reasons for adding separate recorders for any of the classes above we can gradually move the logic from the image generic to control specific image recorder.
Solution is based on UIImageView and UIImage extensions that provide number of flags representing a state of control. These states are taken into account in recording and tinting predicate of the recorder.

REPLAY-1510 Button image background support

---

Sources/Datadog/RUM/DataModels/RUMDataModels.swift
Sources/Datadog/RUM/Integrations/CrashReportReceiver.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/DatadogObjc/RUM/RUMDataModels+objc.swift
Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift

Update the RUM schema to latest, which moves `session.isActive` to only report on View updates and adds `session.startReason`
I'm setting `session.startReason` to nil for now and we'll revisit when we actually add that feature.

Update RUM Schema

---

DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/Fixtures.swift
DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/UnsupportedViews.storyboard
DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/UnsupportedViewsViewController.swift
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests.xcodeproj/project.pbxproj
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/SRSnapshotTests.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UnsupportedViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotBuilder.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UnsupportedViewRecorderTests.swift

Adds special recorder that recognises unsupported views and provides a common placeholder for them.
Snapshot:

REPLAY-1517 Add unsupported views recorder

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogInternal/Sources/Concurrency/Flushable.swift
DatadogInternal/Sources/NetworkInstrumentation/NetworkInstrumentationFeature.swift
Sources/Datadog/DatadogCore/Context/DatadogContextProvider.swift
Sources/Datadog/DatadogCore/DatadogCore.swift
Sources/Datadog/RUM/Feature/DatadogRUMFeature.swift
Sources/Datadog/RUM/RUMMonitor.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

Fix integration tests flakiness by allowing flushing Features.
Creates a `Flushable` protocol for executing all async operations in a complying implementation. Features implementing `Flushable` will be  flushed with the core they are registered in during tests execution.
A missing flush mechanism in `NetworkInstrumentationFeature` was making Integration Tests flaky.

Make Features `Flushable`

---

DatadogInternal/Sources/NetworkInstrumentation/NetworkInstrumentationFeature.swift
DatadogInternal/Tests/NetworkInstrumentation/NetworkInstrumentationFeatureTests.swift

Fix interception of 1st-party hosts in composite delegate.
Use `__URLSessionDelegateProviding` for getting 1st-party host instead of `DatadogURLSessionDelegate`.
Add coverage in unit-tests instead of fuzzy integration test.

Fix 1st-Party Hosts from Custom Delegate

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog iOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog tvOS.xcscheme
DatadogInternal/Sources/NetworkInstrumentation/NetworkInstrumentationFeature.swift
DatadogInternal/Sources/NetworkInstrumentation/URLSession/DatadogURLSessionDelegate.swift
DatadogInternal/Sources/NetworkInstrumentation/URLSession/URLSessionInterceptor.swift
DatadogInternal/Sources/NetworkInstrumentation/URLSession/URLSessionSwizzler.swift
DatadogInternal/Tests/Codable/AnyCodableTests.swift
DatadogInternal/Tests/Codable/AnyCoderTests.swift
DatadogInternal/Tests/Extensions/TimeInterval+ConvenienceTests.swift
DatadogInternal/Tests/NetworkInstrumentation/NetworkInstrumentationFeatureTests.swift
DatadogInternal/Tests/NetworkInstrumentation/URLSessionSwizzlerTests.swift
DatadogInternal/Tests/Utils/SwiftExtensionsTests.swift
Sources/DatadogExtensions/Alamofire/DatadogAlamofireExtension.swift
dependency-manager-tests/cocoapods/App/ViewController.swift
tools/lint/sources.swiftlint.yml
tools/lint/tests.swiftlint.yml

The Alamofire extension was broken following #1210 
Re-introduce the `URLSessionInterceptor` to manually intercept `URLRequest` and `URLSessionTask`. The interceptor will use the `NetworkInstrumentationFeature` to dispatch interception across registered `DatadogURLSessionHandler` (RUM or Tracer).
- I've noticed that the added module's unit-tests were not run with the main target, and so did not run in CI.
- CocoaPods smoke test was broken following #1227
Both have been fixed in this PR.

Re-enable Alamofire Extension

---

CHANGELOG.md
Sources/Datadog/Logging/RemoteLogger.swift
Tests/DatadogTests/Datadog/LoggerTests.swift

Fix RUM context not being attached to log when no user action exists.
Allow `nil` values in RUM context.

RUMM-3239 Fix RUM Context in Logs

---

DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/Basic.storyboard
DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/BasicViewControllers.swift
DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/Fixtures.swift
DatadogSessionReplay/SRSnapshotTests/SRHost/MenuViewController.swift
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests.xcodeproj/project.pbxproj
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/SRSnapshotTests.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewAttributes+Copy.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshot.swift
DatadogSessionReplay/Tests/Mocks/RecorderMocks.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIViewRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotTests.swift

Adds proper support for UIAlertController. Without this change recorders don't capture it's background, which doesn't look good.
It changes `ViewTreeRecordingContext` by adding additional nested `ViewTreeRecordingContext` that carries the type of the view controller and that determines if the view is root view of given view controller. This context knowledge allows us to specify special rules for recording these custom views. Without it we would have to rely on private class type of the view. This approach will be useful in the future for any view controller backed system components.
In this particular instance we override view attributes of the UIAlertController root view to provide consistent background.

REPLAY-1512 UIAlertController support

---

Datadog/Example/Scenarios/URLSession/URLSessionScenarios.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMResourcesScenarioTests.swift

`RUMResourcesScenarioTests` was using `https://httpbin.org` for 3rd party resources. We don't own this service and it could fail to respond in a timely manner.
Using `curl -s https://httpbin.org/get` we can have long response time:
```
time_namelookup:  0.005084
time_connect:  0.210384
time_appconnect:  0.624901
time_pretransfer:  0.414942
time_redirect:  0.000000
time_starttransfer:  31.134719
----------
time_total:  31.135052
```
This integration test now uses `shopist.io` that we own for 3rd party requests, it can be considered more reliable.
1. Use `https://shopist.io/categories.json` for GET and `https://api.shopist.io/checkout.json` for POST as 3rd party resources.
2. Use an `.ephemeral` URLSession instance so we don't use local cache and we can get proper metrics.

[develop] Improve CI Stability

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogInternal/Tests/NetworkInstrumentation/NetworkInstrumentationFeatureTests.swift
DatadogInternal/Tests/NetworkInstrumentation/URLSessionSwizzlerTests.swift
IntegrationTests/IntegrationScenarios/Scenarios/RUM/RUMResourcesScenarioTests.swift
IntegrationTests/Runner/Scenarios/URLSession/URLSessionScenarios.swift

Fix further flakiness:
1. `NetworkInstrumentationFeatureTests` needs flush of the Feature before assertion.
2. `RUMResourcesScenarioTests` was using an external 3rd party service that we don't own.
3. Bad dependency linking in `DatadogLogs iOS` target

[v2] Improve CI Stability

---

IntegrationTests/IntegrationScenarios/Scenarios/CrashReporting/CrashReportingWithLoggingScenarioTests.swift
IntegrationTests/IntegrationScenarios/Scenarios/CrashReporting/CrashReportingWithRUMScenarioTests.swift

On x86 a `fatalError()` results on a SIGILL signal but on an ARM machine it results in a `SIGTRAP`.
Hence, the test case fail on the ARM machine. In order to update the CI to ARM, this needs to be fixed.
Use preprocessor macros to check the architecture and then use the appropriate signal.
Tested on ARM mac under Rosetta and ARM simulators.

RUMM-3266 fix: use arch conditionals to assert arch specific signal

---

Tests/DatadogIntegrationTests/Scenarios/CrashReporting/CrashReportingWithLoggingScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/CrashReporting/CrashReportingWithRUMScenarioTests.swift

Porting https://github.com/DataDog/dd-sdk-ios/pull/1273 to `develop`
On x86 a `fatalError()` results on a SIGILL signal but on an ARM machine it results in a `SIGTRAP`.
Hence, the test case fail on the ARM machine. In order to update the CI to ARM, this needs to be fixed.
Use preprocessor macros to check the architecture and then use the appropriate signal.

[porting to develop] RUMM-3266 fix: use arch conditionals to assert arch specific signal

---

DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/Basic.storyboard
DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/BasicViewControllers.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextViewRecorder.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextViewRecorderTests.swift

Text view recording behaviour was a little flaky. The biggest problem is with carriage, as we can't fully control the text rendering if was appearing in a wrong place for more complex scenarios.
This solution adds basic padding to the text view (experimentally selected by looking at rendered text views).
Additionally we now ignore the subtree recording to remove carriage (which is simple UIView).
I added some additonal text views in the basic text snapshot case, making one of them first responder to simulate the appearance of the carriage.

REPLAY-1620 Text view recording improvements

---

CHANGELOG.md
Sources/Datadog/RUM/RUMVitals/VitalRefreshRateReader.swift
Tests/DatadogTests/Datadog/RUM/RUMVitals/VitalRefreshRateReaderTests.swift

Currently, to find out the FPS of a view, the SDK look for the frame duration and inverses it to get the FPS.
Eg. if the frame duration is 16ms (0.016s), the FPS is 1/0.016 = 60FPS (rounded).
This generally works but when comes to variable refresh rate displays, it becomes an issue. For example, let's say OS has decided to increase the frame duration to 32ms to save battery, the FPS will be 30FPS but that doesn't mean the app is having a poor UI performance. It can very well be that the app is doing nothing.
`CADisplayLink` has a property called `targetTimestamp` which is the time when the next frame is scheduled to be displayed. This is the time when the frame is actually displayed on the screen. Hence, the SDK uses this property to calculate the expected frame duration and then inverses …

RUMM-3222 Use targetTimestamp as reference to calculate FPS

---

Makefile
bitrise.yml

⛏️ The `run_nightly_smoke_and_tools_tests` was failing on CI in:
```
HTTPServerMockTests
✗ testItPullsRecordedRequests, failed - Failed to connect with the server.
✗ testItReturnsRecordedRequests, failed - Failed to connect with the server.
✓ testWhenPullingRecordedRequestExceedsTimeout_itThrowsAnError (5.200 seconds)
```
causing 3 nightly job failures in a row.
The problem was in spawning python process from unit tests and reaching timeout in:
```swift
guard let serverProces = runner.waitUntilServerIsReachable() else {
XCTFail("Failed to connect with the server.")
return
}
```
As a fix, I'm switching from running `HTTPServerMock` unit tests with generated `*.xcodeproj` (that option is already deprecated in SPM). From now on, we can run them directly using `swift test`. I choose this over …

Fix `run_nightly_smoke_and_tools_tests` workflow

---

DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/Basic.storyboard
DatadogSessionReplay/Sources/Drafts/SessionReplayConfiguration.swift
DatadogSessionReplay/Sources/Processor/Privacy/TextObfuscator.swift
DatadogSessionReplay/Sources/Recorder/Utilities/UIKitExtensions.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIDatePickerRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UILabelRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIPickerViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISegmentRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISliderRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextFieldRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeRecordingContext.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotBuilder.swift
DatadogSessionReplay/Sources/SessionReplayPrivacy.swift
DatadogSessionReplay/Tests/Mocks/RecorderMocks.swift
DatadogSessionReplay/Tests/Mocks/UIKitMocks.swift
DatadogSessionReplay/Tests/Processor/Privacy/TextObfuscatorTests.swift
DatadogSessionReplay/Tests/Recorder/Utilties/UIKitExtensionsTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextFieldRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextViewRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotBuilderTests.swift
DatadogSessionReplay/Tests/SessionReplayPrivacyTests.swift

📦 This PR aligns rules of text and appearance masking to what was concluded in [Privacy Options in Mobile SR](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/2945942237/Privacy+Options+in+Mobile+Session+Replay):
<p align="center">
</p>
For **text masking**, above configuration is reflected in `SessionReplayPrivacy` extension:
```swift
/// Text masking strategies per type of text.
extension SessionReplayPrivacy {
var sensitiveTextObfuscator: TextObfuscating
var inputAndOptionTextObfuscator: TextObfuscating
var staticTextObfuscator: TextObfuscating
var hintTextObfuscator: TextObfuscating
}
```
Each node recorder uses `TextObfuscation` to obtain strategy respectively to its text type (e.g. label recorder uses `staticTextObfuscator(for:)`). Same as before, compound recorders can …

REPLAY-1610 Align text and appearance masking rules

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Attributes/Attributes.swift
Sources/Datadog/Logging/RemoteLogger.swift
Tests/DatadogTests/Datadog/Logging/RemoteLoggerTests.swift

In the case of a Cross Platform crash log, a RUM error is already sent. 
We want to prevent this log from triggering another RUM error, which would be a duplicate.
With the change we only see 1 RUM Error:
Look at a cross-platform attribute before creating the log to prevent creating the error.

RUMM-3277 Prevent sending RUM Error from Cross Platform crash logs

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift

#1278 introduced a side effect of creating the 'Application Launch View' at the init of the SDK. This is too early in the process an we need to wait for the first event so it can report the application launch time properly.
Split the Session creation and the Application activation in the Application Scope:
- The initial Session will be created on `RUMSDKInitCommand` or any other commands.
- The Application Launch View is started (app active) on any other command.

RUMM-3237 Fix Application Launch View Creation

---

tools/nightly-unit-tests/bitrise.yml.src

🐞 Fixes a problem that caused our nightly unit tests to ran on a single version of iOS Simulator. It is crucial to run them among different simulators, extending our tests coverage to past iOS versions.
Fixing nightly-generated `bitrise.yml` to use `destination` instead of `simulator_device` and `simulator_os_version` for `xcode-test` step. That change was introduced by Bitrise in https://github.com/bitrise-steplib/steps-xcode-test/pull/185. We [applied it](https://github.com/DataDog/dd-sdk-ios/pull/765#discussion_r812967047) to the main `bitrise.yml` but not to the nightly one.

[Chore] Fix nightly unit tests to run on different iOS Simulator each time

---

Sources/Datadog/DatadogCore/Storage/DataBlock.swift
Sources/Datadog/DatadogCore/Storage/Reading/FileReader.swift
Sources/Datadog/DatadogCore/Storage/Writing/FileWriter.swift
Tests/DatadogTests/Datadog/Core/Persistence/DataBlockTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Writing/FileWriterTests.swift

Length typo fixes. [Length vs Lenght](https://word.tips/spelling/length-vs-lenght/).

Fix length typos

---

Tests/DatadogTests/Datadog/Mocks/CrashReportingFeatureMocks.swift

Fix data race condition issue in `CrashReportingPluginMock`.
CI jobs seems to hang when running `testWhenPendingCrashReportIsFound_itIsSentAndPurged`, and by running the test repeatedly we can run into a data-race condition.
The `CrashReportingPluginMock` was missing a lock mechanism.

Fix data race condition in test

---

Sources/Datadog/Tracing/UUIDs/TracingUUID.swift
Tests/DatadogTests/Datadog/Tracing/UUIDs/TracingUUIDTests.swift

There is a bug in the creation of the `traceparent` of the trace http header.
The type of `TracingUUID.rawValue` is `UInt64`, but it is converted to 32 bits when converted like [format: "%16x"].  
When `trace id : 7242571286695202638`(decimal), the `traceparent` header value is being generated as `[version]-00000000000000000000000063e94f4e-[parent id]-[trace flags]` now.
Use the `%llx` format when converting strings of type UInt64.

Fix TracingUUID toString string format

---

Sources/Datadog/RUM/Integrations/CrashReportReceiver.swift
Tests/DatadogTests/Datadog/RUM/Integrations/CrashReportReceiverTests.swift

We're currently not reporting user set global attributes when collecting a crash. 
This PR addresses this.
Context reported on the RUM Error created when collecting a crash is extracted from the last active RUM View.

RUMM-3349 Add context to crash when there's an active view

---

DatadogCrashReporting.podspec
DatadogSDKCrashReporting.podspec

Rename `DatadogSDKCrashReporting.podspec` to `DatadogCrashReporting.podspec` and mark `DatadogSDKCrashReporting` as deprecated.

RUMM-2387 Rename Crash Reporting podspec

---

Sources/Datadog/RUM/DataModels/RUMDataModels.swift
Sources/Datadog/RUM/Integrations/CrashReportReceiver.swift
Sources/Datadog/RUM/RUMEvent/RUMOperatingSystemInfo.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/DatadogObjc/RUM/RUMDataModels+objc.swift
Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift
tools/rum-models-generator/Sources/CodeDecoration/RUMCodeDecorator.swift
tools/rum-models-generator/Sources/CodeGeneration/Generate/JSONSchema.swift
tools/rum-models-generator/Sources/CodeGeneration/Generate/Transformers/JSON/JSONSchemaToJSONTypeTransformer.swift
tools/rum-models-generator/Tests/CodeGenerationTests/Fixtures/fixture-schema-with-typeless-enum.json
tools/rum-models-generator/Tests/CodeGenerationTests/Generate/Transformers/JSONSchemaToJSONTypeTransformerTests.swift

This PR updates RUM model.
It required a fix for enum without explicit type in generator, after adding fix I generated the code and added blank mocks. They'll be filled in the follow up PR that adds these metrics to the event.

Regenerate rum model

---

Tests/DatadogIntegrationTests/Scenarios/RUM/RUMManualInstrumentationScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMResourcesScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMStopSessionScenarioTests.swift

Since https://github.com/DataDog/dd-sdk-ios/pull/1344 the develop branch `DatadogIntegrationTests` target is broken.
Figured this out after merging develop for https://github.com/DataDog/dd-sdk-ios/pull/1328.
Adapted tests to new model changes.

fix: broken IntegrationTests target

---

DatadogCore/Sources/Core/Storage/Directories.swift
DatadogCore/Sources/Datadog.swift
DatadogCore/Tests/Datadog/Core/DirectoriesTests.swift

Use core instance name instead of client-token for persistent dat folder.

RUMM-2987 Use instance name for data persistency

---

DatadogCrashReporting.podspec
DatadogInternal.podspec
DatadogLogs.podspec
DatadogRUM.podspec
DatadogSDK.podspec
DatadogSDKCrashReporting.podspec
DatadogSessionReplay.podspec
DatadogTrace.podspec
DatadogWebViewTracking.podspec
IntegrationTests/Podfile
dependency-manager-tests/cocoapods/Podfile.src
tools/distribution/release.py

Update CocoaPods specs for v2 release.
Mark `DatadogSDK` as deprecated in favor of DatadogCore, DatadogLogs, DatadogRUM, DatadogTrace, and DatadogWebViewTracking
All `DatadogSDK*` podspecs are now marked as deprecated with proper warning when used:

RUMM-2387 Update CocoaPods specs

---

DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/Images.storyboard
DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/ImagesViewControllers.swift
DatadogSessionReplay/Sources/Processor/Diffing/Diff+SRWireframes.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewRecorder.swift

Follow up PR to https://github.com/DataDog/dd-sdk-ios/pull/1326
It fixes clipsToBounds behaviour when image is present.
Reenabled clipping when image is present + added snapshot tests to cover these scenarios.

REPLAY-1805 image placeholder fixes

---

DatadogSessionReplay/Sources/Drafts/SessionReplayFeature.swift
DatadogSessionReplay/Sources/Recorder/WindowObserver/KeyWindowObserver.swift
Sources/Datadog/Core/PerformancePreset.swift
Sources/Datadog/DatadogInternal/PerformancePresetOverride.swift
Tests/DatadogTests/Datadog/Core/PerformancePresetTests.swift
Tests/DatadogTests/Datadog/DatadogCore/DatadogCoreTests.swift

📦 This PR tunes the performance of SR uploader, making it more eager. This is to increase reliability of replay uploads.
The `PerformancePreset` for Session Replay is now overwritten with values that correspond to `uploadFrequency: .fast` and `batchSize: .small` setup.

REPLAY-1868 Configure Session Replay uploader to be more eager

---

tools/sr-snapshots/Sources/Shell/CommandLine.swift
tools/sr-snapshots/Sources/Shell/ProcessCommandLine.swift
tools/sr-snapshots/Tests/ShellTests/ProcessCommandLineTests.swift

🧰 This PR fixes flakiness of earlier introduced shell-wrapper package. The issue was surfaced as flaky test on CI.
The `tools/sr-snapshots/Shell` is a sub-package leveraged by `sr-snapshots` automation. Its main purpose is bringing the convenience of executing shell sub-processes in our tooling.
The earlier implementation of STDOUT and STDERR capturing was too naive. Learning the lesson from [Running a Child Process with Standard Input and Output](https://developer.apple.com/forums/thread/690310) this PR brings a more solid and versatile solution that could be later utilised as shared/common package for other our tooling.

REPLAY-1616 Fix flaky behaviour of `tools/sr-snapshots/Shell` util

---

DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/Utils/SnapshotTestCase.swift
DatadogSessionReplay/Sources/Feature/RequestBuilder/Multipart/MultipartFormData.swift
DatadogSessionReplay/Sources/Feature/RequestBuilder/RequestBuilder.swift
DatadogSessionReplay/Sources/Feature/SessionReplayFeature.swift
DatadogSessionReplay/Sources/Processor/Processor.swift
DatadogSessionReplay/Sources/Processor/SRDataModelsBuilder/RecordsBuilder.swift
DatadogSessionReplay/Sources/Recorder/Recorder.swift
DatadogSessionReplay/Tests/Feature/RequestBuilder/RequestBuilderTests.swift
DatadogSessionReplay/Tests/Mocks/SRDataModelsMocks.swift
DatadogSessionReplay/Tests/Mocks/SnapshotProducerMocks.swift
DatadogSessionReplay/Tests/Processor/ProcessorTests.swift
DatadogSessionReplay/Tests/Processor/SRDataModelsBuilder/RecordsBuilderTests.swift
DatadogSessionReplay/Tests/Recorder/RecorderTests.swift

📦 For observability, this PR enables telemetry logs in Session Replay module.
Solved all `TODO: send telemetry` left previously due to unavailability of `TelemetryCore` in early development of SR.
Notably, we're enabling 4 telemetry errors:
```
[SR] Could not create segment source from provided string '\(context.source)'
```
```
[SR] Unexpected flow in `Processor`: no previous wireframes and no previous RUM context
```
```
[SR] Failed to create incremental record
```
```
[SR] Failed to take snapshot
```
🎁🏕️ With the full availability of V2, I also filled some gaps in tests coverage. This includes adding missing tests for components that were not covered due to lack of `DatadogInternal` constructs and mocks from `TestUtilities`:
* `SessionReplay: RequestBuilderTests`
* `SessionReplay: …

REPLAY-1463 Enable telemetry in Session Replay

---

DatadogCore/Tests/Datadog/Logs/CrashLogReceiverTests.swift
DatadogCore/Tests/Datadog/Mocks/CrashReportingFeatureMocks.swift
DatadogCore/Tests/Datadog/RUM/Integrations/CrashReportReceiverTests.swift
DatadogCrashReporting/Sources/CrashReportingPlugin.swift
DatadogCrashReporting/Sources/PLCrashReporterIntegration/CrashReport.swift
DatadogCrashReporting/Sources/PLCrashReporterIntegration/DDCrashReportExporter.swift
DatadogCrashReporting/Tests/Mocks.swift
DatadogCrashReporting/Tests/PLCrashReporterIntegration/DDCrashReportExporterTests.swift
DatadogInternal/Sources/Context/DeviceInfo.swift
DatadogInternal/Sources/Context/Sysctl.swift
DatadogInternal/Tests/Context/DeviceInfoTests.swift
DatadogRUM/Sources/RUMEvent/RUMOperatingSystemInfo.swift
DatadogRUM/Tests/RUMEvent/RUMOperatingSystemInfoTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift
TestUtilities/Mocks/DatadogContextMock.swift
TestUtilities/Mocks/FoundationMocks.swift

Add missing error fields in RUM to enable crash export to Apple format.
- `os.build`: The OS build number.
- `error.meta.process`: Add the process ID: `process_name [process_id]`

RUMM-3162 Add missing fields RUM for Apple Crash format

---

DatadogCore/Tests/Datadog/LoggerTests.swift
DatadogCore/Tests/Datadog/Logs/CrashLogReceiverTests.swift
DatadogCore/Tests/Datadog/Mocks/LogsMocks.swift
DatadogLogs/Sources/Feature/MessageReceivers.swift
DatadogLogs/Sources/Log/LogEventBuilder.swift
DatadogLogs/Sources/Log/LogEventEncoder.swift
DatadogLogs/Tests/Log/LogEventBuilderTests.swift
DatadogLogs/Tests/Mocks/LoggingFeatureMocks.swift

Add missing error fields in Logs to enable crash export to Apple format.
- `os.name`: The OS name.
- `os.version`: The OS version.
- `os.build`: The OS build number.

RUMM-3327 Add missing fields to Logs for Apple Crash format

---

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Example iOS.xcscheme
Datadog/Example/AppConfiguration.swift
Datadog/Example/Debugging/DebugRUMSessionViewController.swift
DatadogSessionReplay/Sources/DatadogCoreIntegration/RUMContextReceiver.swift
DatadogSessionReplay/Sources/DatadogCoreIntegration/RUMDependency.swift
DatadogSessionReplay/Tests/DatadogCoreIntegration/RUMContextReceiverTests.swift
Sources/Datadog/Logging/Log/LogEventSanitizer.swift
Sources/Datadog/Logging/LoggingV2Configuration.swift
Sources/Datadog/Logging/RemoteLogger.swift
Sources/Datadog/RUM/Integrations/RUMContextAttributes.swift
Sources/Datadog/TracerConfiguration.swift
Sources/Datadog/Tracing/Span/SpanEventEncoder.swift
Sources/Datadog/Tracing/TracingV2Configuration.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift

APM <-> RUM correlation was not working for local traces due to mismatch in span tag format between the SDK and APM Backend.
fix: https://github.com/DataDog/dd-sdk-ios/issues/1292
This PR removes the direct use of `RUMContextAttributes` in both Log and Span encoding. 
Instead, a mapping layer is added that transforms keys into the required format for each product. 
On the Example app, changes are made to allow enabling a simple debugging option. It's now possible to single a single log, a single span, and a single traced request on a particular RUM session.

RUMM-3320 [V1] Fix APM local spans not correlating with RUM views

---

DatadogCore/Tests/Datadog/Core/PerformancePresetTests.swift
DatadogCore/Tests/Datadog/DatadogCore/DatadogCoreTests.swift
DatadogInternal/Sources/Storage/PerformancePresetOverride.swift
DatadogSessionReplay/Sources/Feature/SessionReplayFeature.swift

⏱️ Following on https://github.com/DataDog/dd-sdk-ios/pull/1363, we want to make SR uploader even more eager.
The rationale is to leverage `-beta` and to promote data consistency over uploads performance slightly more. After getting numbers with next observability tasks, we will lower the preset to more optimised one.
We're leveraging the performance preset override API added earlier. I selected new values by testing in example project - playing smooth scenario and adjusting numbers to achieve relatively short batch buffer.

REPLAY-1902 Make SR uploader even more eager

---

.gitignore
DatadogCore/Sources/Core/Storage/Writing/FileWriter.swift
DatadogInternal/Sources/Storage/PerformancePresetOverride.swift
DatadogRUM/Sources/Feature/RUMViewEventsFilter.swift
bitrise.yml
tools/nightly-unit-tests/bitrise.yml.src
tools/nightly-unit-tests/generate_bitrise_yml.py

```
Failed to execute Step:
command failed with exit status 65 (xcodebuild "-workspace" "/Users/vagrant/git/Datadog.xcworkspace" "-scheme" "Datadog iOS" "test" "-destination" "id=E467E978-443F-4E53-9A7E-C146036E2E69" "-resultBundlePath" "/var/folders/sj/_4jj239s3j33w5w1bdh98yj80000gn/T/XCUITestOutput2480199168/Test-Datadog iOS.xcresult" "-retry-tests-on-failure" "-test-iterations" "2" "-xcconfig" "/var/folders/sj/_4jj239s3j33w5w1bdh98yj80000gn/T/3713649878/temp.xcconfig"):
xcodebuild: error: The workspace named "Datadog" does not contain a scheme named "Datadog iOS". The "-list" option can be used to find the names of the schemes in the workspace.
```
`Datadog iOS` no longer exists rather we have `DatadogCore iOS` which currently runs all the targets. Once V2 migration is fully done, we …

ci: fix scheme name for nightly unit tests

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/Public/TelemetryCoreIntegrationTests.swift
DatadogRUM/Sources/Integrations/TelemetryReceiver.swift

🐞 This PR fixes broken link between RUM Telemetry events and RUM session.
Without this link we can't make data-driven decisions that include `session_id` querying or distributions.
Added integration tests for Telemetry feature, which revealed several issues. Fixed one by one.
All problems follow the same pattern of invalid assumption on RUM context retrieval from `FeatureBaggage`. The only non-optional attribute in RUM context is `application.id`, all other (`session.id`, `view.id` and `action.id`) are optional, so:
```swift
// Wrong:
let attributes: [String: String]? = context.featuresAttributes["rum"]?.ids
// Correct:
let attributes: [String: String?]? = context.featuresAttributes["rum"]?.ids
```
In result of wrong assumption, RUM context information was only attached to these telemetry …

RUMM-3459 fix: Fix linking telemetry events to RUM session

---

tools/distribution/release.py
tools/distribution/src/release/assets/gh_asset.py
tools/distribution/src/utils.py

Update GH asset name for pre-build binaries following [Carthage requirements](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-zip-files).
fix #1318
With v2 and module stability enabled, GH assets will be named `Datadog.xcframework.zip`.
Prior to v2 and since we were not compliant with Carthage, we can always include the Xcode version in the asset name. The `add_xcode_version_to_github_asset` parameter is now unnecessary and has been removed.

Fix xcframework GH assets

---

BenchmarkTests/DataStorage/LoggingStorageBenchmarkTests.swift
BenchmarkTests/DataStorage/RUMStorageBenchmarkTests.swift
BenchmarkTests/DataStorage/TracingStorageBenchmarkTests.swift
Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/Internal/CoreMetricsIntegrationTests.swift
DatadogCore/Sources/Core/Storage/FeatureStorage.swift
DatadogCore/Sources/Core/Storage/FilesOrchestrator.swift
DatadogCore/Sources/Utils/CoreMetrics.swift
DatadogCore/Tests/Datadog/Core/Persistence/FilesOrchestrator+MetricsTests.swift
DatadogCore/Tests/Datadog/Mocks/CoreMocks.swift
TestUtilities/Mocks/TelemetryMocks.swift

📦⏱️ Adding "Batch Closed" metric.
See (internal) [RFC Batching & Upload Observability](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3076063377/RFC+-+Batching+Upload+Observability).
Leveraged metrics API added earlier in #1384.
With this PR, I'm adding full unit tests coverage for both metrics creation in `FilesOrchestrator`.

RUMM-3460 feat: Add "Batch Closed" telemetry

---

README.md

Fixes the `README.md` link to Datadog's Alamofire extension.

Fix README link to Alamofire extension

---

DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISegmentRecorder.swift
DatadogSessionReplay/Sources/Utilities/CGRectExtensions.swift
DatadogSessionReplay/Tests/Recorder/Utilties/ImageDataProviderTests.swift

🧰 The addition of Session Replay to main `.xcworkspace` in #1393 surfaced problems with running SR code in nightly tests.
* Fixed Xcode 13.4.1 build issues.
* Fixed test that was failing below iOS 16.0.

REPLAY-1869 fix: Fix nightly tests for Session Replay

---

CHANGELOG.md
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift

These are the same changes from #1397 cherry picked into the 1.x line.  This prevents attributes from Errors and LongTasks from getting added to views.

RUMS-1778 Do not propagate attributes to views in 1.x

---

CHANGELOG.md
DatadogCore/Tests/Datadog/Mocks/RUMDataModelMocks.swift
DatadogCore/Tests/Datadog/RUM/RUMMonitorTests.swift
DatadogObjc/Sources/RUM/RUMDataModels+objc.swift
DatadogRUM/Sources/DataModels/RUMDataModels.swift
DatadogRUM/Sources/Integrations/CrashReportReceiver.swift
DatadogRUM/Sources/Integrations/TelemetryReceiver.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMResourceScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMUserActionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Tests/Mocks/RUMDataModelMocks.swift

Configuration reporting.
- Update the generated models to sync the models. It required for making `sessionReplaySampleRate` optional.
- Whenever a `RUMViewEvent`, `RUMActionEvent`, `RUMResourceEvent`, `RUMErrorEvent` or `RUMLongTaskEvent` is created, it includes configured sampling rate.

RUMM-3450 feat: include session_sample_rate as part of _dd.configuration blob for all RUM events

---

DatadogTrace/Sources/Trace.swift

changed struct Trace into enum Trace.
In Swift practice way, when it comes to making namespace, it's better off using enum.
because struct can be an instance with `Trace()`, enum can not be.

use enum for namespacing

---

BenchmarkTests/DataStorage/LoggingStorageBenchmarkTests.swift
BenchmarkTests/DataStorage/RUMStorageBenchmarkTests.swift
BenchmarkTests/DataStorage/TracingStorageBenchmarkTests.swift

Fixes build of Benchmark Tests by mocking now required context introduced in:
https://github.com/DataDog/dd-sdk-ios/pull/1412

Fix Benchmark Tests Build

---

CHANGELOG.md
Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Tests/DatadogObjc/DDUIKitRUMActionsPredicateTests.swift
DatadogCore/Tests/DatadogObjc/DDUIKitRUMViewsPredicateTests.swift
DatadogObjc/Sources/RUM/RUM+objc.swift

Adds missing default objective-c predicates, which are part of official documentation:
https://docs.datadoghq.com/real_user_monitoring/ios/?tab=objectivec#initialize-the-rum-monitor-and-ddurlsessiondelegate

Add default objc rum predicates

---

DatadogCore/Tests/Datadog/Core/Upload/DataUploadWorkerTests.swift

Fixes compilation issues on Xcode 13.4.x nightly tests.
Older wait() signature requires timeout parameter. This PR adds that.

Fix Xcode 13.4 Nightly Tests

---

DatadogRUM/Sources/RUMMonitorProtocol+Internal.swift

`RUMMonitorProtocol._internal` required that self be the type `Monitor` before creating the DatadogInternalInterface. This was overspecialization and made it hard to mock internal calls. By casting only to `RUMCommandSubscriber` we can more easily create mocks for testing.

fix(internal): Lower constraints when retrieving `_internal`

---

DatadogCore/Tests/Datadog/CrashReporting/CrashContext/CrashContextProviderTests.swift
DatadogCrashReporting/Sources/CrashContext/CrashContextProvider.swift

`CrashContextProviderTests` were flaky due to missing `flush`.
Additionally, we stop retaining the `core` by using `[weak core]` in the crash-context provider's queue.

Fix flakiness in `CrashContextProvider`

---

BenchmarkTests/DataStorage/LoggingStorageBenchmarkTests.swift
BenchmarkTests/DataStorage/RUMStorageBenchmarkTests.swift
BenchmarkTests/DataStorage/TracingStorageBenchmarkTests.swift
DatadogCore/Sources/Core/DatadogCore.swift
DatadogCore/Sources/Core/Storage/FeatureStorage.swift
DatadogCore/Sources/Core/Storage/FilesOrchestrator.swift
DatadogCore/Sources/Core/Storage/Reading/DataReader.swift
DatadogCore/Sources/Core/Storage/Reading/FileReader.swift
DatadogCore/Sources/Core/Storage/Reading/Reader.swift
DatadogCore/Sources/Core/Storage/Writing/FileWriter.swift
DatadogCore/Sources/Core/Upload/DataUploadWorker.swift
DatadogCore/Tests/Datadog/Core/FeatureTests.swift
DatadogCore/Tests/Datadog/Core/Persistence/FilesOrchestrator+MetricsTests.swift
DatadogCore/Tests/Datadog/Core/Persistence/FilesOrchestratorTests.swift
DatadogCore/Tests/Datadog/Core/Persistence/Reading/FileReaderTests.swift
DatadogCore/Tests/Datadog/Core/Persistence/Writing/FileWriterTests.swift
DatadogCore/Tests/Datadog/Core/Upload/DataUploadWorkerTests.swift
DatadogCore/Tests/Datadog/Mocks/CoreMocks.swift
DatadogCore/Tests/Datadog/RUM/RUMEventOutputs/RUMEventFileOutputTests.swift
DatadogCore/Tests/TestsObserver/DatadogTestsObserver.swift

Reverts in background telemetry changes as they're likely to cause integrity checks flakyness.

Revert in background telemetry

---

.github/PULL_REQUEST_TEMPLATE.md
Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCore iOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCore tvOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCrashReporting iOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCrashReporting tvOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc iOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc tvOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogSessionReplay iOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogWebViewTracking iOS.xcscheme
DatadogCore/Tests/Datadog/OpenTracing/OTSpanTests.swift
DatadogCore/Tests/Datadog/Utils/UIKitExtensionsTests.swift
DatadogCore/Tests/TestsObserver/DatadogTestsObserverLoader.m
DatadogCrashReporting/Tests/PLCrashReporterIntegration/DDCrashReportBuilderTests.swift
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests.xcconfig
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests.xcodeproj/xcshareddata/xcschemes/SRSnapshotTests.xcscheme
DatadogTrace/Tests/ContextMessageReceiverTests.swift
IntegrationTests/xctestplans/DatadogCrashReportingIntegrationTests.xctestplan
IntegrationTests/xctestplans/DatadogIntegrationTests.xctestplan
Makefile
bitrise.yml
tools/ci/choose_workflows.py

🔭 Fixing CI Visibility setup for V2 modules, to gain observability into test runs.
* `Datadog.xcworkspace` - it was partially broken 💔, now works for all modules on both iOS and tvOS;
* `IntegrationTests/IntegrationTests.xcworkspace` - no change, was fine 👍;
* `DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests.xcworkspace` - added 🎁.
<p align="center">
</p>
Following [CI Visibility docs](https://docs.datadoghq.com/continuous_integration/tests/swift/?tab=swiftpackagemanager#installing-the-swift-testing-sdk):
* Fixed ENV setup in `DatadogCore` and `DatadogCrashReporting` test schemes.
* Added ENV setup in `DatadogSessionReplay` scheme.
* Enabled CI Visibility for `SRSnapshotTests` project.
Also:
* 🧽 I removed redundant run of `DatadogCrashReporting` tests (they are run [directly from …

fix: Fix CI Visibility setup and maximise tests observability

---

tools/distribution/dogfood.py

dogfooding script stopped to work on CI due to package.resolved version change.
https://app.bitrise.io/build/7985e5cf-113d-413a-8954-fc93d80f33c7
I just manually updated the version requirement and run it locally. Everything seems to work, unless I'm missing something.

Update dogfood script

---

CHANGELOG.md
DatadogCore/Tests/Datadog/RUM/Integrations/CrashReportReceiverTests.swift
DatadogRUM/Sources/Integrations/CrashReportReceiver.swift

📦 Fixes wrong `error.view.name` being reported in some RUM crashes.
| before | after |
|--------|-------|
| <img width="440" alt="before" src="https://github.com/DataDog/dd-sdk-ios/assets/2358722/5edada16-9420-4310-b46f-a6e3b696de5d"> | <img width="437" alt="after" src="https://github.com/DataDog/dd-sdk-ios/assets/2358722/316c8409-48c1-4e6b-8d71-50d96c65fd76"> |
The `view.name` information was not forwarded from the "previous RUM view (before crash)".
In case of `error.view.name` being empty, RUM BE fallbacks to other `view` properties, notably `view.url`, which may cause the wrong name being displayed.

RUM-966 fix: wrong `view.name` reported in RUM crashes

---

DatadogCore/Tests/Datadog/RUM/RUMMonitorTests.swift
DatadogInternal/Sources/Attributes/Attributes.swift
DatadogObjc/Sources/RUM/RUMDataModels+objc.swift
DatadogRUM/Sources/DataModels/RUMDataModels.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMResourceScope.swift
DatadogSessionReplay/Sources/Writer/Models/SRDataModels.swift

Enable cross platform SDKs to specify GraphQL attributes.
We remove all cross-platform attributes first, and only add the graphql struct if the operation type is present.
The implementation might change in the future when we support GraphQL requests monitoring for iOS, but it should not be hard to migrate the cross platform SDKs then.

RUM-1033 Enable graphql attributes from cross platform SDKs

---

DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeIDGenerator.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/NodeRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIDatePickerRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UILabelRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UINavigationBarRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIPickerViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISegmentRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISliderRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIStepperRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISwitchRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITabBarRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextFieldRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UnsupportedViewRecorder.swift
DatadogSessionReplay/Tests/Mocks/RecorderMocks.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeIDGeneratorTests.swift

Refactors id generation for views in session replay. It prevents from reaching type mismatch for the same view but recorded by different recorders and forcing full snapshot change.

RUM-917 Fix unnecessary type mismatch fix

---

DatadogCore/Tests/Matchers/SRRequestMatcher.swift

🧰 Fixing build compatibility for Xcode 13.4.1. We use that version for running nightly unit tests.
Fixed Swift syntax.

chore: Fix build compatibility Xcode 13.4.1 (for nightly tests)

---

DatadogAlamofireExtension.podspec
DatadogCore.podspec
DatadogCrashReporting.podspec
DatadogInternal.podspec
DatadogLogs.podspec
DatadogObjc.podspec
DatadogRUM.podspec
DatadogSDK.podspec
DatadogSDKAlamofireExtension.podspec
DatadogSDKCrashReporting.podspec
DatadogSDKObjc.podspec
DatadogSessionReplay.podspec
DatadogTrace.podspec
DatadogWebViewTracking.podspec
Package.swift
TestUtilities.podspec
TestUtilities/Package.swift
tools/api-surface/Fixtures/Package.swift
tools/api-surface/Package.swift
tools/rum-models-generator/Package.swift
tools/sr-snapshots/Package.swift

Changes the swift version back to 5.7.1 to maintain compatibility with older Xcodes.

Change swift version to 5.7.1

---

DatadogCore/Tests/Datadog/Core/Persistence/DataBlockTests.swift
tools/nightly-unit-tests/bitrise-nightly-unit-tests.yml
tools/nightly-unit-tests/generate_bitrise_yml.py
tools/nightly-unit-tests/src/simulators_parser.py
tools/nightly-unit-tests/src/utils.py
tools/nightly-unit-tests/tests/test_simulators_parser.py

We want to build with Xcode 14.1 which is minimum version of supported Xcode for AppStore.
- Replace xcversion with xcodes.
- fix test cases
FAQs 
**Why not 14.1**
14.1 fails the CI for some unknown reason across the board, my hunch is due to CI visibility SDK but not confirmed.
failure
```
This Step failed, because it has not sent any output for 15m.
```
**Why not 14.2**
the only benefit that we get from 14.2 is to be able to install iOS 12 simulator but because bitrise runs this on Ventura, the Ventura version doesn't support iOS 12.4 simulator. Bummer.
```
The iOS 12.4 simulator runtime is not supported on hosts after macOS 12.99.0.
```
**Why 14.3**
Our rest of the workflows run on 14.3 and it makes sense to match it if not below.

RUM-1098 ci: update stack to Xcode 14.3

---

DatadogCore/Tests/Datadog/Logs/CrashLogReceiverTests.swift
DatadogLogs/Sources/Feature/MessageReceivers.swift
DatadogLogs/Sources/Log/LogEventBuilder.swift
DatadogLogs/Tests/Log/LogEventBuilderTests.swift

Fixes OS name for log events.
**Before fix:**
**After fix:**
Change was quite simple. We should use osName instead of name from context.device.

RUM-1096 Fix os name in log events

---

DatadogObjc/Sources/RUM/RUMDataModels+objc.swift
DatadogRUM/Sources/DataModels/RUMDataModels.swift
DatadogRUM/Sources/Integrations/WebViewEventReceiver.swift
DatadogRUM/Tests/Integrations/WebViewEventReceiverTests.swift
IntegrationTests/IntegrationScenarios/Scenarios/WebView/WebViewScenarioTest.swift

#1433 broke Browser SDK event overwrite. The `AnyEncodable` did encoded integers to `Int64` but the the `WebViewEventReceiver` was still expected `Int`
As a quick fix and to release as part of `2.3.0`, the `WebViewEventReceiver` now expect `Int64`. But a more robust solution will be applied to `develop`.

RUM-1197 fix: WebView Events Overwrite

---

CHANGELOG.md
DatadogCore/Tests/Datadog/CrashReporting/CrashContext/CrashContextProviderTests.swift
DatadogInternal/Sources/Codable/AnyDecodable.swift
DatadogInternal/Sources/Codable/AnyDecoder.swift
DatadogInternal/Tests/Codable/AnyDecodableTests.swift
DatadogObjc/Sources/RUM/RUMDataModels+objc.swift
DatadogRUM/Sources/DataModels/RUMDataModels.swift

Transmitted a `PassthroughAnyCodable` property on the message-bus is failing when decoding it to `AnyDecodable`.
With the new `FeatureBaggage` introduced in #1442, the `RUMSessionState` decoding was failing on crash-reporting side.
> This is not resolving transmitting `nil` in core context.
Support decoding a `PassthroughAnyCodable` value in `AnyDecodable`.

RUM-1197 fix: Passthrough Decoding

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogLogs/Sources/Logs+Internal.swift
DatadogLogs/Tests/LogsTests.swift
DatadogRUM/Sources/RUM+Internal.swift
DatadogRUM/Tests/RUMTests.swift

Adding methods to internal interfaces for the `RUM` and `Logs` structs to determine if the feature is enabled in a particular core.  These are needed for Flutter to correctly initialize RUM and Logs in `attachToExisting` scenarios.
refs: RUM-1066

feat: Add internal `isEnabled` methods for Logs and RUM

---

DatadogCore/Tests/Datadog/RUM/RUMMonitorTests.swift

RUM monitor tests would fail when Configuration telemetry is sent during the test.
Filter out Telemetry events when the test look for sequence of raw events.

Fix `RUMMonitorTests` flakiness

---

DatadogCore/Sources/Core/Storage/FeatureStorage.swift
DatadogCore/Sources/Core/Storage/FilesOrchestrator.swift
DatadogCore/Sources/Utils/CoreMetrics.swift
DatadogCore/Tests/Datadog/Core/Persistence/FilesOrchestrator+MetricsTests.swift

📦 This PR adds observability to batches closed and deleted during `.pending` [Tracking Consent](https://swiftpackageindex.com/datadog/dd-sdk-ios/develop/documentation/datadogcore/trackingconsent). Previously, only `.granted` batches were counted in mobile metrics. To differentiate the value of consent, we add a new attribute:
```
consent: granted | pending
```
Lack of observability in `.pending` state might explain skews in volumes of "deleted" vs "closed" events (56% vs 44%). If batch was completed during `.pending` but sent in `.granted` consent, we would get "batch deleted" with no matching "batch closed".
* Enabled batching metrics for unauthorized orchestrator (the one managing `.pending` batches).
* Added new attribute to each telemetry.

RUM-1188 Add "consent" attribute to batch telemetry

---

IntegrationTests/IntegrationScenarios/Scenarios/SessionReplay/SRMultipleViewsRecordingScenarioTests.swift
IntegrationTests/IntegrationTests.xcodeproj/project.pbxproj
TestUtilities.podspec

📦 Fixing integration tests build.
#1515 added `JSONObjectMatcher.swift` to `TestUtilities` target in main `.pbxproj`. It overlooked the fact that `TestUtilities` are also exposed for integration tests project through `.podspec`, hence the new file was missing for compilation.
The fix ensures that `JSONObjectMatcher.swift` is included in `TestUtilities.podspec`.

RUM-984 Fix integration tests

---

CHANGELOG.md
DatadogSessionReplay/Sources/Processor/Diffing/Diff+SRWireframes.swift
DatadogSessionReplay/Sources/Processor/SRDataModelsBuilder/WireframesBuilder.swift
DatadogSessionReplay/Sources/Recorder/Utilities/ImageDataProvider.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewRecorder.swift
DatadogSessionReplay/Sources/Writer/Models/SRDataModels.swift
DatadogSessionReplay/Tests/Mocks/MockImageDataProvider.swift
DatadogSessionReplay/Tests/Processor/Diffing/Diff+SRWireframesTests.swift
DatadogSessionReplay/Tests/Recorder/Utilties/ImageDataProviderTests.swift

It leverages new `resourceId` field instead of `base64` for calculating diff of image wireframes, speeds up the calculation and lowers the CPU pressure.
We added new field to SR schema (that will be later on used for different purposes) and started using this field instead of base64 to calculate object's hash.
Now, on Shopist it goes as low as 12% of CPU for the most complex view on idle. Used to be 60% before the change.

RUM-1507 Improved diffing

---

Package.swift

SPM only SDK fails to compile
Include the missing source files.

fix: add missing source directory required for JSONObjectMatcher

---

CHANGELOG.md
DatadogCore/Tests/Datadog/Tracing/TracingURLSessionHandlerTests.swift
DatadogInternal/Sources/NetworkInstrumentation/FirstPartyHosts.swift
DatadogInternal/Sources/NetworkInstrumentation/URLSession/DatadogURLSessionDelegate.swift
DatadogInternal/Sources/NetworkInstrumentation/URLSession/URLSessionInstrumentation.swift
DatadogInternal/Tests/NetworkInstrumentation/FirstPartyHostsTests.swift
DatadogInternal/Tests/NetworkInstrumentation/NetworkInstrumentationFeatureTests.swift
DatadogObjc/Sources/DDURLSessionDelegate+objc.swift
DatadogRUM/Sources/RUMConfiguration.swift
DatadogRUM/Tests/Instrumentation/Resources/URLSessionRUMResourcesHandlerTests.swift
DatadogTrace/Sources/TraceConfiguration.swift

Adds W3C tracecontext to default configuration along with datadog headers.

RUM-1555 Update default tracing headers to datadog + W3C (tracecontext)

---

IntegrationTests/IntegrationScenarios/Scenarios/RUM/RUMStopSessionScenarioTests.swift

Fixes integration test, by removing unnecessary assertion. This assert became flaky after adding view event reduction and now it depends on the number of batches created in the lifecycle of the UI Test.

Fix Integration Tests

---

CHANGELOG.md
DatadogCore/Tests/Datadog/TracerTests.swift
DatadogCore/Tests/Datadog/Tracing/TracingURLSessionHandlerTests.swift
DatadogCore/Tests/DatadogObjc/DDTracerTests.swift
DatadogInternal/Sources/NetworkInstrumentation/W3C/W3CHTTPHeaders.swift
DatadogInternal/Sources/NetworkInstrumentation/W3C/W3CHTTPHeadersWriter.swift
DatadogInternal/Tests/NetworkInstrumentation/W3CHTTPHeadersWriterTests.swift
DatadogRUM/Tests/Instrumentation/Resources/URLSessionRUMResourcesHandlerTests.swift

Currently, we don't send vendor specific information (Datadog here) when using W3C tracecontext headers for distibuted tracing.
This PR adds the vendor specific information to the tracecontext headers.
Datadog | tracecontext (W3C)
| - | - |
x-datadog-sampling-priority | s:{sampling-priority}
x-datadog-origin | o:{origin}
Example
```
x-datadog-trace-id: 1229782938247303441 (0x1111111111111111)
x-datadog-parent-id: 2459565876494606882 (0x2222222222222222)
x-datadog-sampling-priority: 2
x-datadog-origin: rum
x-datadog-tags: _dd.p.dm=-4,_dd.p.usr.id=baz64==
```
translates to
```
traceparent: 00-00000000000000001111111111111111-2222222222222222-01
tracestate: dd=s:2;o:rum;t.dm:-4;t.usr.id:baz64~~,othervendor=t61rcWkgMzE
```
x-datadog-tags is not supported by the SDK, hence it is not added to …

RUM-1923 feat: add tracestate headers when using W3C tracecontext

---

DatadogCore/Tests/Datadog/TracerTests.swift
DatadogCore/Tests/Datadog/Tracing/TracingURLSessionHandlerTests.swift
DatadogCore/Tests/DatadogObjc/DDTracerTests.swift
DatadogInternal/Sources/NetworkInstrumentation/W3C/W3CHTTPHeaders.swift
DatadogInternal/Sources/NetworkInstrumentation/W3C/W3CHTTPHeadersWriter.swift
DatadogInternal/Tests/NetworkInstrumentation/W3CHTTPHeadersWriterTests.swift
DatadogRUM/Tests/Instrumentation/Resources/URLSessionRUMResourcesHandlerTests.swift

Currently, if there is broken proxy in between two system, we will have the broken trace.
Hence, we need datadog trace id which can be used to recover the trace.
Eg. RUM SDK > Broken W3C Proxy > DD Tracer (recovered by reading tracestate from RUM SDK).
This PR adds the datadog trace id to the tracestate header using following format
```
p:{hex-encoded parent-id}
```
Example
```
x-datadog-trace-id: 1229782938247303441 (0x1111111111111111)
x-datadog-parent-id: 2459565876494606882 (0x2222222222222222)
x-datadog-sampling-priority: 2
x-datadog-origin: rum
```
translates to
```
traceparent: 00-00000000000000001111111111111111-2222222222222222-01
tracestate: dd=s:2;o:rum;p:2222222222222222
```

RUM-1923 fix: include hex parent id in tracestate

---

Makefile

Enable/Disable Test Instrumentation via env.

Enable/Disable Test Instrumentation

---

DatadogInternal/Sources/NetworkInstrumentation/URLSession/URLSessionDataDelegateSwizzler.swift
DatadogInternal/Sources/NetworkInstrumentation/URLSession/URLSessionTaskDelegateSwizzler.swift
DatadogInternal/Tests/NetworkInstrumentation/URLSessionDataDelegateSwizzlerTests.swift
DatadogInternal/Tests/NetworkInstrumentation/URLSessionTaskDelegateSwizzlerTests.swift

Check on map items is not correct.
Use delegate key checks to see if the type has been swizzled or not.
Manual test
https://github.com/ganeshnj/dd-sdk-ios-example/blob/main/Example/Example/ContentView.swift#L19

RUM-717 fix: use delegate based check to decide swizzle or not for delegate types

---

DatadogSessionReplay/Sources/Processor/Diffing/Diff+SRWireframes.swift
DatadogSessionReplay/Sources/Writer/Models/SRDataModels.swift
bitrise.yml
tools/rum-models-generator/Sources/rum-models-generator/GenerateSRModels.swift

🧰 This PR enables validation of SR data models in CI.
[SRDataModels.swift](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogSessionReplay/Sources/Writer/Models/SRDataModels.swift) is an auto-generated file created from [RUM Events Format](https://github.com/DataDog/rum-events-format) schema. This file should not be modified manually and to assure this, this PR enables CI validation with `make sr-models-validate` (the same way as we check RUM data models).
1. (in `rum-models-generator`) The template file for SR models generation was updated with `#if os(iOS)` macro introduced in https://github.com/DataDog/dd-sdk-ios/pull/1428
2. (in `bitrise.yml`) The `make sr-models-validate` is now run in separate CI step.
3. To make it pass, the manual change inserted to `SRDataModels.swift` in …

Chore: Fix SR data models validation

---

DatadogRUM/Sources/Integrations/WebViewEventReceiver.swift
DatadogRUM/Tests/Integrations/WebViewEventReceiverTests.swift

Browser events not longer set the `_dd.session.plan`, which result in failure to override the `plan` in RUM.
Set `_dd.session.plan` even if `_dd.session` is not provided by Browser.

Fix WebView event parser following Browser v5

---

Datadog/Example/Debugging/DebugManualTraceInjectionViewController.swift
DatadogCore/Tests/Datadog/TracerTests.swift
DatadogCore/Tests/Datadog/Tracing/TracingURLSessionHandlerTests.swift
DatadogCore/Tests/DatadogObjc/DDTracerTests.swift
DatadogInternal/Sources/NetworkInstrumentation/W3C/W3CHTTPHeaders.swift
DatadogInternal/Sources/NetworkInstrumentation/W3C/W3CHTTPHeadersWriter.swift
DatadogInternal/Tests/NetworkInstrumentation/NetworkInstrumentationFeatureTests.swift
DatadogInternal/Tests/NetworkInstrumentation/W3CHTTPHeadersWriterTests.swift
DatadogObjc/Sources/Tracing/Propagation/W3CHTTPHeadersWriter+objc.swift
DatadogRUM/Sources/Instrumentation/Resources/URLSessionRUMResourcesHandler.swift
DatadogRUM/Tests/Instrumentation/Resources/URLSessionRUMResourcesHandlerTests.swift
DatadogTrace/Sources/Integrations/TracingURLSessionHandler.swift

Currently, "rum" origin is added to the tracestate for Trace and RUM features both. This must be added only when using with RUM feature.
This PR adds the origin to the tracestate only when using with RUM feature. Also refactored some code to make the logic more clear.

RUM-2108 fix: include rum origin when using RUM feature for distributed tracing

---

DatadogRUM/Sources/Integrations/WebViewEventReceiver.swift
DatadogRUM/Tests/Integrations/WebViewEventReceiverTests.swift

🍒 Cherry-picking https://github.com/DataDog/dd-sdk-ios/pull/1552 to have the _"Browser V5 Event Parser"_ fix available in `develop` without waiting for `release/2.5.0`.

[cherry-pick] Fix WebView event parser following Browser v5

---

DatadogSessionReplay/Sources/Processor/Privacy/TextObfuscator.swift
DatadogSessionReplay/Sources/Recorder/PrivacyLevel.swift
DatadogSessionReplay/Sources/Recorder/Recorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeRecordingContext.swift
DatadogSessionReplay/Tests/Mocks/SnapshotProducerMocks.swift
DatadogSessionReplay/Tests/Recorder/PrivacyLevelTests.swift
DatadogSessionReplay/Tests/Recorder/RecordingCoordinatorTests.swift

Expose Text Obfuscator and related types for it to be usable in cross platform SDKs
Using `@_spi(Internal)` to make it public.

Expose text obfuscator for cross platform SDKs

---

DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeIDGenerator.swift

Updates maximum Session Replay ID to not exceed 32-bit. It's an overlooked requirement needed by the player to work correctly. Potentially we'll replace ids with String type in the future.

Update Session Replay default maxID

---

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Example iOS.xcscheme
DatadogCore/Tests/Datadog/Mocks/RUMDataModelMocks.swift
DatadogCore/Tests/Datadog/Mocks/RUMFeatureMocks.swift
DatadogObjc/Sources/RUM/RUMDataModels+objc.swift
DatadogRUM/Sources/DataModels/RUMDataModels.swift
DatadogRUM/Sources/Integrations/CrashReportReceiver.swift
DatadogRUM/Sources/RUMContext/RUMContext.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMApplicationScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMResourceScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMSessionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMUserActionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Tests/Mocks/RUMDataModelMocks.swift
DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMApplicationScopeTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMSessionScopeTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift
TestUtilities/Mocks/DatadogContextMock.swift
tools/rum-models-generator/Sources/CodeDecoration/RUMCodeDecorator.swift

📦 As part of **RUM Session Standarization** project, this PR introduces `sessionPrecondition` attribute to RUM events. This is to add more visibility over the reasons for creating RUM sessions.
```swift
enum RUMSessionPrecondition {
case userAppLaunch
case inactivityTimeout
case maxDuration
case backgroundLaunch
case prewarm
case fromNonInteractiveSession    // not implemented in this PR - TODO in RUM-1646
case explicitStop
}
```
Mid-term goal is to simplify the logic of RUM Sessions creation and pay off portions of tech debt incurred in recent https://github.com/DataDog/dd-sdk-ios/pull/1278, https://github.com/DataDog/dd-sdk-ios/pull/1219 and https://github.com/DataDog/dd-sdk-ios/pull/1290 and previous work.
`RUMApplicationScope` is the main component modified in this PR. 
The idea …

RUM-1335 Add `sessionPrecondition` to RUM events

---

tools/distribution/dogfood.py
tools/distribution/src/dogfood/package_resolved.py

💊 This PR fixes following error in dogfooding automation:
```
❌ Failed to dogfood: 'branch'
------------------------------------------------------------
Traceback (most recent call last):
File "/Users/vagrant/git/tools/distribution/dogfood.py", line 118, in <module>
dogfood(
File "/Users/vagrant/git/tools/distribution/dogfood.py", line 68, in dogfood
new_branch=dependency['state']['branch'],
~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'branch'
------------------------------------------------------------
```
As shown [in example](https://github.com/DataDog/dd-sdk-ios/blob/2ee9279870711548fbad89e38ca59637b315a0a4/tools/distribution/tests/dogfood/test_package_resolved.py#L18-L35), in V1 package definition the `branch` or `version` can be `null`, e.g.:
```json
{
"package": "B",
"repositoryURL": …
```

Fix "KeyError: 'branch'" in dogfooding automation

---

DatadogRUM/Sources/Instrumentation/Resources/URLSessionRUMResourcesHandler.swift

Fixes https://github.com/DataDog/dd-sdk-ios/issues/1582
It's just fixing the typo of `initialized` in a warning message
Updated the typo

Issue 1582: Fix typo of initialized 

---

DatadogSessionReplay/Sources/Processor/Flattening/NodesFlattener.swift
DatadogSessionReplay/Tests/Mocks/CoreGraphicsMocks.swift
DatadogSessionReplay/Tests/Processor/Flattening/NodesFlattenerTests.swift
DatadogSessionReplay/Tests/Processor/ProcessorTests.swift
DatadogSessionReplay/Tests/Recorder/RecorderTests.swift
TestUtilities/Helpers/DDAssert.swift

Improve nodes flattener and adds ability to drop the node when it's outside of the bounds of the screen.
It's based on the assumption each node should intersect with the viewport of the snapshot.

Remove node when it's outside of the bounds of the screen

---

CHANGELOG.md
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift

🧰 Fixes the problem of `view.time_spent` increasing infinitely if view scope tracks dangling resources (ones that were started, but never finished). 
The problem originated in the condition meant to close current view scope if next view is started. This piece of logic was executed for every next view, instead of being limited to the succeeding view only.

fix: Fix `view.time_spent` skews

---

DatadogCore/Sources/Datadog.swift
DatadogLogs/Sources/Logs.swift
DatadogRUM/Sources/RUM.swift
DatadogSessionReplay/Sources/SessionReplay.swift

Swift enums are can't be instantiated and the types which are not meant to be instantiated such as Logs, Trace or Datadog must be enums to make the clear to customers.
Change some types from struct to enum

GH-1606 refactor: make non instantiable types as enums

---

CHANGELOG.md
DatadogInternal/Sources/NetworkInstrumentation/NetworkInstrumentationFeature.swift

Fixes #1607 
Because we intercept originalRequest which could have already been mutated, we end up using a stale version of the request.
Use `currentRequest` for interception.

GH-1607 fix: use currentRequest instead originalRequest for interception

---

Package.swift

First PR of otel tracer, to start with only SPM support is going to be provided followed by other supported package managers.
Take a direct dependency on `opentelemetry-swift` and `OpenTelemetryApi` as dependency to Trace product.

RUM-1836 feat(otel-tracer): take dependency on opentelemetry-swift

---

DatadogSessionReplay/Sources/Processor/SRDataModelsBuilder/RecordsBuilder.swift
DatadogSessionReplay/Tests/Processor/ProcessorTests.swift
DatadogSessionReplay/Tests/Processor/SRDataModelsBuilder/RecordsBuilderTests.swift

I noticed a bug in Session Replay when the root wireframe (first wireframe in the list) is added in an incremental snapshot.
This wireframe will have no `previousId`, and the replay will add it last in the list of wireframes.
This should not happen very often, given we create a full snapshot on every RUM view.
Possible improvements for the PR:
- if the new root is already present in the previous wireframe, there is no need to create a new full snapshot
Also it's worth investigating why we're removing root wireframes in the first place (and thus adding them back afterwards).

RUM-1820 Create full snapshot if root has changed

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogTrace/Sources/Trace.swift
DatadogTrace/Tests/TraceTests.swift

CI uses workspace file to build and test ie changes to `Package.swift` file don't help.
```
Signing libclang_rt.tsan_iossim_dynamic.dylib (in target 'DatadogWebViewTrackingTests iOS' from project 'Datadog')
❌ /Users/vagrant/git/DatadogTrace/Sources/Tracer.swift:9:8: no such module 'OpenTelemetryApi'
```
Include `opentelemetry-swift` dependency in project file.

RUM-1836 feat(otel-tracer): update project with opentelemetry-swift dependency

---

DatadogSessionReplay/Sources/Processor/SRDataModelsBuilder/WireframesBuilder.swift

Add font size argument in `createTextWireframe` public builder.
Today passing a `font` argument is the only way to specify a font size for the text wireframe.
With React Native text views we don't get direct access to the `UIFont`. However we get direct access to the fontSize, 
so we can bypass this by creating a new font on every call, but that takes a lot of time and impacts performance (on an app I tested, it took up to 300ms of time over a minute of usage of the app).
I've tried passing `nil` as font (https://github.com/DataDog/dd-sdk-reactnative/pull/570), but then all elements have a small font size.
I believe enabling to specify only the font size is the best way to get a great fidelity with a small performance cost.
It seems that there is no test covering this part of the code, …

Add font size argument in text Wireframe builder

---

DatadogRUM/Sources/RUMMonitor/Scopes/RUMApplicationScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMSessionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift

Print RUM info in case of synthetics run, to let the Synthetics runner create a link to the RUM session

RUM-2442 print RUM info for Synthetics

---

DatadogSessionReplay/Sources/SessionReplay.swift
DatadogSessionReplay/Tests/SessionReplayTests.swift

Customer pointed out that when sample rate for session replay is 0, we still run it's code (including swizzling), but the code remains dormant. It makes sense to provide early return in the enable function, so in cases like using remote config, customer can use the same code and just change the parameter.
Adds a guard that early returns from the enable function when sampling rate is 0.

Do not start Session Replay when it is sampled out

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Tests/Datadog/Tracing/OTelSpanTests.swift
DatadogTrace/Sources/DDSpan.swift
DatadogTrace/Sources/Integrations/TracingWithLoggingIntegration.swift
DatadogTrace/Sources/OpenTelemetry/OTelSpan.swift

event API support which is akin to log API in Datadog
Like other implementations, we leverage the underlying OT log API to send the OTel event.
In OTel world, the name of the event maps to message in Datadog.
Now this 
```swift
let tracer = Tracer.shared()
let span = tracer.spanBuilder(spanName: "SimpleSpan").setSpanKind(spanKind: .client).startSpan()
span.addEvent(name: "foo")
span.setAttribute(key: resourceKey, value: resourceValue)
span.addEvent(name: "My event", attributes: ["message": AttributeValue.string("test message"),
"newKey": AttributeValue.string("New Value")])
span.end()
```
results in

RUM-1836 feat(otel-tracer): add support for event APIs

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogTrace/Sources/OpenTelemetry/OTelAttributeValue+Datadog.swift
DatadogTrace/Sources/OpenTelemetry/OTelSpan.swift
DatadogTrace/Tests/OpenTelemetry/OTelAttributeValue+DatadogTests.swift
DatadogTrace/Tests/OpenTelemetry/OTelSpanTests.swift

Currently, attributes that are array or set which is composition of primitive types are not supported.
Attributes are flattened using the recursive flattening.
This is inspired from Java version of tracer https://github.com/DataDog/dd-trace-java/blob/0f986a71765d0bad85ed4e5c3bc6ef44b8cb78fe/dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/trace/OtelSpan.java#L51-L63
The idea here is to create a key along with the path and save the value as it is in a flat dictionary (tags). In case of arrays, items are indexed with `key.{index}` pattern.

RUM-1836 feat(otel-tracer): support multi level tags using key flattening

---

DatadogTrace/Sources/OpenTelemetry/OTelSpan.swift
DatadogTrace/Tests/OpenTelemetry/OTelSpanTests.swift

Status API
Status API saves of the status of the span indicating whether the span has recorded errors.
This is done by setting error.message tag on the span.
Along with the updating the tags, given dd-sdk-ios sends logs for errors, we replicate the same behavior and record error on the DDSpan which eventually sends a log entry.

RUM-1836 feat(otel-tracer): add support for status API

---

DatadogCore/Sources/Core/Storage/FilesOrchestrator.swift

🧰 The internal `Datadog.internalFlushAndDeinitialize()` does not work without setting `DD_SDK_COMPILED_FOR_TESTING` compiler flag. To simplify the reasoning about internal "flush", I propose to remove this macro from downstream logic. It will be still used to hide the public API behind this feature, see:
https://github.com/DataDog/dd-sdk-ios/blob/a43c63dd422ffd050ed24a1ac1dfd7b156f063c2/DatadogCore/Sources/Datadog.swift#L485-L489
Solves #1618
The "flush" logic was protected twice:
- first, the public API was hidden behind `DD_SDK_COMPILED_FOR_TESTING` flag,
- second, part of its implementation was conditionally enabled on `DD_SDK_COMPILED_FOR_TESTING`.
The second occurrence was redundant and it is removed.

GH1618 Simplify (internal) flushing logic

---

CHANGELOG.md
DatadogCore/Sources/Core/Context/DatadogContextProvider.swift
DatadogCore/Sources/Core/DatadogCore.swift
DatadogCore/Sources/Datadog.swift
DatadogCore/Tests/Datadog/DatadogCore/DatadogCoreTests.swift
DatadogCore/Tests/Datadog/DatadogTests.swift
DatadogRUM/Sources/RUMVitals/VitalRefreshRateReader.swift
IntegrationTests/IntegrationScenarios/Scenarios/Core/StopCoreScenarioTests.swift
IntegrationTests/IntegrationScenarios/Scenarios/RUM/RUMCommonAsserts.swift
IntegrationTests/IntegrationTests.xcodeproj/project.pbxproj
IntegrationTests/Runner/AppConfiguration.swift
IntegrationTests/Runner/AppDelegate.swift
IntegrationTests/Runner/Scenarios/Core/CoreScenarios.swift
IntegrationTests/Runner/Scenarios/Core/StopCoreInstance/CSHomeViewController.swift
IntegrationTests/Runner/Scenarios/Core/StopCoreInstance/CSPictureViewController.swift
IntegrationTests/Runner/Scenarios/Core/StopCoreInstance/CSRootViewController.swift
IntegrationTests/Runner/Scenarios/Core/StopCoreInstance/StopCoreScenario.storyboard
IntegrationTests/Runner/Scenarios/Logging/ManualInstrumentation/SendLogsFixtureViewController.swift
IntegrationTests/Runner/Scenarios/Tracing/ManualInstrumentation/SendTracesFixtureViewController.swift
IntegrationTests/Runner/Scenarios/TrackingConsent/TrackingConsent/TSHomeViewController.swift
IntegrationTests/Runner/Scenarios/URLSession/URLSessionScenarios.swift
IntegrationTests/Runner/Utils/CustomURLSessionDelegate.swift
instrumented-tests/http-server-mock/Sources/HTTPServerMock/ServerMock.swift
instrumented-tests/http-server-mock/python/start_mock_server.py

Add public interface for stopping core instance of the SDK. Stopping the core will deallocate all Features and their storage & upload units.
In parity with Android, the `stopInstance` static method will stop and unregister all feature of the core. Their storage and upload process will be deallocated so no event-write-context and upload will execute.
This change was a good opportunity to streamline flushing mechanism of the core (e.g. #1522). But the number of GDC queues involved in the core and Features made the task very tedious with high risk of introducing flakiness. I believe we should continue decreasing the number of queues, by using exclusion-queue as described in [WWDC 2017 - Modernizing Grand Central Dispatch Usage](https://developer.apple.com/videos/play/wwdc2017/706/), with …

RUM-1040 Stop Core Instance

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogTrace/Sources/OpenTelemetry/OTelSpan.swift
DatadogTrace/Sources/OpenTelemetry/OTelSpanBuilder.swift
DatadogTrace/Sources/OpenTelemetry/OTelSpanLink.swift
DatadogTrace/Sources/OpenTelemetry/OTelTraceState+Datadog.swift
DatadogTrace/Tests/OpenTelemetry/OTelSpanLinkTests.swift
DatadogTrace/Tests/OpenTelemetry/OTelTraceState+DatadogTests.swift
DatadogTrace/Tests/Span/SpanEventBuilderTests.swift

Span link is an otel concept which allows casual relationship among spans. This is similar to parent but it can be many-many.
In datadog, span links are supported via `_dd.span_links` tag which takes a list of links.
A link is represented with 
```json
{
"trace_id": "<exactly 32 character, zero-padded lower-case hexadecimal encoded trace id>",
"span_id": "<exactly 16 character, zero-padded lower-case hexadecimal encoded span id>",
"attributes": {"key":"value", "pairs":"of", "arbitrary":"values"},
"dropped_attributes_count": <decimal 64 bit integer>,
"tracestate": "a tracestate as defined in the W3C standard",
"flags": <an integer representing the flags as defined in the W3C standard>
}
```
Because RUM backend only supports [String: String] tags, this implementation escapes the span links …

RUM-1836 feat(otel-tracer): add support for span links

---

DatadogCore/Tests/Datadog/Mocks/RUMDataModelMocks.swift
DatadogCore/Tests/Datadog/RUM/RUMMonitorTests.swift
DatadogObjc/Sources/RUM/RUMDataModels+objc.swift
DatadogRUM/Sources/DataModels/RUMDataModels.swift
DatadogRUM/Sources/RUMEvent/RUMConnectivityInfoProvider.swift
DatadogRUM/Tests/Mocks/RUMDataModelMocks.swift
Makefile
tools/rum-models-generator/Sources/CodeGeneration/Generate/Transformers/Swift/JSONToSwiftTypeTransformer.swift
tools/rum-models-generator/Tests/CodeGenerationTests/Generate/Transformers/JSONToSwiftTypeTransformerTests.swift
tools/rum-models-generator/run.py

🧰 Fixes the impact of recent update in rum-events-format: https://github.com/DataDog/rum-events-format/pull/177. The PR to Browser RUM schema has changed optionality of the `RUMConnectivity.interfaces` field (non-optional → optional) breaking decoding of browser events in our WebView integration tests:
```
failed - keyNotFound(CodingKeys(stringValue: "interfaces", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "connectivity", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"interfaces\", intValue: nil) (\"interfaces\").", underlyingError: nil)):
```
I updated RUM models to the new commit in `rum-events-format`, so we use recent schema for decoding Browser events.
This comes along with 2 changes to …

chore: Update RUM models to fix webview integration tests

---

CHANGELOG.md
Datadog/Example/Base.lproj/Main iOS.storyboard
Datadog/Example/Debugging/DebugRUMViewController.swift
DatadogInternal/Sources/NetworkInstrumentation/URLSession/URLSessionInstrumentation.swift
DatadogInternal/Sources/NetworkInstrumentation/URLSession/URLSessionSwizzler.swift
DatadogInternal/Sources/NetworkInstrumentation/URLSession/URLSessionTaskSwizzler.swift

🧰 Fixing broken network instrumentation on iOS 13.x and 12.x by remedying the `URLSessionTask.resume()` swizzling and making sure `DatadogInternalTests` pass on these OSes.
When swizzling `URLSessionTask.resume()` selector, the interception callback was not called on iOS 13 and 12. Being inspired with [these hints](https://github.com/FLEXTool/FLEX/blob/81f748a33e257be82f5cdec8e2ddf10e1afddc2f/Classes/Network/PonyDebugger/FLEXNetworkObserver.m#L602-L618), this PR changes the swizzled class to private `__NSCFLocalSessionTask`.
Observation: `__NSCFLocalSessionTask` seems to be uniformly used across existing major versions of the OS, making it a good candidate to swizzle. We can't anticipate if this will continue to work in future versions of the OS. I did several attempts on adding …

RUM-2690 fix: `URLSession*` swizzling issues on iOS 13 and 12

---

CHANGELOG.md
DatadogCore/Sources/Core/Upload/DataUploadStatus.swift
DatadogCore/Tests/Datadog/Core/Upload/DataUploadStatusTests.swift

📦 This PR adds following HTTP status codes to the list of retryable codes. This is to prevent data loss upon receiving them from Intake:
- 502 - bad gateway
- 504 - gateway timeout
- 507 - insufficient storage
Counterpart of: https://github.com/DataDog/dd-sdk-android/pull/1819
Added these codes to `HTTPResponseStatusCode`. We use fuzzy testing in this part, so no extra tests added, but the configuration of existing ones is updated.

RUM-2746 feat: Add additional status codes as retryable

---

Package.swift

Resource path was invalid in `Package.swift`

RUM-456 fix: SPM resource path

---

CHANGELOG.md
Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/CrashReporting/SendingCrashReportTests.swift
DatadogCore/Tests/Datadog/Logs/CrashLogReceiverTests.swift
DatadogCore/Tests/Datadog/Mocks/CrashReportingFeatureMocks.swift
DatadogCrashReporting/Sources/CrashReporting.swift
DatadogLogs/Sources/Feature/Baggages.swift
DatadogLogs/Sources/Feature/MessageReceivers.swift
DatadogLogs/Sources/Log/LogEventEncoder.swift
DatadogLogs/Sources/RemoteLogger.swift
DatadogLogs/Tests/WebViewLogReceiverTests.swift

📦 This PR adds link to the RUM session for crash reports sent as emergency Log event.
See:
With the "last `RUMViewEvent`" being already encoded in `CrashContext.data`, this PR adds extra logic in `DatadogLogs` to decode RUM session attributes. Decoding is limited only to these fields that are required so we don't decode the whole event (that wouldn't be even possible as `DatadogLogs` has no dependency on `DatadogRUM`).
Once decoded, these attributes are attached to `LogEvent` following the contract between SDK and Datadog app.
Except unit tests covering edge cases (like malformed RUM view information), this PR also adds integration unit tests for "Sending Crash Reports as Logs and RUM".
Last, I took extra time to document logs, spans and RUM correlations in [this spec …

RUM-1833 feat: Link (emergency) crash Logs to crashed RUM session

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/Public/NetworkInstrumentationIntegrationTests.swift
DatadogInternal/Sources/NetworkInstrumentation/DatadogURLSessionHandler.swift
DatadogInternal/Sources/NetworkInstrumentation/NetworkInstrumentationFeature.swift
DatadogInternal/Sources/NetworkInstrumentation/URLSession/URLSessionTaskInterception.swift
DatadogInternal/Tests/NetworkInstrumentation/NetworkInstrumentationFeatureTests.swift
DatadogRUM/Sources/Instrumentation/Resources/URLSessionRUMResourcesHandler.swift
DatadogRUM/Tests/Instrumentation/Resources/URLSessionRUMResourcesHandlerTests.swift
DatadogTrace/Sources/Integrations/TracingURLSessionHandler.swift
DatadogTrace/Tests/TracingURLSessionHandlerTests.swift
TestUtilities/Mocks/NetworkInstrumentationMocks.swift

Proposal on propagating parent span id to distributing tracing.
Additionally, stop overwriting propagation headers.
`DatadogTrace` now uses the active span as parent context in distributing tracing, if available.
Parent span propagation only works with APM, not with RUM-to-APM.

RUM-2149 Propagate Parent Span

---

CHANGELOG.md
DatadogCore/Resources/PrivacyInfo.xcprivacy

Missing the `NSPrivacyCollectedDataTypes` prevents from generating the Privacy Report.
Resolve #1655

Add `NSPrivacyCollectedDataTypes`

---

.gitlab-ci.yml
Datadog/Example/Utils/ConsoleOutputInterceptor.swift
DatadogCore/Tests/Datadog/DatadogCore/Context/CarrierInfoPublisherTests.swift
DatadogCore/Tests/Datadog/TracerTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeRecorderTests.swift
Makefile

⚙️ This PR adds GitLab configuration to run unit and integration tests. This is to start shadowing their runs using new runner. No change to Bitrise CI configuration, which remains to be our main CI.
We use Xcode 15.0.1 on GitLab with running tests on iOS 17.
Added simple GitLab pipeline:
```
[ ENV info ]
↓
[ Lint ]
↓
[SDK unit tests (iOS)] + [SDK unit tests (tvOS)] + [SDK integration tests (iOS)]
```
In GitLab stages are sequential and jobs are parallel, meaning the test jobs will run in parallel.
🎁 I had to fix few remaining Xcode 15 x iOS 17 issues that were not spotted in #1640.
For the moment, GitLab status seems to be synced into this PR, so it may block it if the pipeline fails. My guess is we need to disable it in branch protection settings (on GitHub). This will be likely …

RUM-2700 chore: Shadow unit and integration test runs in GitLab

---

.gitlab-ci.yml

📦 Supplement for #1654. This PR allows failure in GitLab jobs. This is to not block the status of GH PRs while GitLab setup is still being evaluated.
Adding `allow_failure: true` to all GitLab jobs.
We can still know which jobs have failed, but their faults will not block our workflow. I also created `RUM-3158` to enable [Pipelines Visibility](https://docs.datadoghq.com/continuous_integration/pipelines/gitlab/?tab=gitlabcom) product and get further insights into performance of GitLab in our work.

RUM-2700 chore: Allow job failures in shadowing test runs on GitLab

---

DatadogCore.podspec
DatadogCore/Resources/PrivacyInfo.xcprivacy
dependency-manager-tests/carthage/App/PrivacyInfo.xcprivacy
dependency-manager-tests/carthage/App/ViewController.swift
dependency-manager-tests/carthage/CTProject.xcodeproj/project.pbxproj
dependency-manager-tests/cocoapods/App/PrivacyInfo.xcprivacy
dependency-manager-tests/cocoapods/App/ViewController.swift
dependency-manager-tests/cocoapods/CPProject.xcodeproj/project.pbxproj
dependency-manager-tests/spm/App/PrivacyInfo.xcprivacy
dependency-manager-tests/spm/App/ViewController.swift
dependency-manager-tests/spm/SPMProject.xcodeproj.src/project.pbxproj
dependency-manager-tests/xcframeworks/App/PrivacyInfo.xcprivacy
dependency-manager-tests/xcframeworks/App/ViewController.swift
dependency-manager-tests/xcframeworks/XCProject.xcodeproj/project.pbxproj

When using static linkage in CocoaPods with `use_frameworks! :linkage => :static`. The pod's resource gets copied at root of the app bundle, resulting in collision with the app's `PrivacyInfo.xcprivacy`.
Resolve #1665
Use `resource_bundle` to keep the `PrivacyInfo.xcprivacy` in it own bundle.
The smoke tests apps now all define privacy-manifest to catch any collision.

Fix privacy manifest collision

---

DatadogCore/Tests/Matchers/SRRequestMatcher.swift
DatadogCore/Tests/Matchers/SRSegmentMatcher.swift
DatadogSessionReplay/Sources/Feature/RequestBuilders/JSON/SegmentJSONBuilder.swift
DatadogSessionReplay/Sources/Feature/RequestBuilders/Multipart/MultipartFormData.swift
DatadogSessionReplay/Sources/Feature/RequestBuilders/ResourceRequestBuilder.swift
DatadogSessionReplay/Sources/Feature/RequestBuilders/SegmentRequestBuilder.swift
DatadogSessionReplay/Tests/Feature/RequestBuilder/JSON/SegmentJSONBuilderTests.swift
DatadogSessionReplay/Tests/Feature/RequestBuilder/Multipart/MultipartFormDataTests.swift
DatadogSessionReplay/Tests/Feature/RequestBuilder/ResourceRequestBuilderTests.swift
DatadogSessionReplay/Tests/Feature/RequestBuilder/SegmentRequestBuilderTests.swift
DatadogSessionReplay/Tests/Mocks/MultipartBuilderSpy.swift
IntegrationTests/IntegrationScenarios/Scenarios/SessionReplay/SRMultipleViewsRecordingScenarioTests.swift

The replay endpoint now supports multiple segments in multipart forms.
Follow specs from https://github.com/DataDog/dd-sdk-android/pull/1805

RUM-2818 New Replay Payload Format

---

Cartfile
Cartfile.resolved
Datadog/Datadog.xcodeproj/project.pbxproj
DatadogTrace.podspec
DatadogTrace/Sources/OpenTelemetry/OTelAttributeValue+Datadog.swift
DatadogTrace/Sources/OpenTelemetry/OTelSpan.swift
Makefile
dependency-manager-tests/carthage/CTProject.xcodeproj/project.pbxproj
dependency-manager-tests/carthage/Makefile
dependency-manager-tests/cocoapods/CPProject.xcodeproj/project.pbxproj
dependency-manager-tests/xcframeworks/Makefile
dependency-manager-tests/xcframeworks/XCProject.xcodeproj/project.pbxproj
tools/distribution/build-xcframework.sh

Otel APIs must work on all packages manager setups.
This PR introduces mechanism to consume the Trace package with pure xcframework, CP, Carthage  and SPM (already added). This is done via shipping the `OpenTelemetryApi` package as a standalone package in all three formats. Its release are managed at https://github.com/DataDog/opentelemetry-swift-packages
https://datadoghq.atlassian.net/browse/RUM-3185 is created to re-enable the CI visibility.

RUM-1836 feat(otel-tracer) integrate OpenTelemetrySwiftApi in package managers

---

Cartfile
Cartfile.resolved
Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Tests/Datadog/Tracing/OTelSpanTests.swift
DatadogTrace/Sources/OpenTelemetry/OTelTracerProvider.swift
DatadogTrace/Sources/Tracer.swift

In current setup, `Tracer.shared(in:)` returns instances of both OT and OTel tracers which can be confusing to customers. Specially new customers who don't understand both standards and they will end mix using both OT and OTel APIs which is not a great experience.
Fallback on the OTel way of doing the things by providing `OTelTracerProvider` which conforms to `OpenTelemetryApi.TracerProvider`.

RUM-1836 feat(otel-tracer): refactor "how to get otel tracer"

---

DatadogCore/Sources/Core/DatadogCore.swift
DatadogCore/Sources/Core/Storage/FeatureStorage.swift
DatadogCore/Sources/Core/Storage/FilesOrchestrator.swift
DatadogCore/Sources/Core/Storage/Writing/FileWriter.swift
DatadogCore/Tests/Datadog/Core/FeatureTests.swift
DatadogCore/Tests/Datadog/Core/Persistence/FilesOrchestrator+MetricsTests.swift
DatadogCore/Tests/Datadog/Core/Persistence/FilesOrchestratorTests.swift
DatadogCore/Tests/Datadog/Core/Persistence/Writing/FileWriterTests.swift
DatadogCore/Tests/Datadog/Core/Upload/DataUploadWorkerTests.swift
DatadogCore/Tests/Datadog/DatadogCore/DatadogCoreTests.swift
DatadogCore/Tests/Datadog/Mocks/CoreMocks.swift
DatadogCore/Tests/Datadog/Mocks/DatadogInternal/DatadogCoreProxy.swift
DatadogCore/Tests/Datadog/RUM/RUMEventOutputs/RUMEventFileOutputTests.swift
DatadogInternal/Sources/DatadogCoreProtocol.swift
DatadogLogs/Sources/Feature/MessageReceivers.swift
DatadogSessionReplay/Sources/Writers/RecordWriter.swift
DatadogSessionReplay/Sources/Writers/ResourcesWriter.swift
DatadogSessionReplay/Tests/Writer/RecordsWriterTests.swift
DatadogTrace/Sources/Span/SpanWriteContext.swift
DatadogTrace/Tests/Span/SpanWriteContextTests.swift
TestUtilities/Mocks/CoreMocks/PassthroughCoreMock.swift
TestUtilities/Mocks/CoreMocks/SingleFeatureCoreMock.swift

Replay endpoint now support multiple segments per request, remove the need for forcing a new batch.
Remove force-new-batch ability.

RUM-2817 Remove forcing a new batch

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/Utils/ImageRendering.swift
DatadogSessionReplay/Sources/Models/SRDataModels.swift
DatadogSessionReplay/Sources/Processor/Diffing/Diff+SRWireframes.swift
DatadogSessionReplay/Sources/Processor/SRDataModelsBuilder/RecordsBuilder.swift
DatadogSessionReplay/Sources/Processor/SRDataModelsBuilder/WireframesBuilder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/WKWebViewRecorder.swift
DatadogSessionReplay/Tests/Mocks/SRDataModelsMocks.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/WKWebViewRecorderTests.swift
tools/rum-models-generator/Sources/CodeDecoration/SRCodeDecorator.swift

Add support of the new `WebViewWireframe`.
`WKWebView` is still part of the unsupported views as we need updates in the JS bridge which are coming in a following PR.

RUM-2815 [SR] feat: Web-view Wireframe and Recorder

---

CHANGELOG.md
Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/RUM/AppHangsMonitoringTests.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/Instrumentation/AppHangs/AppHangsObserver.swift
DatadogRUM/Sources/Instrumentation/AppHangs/AppHangsWatchdogThread.swift
DatadogRUM/Sources/Instrumentation/RUMInstrumentation.swift
DatadogRUM/Sources/RUMConfiguration.swift
DatadogRUM/Tests/Instrumentation/AppHangs/AppHangsWatchdogThreadTests.swift
DatadogRUM/Tests/Instrumentation/RUMInstrumentationTests.swift
tools/lint/sources.swiftlint.yml
tools/lint/tests.swiftlint.yml

📦 First part of non-fatal App Hangs monitoring as RUM errors. App Hangs lasting more than 2s (TBD) will be reported as RUM errors.
Before this change, App Hangs were only tracked as RUM long tasks through [`RUM.LongTaskObserver`](https://github.com/DataDog/dd-sdk-ios/blob/3f2d8a043ec54b0f0aaa719797e97809551d0643/DatadogRUM/Sources/Instrumentation/LongTasks/LongTaskObserver.swift#L73), using the default threshold of 0.1s. Because long tasks are tracked on the main thread (using `CFRunLoopObserver`) it is impossible to capture their backtrace during the hang. Lack of stack traces makes it harder to troubleshoot, hence we implement additional layer of reporting hangs as RUM errors using secondary watchdog thread.
Next PRs will add logic for capturing the stack trace of the hanged main …

RUM-2925 feat: Report non-fatal App Hangs as RUM errors

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/ExampleAppDelegate.swift
Datadog/IntegrationUnitTests/CrashReporting/GeneratingBacktraceTests.swift
Datadog/IntegrationUnitTests/RUM/AppHangsMonitoringTests.swift
DatadogCrashReporting/Sources/Integrations/BacktraceReporter.swift
DatadogCrashReporting/Sources/PLCrashReporterIntegration/PLCrashReporterIntegration.swift
DatadogCrashReporting/Sources/ThirdPartyCrashReporter.swift
DatadogCrashReporting/Tests/Mocks.swift
DatadogInternal/Sources/BacktraceReporting/BacktraceReporter.swift
DatadogInternal/Sources/BacktraceReporting/BacktraceReportingFeature.swift
DatadogRUM/Sources/DataModels/RUMDataModelsMapping.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/Instrumentation/AppHangs/AppHangsObserver.swift
DatadogRUM/Sources/Instrumentation/AppHangs/AppHangsWatchdogThread.swift
DatadogRUM/Sources/Instrumentation/RUMInstrumentation.swift
DatadogRUM/Sources/RUMMonitor/RUMCommand.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Tests/Instrumentation/AppHangs/AppHangsWatchdogThreadTests.swift
DatadogRUM/Tests/Instrumentation/RUMInstrumentationTests.swift
TestUtilities/Helpers/UIKitHelpers.swift
TestUtilities/Mocks/BacktraceReportingMocks.swift
TestUtilities/Mocks/FeatureModels/CrashReporting/BacktraceReportMocks.swift
TestUtilities/Mocks/FeatureModels/CrashReporting/BinaryImageMocks.swift
TestUtilities/Mocks/FeatureModels/CrashReporting/DDCrashReportMocks.swift
TestUtilities/Mocks/FeatureModels/CrashReporting/DDThreadMocks.swift

📦 Following #1685 and #1687, this PR adds `error.stack`, `error.threads` and `error.binary_images` for App Hang RUM errors, so they can be later symbolicated in Datadog app:
<p align="center">
</p>
This leverages the [`generateLiveReportWithThread:`](https://github.com/microsoft/plcrashreporter/blob/c071a07986a527d961383558e0604a456fb64b92/Source/PLCrashReporter.m#L675-L686) API from PLCR, to promote the main thread stack as the key one in produced Live Report. In our domain, it is called through convenience variant next to `generateBacktrace()` added earlier in #1687. To identify the thread, we use [`thread_t`](https://developer.apple.com/documentation/kernel/thread_t) aliased through  `DatadogInternal.ThreadID`.
The backtrace for the caller thread or and any thread can be generated as …

RUM-2925 feat: Add stack trace to App Hang errors in RUM

---

Datadog/Example/ExampleAppDelegate.swift
Datadog/IntegrationUnitTests/Public/NetworkInstrumentationIntegrationTests.swift
Datadog/IntegrationUnitTests/RUM/StartingRUMSessionTests.swift
DatadogInternal/Sources/NetworkInstrumentation/NetworkInstrumentationFeature.swift
DatadogInternal/Sources/NetworkInstrumentation/URLSession/DatadogURLSessionDelegate.swift
DatadogInternal/Sources/NetworkInstrumentation/URLSession/NetworkInstrumentationSwizzler.swift
DatadogInternal/Sources/NetworkInstrumentation/URLSession/URLSessionSwizzler.swift
DatadogInternal/Sources/NetworkInstrumentation/URLSession/URLSessionTask+Tracking.swift
DatadogInternal/Tests/NetworkInstrumentation/URLSessionSwizzlerTests.swift
DatadogRUM/Sources/RUMConfiguration.swift

Fixes #1680
This PR mimics the old behavior of the instrumentation.
When completion handler is provided in `URLSession` APIs, `urlSession(_:dataTask:didReceive:)` is not called, which means we can't buffer the data and in the called the Resource Attribute Provider.
This is not only true for the completion handler based APIs but also true for async-await APIs.
Meanwhile we use 	`urlSession(_:task:didFinishCollecting:)` to mark the completion of the network operation which is the only reliable API at this moment. We use this to mark completion for async-await APIs.
For some APIs, both `urlSession(_:task:didFinishCollecting:)` and `urlSession(_:task:didCompleteWithError:)` are called. But there is not specific order guaranteed which one comes first, ie the one called first, marks the end of …

fix: pass through data when network request completes

---

Datadog/IntegrationUnitTests/RUM/AppHangsMonitoringTests.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/Instrumentation/RUMInstrumentation.swift
DatadogRUM/Sources/RUMConfiguration.swift
DatadogRUM/Tests/RUMConfigurationTests.swift
DatadogRUM/Tests/RUMTests.swift

📦 The final touch on https://github.com/DataDog/dd-sdk-ios/pull/1699. Adding public API for App Hangs monitoring in `RUM.Configuration`:
```swift
/// Enables App Hangs monitoring with the given threshold (in seconds).
///
/// Only App Hangs that last more than this threshold will be reported. The minimal allowed value for this option is `0.1` seconds.
/// To disable hangs monitoring, set this parameter to `nil`.
///
/// - Note: Be cautious when setting the threshold to very small values, as it may lead to excessive reporting of hangs.
///         The SDK implements a secondary thread for monitoring App Hangs. To reduce CPU utilization, it tracks hangs with a tolerance of 2.5%, meaning that
///         some hangs lasting very close to this threshold may not be reported.
///
/// - Note: App …
```

RUM-2925 feat: Add public API for non-fatal App Hangs monitoring

---

DatadogTrace/Sources/DatadogTracer.swift
DatadogTrace/Tests/OpenTelemetry/OTelSpanTests.swift

Client is not right value for the span kind as per definition of
>CLIENT Indicates that the span describes a request to some remote service. This span is usually the parent of a remote SERVER span and does not end until the response is received.
Source: https://opentelemetry.io/docs/specs/otel/trace/api/#spankind
Revert to default ie Internal.

RUM-1836 feat(otel-tracer): change default span kind to internal

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore.podspec
DatadogCore/Resources/PrivacyInfo.xcprivacy
DatadogCrashReporting.podspec
DatadogCrashReporting/Resources/PrivacyInfo.xcprivacy
DatadogRUM.podspec
DatadogRUM/Resources/PrivacyInfo.xcprivacy
DatadogSDKCrashReporting.podspec
Package.swift
dependency-manager-tests/carthage/App/PrivacyInfo.xcprivacy
dependency-manager-tests/cocoapods/App/PrivacyInfo.xcprivacy
dependency-manager-tests/cocoapods/CPProject.xcodeproj/project.pbxproj
dependency-manager-tests/spm/App/PrivacyInfo.xcprivacy
dependency-manager-tests/spm/Makefile
dependency-manager-tests/xcframeworks/App/PrivacyInfo.xcprivacy

Add data use decription in Privacy Manifests for:
- `DatadogCore`
- `DatadogRUM`
- `DatadogCrashReporting`

RUM-3291 Privacy Manifest - describe data use

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Tests/Datadog/Mocks/RUMFeatureMocks.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/Integrations/WebViewEventReceiver.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMScopeDependencies.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMSessionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/Utils/ViewCache.swift
DatadogRUM/Tests/Integrations/WebViewEventReceiverTests.swift
DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMSessionScopeTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/Utils/ViewCacheTests.swift
IntegrationTests/IntegrationScenarios/Scenarios/WebView/WebViewScenarioTest.swift
IntegrationTests/Runner/Scenarios/WebView/WebViewScenarios.swift

As part of WebView Replay requirements, each Browser event should include a `container` field with the native source and `view.id`. As described in [_view-container-schema.json](https://github.com/DataDog/rum-events-format/blob/master/schemas/rum/_view-container-schema.json).
This field will help the player to retrieve the Browser RUM View contained in a native replay.
The Browser SDK sends views through the JS bridge asynchronously with delays, meaning that a browser event could come from a previous view. See the following user-journey:
```
View 1 (id: 1) -> View 2 (id: 2) -> Back to View 1 (id: 3)
```
Assuming that View 1 presents a web-view, we could receive Browser events contained in view.id 1 while being in view.id 3.
To assign the right container to the right Browser event, we need …

RUM-3437 Inject Container to Browser Events

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/Public/TelemetryCoreIntegrationTests.swift
DatadogCore/Sources/Core/Storage/FilesOrchestrator.swift
DatadogCore/Sources/Utils/CoreMetrics.swift
DatadogInternal/Sources/Telemetry/Telemetry.swift
DatadogInternal/Sources/Utils/SharedMetrics.swift
DatadogInternal/Tests/Telemetry/TelemetryTests.swift
DatadogRUM/Sources/Integrations/TelemetryReceiver.swift
DatadogRUM/Tests/Integrations/TelemetryReceiverTests.swift
DatadogSessionReplay/Sources/Recorder/Recorder.swift
DatadogSessionReplay/Tests/Recorder/RecorderTests.swift

This PR adds telemetry for [Method Called (internal)](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3528197707/Method+Called+Telemetry+-+Spec).
This telemetry allows measuring execution time of methods + adds call side sampling for heavily called functions.
Along with these interfaces, we implement first function to utilise this: `SessionReplay.Recorder.captureNextRecord()`.
It's mostly reusing existing strategy for Batch metrics adding a little bit of convenience methods for measuring execution time.

RUM-1843 Method Call telemetry

---

CHANGELOG.md
DatadogLogs/Sources/Feature/MessageReceivers.swift
DatadogLogs/Sources/Log/LogEventBuilder.swift
DatadogLogs/Sources/Log/LogEventEncoder.swift
DatadogLogs/Sources/Logs.swift
DatadogLogs/Sources/RemoteLogger.swift
DatadogLogs/Tests/Log/LogEventBuilderTests.swift
DatadogLogs/Tests/RemoteLoggerTests.swift
DatadogRUM/Sources/RUM.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMResourceScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMResourceScopeTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift
IntegrationTests/IntegrationScenarios/Scenarios/Logging/LoggingScenarioTests.swift
IntegrationTests/IntegrationScenarios/Scenarios/RUM/RUMManualInstrumentationScenarioTests.swift
IntegrationTests/IntegrationTests.xcodeproj/project.pbxproj
IntegrationTests/Runner/Scenarios/Logging/ManualInstrumentation/SendLogsFixtureViewController.swift
IntegrationTests/Runner/Scenarios/RUM/ManualInstrumentation/SendRUMFixture1ViewController.swift
IntegrationTests/Runner/Scenarios/RUM/ManualInstrumentation/SendRUMFixture3ViewController.swift

Allow users to provide custom error fingerprint attribute.
In Logs the attribute `Logs.Attributes.errorFingerprint` is added to any log call and added to the `LogEvent.Error.fingerprint` member. 
In RUM, the attribute `RUM.Attributes.errorFingterprint` is added to  `addError` calls and it is transferred to the `RUMError.finterprint` member
refs: RUM-2906
A special attribute (defined at `Logs.Attributes.errorFingerprint`) is read and moved during LogEvent creation

feat(logs): Add error fingerprint attribute

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Sources/Core/DataStore/DataStore+TLV.swift
DatadogCore/Sources/Core/DataStore/DataStoreFileReader.swift
DatadogCore/Sources/Core/DataStore/DataStoreFileWriter.swift
DatadogCore/Sources/Core/DataStore/FeatureDataStore.swift
DatadogCore/Sources/Core/DatadogCore.swift
DatadogCore/Sources/Core/Storage/Directories.swift
DatadogCore/Sources/Core/Storage/Files/File.swift
DatadogCore/Sources/Core/Storage/Storage+TLV.swift
DatadogCore/Sources/Core/TLV/TLVBlock.swift
DatadogCore/Sources/Core/TLV/TLVBlockReader.swift
DatadogCore/Tests/Datadog/Core/DataStore/DataStore+TLVTests.swift
DatadogCore/Tests/Datadog/Core/DataStore/DataStoreFileReaderTests.swift
DatadogCore/Tests/Datadog/Core/DataStore/DataStoreFileWriterTests.swift
DatadogCore/Tests/Datadog/Core/DataStore/FeatureDataStoreTests.swift
DatadogCore/Tests/Datadog/Core/TLV/TLVBlockReaderTests.swift
DatadogCore/Tests/Datadog/Core/TLV/TLVBlockTests.swift
DatadogCore/Tests/Datadog/DatadogCore/DatadogCore+FeatureDataStoreTests.swift
DatadogCore/Tests/Datadog/Mocks/DatadogInternal/DatadogCoreProxy.swift
DatadogCore/Tests/Datadog/Mocks/DirectoriesMock.swift
DatadogCore/Tests/Helpers/DatadogExtensions.swift
DatadogInternal/Sources/DataStore/DataStore.swift
DatadogInternal/Sources/DatadogCoreProtocol.swift
TestUtilities/Helpers/DDAssert.swift
TestUtilities/Helpers/TestsDirectory.swift
TestUtilities/Mocks/CoreMocks/FeatureRegistrationCoreMock.swift
TestUtilities/Mocks/CoreMocks/PassthroughCoreMock.swift
TestUtilities/Mocks/FoundationMocks.swift

📦 This PR introduces a `DataStore` interface designed to store key-value pairs for a given feature. The primary goal is to provide a mechanism for persisting data between app launches.
For the full list of use cases and requirements considered in this implementation, see [RFC - Local Datastore (internal)](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3327557955/RFC+-+Local+Datastore+Problem+Statement).
**New APIs**
`DataStore` interface:
```swift
public protocol DataStore {
func setValue(_ value: Data, forKey key: String, version: DataStoreKeyVersion = 0) {}
func value(forKey key: String, callback: @escaping (DataStoreValueResult) -> Void) {}
func removeValue(forKey key: String) {}
}
public enum DataStoreValueResult {
case value(Data, DataStoreKeyVersion)
case noValue
case …
```

RUM-3462 feat: Introduce `DataStore`

---

TestUtilities/Mocks/CoreMocks/PassthroughCoreMock.swift

🧰 Fixing CI which fails on `@testable import` (in `TestUtilities`) when running integration tests.
`@testable import DatadogInternal` → `import DatadogInternal` as `@testable` is not necessary.

fix: Fix compilation problem in integration tests

---

instrumented-tests/http-server-mock/Sources/HTTPServerMock/ServerSession.swift
instrumented-tests/http-server-mock/Tests/HTTPServerMockTests/HTTPServerMockTests.swift

📦 Adding more context to `HTTPServerMock` errors in UI testing.
This is ambiguous if we pull data from more than 2 endpoints in test:
Added extra context on what endpoint is being pulled and what is the caller code.

chore: Add more context to `HTTPServerMock` errors

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Sources/Core/DatadogCore.swift
DatadogCore/Tests/Datadog/DatadogCore/DatadogCore+FeatureDataStoreTests.swift
DatadogCore/Tests/Datadog/DatadogCore/DatadogCoreTests.swift
DatadogCore/Tests/Datadog/Mocks/DatadogInternal/DatadogCoreProxy.swift
DatadogCore/Tests/Datadog/RUM/RUMMonitorConfigurationTests.swift
DatadogInternal/Sources/DatadogCoreProtocol.swift
DatadogLogs/Sources/Feature/MessageReceivers.swift
DatadogLogs/Sources/RemoteLogger.swift
DatadogRUM/Sources/Instrumentation/Actions/SwiftUI/SwiftUIActionModifier.swift
DatadogRUM/Sources/Integrations/CrashReportReceiver.swift
DatadogRUM/Sources/Integrations/TelemetryReceiver.swift
DatadogRUM/Sources/Integrations/WebViewEventReceiver.swift
DatadogRUM/Sources/RUMMonitor/Monitor.swift
DatadogSessionReplay/Sources/Writers/RecordWriter.swift
DatadogSessionReplay/Sources/Writers/ResourcesWriter.swift
DatadogTrace/Sources/Span/SpanWriteContext.swift
TestUtilities/Mocks/CoreMocks/FeatureRegistrationCoreMock.swift
TestUtilities/Mocks/CoreMocks/FeatureScopeMock.swift
TestUtilities/Mocks/CoreMocks/PassthroughCoreMock.swift
TestUtilities/Mocks/CoreMocks/SingleFeatureCoreMock.swift

📦 This PR straightens the `FeatureScope` interface, proposing it to become the main (and in most cases the only) dependency for features implementation. Instead of spreading the `core` reference across features and managing it in a `weak` manner, the implementation should take a strong dependency on `FeatureScope`.
There are 3 category of motivations behind this change:
- Short-term goal: Necessary for fatal App Hangs monitoring. This change is to ensure `DataStore` can be available in `AppHangsObserver` before `RUMFeature` is initialized. 
- Mid-term goal: We want features implementation to take dependency on `FeatureScope` rather than managing the `DatadogCoreProtocol` reference by themselves. As this PR proves, **manual management of the core reference is error-prone** and may …

RUM-3462 refactor: Make `FeatureScope` always available

---

CHANGELOG.md
Datadog/Example/ExampleAppDelegate.swift
DatadogCore/Tests/Datadog/Logs/CrashLogReceiverTests.swift
DatadogCore/Tests/Datadog/Mocks/LogsMocks.swift
DatadogCore/Tests/Matchers/LogMatcher.swift
DatadogLogs/Sources/Feature/LogsFeature.swift
DatadogLogs/Sources/Feature/MessageReceivers.swift
DatadogLogs/Tests/Mocks/LoggingFeatureMocks.swift
IntegrationTests/IntegrationScenarios/Scenarios/CrashReporting/CrashReportingWithLoggingScenarioTests.swift
IntegrationTests/Runner/Scenarios/CrashReporting/CrashReportingScenarios.swift

This adds a call to the configured log event mapper when a crash is reported to the Logs feature.  It's tested in the integration test app by adding a fingerprint to the reported crash.
refs: RUM-2209

feat: Support eventMapper on crashes for logs

---

IntegrationTests/IntegrationScenarios/Scenarios/SessionReplay/SRMultipleViewsRecordingScenarioTests.swift

Fix flakiness in Session Replay Integration Tests by changing the baseline expectation.

Fix flakiness - Follow baseline from new segment payload

---

DatadogCore/Tests/Datadog/Mocks/RUMFeatureMocks.swift
DatadogCore/Tests/Datadog/RUM/Integrations/CrashReportReceiverTests.swift
DatadogCore/Tests/Datadog/RUM/RUMMonitorConfigurationTests.swift
DatadogInternal/Sources/DatadogCoreProtocol.swift
DatadogInternal/Sources/MessageBus/FeatureMessageReceiver.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/Integrations/CrashReportReceiver.swift
DatadogRUM/Sources/Integrations/ErrorMessageReceiver.swift
DatadogRUM/Sources/Integrations/TelemetryReceiver.swift
DatadogRUM/Sources/Integrations/WebViewEventReceiver.swift
DatadogRUM/Sources/RUMMonitor/Monitor.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMScopeDependencies.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMSessionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Tests/Integrations/ErrorMessageReceiverTests.swift
DatadogRUM/Tests/Integrations/TelemetryReceiverTests.swift
DatadogRUM/Tests/Integrations/WebViewEventReceiverTests.swift
DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift
DatadogRUM/Tests/RUMMonitor/MonitorTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMSessionScopeTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift
DatadogRUM/Tests/RUMMonitorProtocol+ConvenienceTests.swift
DatadogRUM/Tests/RUMMonitorProtocol+InternalTests.swift
TestUtilities/Mocks/CoreMocks/FeatureScopeMock.swift
TestUtilities/Mocks/FeatureMessageMocks.swift

📦 Utilizing the change from #1744, this PR updates the whole RUM to depend on `FeatureScope` interface rather than `DatadogCoreProtocol` directly.
This will be leveraged in fatal App Hangs monitoring, where `AppHangObserver` will take a dependency on `FeatureScope` to access DataStore, Event Write Context and Telemetry.
With `FeatureScope` being available during RUM feature registration (https://github.com/DataDog/dd-sdk-ios/pull/1744), it is now injected into all downstream components in RUM including the `Monitor` and all message receivers.

RUM-3461 refactor: Replace `core` dependency in RUM with `FeatureScope`

---

CHANGELOG.md
DatadogCore/Tests/Datadog/Mocks/RUMFeatureMocks.swift
DatadogCore/Tests/Datadog/RUM/Integrations/CrashReportReceiverTests.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/Integrations/CrashReportReceiver.swift
DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift
IntegrationTests/IntegrationScenarios/Scenarios/CrashReporting/CrashReportingWithRUMScenarioTests.swift
IntegrationTests/Runner/Scenarios/CrashReporting/CrashReportingScenarios.swift

CrashReportReceiver now supports calling both the view and event mapper before writing the crash to storage.
refs: RUM-2206

feat: Allow crash reporting to use event mappers

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/RUM/WebEventIntegrationTests.swift
DatadogInternal/Sources/Models/WebViewTracking/WebViewMessage.swift
DatadogRUM/Sources/Integrations/WebViewEventReceiver.swift
DatadogRUM/Tests/Integrations/WebViewEventReceiverTests.swift
DatadogWebViewTracking/Sources/MessageEmitter.swift
DatadogWebViewTracking/Tests/MessageEmitterTests.swift

Following #1691, the telemetry events coming from Browser were no longer forwarded to RUM track.
Support `internal_telemetry` message type and forward them to RUM.

RUM-2813 Add support for `internal_telemetry` from browser

---

Datadog/Example/Base.lproj/Main iOS.storyboard
DatadogTrace/Sources/OpenTelemetry/OTelSpanBuilder.swift

There was a miss caught here where set active was not passed to the DDSpan.
Mark underlying span as active when builder is configured as active span.

RUM-3853 feat(otel-tracer): make DDSpan active when OtelSpanBuilder starts a span as active

---

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCore iOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCore tvOS.xcscheme
Datadog/Example/Debugging/DebugOTelTracingViewController.swift
DatadogCore/Tests/Datadog/Tracing/OTelSpanTests.swift
DatadogTrace/Sources/OpenTelemetry/OTelSpan.swift
DatadogTrace/Tests/OpenTelemetry/OTelSpanTests.swift
Makefile

Some tests to cover active span cases.
There are various a parent can be set
1. Explicit parent
```swift
let span = tracer.spanBuilder(spanName: "parentSpan").setSpanKind(spanKind: .client).startSpan()
span.setAttribute(key: sampleKey, value: sampleValue)
let childSpan = tracer.spanBuilder(spanName: "childSpan").setSpanKind(spanKind: .client).setParent(span).startSpan()
childSpan.setAttribute(key: sampleKey, value: sampleValue)
childSpan.end()
span.end()
```
2. On the context provider
```swift
let span = tracer.spanBuilder(spanName: "parentSpan").setSpanKind(spanKind: .client).startSpan()
span.setAttribute(key: sampleKey, value: sampleValue)
OpenTelemetry.instance.contextProvider.setActiveSpan(span)
let childSpan = tracer.spanBuilder(spanName: "childSpan").setSpanKind(spanKind: …
```

RUM-3853 feat(otel-tracer): add test cases for setting active span

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogWebViewTracking/Sources/WebViewTracking.swift
DatadogWebViewTracking/Tests/Mocks.swift
DatadogWebViewTracking/Tests/WebViewTrackingTests.swift

Add `SessionReplayConfiguration` to web-view tracking.

RUM-2813 Add webview replay configuration

---

CHANGELOG.md
DatadogCore/Tests/Datadog/Tracing/TracingURLSessionHandlerTests.swift
DatadogInternal/Sources/NetworkInstrumentation/NetworkInstrumentationFeature.swift
DatadogInternal/Sources/NetworkInstrumentation/URLSession/URLSessionTaskInterception.swift
DatadogRUM/Sources/Instrumentation/Resources/URLSessionRUMResourcesHandler.swift
DatadogRUM/Tests/Instrumentation/Resources/URLSessionRUMResourcesHandlerTests.swift
DatadogTrace/Tests/TracingURLSessionHandlerTests.swift
TestUtilities/Mocks/NetworkInstrumentationMocks.swift

📦 This PR addresses the crashes reported in #1638 by implementing extra thread safety measures.
```
Thread 10 Crashed:
0   CoreFoundation                  0x31fe4ac54         CF_IS_OBJC
1   CoreFoundation                  0x31fe694e4         [inlined] CFDictionaryGetCount
2   CoreFoundation                  0x31fe694e4         CFDictionaryGetCount
3   CFNetwork                       0x3221fb2b8         _CFHTTPServerResponseEnqueue
4   CFNetwork                       0x3221e2be0         CFHTTPCookieStorageUnscheduleFromRunLoop
5   Foundation                      0x31e1a2718         URLRequest.allHTTPHeaderFields.getter
6   <AppName>                         0x104ec81c4         NetworkInstrumentationFeature.extractTrace (NetworkInstrumentationFeature.swift:246)
7   <AppName> …
```

RUM-2916 fix: Crash in `NetworkInstrumentationFeature`

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/CrashReporting/SendingCrashReportTests.swift
DatadogCore/Tests/Datadog/Mocks/RUMDataModelMocks.swift
DatadogCore/Tests/Datadog/RUM/Integrations/CrashReportReceiverTests.swift
DatadogCrashReporting/Sources/CrashReportingFeature.swift
DatadogCrashReporting/Sources/Integrations/CrashReportSender.swift
DatadogInternal/Sources/Models/CrashReporting/BinaryImage.swift
DatadogInternal/Sources/Models/CrashReporting/DDCrashReport.swift
DatadogInternal/Sources/Models/CrashReporting/DDThread.swift
DatadogLogs/Sources/Feature/MessageReceivers.swift
DatadogRUM/Sources/DataModels/RUMDataModelsMapping.swift
DatadogRUM/Sources/FatalErrorBuilder.swift
DatadogRUM/Sources/Instrumentation/AppHangs/AppHang.swift
DatadogRUM/Sources/Instrumentation/AppHangs/AppHangsMonitor.swift
DatadogRUM/Sources/Instrumentation/AppHangs/FatalAppHangsHandler.swift
DatadogRUM/Sources/Integrations/CrashReportReceiver.swift
DatadogRUM/Sources/Scrubbing/RUMEventsMapper.swift
DatadogRUM/Tests/Instrumentation/AppHangs/AppHangsMonitorTests.swift
DatadogRUM/Tests/Mocks/RUMDataModelMocks.swift
DatadogRUM/Tests/Scrubbing/RUMEventsMapperTests.swift
TestUtilities/Mocks/TelemetryMocks.swift

📦 This PR adds the logic of sending RUM errors for fatal App Hangs. It completes the previous work done in #1751 where fatal hangs were tracked, but not yet sent.
🎁 Because the condition of uploading fatal App Hangs to previous RUM session is very similar to the flow of sending RUM errors for app crashes, this PR brings additional refactoring to reuse existing concepts for both kinds of fatal error. That includes:
- solving `RUM-3115` by dropping `RUMCrashEvent` and setting `error.threads`, `error.meta`, `error.binary_images` and `error.was_truncated` directly in `RUMErrorEvent`;
- introducing `FatalErrorBuilder` that is shared between fatal App Hangs handler and Crash receiver.
To cut corners, proposed implementation considers only the main scenario when hang happens in existing RUM …

RUM-3461 feat: Send fatal App Hang after app restart

---

CHANGELOG.md
DatadogCore/Sources/Core/Storage/FilesOrchestrator.swift
DatadogCore/Sources/Kronos/KronosTimeFreeze.swift
DatadogCore/Sources/Kronos/KronosTimeStorage.swift
tools/lint/sources.swiftlint.yml

📦 This PR renames symbols in our codebase to avoid false-positive warnings on using [Required Reason APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api). Next to this, it adds basic linter rule to prevent from using names that may result with conflicts.
Related GH Issues: #1749, #1756
Renamed: `.creationDate` → `.fileCreationDate` and `systemUptime` → `getSystemUptime`.
Added custom linter rule that scans the code for Required Reason API names. If found, it raises an error:
The rule is inspired by the text scanner from [this repo](https://github.com/Wooder/ios_17_required_reason_api_scanner). It is up to date with the list of Apple APIs.

RUM-3808 fix: Avoid name collision with Required Reason APIs

---

DatadogCore/Tests/Datadog/LoggerTests.swift
DatadogTrace/Sources/OpenTelemetry/OTelSpan.swift

`event` is not supported. 
- Make event API not supported
- Test case for logs integration

RUM-3853 feat(otel-tracer): remove support for event API

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCore iOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCore tvOS.xcscheme
DatadogCore/Tests/Datadog/Tracing/OTelSpanTests.swift
Makefile

DatadogSDKTesting is not enabled on otel-tracer branch.
There is a history why? It is mainly because `OpenTelemetryApi` package is imported by both `DatadogTrace` and `DatadogSDKTesting`. Linker is not intelligent enough to decide which one to use and it randomly select one. This random from the experience is frameworks ordered by name and then whichever comes first.
I had success with two solutions.
1. Use `OpenTelemetryApi` and `DatadogSDKTesting` as SPM. But we have big limitation, lack of iOS 12 support https://github.com/open-telemetry/opentelemetry-swift/issues/521
2. Use `OpenTelemetryApi` as xcframework and `DatadogSDKTesting` as SPM which worked as well and hence this PR.
One thing to notice here, now the `DatadogSDKTesting` SDK will be added to the workspace. It is no longer …

RUM-3185 feat(otel-tracer): use DatadogSDKTesting as SPM dependency

---

DatadogSessionReplay/Sources/Recorder/Utilities/UIImage+SessionReplay.swift
DatadogSessionReplay/Sources/Writers/ResourcesWriter.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageResourceTests.swift
DatadogSessionReplay/Tests/Writer/ResourcesWriterTests.swift

Fixes the SR color identifier, which is causing unnecessary upload of resources.
Previous implementation was relying on UIColor (NSObject) hash. It appears to be stable only in the developer environment, but it feels random on production.
Testing is tricky, because different versions of iOS produce different images, and hashes.
Improved tests to check if length of the identifier, as well as if it contains color for tinted images.
Also, it resets the store version.

Fix color SR identifier

---

DatadogCore/Sources/Datadog.swift
DatadogInternal/Sources/Concurrency/ReadWriteLock.swift

When building a host application target that imports the Datadog iOS SDK and has `complete` concurrency checking enabled on the application target, `Datadog.verbosityLevel` emits the following warning:
> Static property 'verbosityLevel' is not concurrency-safe because it is non-isolated global shared mutable state; this is an error in Swift 6
This PR addresses the defect using an existing synchronization utility within _DatadogInternal_.
By downgrading `Datadog.verbosityLevel` to a computed property, backed by a private property using an instance of `ReadWriteStorage<Value>` to ensure efficient synchronization, the concurrency checker warning is fully resolved.
The warning that the concurrency checker emits, according to the setup described above, is a valid one. It's an example of the …

[#1549] Address Swift 6 concurrency warning by synchronizing access to verbosityLevel.

---

Datadog/E2ETests/Tracing/TracerE2ETests.swift

📦 🧰 Fixes build failure in (nightly) E2E tests:
```
Failed to execute Step:
command failed with exit status 65 (xcodebuild "-workspace" "/Users/vagrant/git/Datadog.xcworkspace" "-scheme" "E2ETests" "test" "-destination" "id=3B2CA806-D170-4AFA-A9B9-032CDF42BEAB" "-resultBundlePath" "/var/folders/yy/6kcn9mkd5svdbqnznwf474f00000gn/T/XCUITestOutput565255057/Test-E2ETests.xcresult" "-xcconfig" "/var/folders/yy/6kcn9mkd5svdbqnznwf474f00000gn/T/3094384847/temp.xcconfig"):
/Users/vagrant/git/Datadog/E2ETests/Tracing/TracerE2ETests.swift:54:25: error: 'init(sampleRate:)' is deprecated: This will be removed in future versions of the SDK. Use `init(samplingStrategy: .custom(sampleRate:))` instead.
```
The `HTTPHeadersWriter()` initializer was deprecated in #1794. Because we treat warnings as errors, …

chore: Fix nightly tests build failure

---

CHANGELOG.md
DatadogCore/Tests/DatadogObjc/DDDatadogTests.swift
DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDDatadog+apiTests.m
DatadogObjc/Sources/Datadog+objc.swift
api-surface-objc

This method was missing in ObjC API, despite being present in Swift.

Add `addUserExtraInfo` method to ObjC API

---

CHANGELOG.md
DatadogCore/Tests/DatadogObjc/DDDatadogTests.swift
DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDDatadog+apiTests.m
DatadogObjc/Sources/Datadog+objc.swift
api-surface-objc

This PR adds `isInitialized` and `stopInstance` methods to ObjC API which were missing, but exist in Swift API.

Add `isInitialized` and `stopInstance` methods to ObjC API

---

Makefile
api-surface-swift

This PR adds `DatadogSessionReplay` to the Swift API surface generation.
One thing which comes from this PR is that since `DatadogSessionReplay` also contains some Objective-C bindings, they leak into Swift API surface file. But to address this changes are needed in generation logic, it seems.

Add `DatadogSessionReplay` to the Swift API surface generation

---

CHANGELOG.md
Datadog/IntegrationUnitTests/Trace/HeadBasedSamplingTests.swift
DatadogCore/Tests/Datadog/Tracing/TracingURLSessionHandlerTests.swift
DatadogCore/Tests/DatadogObjc/DDTracerTests.swift
DatadogInternal/Sources/NetworkInstrumentation/Datadog/HTTPHeadersReader.swift
DatadogInternal/Sources/NetworkInstrumentation/Datadog/HTTPHeadersWriter.swift
DatadogInternal/Tests/NetworkInstrumentation/HTTPHeadersWriterTests.swift
DatadogRUM/Tests/Instrumentation/Resources/URLSessionRUMResourcesHandlerTests.swift
DatadogTrace/Tests/TracingURLSessionHandlerTests.swift
IntegrationTests/IntegrationScenarios/Scenarios/RUM/RUMResourcesScenarioTests.swift
IntegrationTests/IntegrationScenarios/Scenarios/Tracing/TracingURLSessionScenarioTests.swift

Fixes #1797
With 128 bit id support, the trace id and span id for datadog headers were changed to hex format which was wrong. These must stay in decimal format and the higher 64 bits must be in hex.

GH-1797 fix: use trace and span id as decimal

---

CHANGELOG.md
Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Sources/Core/DatadogCore.swift
DatadogCore/Sources/Core/Storage/Directories.swift
DatadogCore/Sources/Core/Upload/BackgroundTaskCoordinator.swift
DatadogCore/Sources/Core/Upload/FeatureUpload.swift
DatadogCore/Sources/Datadog.swift
DatadogCore/Tests/Datadog/Core/DirectoriesTests.swift
DatadogCore/Tests/Datadog/Core/Upload/AppBackgroundTaskCoordinatorTests.swift
DatadogCore/Tests/Datadog/Core/Upload/ExtensionBackgroundTaskCoordinatorTests.swift

This PR makes extension targets use `beginActivity(options:reason:)` and `endActivity(_:)` APIs when `backgroundTasksEnabled` configuration is enabled. This allows slightly extending the lifetime of the extension in order to upload all the necessary data.
https://developer.apple.com/documentation/foundation/processinfo/1415995-beginactivity
https://developer.apple.com/documentation/foundation/processinfo/1411321-endactivity
It is recommended to use this configuration of the SDK when initialising from extensions:
```swift
Datadog.initialize(
with: Datadog.Configuration(
clientToken: clientToken,
env: environment,
site: .us1,
backgroundTasksEnabled: true // This will give more time for extensions to upload SDK data
),
trackingConsent: .granted,
instanceName: "UniqueExtensionName" // This …
```

RUM-3284 Extension background upload

---

DatadogCore/Tests/DatadogObjc/DDLogsTests.swift
DatadogObjc/Sources/Logs/Logs+objc.swift
api-surface-objc

`Logs.removeAttribute` / `Logs.addAttribute` API is missing in ObjC, while it exists in Swift. This PR adds the missing.

RUM-4418: Add missing global `addAttribute`/`removeAttribute` Logs API in ObjC

---

DatadogCore/Tests/DatadogObjc/DDLogsTests.swift
DatadogObjc/Sources/Logs/Logs+objc.swift
api-surface-objc

`sampleRate` parameter wasn't actually used in the constructor `DDLogsConfiguration` object and underlying `Logs.Configuration` has no space for it.
It is a breaking change, but even if build will be broken on the customer side using `DatadogObjC`, it is easy to address that, this parameter had no effect anyway.

Remove unused `sampleRate` parameter from `DDLogsConfiguration` object

---

Datadog/IntegrationUnitTests/RUM/AppHangsMonitoringTests.swift
DatadogCore/Tests/Datadog/RUM/RUMMonitorTests.swift
DatadogRUM/Sources/Debugging/RUMDebugging.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/RUMMonitor/Monitor.swift
DatadogRUM/Tests/RUMMonitor/MonitorTests.swift

📦 This PR removes the internal `queue` used in `RUM.Monitor`. This is to ease the upcoming work on sending view updates on RUM attributes change (`RUM-3588`) by simplifying internal state management in monitor's implementation.
As an extra benefit, this change reduces the number of threads consumed by RUM. It has no performance impact, as the removed queue was called with `.sync {}` anyway.
`RUM.Monitor` state that is now synchronised using **`@ReadWriteLock`**:
- Global RUM attributes.
- The `monitor.debug` flag.
`RUM.Monitor` operations that are now synchronised using **SDK context thread**:
- Events processing through `RUMScopes` (already using context thread before).
- Executing current sessionID callback (already using context thread before).
- Managing `monitor.debug` utility (using …

Refactor: Replace RUM monitor `queue` with `@ReadWriteLock`

---

Datadog/IntegrationUnitTests/Public/WebLogIntegrationTests.swift
Datadog/IntegrationUnitTests/RUM/WebEventIntegrationTests.swift

Newly introduced webview tests were flaky. It seems that instantiated a `WKWebView` is sporadically retaining a core after the end of the test. **I'm not able to find any retain**, the core is always `weak`.
Enabe webview tracking on the `WKUserContentController` in tests, instead of a parent `WKWebView`.

fix: Remove `WKWebView` instance in tests

---

DatadogCore/Tests/Datadog/DatadogTests.swift

The upload at init could pick files in the authorized folder, so we cannot guarantee that the files will be there while running the test.
The assertion can be removed as we only need to assert that the `clearAllData` removes all files.

fix: Remove flaky assertion due to upload at init

---

Datadog/IntegrationUnitTests/SessionReplay/WebRecordIntegrationTests.swift

Yet another fix for flakiness introduced by a webview test:
Prevent sharing cookies between webview instances by setting a new `WKProcessPool`. It is possible that the cookie storage creates leak.

fix: WebView leak in test

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogRUM/Sources/RUMMonitor/Monitor.swift
DatadogRUM/Tests/RUMMonitor/Monitor+GlobalAttributesTests.swift

📦 This PR adds tests to existing RUM global attributes logic. This is to increase unit tests coverage in different scenarios:
- changing attributes right after SDK init;
- changing attributes after view is started;
- changing attributes while inactive view (view with pending resource).
Defined new **unit test** suite in `DatadogRUMTests` - asserting all existing behaviours for global RUM attributes handling.
I'm not yet removing the [existing RUM attributes **integration tests** in `DatadogCoreTests`](https://github.com/DataDog/dd-sdk-ios/blob/2e74021bfd7a1fd52a7e1c89a9da26eca776b580/DatadogCore/Tests/Datadog/RUM/RUMMonitorTests.swift#L1426-L1446) as they cover also the situation logic of merging command-specific attributes with global ones.

RUM-3588 chore: Add tests for global RUM attributes

---

tools/distribution/dogfood.py
tools/distribution/src/dogfood/package_resolved.py
tools/distribution/tests/dogfood/test_package_resolved.py

```
Failed to dogfood: .package.resolved uses version 3 but `PackageResolvedFile` only supports versions `1` and `2`. Update `PackageResolvedFile` to support new version.`
```
Added V3 version which basically same as V2 with extra field originHash. We are not using it.

chore: add support for Package.resolved V3

---

DatadogRUM/Sources/RUMMonitor/Scopes/RUMApplicationScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMSessionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift

Synthetics reads RUM context shared on the device Console but the `print` function only prints to the Xcode console, while `NSLog` also prints entries into Console.
Follow up #1602
Replace `print` with `NSLog`.

fix: RUM to S8S context

---

Cartfile
Cartfile.resolved
DatadogCrashReporting.podspec
DatadogSDKCrashReporting.podspec
Package.swift

📦 Upgrading the PLCR dependency to [1.11.2](https://github.com/microsoft/plcrashreporter/releases/tag/1.11.2).
PLCR changelog:
```
[Improvement] Update PLCrashReporter to include privacy manifest.
[Improvement] Increase the maximum report size to 1MB.
```
Updated PLCR version for SPM, CP and CT.
Even tho PLCR now ships the privacy manifest which was earlier duplicated for `DatadogCrashReporting`, we decide to keep our manifest. There should be no harm in this setup:
- [our manifest](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogCrashReporting/Resources/PrivacyInfo.xcprivacy)
- [same fields in PLCR’s manifest](https://github.com/microsoft/plcrashreporter/blob/1.11.2/Resources/PrivacyInfo.xcprivacy#L13-L24)

RUM-4440 feat: Upgrade PLCR to `1.11.2`

---

DatadogCore/Sources/Datadog.swift

🐞 🔭 This PR fixes wrong value of the `batch_size` reported in RUM telemetry.
The previous value was set to "max file size", leading to reporting constant `4194304` bytes.
It is now fixed to report the [`uploaderWindow` value](https://github.com/DataDog/dd-sdk-ios/blob/61ec70ff47462095c90522f5da529eb5e7f441f7/DatadogCore/Sources/PerformancePreset.swift#L48) which is computed from the [SDK's configuration `batchSize`](https://github.com/DataDog/dd-sdk-ios/blob/61ec70ff47462095c90522f5da529eb5e7f441f7/DatadogCore/Sources/Datadog.swift#L37-L46) option (`3`, `10` or `35` seconds depending on the setting).

RUM-789 fix: Fix `batch_size` in configuration telemetry

---

DatadogCore/Sources/Core/Storage/FilesOrchestrator.swift
DatadogCore/Tests/Datadog/Core/Persistence/FilesOrchestrator+MetricsTests.swift
DatadogCore/Tests/Datadog/Core/Persistence/FilesOrchestratorTests.swift

📦 🔭 This PR fixes the wrong value reported in `batch_duration` for "Batch Closed" metrics.
For 1w data, Android SDK reports it as 1.41s in p50 and 9.42s in p90, whereas for iOS SDK it is respectively ~30s and ~3min. 
Now we measure `batch_duration` in the same way [as Android SDK does](https://github.com/DataDog/dd-sdk-android/blob/a0e05c37a8ec3ee78415e082fb18f8e3a10668e2/dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestrator.kt#L49C17-L49C40) - by marking the last writable access to the batch and computing `batch_duration` as the duration from batch creation to last access.

RUM-347 fix: Fix `batch_duration` in "Batch Closed" metric

---

CHANGELOG.md
DatadogCore/Tests/DatadogObjc/DDRUMMonitorTests.swift
DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDRUMMonitor+apiTests.m
DatadogObjc/Sources/RUM/RUM+objc.swift

📦 This PR adds missing RUM APIs for Objective-C SDK.
The list includes:
- `[monitor currentSessionIDWithCompletion:]`
- `[monitor stopSession]`
- `[monitor addFeatureFlagEvaluationWithName:value:]`
- `[monitor setDebug:]`

RUM-4315 feat: Add missing RUM APIs for Objective-C

---

tools/rum-models-generator/Sources/CodeDecoration/RUMCodeDecorator.swift
tools/rum-models-generator/Sources/CodeGeneration/Generate/JSONSchema.swift

🧰 This PR updates `rum-model-generator` so we can generate models from latest commits in [rum-events-format](https://github.com/DataDog/rum-events-format).
There were two breaking commits in `rum-events-format`:
**✨[RUM-4029 bootstrap telemetry usage schema](https://github.com/DataDog/rum-events-format/pull/197)** adding a whole new root-level schema for "usage telemetry". It requires generating polymorphic Swift types at nested level which isn't yet supported. Generation fails with:
```
🚧 Unimplemented: Building `SwiftAssociatedTypeEnum` case label for JSONObject is not supported
```
Because we don't yet leverage this feature, this PR explicitly ignores this subschema. The actual work to add this support is moved to `RUM-4571`.
**[RUM-1844: Add device and os info to telemetry …

chore: Fix generating rum models

---

CHANGELOG.md
Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/CrashReporting/SendingCrashReportTests.swift
DatadogCore/Tests/Datadog/CrashReporting/CrashContext/CrashContextProviderTests.swift
DatadogCore/Tests/Datadog/CrashReporting/CrashContext/CrashContextTests.swift
DatadogCore/Tests/Datadog/Mocks/CrashReportingFeatureMocks.swift
DatadogCore/Tests/Datadog/Mocks/RUMFeatureMocks.swift
DatadogCore/Tests/Datadog/RUM/Integrations/CrashReportReceiverTests.swift
DatadogCrashReporting/Sources/CrashContext/CrashContext.swift
DatadogCrashReporting/Sources/CrashContext/CrashContextProvider.swift
DatadogInternal/Sources/Models/RUM/GlobalRUMAttributes.swift
DatadogLogs/Tests/LogsTests.swift
DatadogRUM/Sources/Feature/RUMBaggageKeys.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/Instrumentation/AppHangs/AppHangsMonitor.swift
DatadogRUM/Sources/Instrumentation/AppHangs/FatalAppHangsHandler.swift
DatadogRUM/Sources/Instrumentation/RUMInstrumentation.swift
DatadogRUM/Sources/Integrations/CrashReportReceiver.swift
DatadogRUM/Sources/RUMMonitor/Monitor.swift
DatadogRUM/Sources/RUMMonitor/RUMCommand.swift
DatadogRUM/Sources/RUMMonitor/Scopes/FatalErrorContextNotifier.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMScopeDependencies.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Tests/Instrumentation/RUMInstrumentationTests.swift
DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift
DatadogRUM/Tests/RUMMonitor/Monitor+GlobalAttributesTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/FatalErrorContextNotifierTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMSessionScopeTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift
TestUtilities/Helpers/DDAssert.swift

📦 With this PR, RUM error and RUM view sent after crash will always include up-to-date attributes set on `RUMMonitor`.
Because we don't update crash context with the "last RUM view" info on every change to global attributes, the global RUM attributes held in "last view" were not always correct. Global attributes change that happened during the last active view was never included in the crash error.
The `RUM.FatalErrorContextNotifier` is updated with `globalAttributes` property. Upon change, it sends a baggage over message bus holding `DatadogInternal.GlobalRUMAttributes` (new type). It is received in `DatadogCrashReporting` and gets encoded into `CrashContext`. 
Upon restarting the app from crash, the value is decoded to `RUM.CrashContext` on regular basis.
🎁 On testing front, I separated …

RUM-3588 fix: Always update crash context with RUM attributes

---

DatadogCore/Sources/FeaturesIntegration/CITestIntegration.swift

📦 Re-attempt on https://github.com/DataDog/dd-sdk-ios/pull/1833 after fixing linter and bumping `swiftlint` in https://github.com/DataDog/dd-sdk-ios/pull/1850
From original PR:
> Swift testing library is using MachPorts to communicate with this library. They are unique for OS kernel, so each process should have a unique name for them. Right now we are using hardcoded names, so two running test processes will fail.
> Testing library sets CI_VISIBILITY_MESSAGE_CHANNEL_UUID variable which is used for name generation for MachPorts.

[CIVIS-9813] Fix for test sdk integration

---

Datadog/E2ETests/Tracing/TracerE2ETests.swift

```
❌ /Users/vagrant/git/Datadog/E2ETests/Tracing/TracerE2ETests.swift:54:84: missing argument for parameter 'traceContextInjection' in call
let anyWriter = HTTPHeadersWriter(samplingStrategy: .custom(sampleRate: 20))
```
Set arg value.

fix: set traceContextInjection param for E2E test case

---

Datadog/Example/Base.lproj/Main iOS.storyboard
Datadog/Example/Debugging/DebugCrashReportingWithRUMViewController.swift

We need ability to simulate OOM crash.
Inspired from https://github.com/getsentry/sentry-cocoa/blob/fdb003d575899e95a873327b0077b7bc04825f71/Samples/iOS-Swift/iOS-Swift/ErrorsViewController.swift#L69

RUM-3464 feat(oom): simulate OOM crash in Example app

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/Public/CoreTelemetryIntegrationTests.swift
DatadogCore/Sources/Datadog+Internal.swift
DatadogCore/Tests/Datadog/OpenTracing/OTSpanTests.swift
DatadogCore/Tests/Datadog/RUM/TelemetryReceiverTests.swift
DatadogInternal/Sources/Telemetry/Telemetry.swift
DatadogInternal/Tests/Telemetry/TelemetryTests.swift
DatadogRUM/Sources/Integrations/TelemetryReceiver.swift
DatadogRUM/Tests/Integrations/TelemetryReceiverTests.swift
DatadogSessionReplay/Tests/Feature/RequestBuilder/SegmentRequestBuilderTests.swift
DatadogSessionReplay/Tests/SessionReplayTests.swift
TestUtilities/Helpers/ModuleName.swift
TestUtilities/Mocks/FeatureMessageMocks.swift
TestUtilities/Mocks/TelemetryMocks.swift

📦 This PR changes the `error.kind` (and also `error.stack`) in SDK error telemetry to be non-optional (always set).
This serves two purposes:
- adds more context to SDK errors and avoid having error logs with no `error.kind`,
- increases the `error.kind` cardinality for later aggregating SDK errors by their kind in "RUM Session Ended" metric.
The `error.kind` now defaults to the `#fileID`:
```
e.g. `DatadogSR/Recorder.swift`
```
This will increase the cardinality of `error.kind` in SDK errors telemetry.
The `error.stack` now defaults to `#fileID` and `#line`:
```
e.g. `DatadogSR/Recorder.swift:42
```
This will add more clarity on SDK errors origin in certain SDK version.

refactor: Make `error.kind` and `error.stack` non-optional in SDK errors

---

DatadogSessionReplay/Sources/Recorder/Recorder.swift

Reduced Capture Record Method Called sampling rate from 3% to 0.1%.
Right now we gather way more data than we need. It should ease the load on the performance of dashboard maintaining statistical distribution.

Reduce telemetry sampling for method called

---

bitrise.yml
tools/distribution/dogfood.py
tools/distribution/src/dogfood/package_resolved.py

🧰 💊 Fixes the recent problem with dogfooding script:
```
❌ Failed to dogfood: 'repositoryURL'
------------------------------------------------------------
Traceback (most recent call last):
File "/Users/vagrant/git/tools/distribution/dogfood.py", line 119, in <module>
dogfood(
File "/Users/vagrant/git/tools/distribution/dogfood.py", line 76, in dogfood
repository_url=dependency['repositoryURL'],
~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'repositoryURL'
```
The `dependency['repositoryURL']` is not valid syntax for version 2 and version 3 `Package.resolved`. Updating the key name to `location` fixes the problem.
🎁 As a bonus, I added a basic smoke test for dogfooding automation. By running it with dry-run mode we ensure that it works fine after any change to `dogfooding.py`.

chore: Fix dogfooding automation

---

DatadogCore/Tests/DatadogObjc/DDRUMConfigurationTests.swift
DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDRUM+apiTests.m
DatadogObjc/Sources/RUM/RUM+objc.swift
api-surface-objc
api-surface-swift

This PR adds app hang tracking to Objective-C API. It exists for Swift, but was missing in Objective-C.

Add app hang tracking to Objective-C API

---

tools/distribution/src/release/assets/gh_asset.py

Validate `OpenTelemetryApi.xcframework` during distribution.

Fix GH asset otel validation

---

DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UINavigationBarRecorderTests.swift

The `testWhenViewIsOfExpectedType` uses a fuzzy fixture, following #1864 we now ignore invisible navigation bar so we need to remove  the `.invisible` attribute from fixture as well.

fix: SR Test Flakiness

---

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCore iOS.xcscheme
DatadogTrace/Tests/OpenTelemetry/OTelSpanTests.swift
DatadogTrace/Tests/TracingFeatureMocks.swift

📦 ❄️ This PR disables flaky OTel test ([`testSetActive_givenParentSpan()`](https://github.com/DataDog/dd-sdk-ios/blob/b142cf9bbd48c97ffbfa9fda3092e52af50b22a4/DatadogTrace/Tests/OpenTelemetry/OTelSpanTests.swift#L252)). This is to address recent CI failures.
Disabled failed test and created `RUM-4795` to re-enable it when possible.
I also revamped the whole `OTelSpanTests` suite to take dependency on `FeatureScope` rather than core mock. This is to address mid-term goals from https://github.com/DataDog/dd-sdk-ios/pull/1744 - having less and simpler dependency in tests so they run faster, more stable and are easier to debug.

chore: Disable flaky `OTelSpan.testSetActive_givenParentSpan()` test

---

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCore tvOS.xcscheme

📦 Same as https://github.com/DataDog/dd-sdk-ios/pull/1881 but for tvOS.
Disabling flaky test for tvOS target.

chore: Disable flaky OTelSpan.testSetActive_givenParentSpan() test for tvOS

---

DatadogSessionReplay/Sources/Models/SRDataModels.swift
DatadogSessionReplay/Sources/Processor/Diffing/Diff+SRWireframes.swift
DatadogSessionReplay/Tests/Processor/Builders/RecordsBuilderTests.swift
DatadogSessionReplay/Tests/Processor/Diffing/Diff+SRWireframesTests.swift

Adds extra telemetry info to to help resolving type mismatch error in Session Replay.
Expands error type to contain from and to types of the wireframe that conflicted.

RUM-917 Improve telemetry of type mismatch

---

E2ETests/Runner/Scenarios/SessionReplayWebView/SessionReplayWebViewScenario.swift

Set the `SessionReplayWebView` scenario name as RUM attribute, this will help defining monitors to assert the E2E test.

RUM-2814 Add scenario to RUM attribute

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/Public/WebLogIntegrationTests.swift
Datadog/IntegrationUnitTests/RUM/WebEventIntegrationTests.swift
DatadogCore/Sources/Core/DatadogCore.swift
DatadogCore/Tests/Datadog/Mocks/DatadogInternal/DatadogCoreProxy.swift
DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDWebViewTracking+apiTests.m
DatadogInternal/Sources/DatadogCoreProtocol.swift
DatadogInternal/Sources/Models/SessionReplay/SessionReplayConfiguration.swift
DatadogObjc/Sources/SessionReplay/SessionReplay+objc.swift
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/Utils/SnapshotTestCase.swift
DatadogSessionReplay/Sources/Feature/SessionReplayFeature.swift
DatadogSessionReplay/Sources/Recorder/PrivacyLevel.swift
DatadogSessionReplay/Sources/SessionReplay+objc.swift
DatadogSessionReplay/Sources/SessionReplayConfiguration.swift
DatadogSessionReplay/Tests/Mocks/RecorderMocks.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UINavigationBarRecorderTests.swift
DatadogWebViewTracking/Sources/ObjC/WebViewTracking+objc.swift
DatadogWebViewTracking/Sources/WebViewTracking.swift
DatadogWebViewTracking/Tests/Mocks.swift
DatadogWebViewTracking/Tests/WebViewTrackingTests.swift
IntegrationTests/IntegrationTests.xcodeproj/project.pbxproj
TestUtilities/Mocks/CoreMocks/FeatureRegistrationCoreMock.swift
TestUtilities/Mocks/CoreMocks/PassthroughCoreMock.swift
TestUtilities/Mocks/CoreMocks/SingleFeatureCoreMock.swift
TestUtilities/Mocks/FeatureModels/SessionReplayConfigurationMocks.swift

Use the Session Replay masking when enabling WebView Tracking.
Allow retrieving any type from the core's feature registry and share the `SessionReplayConfiguration` protocol definition so it can be read from WebView tracking.

RUM-4632 Use global session-replay configuration in webview tracking

---

DatadogRUM/Sources/RUMMonitor/Scopes/RUMApplicationScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMSessionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift

Same as https://github.com/DataDog/dd-sdk-android/pull/1813
Emit the Application and Session ID with the view so S8S can retrieve them in the device logs.

RUM-2442 [S8S] Emit `_dd.session.id` and `_dd.application.id` on view change

---

CHANGELOG.md
DatadogCore/Tests/DatadogObjc/DDRUMMonitorTests.swift
DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDRUMMonitor+apiTests.m
DatadogObjc/Sources/RUM/RUM+objc.swift
api-surface-objc

These values exist on the RUM data model side, but were not exposed in ObjC API.

Add `connect`, `trace`, `options` values to DDRumMethod type

---

DatadogSessionReplay/Sources/Recorder/Utilities/UIImage+SessionReplay.swift

Color identifier calculation seems to be quite slow for the customer testing. We can improve by making it lazy the same way we did for UIViews.
Leverages associated object to calculate identifier once and retain it for given instance of color.

RUM-4824 Make color SR identifier lazy

---

E2ETests/Runner/Scenarios/SessionReplayWebView/SessionReplayWebViewController.swift

🧰 Fixes E2E test build error:
```
❌ /Users/vagrant/git/E2ETests/Runner/Scenarios/SessionReplayWebView/SessionReplayWebViewController.swift:26:57: extra argument 'sessionReplayConfiguration' in call
sessionReplayConfiguration: WebViewTracking.SessionReplayConfiguration(
```
It comes from public API change to `DatadogWebViewTracking` introduced in https://github.com/DataDog/dd-sdk-ios/pull/1879
Aligned public API use to changes from https://github.com/DataDog/dd-sdk-ios/pull/1879.

chore: Fix E2E tests build

---

Datadog/Example/Debugging/DebugRUMSessionViewController.swift
Datadog/Example/Debugging/Helpers/SwiftUI.swift

📦 This PR adds convenience to the RUM Session Debugging page in Example app.
It comes handy in debugging RUM sessions, notably for the "Session Ended" telemetry added in #1866.
Re-opening https://github.com/DataDog/dd-sdk-ios/pull/1894 which was closed by GH 🤔💭.
3 changes:
- added a button to manually end the session through `stopSession()` API,
- added extra label displaying the current session ID,
- overal revamp to make more space for rendering session state at the bottom.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

RUM-1660 chore: Enhance RUM session debugging in Example app

---

Datadog/IntegrationUnitTests/RUM/SDKMetrics/RUMSessionEndedMetricIntegrationTests.swift
DatadogCore/Tests/Datadog/Mocks/RUMFeatureMocks.swift
DatadogRUM/Sources/Instrumentation/Views/RUMViewsHandler.swift
DatadogRUM/Sources/RUMMonitor/Monitor.swift
DatadogRUM/Sources/RUMMonitor/RUMCommand.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMApplicationScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMSessionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Sources/SDKMetrics/SessionEndedMetric.swift
DatadogRUM/Sources/SDKMetrics/SessionEndedMetricController.swift
DatadogRUM/Tests/Integrations/TelemetryInterceptorTests.swift
DatadogRUM/Tests/Mocks/RUMDataModelMocks.swift
DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMSessionScopeTests.swift
DatadogRUM/Tests/SDKMetrics/SessionEndedMetricControllerTests.swift
DatadogRUM/Tests/SDKMetrics/SessionEndedMetricTests.swift

📦 🔭 According to [the spec](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3663167927/RUM+Session+Ended+Telemetry+-+Spec) (internal), this PR adds "diagnostic attributes" to "RUM Session Ended" telemetry.
This is a follow-up on https://github.com/DataDog/dd-sdk-ios/pull/1866 where we implemented a handset of "quality attributes".
The list of added attributes:
Indicates whether [tracking of background events](https://github.com/DataDog/dd-sdk-ios/blob/888d39fc5407e01b72deab78451be689232b3342/DatadogRUM/Sources/RUMConfiguration.swift#L105-L112) was enabled in the RUM configuration.
Holds the map of instrumentation type to the number of distinct views (view UUIDs) tracked through it (`manual` | `swiftui` | `uikit`).
The number of views with `has_replay == true`.
The NTP offset at the …

RUM-4591 chore: Add diagnostic attributes to "RUM Session Ended" telemetry

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Tests/Datadog/Mocks/CrashReportingFeatureMocks.swift
DatadogCrashReporting/Sources/CrashReportingFeature.swift
DatadogCrashReporting/Sources/Integrations/CrashReportSender.swift
DatadogInternal/Sources/Context/AppState.swift
DatadogInternal/Sources/Context/DeviceInfo.swift
DatadogInternal/Sources/Context/Sysctl.swift
DatadogInternal/Sources/MessageBus/FeatureMessageReceiver.swift
DatadogInternal/Sources/Models/CrashReporting/LaunchReport.swift
DatadogRUM/Sources/Feature/RUMDataStore.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/Instrumentation/RUMInstrumentation.swift
DatadogRUM/Sources/Instrumentation/WatchdogTerminations/WatchdogTerminationAppState.swift
DatadogRUM/Sources/Instrumentation/WatchdogTerminations/WatchdogTerminationAppStateManager.swift
DatadogRUM/Sources/Instrumentation/WatchdogTerminations/WatchdogTerminationChecker.swift
DatadogRUM/Sources/Instrumentation/WatchdogTerminations/WatchdogTerminationMonitor.swift
DatadogRUM/Sources/Instrumentation/WatchdogTerminations/WatchdogTerminationReporter.swift
DatadogRUM/Sources/Integrations/LaunchReportReceiver.swift
DatadogRUM/Tests/Instrumentation/RUMInstrumentationTests.swift
DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationAppStateManagerTests.swift
DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationCheckerTests.swift
DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationMocks.swift
DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationMonitorTests.swift
TestUtilities/Mocks/DatadogContextMock.swift

We want to detect the watchdog terminations in the SDK and report them as a crash to the backend.
This PR setups the building block of detecting a watchdog termination using the heuristic based approach. The heuristic works on checking all the possible ways an app can be terminated and if the termination is from an unknown method, it is considered as a watchdog termination.
Read more about the approach in the [internal RFC](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3750756810).
The reporting part is not yet implemented in this PR.

RUM-3463 feat(watchdog-termination): track app state and detect watchdog terminations

---

CHANGELOG.md
DatadogCore/Tests/DatadogObjc/DDRUMConfigurationTests.swift
DatadogObjc/Sources/RUM/RUM+objc.swift

Unlike long tasks tracking, app hang monitoring can be disabled. This PR treats 0 passed as an argument in ObjC API as a special value to disable app hang monitoring (to avoid changing property type to the optional).

Allow disabling app hang monitoring in ObjC API

---

DatadogCore/Sources/Core/Storage/Files/Directory.swift
DatadogCore/Sources/Core/Storage/Files/File.swift
DatadogCore/Tests/Datadog/Core/Persistence/Files/DirectoryTests.swift
DatadogCore/Tests/Datadog/Core/Persistence/Files/FileTests.swift

We need to know the timestamp of file update to get the approximate timing for the watchdog termination. This will be used to build the rum error event.
The implementation is quite straight forward, with the new API `Directory.mostRecentModifiedFile(before:)`, we can find the most recently updated file. It recursively checks all the subdirectories, files and itself and returns the file which is most recently updated.

RUM-4911 feat(watchdog-termination): ability to find most recently updated file in a dir

---

Datadog/Example/ExampleAppDelegate.swift
DatadogCrashReporting/Sources/CrashReportingFeature.swift
DatadogObjc/Sources/RUM/RUM+objc.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/Instrumentation/RUMInstrumentation.swift
DatadogRUM/Sources/Instrumentation/WatchdogTerminations/WatchdogTerminationMonitor.swift
DatadogRUM/Sources/RUMConfiguration.swift
DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationMocks.swift
DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationMonitorTests.swift

Ability to enable disable WT. Default is false.
We don't want to enable WT by default as they will have huge disk IO implications.

RUM-4911 feat(watchdog-termination): setup trackWatchdogTermination configuration

---

DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITabBarRecorder.swift
DatadogWebViewTracking/Sources/ObjC/WebViewTracking+objc.swift
Makefile
tools/spm.sh

https://swiftpackageindex.com/DataDog/dd-sdk-ios/builds
- fix the build issues
- added ability to build the SDK all from Package.swift file
- We first delete the workspace file, in order to force SPM build

chore: fix SPM build and add scripts to check locally

---

DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/Utils/SnapshotTestCase.swift
DatadogSessionReplay/Sources/Feature/SessionReplayFeature.swift
DatadogSessionReplay/Sources/Processor/Builders/WireframesBuilder.swift
DatadogSessionReplay/Sources/Processor/SnapshotProcessor.swift
DatadogSessionReplay/Sources/Recorder/Recorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIDatePickerRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIPickerViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITabBarRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextFieldRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshot.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotBuilder.swift
DatadogSessionReplay/Tests/Mocks/RecorderMocks.swift
DatadogSessionReplay/Tests/Mocks/ResourceProcessorSpy.swift
DatadogSessionReplay/Tests/Processor/Builders/WireframesBuilderTests.swift
DatadogSessionReplay/Tests/Processor/SnapshotProcessorTests.swift
DatadogSessionReplay/Tests/Recorder/RecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewWireframesBuilderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotTests.swift

Previously, resources where created while recording the views. But in SwiftUI, we will only be able to create resources at the processing phase. To accommodate this, resources will now be created when building the wireframes and written by the snapshot processor.
The `SnapshotProcessor` now holds a reference to a `ResourceProcessor`, and the `SessionReplayWireframesBuilder` will keep track of resources while building the wireframes. The `SnapshotProcessor` will pass all collected resources to its `ResourceProcessor` instance. 
**Note:**
The `ResourceProcessor` and the `ResourcesWriter` are doing the same checks to deduplicate images, but on different threads. This needs a refactoring as well, but it's outside the scope of this PR.

RUM-5004 Record resources while processing snapshots

---

DatadogCore/Sources/Core/Storage/FilesOrchestrator.swift
DatadogCore/Sources/Core/Storage/Writing/FileWriter.swift
DatadogCore/Tests/Datadog/Core/Persistence/Writing/FileWriterTests.swift
DatadogCore/Tests/Datadog/Mocks/CoreMocks.swift

Current telemetry message is not very helpful to diagnose file IO related issues
For example
```
Failed to write data to file - Cannot create file at path: /var/mobile/Containers/Data/Application/*/Library/Caches
```
Split the big `do-try-catch` block into individual ones to get more insights where the issue.

RUM-1000 chore: improve telemetry messages for file I/O errors

---

CHANGELOG.md

📦 As mentioned in https://github.com/DataDog/dd-sdk-ios/issues/1877#issuecomment-2191541062, we cherry-pick https://github.com/DataDog/dd-sdk-ios/issues/1892 fix to 2.11 release, making `2.11.1` hotfix.
We don't follow regular git-flow for this hotfix as the released change already exists in `2.13.0` and we only cherry-pick it.
The `2.11.1` tag will be put on the [last commit](https://github.com/DataDog/dd-sdk-ios/commits/hotfix/2.11.1/) from `hotfix/2.11.1` branch. Check [`hotfix/2.11.1` → `master` diff](https://github.com/DataDog/dd-sdk-ios/compare/master...hotfix/2.11.1?expand=1) to review what we're about to release.

chore: Update CHANGELOG.md with `hotfix/2.11.1`

---

Cartfile
SmokeTests/carthage/Makefile

📦 This is to ensure that upstream projects resolve the right version of `OpenTelemetryApi`. This includes not only customer projects, but also `carthage` Smoke Tests in our repo.
Pinned the version of `OpenTelemetryApi` in `Cartfile`

chore: Pin OpenTelemetryApi version in Cartfile

---

DatadogCore/Tests/DatadogObjc/DDDatadogTests.swift
DatadogCore/Tests/DatadogObjc/DDRUMMonitorTests.swift
DatadogObjc/Sources/ObjcIntercompatibility/ObjcIntercompatibility.swift

All the attributes coming from ObjC API are wrapped into `AnyEncodable` https://github.com/DataDog/dd-sdk-ios/blob/1a61f0f8b1388b12145c4ef5695b7892b48146d6/DatadogObjc/Sources/ObjcIntercompatibility/ObjcIntercompatibility.swift#L13. It means that we cannot get raw attribute value when getting it by key, we need to unwrap it.
Wrap objc attribute in `AnyEncodable` **only** if the type is not already `Encodable`.

RUM-5174 Fix attributes objc interop

---

DatadogSessionReplay/Sources/SessionReplayConfiguration.swift

📦 Fixing lint problem for `swiftlint` 0.55.1.
It passed CI because we use `swiftlint` 0.53.0 in our runners. This fix prepares `develop` branch for linter upgrade on CI.
The `@_exported import` introduced for SR configuration was missing linter opt-out. It is now added the same way as it was done for in [RUM](https://github.com/DataDog/dd-sdk-ios/blob/1a61f0f8b1388b12145c4ef5695b7892b48146d6/DatadogRUM/Sources/RUMConfiguration.swift#L11-L17) and [Trace](https://github.com/DataDog/dd-sdk-ios/blob/1a61f0f8b1388b12145c4ef5695b7892b48146d6/DatadogTrace/Sources/TraceConfiguration.swift#L11-L22) configuration.

chore: Fix linter issue for `swiftlint` 0.55.1

---

DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/Instrumentation/WatchdogTerminations/WatchdogTerminationAppState.swift
DatadogRUM/Sources/Instrumentation/WatchdogTerminations/WatchdogTerminationAppStateManager.swift
DatadogRUM/Sources/Instrumentation/WatchdogTerminations/WatchdogTerminationChecker.swift
DatadogRUM/Sources/RUMConfiguration.swift
DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationAppStateManagerTests.swift
DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationCheckerTests.swift
DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationMocks.swift
DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationMonitorTests.swift

After starting dogfooding WT, we saw 300+ terminations caused by WT in s8s but those are not actually WT but normal terminations caused by https://github.com/appium/appium-xcuitest-driver/blob/main/lib/real-device.js#L216 API. This API is used by s8s for Restart Application special action.
Add extra `syntheticsEnvironment` state variable which stores the state if the app was running in s8s or not. This value is determined based on the presence of `_dd.synthetics.test_id` or `_dd.synthetics.result_id` env vars.
I couldn't find any other information in the form of env var, args or launch args which we can use to make a decision so it not only covers s8s but also covers other UI automation frameworks.

fix: Watchdog Termination is not supported in Synthetics env

---

Package.swift

Related https://github.com/DataDog/opentelemetry-swift-packages/pull/17
We are not sure when the dependency issue will be resolved at the root level. 
Take a dependency on the forked version of otel-swift that has only APIs.

chore: use otel-swift fork that only has APIs

---

CHANGELOG.md
DatadogRUM/Sources/RUMMonitorProtocol+Convenience.swift
DatadogRUM/Sources/RUMMonitorProtocol.swift
DatadogRUM/Tests/DDTAssertValidRUMUUID.swift
DatadogRUM/Tests/Instrumentation/RUMInstrumentationTests.swift
TestUtilities/Helpers/DDAssert.swift

#filePath exposes full paths of build files. Use of #fileID is encouraged by Apple both because it gives you better privacy and reduces the size of the compiled binary.
refs: RUM-5155

feat: Replace use of #filePath with #fileID

---

.gitlab-ci.yml
CHANGELOG.md
DatadogLogs/Sources/Logs.swift
DatadogLogs/Tests/LogsTests.swift

Follow-up for https://github.com/DataDog/dd-sdk-ios/commit/00fd8f7366e80cb2fed92bcc883f41026cdaed9e - backtrace reporter was added to the Logs feature, but it was never passed in the constructor call.

Inject backtrace reporter into Logs feature

---

CHANGELOG.md
DatadogCore/Sources/Core/DataStore/FeatureDataStore.swift
DatadogCore/Sources/Core/DatadogCore.swift
DatadogCore/Sources/Core/Storage/Directories.swift
DatadogCore/Sources/Core/Storage/Files/File.swift
DatadogCore/Tests/Datadog/DatadogTests.swift
DatadogInternal/Sources/DataStore/DataStore.swift
TestUtilities/Mocks/DataStoreMock.swift

We have `clearAllData` today which clears the events but doesn't clear the feature data storage that we use for persisting data for feature likes app hangs, watchdog terminations etc.
Introduce new API to clear data in the feature data storage.

RUM-5084 feat: add ability to clear data in feature data storage

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/Debugging/DebugManualTraceInjectionViewController.swift
Datadog/Example/Utils/MultiSelector.swift
DatadogInternal/Sources/NetworkInstrumentation/TraceContextInjection.swift

Testing multiple header types and injection control is not one click away.
I'm not a SwiftUI expert, the MultiSelector code is inspired from https://github.com/Jeehut/MultiSelectorDemo/tree/main
This code was in my stashes for some time and it makes sense to add to our manual testing to help everyone.
- Add support injection types
- Ability to select multiple headers
- Print JSON response for quick verification
- Changed default address to https://httpbin.org/get which returns back the headers which we can quickly verify.

chore: make testing distributed header injection easier in Example app

---

DatadogCore/Sources/Core/Storage/Files/Directory.swift

The error message we get today is non actionable and doesn't provide information why the file create failed.
```
InternalError: Failed to write data to file - Cannot create file at path: /var/mobile/Containers/Data/Application/E08E89DC-F1F2-496E-BEB0-B5D9E9359F8E/Library/Caches/com.datadoghq/v2/5168944e862876aa5a9ad4e5df4a654f6d54deca3edc50e66544bff2a690103e/rum/v2/742819228496
```
Replaced file creation with a API which throws.

RUM-1000 chore: use throwing API to create the file

---

CHANGELOG.md
Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Sources/Core/MessageBus.swift
DatadogObjc/Sources/RUM/RUMDataModels+objc.swift
DatadogRUM/Sources/DataModels/RUMDataModels.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/Instrumentation/MemoryWarnings/MemoryWarning.swift
DatadogRUM/Sources/Instrumentation/MemoryWarnings/MemoryWarningMonitor.swift
DatadogRUM/Sources/Instrumentation/MemoryWarnings/MemoryWarningReporter.swift
DatadogRUM/Sources/Instrumentation/RUMInstrumentation.swift
DatadogRUM/Sources/RUMMonitor/RUMCommand.swift
DatadogRUM/Tests/Instrumentation/MemoryWarnings/MemoryWarningMocks.swift
DatadogRUM/Tests/Instrumentation/MemoryWarnings/MemoryWarningMonitorTests.swift
DatadogRUM/Tests/Instrumentation/RUMInstrumentationTests.swift

memory warnings are not reported, with WT now in place these warnings can be helpful to get bigger picture and root cause the WT.
Initial plan was to setup a context observer which will listen to memory warnings but the current dependency management around backtrace tracking doesn't allow generating a backtrace in DatadogContextProvider. This would have been a generic solution where any target can listen to memory warnings but had to drop this idea.
Instead, I added `MemoryWarningMonitor` which monitors the memory warnings and reports them when they occur.
Reporting part is kept outside the monitor to keep the monitor simple and testable.
Model update https://github.com/DataDog/rum-events-format/pull/215
PS: I had the context observer working property basis which can be retrieved from …

RUM-5248 feat: send memory warning as RUM error

---

.gitlab-ci.yml

📦 Fixes the problem of [blocking CI pipeline](https://gitlab.ddbuild.io/DataDog/dd-sdk-ios/-/pipelines/39669904) for `develop` when manual Dogfooding jobs are added (since https://github.com/DataDog/dd-sdk-ios/pull/1961).
Expected behaviorus are:
- The `develop` pipeline is not blocked by awaiting manual jobs to be ran.
- The failures of Dogfooding jobs should not alter the state of `develop` commit integration (such should be only determined from default integration stages like tests, ui-tests and smoke-tests).
Using [`rules:allow_failure:true`](https://docs.gitlab.com/ee/ci/yaml/index.html#rulesallow_failure):
> Use [`allow_failure: true`](https://docs.gitlab.com/ee/ci/yaml/index.html#allow_failure) in rules to allow a job to fail without stopping the pipeline.
> 
> You can also use …

RUM-4079 chore: Do not block CI pipeline with dogfooding jobs

---

CHANGELOG.md
DatadogCore/Tests/Datadog/Tracing/TracingURLSessionHandlerTests.swift
DatadogTrace/Sources/Integrations/TracingURLSessionHandler.swift
DatadogTrace/Sources/TraceConfiguration.swift
DatadogTrace/Sources/Tracer.swift
DatadogTrace/Tests/TracingURLSessionHandlerTests.swift

APM needs to be able to differentiate between a client span vs other span to be able to build features on top of it.
Attach `span.kind` for all network spans in Trace module.
The ask is for APM spans only, not for RUM spans as they are ingested by RUM BE.

RUM-4709 feat: decorate network span kind as `client`

---

DatadogCore/Sources/Core/Context/DatadogContextProvider.swift
DatadogCore/Tests/Datadog/DatadogCore/Context/DatadogContextProviderTests.swift
DatadogRUM/Sources/Instrumentation/WatchdogTerminations/WatchdogTerminationMonitor.swift
DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationMonitorTests.swift

TLDR: when reading `context` from `FeatureScope` triggers a context update which again publishes context updates again to all the subscribes and we end up in a loop.
This shoots up CPU usage and an app termination likely.
- Now, when we read the context, we no longer update it.
- a small improvement in WT message receiver
There a few learnings from this bug
- The current pub-sub mechanism is very complex and requires a lot of dive deep before you can start making sense.
- The value pub-sub delivers to its consumers is very simple which we have talked before also. For example, on every context, telemetry, webview or baggage message, each receiver is notified which is wastage of CPU cycles. The receivers must be able to subscribe to individual message or part of message.

fix: do not send context updates on context read

---

.gitlab-ci.yml
SmokeTests/carthage/Makefile
tools/carthage-shim.sh
tools/release/build-xcframeworks.sh
tools/repo-setup/repo-setup.sh
tools/secrets/config.sh
tools/secrets/get-secret.sh

📦 To prevent a known [Carthage issue](https://github.com/Carthage/Carthage/issues/545) where the GitHub API rate limit is exceeded:
```
GitHub API request failed: API rate limit exceeded for (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```
this PR introduces the use of `GITHUB_ACCESS_TOKEN` to authenticate Carthage operations. By using a GitHub token, Carthage will benefit from a higher rate limit, as detailed [here](https://github.com/Carthage/Carthage/pull/605). This setup was previously implemented in Bitrise, and we are now porting it to GitLab.
Unlike in Bitrise, where we could export a global `GITHUB_ACCESS_TOKEN` environment variable for a single workflow, GitLab requires a different approach. We use …

RUM-5344 chore: Export GH token to avoid rate limiting `carthage` in CI

---

.gitlab-ci.yml

🧰 💊 The [Cocoapods podspec lint job](https://gitlab.ddbuild.io/DataDog/dd-sdk-ios/-/jobs/584827484) failed for the `2.15.0` release due to:
```
- ERROR | [watchOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
- NOTE  | [watchOS] xcodebuild:  xcodebuild: error: Found no destinations for the scheme 'App' and action clean.
```
Root cause:
- In #1918 we added `watchOS` build compatibility which required Internal, Core, Logs, and Trace podspecs to build for `watchOS`.
- The "Publish CP podspecs (*)" jobs were [using Xcode 15.3.0](https://github.com/DataDog/dd-sdk-ios/blob/0331b7ef6605b6c014f169ac96993dfbd450c010/.gitlab-ci.yml#L348) without supplying watchOS runtime via `./tools/runner-setup.sh` script.
Following the [latest upgrade to macOS …

chore: Upgrade CI jobs to Xcode 15.4.0; fix: Cocoapods release in 2.15.0

---

.gitlab-ci.yml

🩹 Patching `master` with #1975 fix to release pipeline.
For fix details, see: #1975
[2.15.0 pre-relase is out](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.15.0), so after this PR is merged to `master` I will move the `2.15.0` tag to recent commit on `master`. This should restart the release automation. The automation was tested for this fix using `RELEASE_DRY_RUN=1` and `RELEASE_GIT_TAG=2.15.0` in [this job](https://gitlab.ddbuild.io/DataDog/dd-sdk-ios/-/pipelines/40192896):

Merge #1975 to `master` (fix: Cocoapods release in 2.15.0)

---

DatadogAlamofireExtension.podspec
DatadogExtensions/Alamofire/README.md
README.md

📦 Starting from [2.5.0](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.5.0), RUM can automatically track Alamofire requests, making the DatadogAlamofireExtension pod obsolete. Maintaining this pod is cumbersome as it adds an extra code path to the network instrumentation logic, which became problematic in [issue #1638](https://github.com/DataDog/dd-sdk-ios/issues/1638).
The new network instrumentation API introduced in 2.5.0 can handle Alamofire requests without requiring a separate pod. This solution also works for SPM, Carthage, and XCFramework integration. This PR deprecates DatadogAlamofireExtension in favor of the new instructions explained in the following documentation PR:
- https://github.com/DataDog/documentation/pull/24253
- Created …

RUM-3060 feat: Deprecate Alamofire extension pod

---

CHANGELOG.md
DatadogCore/Tests/Datadog/RUM/RUMVitals/VitalRefreshRateReaderTests.swift
DatadogRUM/Sources/RUMVitals/VitalRefreshRateReader.swift

Last time when we touched this area, we normalized the FPS relative to the expected rendering rate for variable refresh rate displays.
ie when a display is rendering at 30fps and expected rate is also 30fps, we report 60fps. This is because our backend only supports 60fps and renders useful indicators.
However, in some case, it has been observed that sometimes display renders quicker than expected.
ie when a display is rendering at 45fps and expected rate is 30fps, in this case normalization doesn't work and we go on to report 90fps which is not correct.

RUM-2903 fix: refresh rate vital for variable refresh rate displays when over performing

---

tools/clean.sh

🧰 This PR recovers our CI after the bad effect of moving pre-release tag in **2.15.0** release. 
What has happened:
- 2.15.0 tag was originally put on master [0331b7e](https://github.com/DataDog/dd-sdk-ios/commit/0331b7ef6605b6c014f169ac96993dfbd450c010) by creating **2.15.0** pre-release
- “Publish CP podspecs (internal)” job has failed and required #1975 patch
- With patch merged, the 2.15.0 tag was moved to [df7f98e](https://github.com/DataDog/dd-sdk-ios/commit/df7f98ea7cadbe2f8e775b474573f3db7ba81938)
We assumed that moving tags for GH pre-releases is safe but it is definitely not. Some iOS dependency managers rely on cloning `dd-sdk-ios` repo and caching it. By changing tag’s reference we interrupted these systems.
The problem became evident in our CI with `carthage bootstrap` …

chore: Clean Carthage cache as part of `make clean`

---

CHANGELOG.md
tools/clean.sh

📦 We cherry-pick #1968 and #1967 fixes to `2.14.x` release, making `2.14.2` hotfix.
We don't follow regular git-flow for this hotfix as the released change already exists in `2.15.0` and we only cherry-pick it to `2.14.x` family.
The `2.14.2` tag will be put on the [last commit](https://github.com/DataDog/dd-sdk-ios/commits/hotfix/2.14.2/) from `hotfix/2.14.2` branch. Check [`hotfix/2.14.2` → `master` diff](https://github.com/DataDog/dd-sdk-ios/compare/master...hotfix/2.14.2?expand=1) to review what we're about to release.

chore: Update CHANGELOG.md with `hotfix/2.14.2`

---

DatadogObjc/Sources/RUM/RUMDataModels+objc.swift
DatadogRUM/Sources/DataModels/RUMDataModels.swift

The telemetry configuration schema has been updated in [this PR](https://github.com/DataDog/rum-events-format/pull/216) to add the new `startRecordingImmediately` parameter, which allows to automatically start a recording when enabling Session Replay on mobile SDKs ([RFC](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3897426405/RFC+-+Session+Replay+Start+Stop+API)). This PR takes care of updating the corresponding models in the iOS SDK.
Running `make rum-models-generate` to automatically update the models locally.

RUM-5598 Update RUM models with startRecordingImmediately

---

CHANGELOG.md
DatadogExtensions/Alamofire/DatadogAlamofireExtension.swift

Customers are not fully aware that extension is no longer support from APIs.
Marked all the Alamofire types as deprecated with suggesting to use `URLSessionInstrumentation`

chore: mark Alamofire extension types deprecated

---

DatadogInternal/Sources/Concurrency/ReadWriteLock.swift
DatadogInternal/Sources/Telemetry/Telemetry.swift
DatadogInternal/Tests/Telemetry/TelemetryMocks.swift
DatadogRUM/Sources/Integrations/TelemetryReceiver.swift
DatadogSessionReplay/Sources/Feature/Baggages.swift
DatadogSessionReplay/Sources/Feature/SessionReplayFeature.swift
DatadogSessionReplay/Sources/Recorder/RecordingCoordinator.swift
DatadogSessionReplay/Sources/SessionReplay.swift
DatadogSessionReplay/Sources/SessionReplayConfiguration.swift
DatadogSessionReplay/Tests/Recorder/RecordingCoordinatorTests.swift
DatadogSessionReplay/Tests/SessionReplayConfigurationTests.swift
DatadogSessionReplay/Tests/SessionReplayTests.swift

This PR adds the ability for customers to:
- Start and stop a recording 
- Disable automatic recording when enabling Session Replay
See [RFC](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3897426405/RFC+-+Session+Replay+Start+Stop+API#Actions) for more details.
- Introduce a new `startRecordingImmediately` optional parameter when enabling Session Replay, defaulting to `true`
- A new field has been added for telemetry as well
- Models have already been updated in [#216](https://github.com/DataDog/rum-events-format/pull/216) and #1983
- Add new set of `start` and `stop` public APIs to the existing `SessionReplay` public enum, through static functions
- Introduce a `recordingEnabled` variable to `RecordingCoordinator` to track when the user wants to start or stop a recording
- …

RUM-5536 [SR] Start / Stop API

---

BenchmarkTests/Benchmarks/Sources/Benchmarks.swift
BenchmarkTests/Benchmarks/Sources/Metrics.swift

Collect FPS metrics during benchmarks.

RUM-5555 Benchmarks: Collect FPS Metric

---

DatadogCore/Tests/DatadogObjc/DDSessionReplayTests.swift
DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDSessionReplay+apiTests.m
DatadogInternal/Sources/Models/SessionReplay/SessionReplayConfiguration.swift
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/Utils/SnapshotTestCase.swift
DatadogSessionReplay/Sources/Feature/SessionReplayFeature.swift
DatadogSessionReplay/Sources/Recorder/PrivacyLevel.swift
DatadogSessionReplay/Sources/Recorder/Recorder.swift
DatadogSessionReplay/Sources/Recorder/RecordingCoordinator.swift
DatadogSessionReplay/Sources/SessionReplay+objc.swift
DatadogSessionReplay/Sources/SessionReplay.swift
DatadogSessionReplay/Sources/SessionReplayConfiguration.swift
DatadogSessionReplay/Tests/Feature/RequestBuilder/JSON/SegmentJSONTests.swift
DatadogSessionReplay/Tests/Mocks/RecorderMocks.swift
DatadogSessionReplay/Tests/Processor/SnapshotProcessorTests.swift
DatadogSessionReplay/Tests/Recorder/RecordingCoordinatorTests.swift
DatadogSessionReplay/Tests/SessionReplayTests.swift
DatadogWebViewTracking/Tests/WebViewTrackingTests.swift
TestUtilities/Mocks/FeatureModels/SessionReplayConfigurationMocks.swift

This PR is the first step towards providing more granular control over global masking in Session Replay. It introduces a new privacy level for user touches (e.g., tap, swipe), allowing customers to choose whether to show or hide these touches in replays. Currently, touches are always visible.
For full context, refer to the [RFC](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3884548349/RFC+-+Session+Replay+Global+Masking+Configuration).
This PR establishes the new privacy level within the Session Replay Configuration but does not yet implement the logic for touch visibility in snapshots.
Future PRs will introduce additional privacy levels for images, text, and user inputs. The current Privacy Level will be deprecated once the global masking feature is fully implemented and …

RUM-5762 [SR] Create touchPrivacyLevel masking option

---

CHANGELOG.md
Datadog/Example/ExampleAppDelegate.swift
DatadogTrace/Sources/OpenTelemetry/OTelSpan.swift
DatadogTrace/Tests/OpenTelemetry/OTelSpanTests.swift

Currently global tags are not included in the otel spans
- add global tags to the span first
- add local tags to the span, and if there is same key, then replace it

RUM-5716 fix: propagate global Tracer tags to otel span attributes

---

DatadogLogs/Sources/RemoteLogger.swift
DatadogLogs/Tests/RemoteLoggerTests.swift

Certain attributes (fingerprint and error source type) are removed as part of log processing because they are moved onto official properties of errors in logs.  However, when these errors are transmitted to RUM, the properties are not replaced, which they should be, so that RUM has all of the information about the error.

fix: Ensure needed attributes are sent from logs on the message bus

---

DatadogCore/Sources/Core/Upload/DataUploadConditions.swift

Workaround for the issue https://github.com/DataDog/dd-sdk-ios/issues/2004.
On a real Apple Watch device, `NWPathMonitor` component always returns value of `.unsatisfied` that results in no logs being ever uploaded to API. As there is no straight-forward replacement for watchOS platform, this PR assumes that Apple Watch device is always online (another solution could be to implement periodic URL check in time interval).
From _https://developer.apple.com/documentation/Technotes/tn3135-low-level-networking-on-watchOS_:
Datadog dashboard logs using the fix:
| Simulator | Real device |
| - | - |
| ![Capture-2024-08-20-141120](https://github.com/user-attachments/assets/a9d9248d-d56d-4507-b53d-cda41f0ebe15) | ![Capture-2024-08-20-140535](https://github.com/user-attachments/assets/c7f5efc3-e8c0-4 …

Always assume device is online on Apple Watch

---

DatadogCore/Tests/DatadogObjc/DDSessionReplayTests.swift
DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDSessionReplay+apiTests.m
DatadogInternal/Sources/Models/SessionReplay/SessionReplayConfiguration.swift
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/Utils/SnapshotTestCase.swift
DatadogSessionReplay/Sources/Feature/SessionReplayFeature.swift
DatadogSessionReplay/Sources/Recorder/PrivacyLevel.swift
DatadogSessionReplay/Sources/Recorder/Recorder.swift
DatadogSessionReplay/Sources/Recorder/RecordingCoordinator.swift
DatadogSessionReplay/Sources/SessionReplay+objc.swift
DatadogSessionReplay/Sources/SessionReplayConfiguration.swift
DatadogSessionReplay/Tests/Feature/RequestBuilder/JSON/SegmentJSONTests.swift
DatadogSessionReplay/Tests/Mocks/RecorderMocks.swift
DatadogSessionReplay/Tests/Processor/SnapshotProcessorTests.swift
DatadogSessionReplay/Tests/Recorder/RecordingCoordinatorTests.swift
DatadogSessionReplay/Tests/SessionReplayTests.swift
DatadogWebViewTracking/Tests/WebViewTrackingTests.swift
TestUtilities/Mocks/FeatureModels/SessionReplayConfigurationMocks.swift

Following #1992, this PR introduces a new privacy level for text and inputs (e.g., label, textfield, checkbox, switch), allowing customers to decide what they want to mask. Currently, text and inputs are handled through the `defaultPrivacyLevel`, which will be later deprecated.
There are 3 levels:
- `maskSensitiveInputs`: shows all texts except sensitive inputs, eg. password fields.
- `maskAllInputs`: masks all inputs fields, eg. textfields, switches, checkboxes.
- `maskAll`: masks all texts and inputs, even labels.
For full context, refer to the [RFC](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3884548349/RFC+-+Session+Replay+Global+Masking+Configuration).
This PR establishes the new privacy level within the Session Replay Configuration but does not yet implement the new logic …

RUM-5760 [Session Replay] Add textAndInputPrivacyLevel

---

CHANGELOG.md
Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Tests/DatadogObjc/DDLogsTests.swift
DatadogObjc/Sources/Logs/Logs+objc.swift
DatadogObjc/Sources/Logs/LogsDataModels+objc.swift
api-surface-objc
api-surface-swift

This PR adds `setEventMapper` ObjC API for logs.

RUM-4311: Add Logs event mapper to ObjC API

---

DatadogSessionReplay/Sources/Recorder/Utilities/UIImage+SessionReplay.swift

While working on the configuration we have discovered that lazy identifier for UIImages in Session Replay doesn't work.
Mitigation is simple. When introducing `DatadogExtension` instead of direct extension we forget to change the object that maintains associated objects.
This is hard to test. We could potentially measure the time. Second time should be way faster than the first one, but it has a risk of being flaky.

Fix lazy image SR identifier

---

tools/license/check-license.sh

Exclude `BenchmarkTests/UIKitCatalog` from license check.
Not sure why the job was not executed for the PR 🤔

fix: Exclude `BenchmarkTests/UIKitCatalog` from license check

---

.gitlab-ci.yml
BenchmarkTests/Makefile
BenchmarkTests/Runner/AppDelegate.swift
Makefile

Add job to build the `BenchmarkTests` project if any changes were applied to catch build failures in PRs.
```yml
Benchmark Build:
stage: smoke-test
rules:
- if: '$CI_COMMIT_BRANCH' # when on branch with following changes compared to develop
changes:
paths:
- "BenchmarkTests/**/*"
compare_to: 'develop'
script:
- make benchmark-build
```

RUM-5555 Add job to build benchmarks runner

---

BenchmarkTests/BenchmarkTests.xcodeproj/project.pbxproj
BenchmarkTests/BenchmarkTests.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
BenchmarkTests/Makefile
BenchmarkTests/Runner/AppDelegate.swift
BenchmarkTests/Runner/Info.plist

Updates in `Info.plist` were not used in the `.app` build
Use `agvtool new-version` to update the `CURRENT_PROJECT_VERSION` from the Runner target only.
The `CURRENT_PROJECT_VERSION` will translate to `CFBundleVersion` in app bundle which will be used as metric tag.

fix: Increment the `CURRENT_PROJECT_VERSION` only

---

Datadog/IntegrationUnitTests/Public/CoreTelemetryIntegrationTests.swift
Datadog/IntegrationUnitTests/RUM/SDKMetrics/RUMSessionEndedMetricIntegrationTests.swift
DatadogCore/Sources/Core/Storage/FilesOrchestrator.swift
DatadogCore/Tests/Datadog/Mocks/RUMFeatureMocks.swift
DatadogInternal/Sources/Telemetry/Telemetry.swift
DatadogInternal/Tests/Telemetry/TelemetryTests.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/Integrations/TelemetryReceiver.swift
DatadogRUM/Sources/RUMConfiguration.swift
DatadogRUM/Sources/SDKMetrics/SessionEndedMetricController.swift
DatadogRUM/Tests/Integrations/TelemetryInterceptorTests.swift
DatadogRUM/Tests/Integrations/TelemetryReceiverTests.swift
DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift
DatadogRUM/Tests/RUMTests.swift
DatadogRUM/Tests/SDKMetrics/SessionEndedMetricControllerTests.swift
DatadogSessionReplay/Sources/Recorder/RecordingCoordinator.swift
TestUtilities/Mocks/TelemetryMocks.swift

📦 This PR introduces the ability to sample each SDK metric using distinct sample rates.
Previously, [all metrics](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3534554673/Telemetry+Metric+Specs) shared the same [`metricTelemetrySampleRate`](https://github.com/DataDog/dd-sdk-ios/blob/691fc07fbc32267ec313cd3c3590f1155a9573ac/DatadogRUM/Sources/RUMConfiguration.swift#L273-L276) (15%). To sample batch metrics at different rates in `RUM-5083`, this refactoring is necessary.
A new property, `sampleRate`, has been added to the telemetry message that carries metric data:
```swift
public struct MetricTelemetry {
public let name: String
public let attributes: [String: Encodable]
/// The sample rate for this metric, applied in addition to the telemetry sample rate.
/// ...
/// This sample …
```

RUM-5083 refactor: Allow different sampling rates for each metric

---

DatadogCore/Sources/Core/Storage/FilesOrchestrator.swift
DatadogCore/Sources/SDKMetrics/BatchMetrics.swift
DatadogCore/Tests/Datadog/Core/Persistence/FilesOrchestrator+MetricsTests.swift

📦 This PR lowers the sample rate for "Batch Deleted" and "Batch Closed" metrics from 15% to 1.5%.
Counterpart of https://github.com/DataDog/dd-sdk-android/pull/2146
Leveraging metric-specific sample rate configuration added in https://github.com/DataDog/dd-sdk-ios/pull/2015, this PR changes `sampleRate` in batch metrics from default 15% to custom 1.5%.

RUM-5083 chore: Lower Batch Metrics sample rate to 10% of its original value

---

DatadogCore/Tests/Datadog/Logs/DatadogLogsFeatureTests.swift
DatadogCore/Tests/Datadog/Tracing/DatadogTraceFeatureTests.swift
DatadogLogs/Sources/Feature/RequestBuilder.swift
DatadogTrace/Sources/Feature/RequestBuilder.swift
IntegrationTests/IntegrationScenarios/Scenarios/Logging/LoggingCommonAsserts.swift
IntegrationTests/IntegrationScenarios/Scenarios/Tracing/TracingCommonAsserts.swift

query param ddtags getting injected to log tags
https://docs.datadoghq.com/api/latest/logs/
This PR removes retry info from non RUM endpoints where we are not sure about the behavior of ddtags query param.

RUM-3889 fix: remove retry information from Logs and Trace requests

---

BenchmarkTests/BenchmarkTests.xcodeproj/project.pbxproj
BenchmarkTests/Benchmarks/Package.swift
BenchmarkTests/Benchmarks/Sources/Benchmarks.swift
BenchmarkTests/Makefile
BenchmarkTests/Runner/AppDelegate.swift
BenchmarkTests/Runner/BenchmarkProfiler.swift
Datadog/Datadog.xcodeproj/project.pbxproj
DatadogInternal/Sources/Benchmarks/BenchmarkProfiler.swift
Package.swift

Expose profiler interface for benchmarking.
During benchmarking, a concrete implementation of the profiler will be injected to collect data during execution of the SDK. In production, the profiler is no-op and immutable.
Current profiler interface can create a tracer instance for a given operation.
The `BenchmarkProfiler` is added to the `DatadogInternal` module with a single static variable allowing injecting a profiler instance from the Benchmark project.

RUM-5755 Add Benchmark Profiler Interface

---

Gemfile.lock

Updates dependencies using `Bundler` to address [dependabot](https://github.com/DataDog/dd-sdk-ios/security/dependabot) warnings.
By running:
`bundle update`

Bundle dependencies update

---

DatadogSessionReplay/Sources/Recorder/Recorder.swift
DatadogSessionReplay/Tests/Recorder/RecorderTests.swift
IntegrationTests/Runner/Scenarios/SessionReplay/SRScenarios.swift

In #1992, we introduced a new privacy level: `SessionReplayTouchPrivacyLevel`, with offers 2 options: `.show` and `.hide`. This PR ensures that the privacy configuration is respected by preventing the capture of touch snapshots when the level is set to `.hide`.
This update skips touch snapshots when `touchPrivacyLevel` is set to `.hide`

RUM-5762 [SR] Ignore touch snapshots when touchPrivacyLevel is set to .hide

---

.gitlab-ci.yml
BenchmarkTests/Makefile

Set env `DD_BENCHMARK` for benchmark build

fix: Benchmark Upload

---

CHANGELOG.md
DatadogRUM/Sources/RUMMonitor/Monitor.swift
DatadogRUM/Sources/RUMMonitor/RUMCommand.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Sources/RUMMonitorProtocol.swift
DatadogRUM/Sources/SDKMetrics/SessionEndedMetric.swift
DatadogRUM/Tests/RUMMonitor/Monitor+GlobalAttributesTests.swift

https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3951001790/RFC+View+loading+time+manual+API
This PR follows the RFC and introduces `addViewLoadingTime` API. The implementation follows the existing command pattern and updates the `RUMViewEvent.view.loading` when called which also triggers the view update.
This PR doesn't introduce any telemetry which will be added in upcoming PRs. We will require https://github.com/DataDog/dd-sdk-ios/pull/2019 to merged as prerequisite.

RUM-5841 feat(view-loading-api): implement addViewLoadingTime API

---

.gitlab-ci.yml

📦 This PR enables CI Test Visibility in Unit Test jobs (iOS and tvOS).
Test Visibility was earlier integrated in https://github.com/DataDog/dd-sdk-ios/pull/1999 through separate "shadow" job. It was to pre-check the impact on our CI in sandbox environment. Because everything looks stable and performant, we now integrate it to regular jobs.
- Removed "shadow" job.
- Changed regular jobs to `USE_TEST_VISIBILITY=1`

chore: Enable test visibility in unit test jobs (iOS + tvOS)

---

.gitlab-ci.yml

🧰 This PR adds an additional 20-minute delay to the "Publish CP podspecs (legacy)" release job. The extra time ensures that "internal" and "dependent" podspecs, published earlier, are  available, reducing the need for manual job restart.
This delay should have been included in [PR #1945](https://github.com/DataDog/dd-sdk-ios/pull/1945) but was missed due to an oversight.
The job configuration was updated to include the extended delay.

chore: Increase delay in publish "legacy" podspecs job

---

DatadogInternal/Sources/Telemetry/Telemetry.swift
DatadogRUM/Sources/Integrations/TelemetryReceiver.swift
DatadogRUM/Sources/RUMMonitor/Monitor.swift
DatadogRUM/Sources/RUMMonitor/RUMCommand.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMSessionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Sources/RUMMonitorProtocol.swift
DatadogRUM/Tests/RUMMonitor/Monitor+GlobalAttributesTests.swift

https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3951001790/RFC+View+loading+time+manual+API
- Integration of the telemetry events
- happy path
- when there is overwrite
- when there the current view is not active
- when there is no view scope
- `overwrite` argument to the API

RUM-5841 feat(view-loading-api): introduce telemetry for the API and overwrite flag

---

.gitlab-ci.yml

📦 This PR adds utility job a the end of every CI pipeline. It will be listed in "status checks" required for PR to be merged.
After this is merged, this job should be listed as the only job in:

chore: Add "Sync GH Checks" utility job

---

CHANGELOG.md
DatadogSessionReplay/Sources/Recorder/Utilities/UIKitExtensions.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISwitchRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextFieldRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextViewRecorder.swift
DatadogSessionReplay/Tests/Recorder/Utilties/UIKitExtensionsTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextFieldRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextViewRecorderTests.swift

`UITextInputTraits`'s `isSecureTextEntry` and `textContentType` properties are mutable, meaning that a sensitive texts could be revealed to the end user. e.g.: Revealing a password for verification.
But in Session Replay, we should keep considering the text as sensitive even if it was revealed.
Keep sensitivity in memory using associated object on views conforming to `UITextInputTraits`.

RUM-872 Keep Secured Text Hidden

---

DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDSessionReplay+apiTests.m
DatadogSessionReplay/Sources/SessionReplay+objc.swift

The `startRecording` and `stopRecording` public APIs were introduced in #1986 to allow manual control over session recording. However, these APIs were not exposed to Objective-C, limiting access for ObjC users. This PR addresses that gap.
This PR adds `startRecording` and `stopRecording` methods to the `DDSessionReplay` class, making them accessible from Objective-C.

Expose Start/Stop API to Objc

---

DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDSessionReplay+apiTests.m
DatadogSessionReplay/Sources/PrivacyLevel+SessionReplay.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshot.swift
DatadogSessionReplay/Sources/SessionReplayOverrides+objc.swift
DatadogSessionReplay/Tests/DDSessionReplayOverridesTests.swift
DatadogSessionReplay/Tests/Mocks/RecorderMocks.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIViewRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotTests.swift
DatadogSessionReplay/Tests/SessionReplayOverrideTests.swift

This PR implements the logic for the hidden property in Session Replay, as a continuation of #2058, which introduces Fine-Grained Masking (FGM) overrides.
- Added a new `SessionReplayOverrideExtension` property to `ViewAttributes`.
- In the view recorder, it now checks for the `hiddenPrivacy` property.
- When this property is set, it returns a placeholder frame for the hidden view and ignores its child views.
- Renamed `hiddenPrivacy` to `hide`, as it is now a `Bool`, making the name more intuitive after converting from an `enum`.
- Addressed [this comment](https://github.com/DataDog/dd-sdk-ios/pull/2058#discussion_r1775231721) from the previous PR to clean up the `SessionReplayOverrideExtension` implementation.

RUM-6223 Implement Hidden Override logic

---

DatadogSessionReplay/Tests/Mocks/SRDataModelsMocks.swift

Tiny follow-up for https://github.com/DataDog/dd-sdk-ios/pull/2070 which I missed. It adds a value to the random value mock as well.

Add KMP to the `Segment.Source` random value mock

---

CHANGELOG.md
Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Tests/DatadogObjc/DDInternalLoggerTests.swift
DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDInternalLogger+apiTests.m
DatadogObjc/Sources/DDInternalLogger+objc.swift
api-surface-objc

This PR adds simple APIs to do SDK logging/telemetry from Objective-C side.

RUM-6395: Add internal logging/telemetry APIs to ObjC

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDSessionReplay+apiTests.m
DatadogSessionReplay/Sources/PrivacyLevel+SessionReplay.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIDatePickerRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UILabelRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIPickerViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISegmentRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextFieldRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewAttributes+Copy.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshot.swift
DatadogSessionReplay/Sources/SessionReplayOverrides+objc.swift
DatadogSessionReplay/Sources/SessionReplayPrivacyOverrides.swift
DatadogSessionReplay/Tests/DDSessionReplayOverridesTests.swift
DatadogSessionReplay/Tests/Mocks/RecorderMocks.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UILabelRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UINavigationBarRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISegmentRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITabBarRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextFieldRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextViewRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIViewRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotTests.swift
DatadogSessionReplay/Tests/SessionReplayOverrideTests.swift

This PR builds on the work from #2058, which introduced Fine-Grained Masking (FGM) overrides (see the [RFC](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3901129961/RFC+-+Session+Replay+Fine+Grained+Masking+Overrides) [internal] for more details). It implements the logic for applying the text and input privacy override, as well as image privacy override, at the view level. The goal is to allow views to have a specific privacy setting that overrides the global configuration.
Additionally, it ensures that privacy overrides propagate to child views, allowing parents to enforce privacy settings for their entire subtree, unless explicitly overridden by child views.
- Updated recorders that handle text and user inputs, as well as images (e.g., `UILabelRecorder`, `UIPickerViewRecorder`, …

RUM-6284 Implement Overrides Logic

---

.gitlab-ci.yml
tools/runner-setup.sh

📦 This PR reorganizes and improves the coverage of smoke tests for our iOS SDK. It now includes coverage for all supported Swift versions while maintaining compatibility with various dependency managers.
The `smoke-test` stage has been streamlined to 4 key jobs:
- **Smoke Test (iOS)** and **Smoke Test (tvOS)**: These jobs test SDK integration through CocoaPods, Carthage, Xcode's SPM, and XCFrameworks. They run on a `macos:sonoma` runner with Xcode 15.4.
- **SPM Build (Swift 5.9)**: This job builds `Package.swift` for each supported platform using the `macos:ventura` runner with Xcode 15.2.
- **SPM Build (Swift 5.10)**: Similar to the above, but for Swift 5.10 using the `macos:sonoma` runner with Xcode 15.4.
The two "SPM Build" jobs now fully mirror [SDK builds in Swift Package …

RUM-5650 chore: Refine Smoke Tests and add Swift 5.9 coverage

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogSessionReplay/Sources/SessionReplay+objc.swift
DatadogSessionReplay/Tests/DDSessionReplayTests.swift
api-surface-swift

The current Objective-C interface for Session Replay doesn't adhere to the internal guidelines for Objective-C interoperability (see [RFC](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3157787243/RFC+-+Modular+Objective-C+Interface#Recommended-solution)).
- Applied `@_spi(objc)` to hide the ObjC interfaces from Swift consumers while keeping them accessible to ObjC clients.
- Prefixed types with `objc_*` to differentiate them from Swift-native types.
- Updated the ObjC interface for `SessionReplay`, `SessionReplayConfiguration`, and the different privacy levels following the modular interface guidelines.
- Moved `DDSessionReplayTests` to the Session Replay module

Fix Session Replay ObjC interface

---

.github/PULL_REQUEST_TEMPLATE.md

It happened several times that when adding a new public API, we forget to add the corresponding Objective-C interface. Adding a dedicated checkbox to the PR template will serve as a reminder and help prevent this oversight in the future.

Add ObjC checkbox to PR template

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Tests/Datadog/Mocks/RUMFeatureMocks.swift
DatadogCore/Tests/Datadog/RUM/UIApplicationSwizzlerTests.swift
DatadogRUM/Sources/Instrumentation/Actions/RUMActionsHandler.swift
DatadogRUM/Sources/Instrumentation/Actions/SwiftUI/SwiftUIActionModifier.swift
DatadogRUM/Sources/Instrumentation/Actions/UIKit/UIApplicationSwizzler.swift
DatadogRUM/Sources/Instrumentation/Actions/UIKit/UIEventCommandFactory.swift
DatadogRUM/Sources/Instrumentation/RUMCommandSubscriber.swift
DatadogRUM/Sources/Instrumentation/RUMInstrumentation.swift
DatadogRUM/Sources/Instrumentation/Views/RUMViewsHandler.swift
DatadogRUM/Sources/Instrumentation/Views/SwiftUI/SwiftUIViewModifier.swift
DatadogRUM/Sources/RUMMonitor/Monitor.swift
DatadogRUM/Sources/RUMMonitor/RUMCommand.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMUserActionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Tests/Instrumentation/Actions/RUMActionsHandlerTests.swift
DatadogRUM/Tests/Instrumentation/RUMInstrumentationTests.swift
DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift
DatadogRUM/Tests/RUMTests.swift

📦 This PR resolves a conflict in RUM actions instrumentation that occurs when a user taps a SwiftUI button embedded inside a UIKit table view cell. This issue arises in apps that mix both UI frameworks, leading to inaccurate tracking of the tap action.
```
+--------UITableView----------+
|   +----UITableViewCell----+  |
|   |                       |  |
|   |  [  SwiftUI Button ]  |  |
|   |                       |  |
|   +-----------------------+  |       
+-------------------------------+
```
In this case, UIKit’s instrumentation [handled by `UIKitRUMActionsHandler`](https://github.com/DataDog/dd-sdk-ios/blob/d4e2247a6f55b95292e4b1b2953a25bdd8c67306/DatadogRUM/Sources/Instrumentation/Actions/UIKit/UIKitRUMUserActionsHandler.swift#L137) treats the `UITableViewCell` as the best target for …

RUM-6354 fix: Prioritize SwiftUI RUM actions over UIKit actions

---

Datadog/IntegrationUnitTests/SessionReplay/WebRecordIntegrationTests.swift
DatadogSessionReplay/Sources/SessionReplayConfiguration.swift
DatadogSessionReplay/Tests/SessionReplayConfigurationTests.swift

We decided to add a default value for session replay sample rate. This aligns with other public APIs which all provide a default value for sampling rates.
- Added a default value of `100` to `replaySampleRate` for both Session Replay Configuration public APIs
- Updates tests accordingly

RUM-6386 Add default value for replaySampleRate

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogInternal/Sources/CoreRegistry.swift
DatadogInternal/Tests/CoreRegistryTest.swift
DatadogSessionReplay/Sources/SessionReplay.swift
DatadogSessionReplay/Tests/SessionReplayTests.swift
TestUtilities/Mocks/CoreMocks/MockFeature.swift

While we support multiple core instances for most features, we want to restrict this for Session Replay. 
- Before enabling Session Replay, check if any instance has already enabled the feature.
- If Session Replay has been enabled, then an error is thrown, and a telemetry debug message is logged

RUM-6376 Only enable single core for Session Replay

---

DatadogCore/Sources/Core/DatadogCore.swift
DatadogCore/Sources/Core/Storage/FeatureStorage.swift
DatadogCore/Sources/Core/Storage/FilesOrchestrator.swift
DatadogCore/Sources/SDKMetrics/BatchMetrics.swift
DatadogCore/Tests/Datadog/Core/FeatureTests.swift
DatadogCore/Tests/Datadog/Core/Persistence/FilesOrchestrator+MetricsTests.swift
DatadogCore/Tests/Datadog/Core/Persistence/Writing/FileWriterTests.swift
DatadogInternal/Tests/Telemetry/TelemetryTests.swift

Enriches `Batch Deleted` telemetry metric with `backgroundTaskEnabled` configuration info.
This is needed for measuring batch delivery success rate based on existence of the configuration.
I have added new field `background_tasks_enabled`.
`in_background` is still hardcoded to false, because knowing if the deletion happen in the background is not trivial.
Although I think we're mostly interested in measuring the difference is success rate for two different configurations, rather than knowing if batch file was deleted in background/foreground.

Add background upload configuration info to batch deleted telemetry

---

.gitlab-ci.yml

📦 Temporarily disabling CI Tests until we find resolution to this problem:
```
🔥 Failed to delete `TestsDirectory`: Error Domain=NSCocoaErrorDomain Code=512 ""com.datadoghq.ios-sdk-tests-434C4A49-7195-4957-AE16-9A943737BDBF" couldn't be removed."
```
We observe this problem disappearing if CI Tests is disabled.
Disabling CI Tests on CI via `USE_TEST_VISIBILITY` env.

chore: Temporarily disable CI Tests as causing test failures

---

.github/PULL_REQUEST_TEMPLATE.md
api-surface-swift

There has been some recent updates in our public APIs, including:
- Privacy overrides recently merged from feature branch #2088
- Default value for Session Replay sample rate #2075
Run `make api-surface` to update the `api-surface-swift` file.

Update API surface

---

.gitlab-ci.yml
CHANGELOG.md
DatadogAlamofireExtension.podspec
DatadogCore.podspec
DatadogCore/Sources/Versioning.swift
DatadogCrashReporting.podspec
DatadogInternal.podspec
DatadogLogs.podspec
DatadogObjc.podspec
DatadogRUM.podspec
DatadogSessionReplay.podspec
DatadogTrace.podspec
DatadogWebViewTracking.podspec
TestUtilities.podspec
tools/clean.sh

Merge `release/2.19.0` to `develop`

---

Datadog/IntegrationUnitTests/Public/NetworkInstrumentationIntegrationTests.swift

Some URL session tests depend on `https://www.datadoghq.com` which could fail to load (somehow). But our test are expecting data by force unwrapping the response.
Loose the expectation by comparing the URL response with the response that was instrumented, regardless of its data.

Fix Flaky Test - Remove force unwrapping in URL response validation

---

CHANGELOG.md
DatadogCore/Tests/Datadog/Mocks/RUMDataModelMocks.swift
DatadogObjc/Sources/RUM/RUMDataModels+objc.swift
DatadogRUM/Sources/DataModels/RUMDataModels.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMResourceScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Tests/Mocks/RUMDataModelMocks.swift
DatadogSessionReplay/Sources/Models/SRDataModels.swift
api-surface-objc
api-surface-swift
tools/rum-models-generator/Package.swift
tools/rum-models-generator/Sources/CodeGeneration/Generate/Transformers/Swift/JSONToSwiftTypeTransformer.swift
tools/rum-models-generator/Sources/CodeGeneration/Print/ObjcInteropPrinter.swift
tools/rum-models-generator/Sources/CodeGeneration/Print/SwiftPrinter.swift
tools/rum-models-generator/Tests/CodeGenerationTests/Generate/Transformers/JSONToSwiftTypeTransformerTests.swift
tools/rum-models-generator/Tests/CodeGenerationTests/Print/SwiftPrinterTests.swift

Additional properties are generated with `internal(set)` accessor, preventing users from mutating their attributes using event mappers. These changes align with Android and allow additional properties mutation in both Swift and ObjC.
- Update model generator to make additional properties mutable
- Fix Swift reserved keyword in generator; following schema change that define a property named `protocol`.

RUM-5992 Support additional properties mutation

---

CHANGELOG.md
DatadogCore/Sources/Core/DatadogCore.swift
DatadogCore/Tests/Datadog/DatadogCore/DatadogCoreTests.swift
DatadogCore/Tests/Datadog/Mocks/DatadogInternal/UploadMock.swift

📦🐞 This PR fixes a race condition that occurs during the change of tracking consent from `.pending` to `.granted`. This issue could result in the loss of events recorded on the current thread right before the consent change. 
The fix involves synchronizing data migration on the context queue to prevent conflicts with ongoing "event write" operations. This change guarantees that all latest events are accurately migrated based on the updated consent state.

RUM-3175 fix: Fix race condition during consent change (pending → granted)

---

DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/Instrumentation/WatchdogTerminations/WatchdogTerminationMonitor.swift
DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationMocks.swift
DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationMonitorTests.swift

Fix typo in WatchdogTerminationMonitor init argument name.
~~stroage~~ storage

Fix: Typo in WatchdogTerminationMonitor init argument

---

CHANGELOG.md
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIDatePickerRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIPickerViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITabBarRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextFieldRecorder.swift

Fixes the issues of type mismatch error which was causing full snapshot enforcement in some cases.
We've been wrongly passing identifier of the parent recorder to it's children which was causing in some cases issue where two views would be recorded with different type but the same id. It's because `NodeIDGenerator` depends on the identifier of the recorder.

RUM-917 Fix type mistmatch error

---

tools/dogfooding/dogfood.sh

Appears that dependencies are no longer pinned in `DatadogApp.xcworkspace/xcshareddata/swiftpm/Package.resolved` but only in `.package.resolved`.

chore: Fix dogfooding in mobile app

---

CHANGELOG.md
DatadogCore/Sources/Core/Storage/FilesOrchestrator.swift
DatadogCore/Tests/Datadog/Core/Persistence/FilesOrchestratorTests.swift

📦 This PR addresses a potential file name conflict issue during tracking consent changes.
Initially considered a flakiness ❄️ in [testWhenWritingEventsWithPendingConsentThenGranted_itUploadsAllEvents()](https://github.com/DataDog/dd-sdk-ios/blob/004ca93c6036c0ceead2f09fedebfae9496c9da3/DatadogCore/Tests/Datadog/DatadogCore/DatadogCoreTests.swift#L81) (added in https://github.com/DataDog/dd-sdk-ios/pull/2063), it was discovered to be a real issue that can occur in certain edge cases.
The conflict happens when files are moved between `.pending` and `.granted` folders and events are written immediately before and after the consent change. If this occurs very quickly (under 1ms), the last batch in the pending folder may be named the same as the next batch in the granted folder. Since the SDK …

RUM-3175 Fix possible file name conflict during consent change

---

CHANGELOG.md
Datadog/Datadog.xcodeproj/project.pbxproj
DatadogInternal/Sources/NetworkInstrumentation/URLSession/URLSessionInterceptor.swift
DatadogInternal/Tests/NetworkInstrumentation/URLSessionInterceptorTests.swift

The `URLSessionInterceptor` keeps a cache of trace context but the `shared()` methods returns a new instance each time, leading to trace discontinuity.
Make the trace-context cache static.

RUM-7251 Static trace context caching

---

CHANGELOG.md
DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDSessionReplay+apiTests.m
DatadogSessionReplay/Sources/SessionReplay+objc.swift
DatadogSessionReplay/Tests/DDSessionReplayTests.swift
api-surface-swift

This PR adds missing Session Replay `startRecordingImmediately` ObjC API.

RUM-7435: Add Session Replay `startRecordingImmediately` ObjC API

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/Utils/SnapshotTestCase.swift
DatadogSessionReplay/Sources/Feature/SessionReplayFeature.swift
DatadogSessionReplay/Sources/Recorder/Recorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UnsupportedViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotBuilder.swift
DatadogSessionReplay/Sources/SessionReplayConfiguration.swift
DatadogSessionReplay/Tests/Mocks/FeatureFlagsMock.swift
DatadogSessionReplay/Tests/Processor/SnapshotProcessorTests.swift
DatadogSessionReplay/Tests/Recorder/RecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UnsupportedViewRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotBuilderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotTests.swift

Enable SwiftUI recording using a feature-flag
Defines `SessionReplay.Configuration.FeatureFlags` with `.swiftui` disabled by default.

RUM-7316 Session Replay SwiftUI Feature Flag

---

DatadogCrashReporting/Sources/CrashContext/CrashContext.swift
DatadogCrashReporting/Sources/CrashReporting.swift
DatadogCrashReporting/Sources/CrashReportingFeature.swift
DatadogCrashReporting/Sources/CrashReportingPlugin.swift
DatadogCrashReporting/Sources/PLCrashReporterIntegration/CrashReport.swift
DatadogCrashReporting/Sources/PLCrashReporterIntegration/CrashReportMinifier.swift
DatadogCrashReporting/Sources/PLCrashReporterIntegration/DDCrashReportBuilder.swift
DatadogCrashReporting/Sources/PLCrashReporterIntegration/DDCrashReportExporter.swift
DatadogCrashReporting/Sources/PLCrashReporterIntegration/PLCrashReporterIntegration.swift
DatadogCrashReporting/Sources/PLCrashReporterIntegration/PLCrashReporterPlugin.swift

This PR makes the crash reporter public and adds some hooks to send reports at other times than startup.
---
This pull request includes several changes to the `DatadogCrashReporting` module, focusing on enhancing crash reporting functionality and improving compatibility with conditional imports. The most important changes include adding a new method to merge RUM attributes in `CrashContext`, updating the `CrashReporting` class to handle conditional imports, and making the `CrashReportingFeature` class and `CrashReportingPlugin` protocol public.
Enhancements to crash reporting functionality:
* [`DatadogCrashReporting/Sources/CrashContext/CrashContext.swift`](diffhunk://#diff-b3539333f9d72967f5061090c4d4ba9a73edadb9334e088f8815fd032199e6f0R168-R195): Added a new method …

Make Crash Reporter Plugin Public

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/DisplayList+Reflection.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/DisplayList.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/SwiftUIWireframesBuilder.swift
DatadogSessionReplay/Tests/Mocks/SRDataModelsMocks.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIHostingViewRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeRecorderTests.swift

Support SwiftUI scroll-view offset.
The `ViewInfo` for the SwiftUI view-cache includes a `view` reference as well as a `container` reference, both of `UIView` type. In most effects, both referred to the same instance. But when the `.platformGroup` effect is applied, all the items of the subtree will be renderer in as a group in a the `container` of a platform view (aka `UIView`).
A `SwiftUI.ScrollView` creates a `.platformGroup` effect where the `view` is the a `UIScrollView` and the `container` its content. This effect place the container frame in the view's coordinate space, meaning that the container will translate when the view scrolls.
In order to support `.platformGroup`, we get the [container's frame in the view's coordinate …

RUM-7178 Support SwiftUI platform group

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/SwiftUIWireframesBuilder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIHostingViewRecorder.swift
DatadogSessionReplay/Tests/Recorder/GraphicImagePrivacyTests.swift

With SwiftUI images now being recorded in Session Replay, we need to apply the global privacy level set by the customer.
- Added an `ImagePrivacyLevel` property to `SwiftUIWireframesBuilder` to handle image masking logic.
- Extended `ImagePrivacyLevel` to provide a utility for resolving the correct image privacy level during image recording.
- Applied heuristics to mask images larger than 100 points when the privacy setting is `maskNonBundledOnly`, aligning with Android's implementation.

RUM-7462 [SR][SwiftUI] Apply global image privacy

---

DatadogCore/Tests/Datadog/RUM/RUMVitals/VitalCPUReaderTests.swift

The test [testWhenCPUUnderHeavyLoadItMeasuresHigherCPUTicks()](https://github.com/datadog/dd-sdk-ios/blob/965f1e09f704a79c7158233d00608c99d38ac498/DatadogCore/Tests/Datadog/RUM/RUMVitals/VitalCPUReaderTests.swift#L15-L25) compares the CPU ticks under heavy and light processing and it started being flaky in GitLab. The CPU ticks measured should be greater on heavy processing.
This PR mitigates the flakiness of the test.
- To avoid false positives, the blocks of processing are run more than once. This way we can have an average of measures that dilute the false positives. 
- The duration of both tasks are now the same, to avoid comparisons of CPU ticks under different time intervals. 
- It uses `CFAbsoluteTimeGetCurrent` instead of `Date` to get the time since it is more suitable for …

RUM-6583: Fix flaky test for RUM CPU vital

---

CHANGELOG.md
DatadogCore/Tests/DatadogObjc/DDConfigurationTests.swift
DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDConfiguration+apiTests.m
DatadogObjc/Sources/DatadogConfiguration+objc.swift
api-surface-objc

This PR adds missing `backgroundTasksEnabled` ObjC API to the Datadog configuration.

Add `backgroundTasksEnabled` ObjC API

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Tests/Datadog/Mocks/RUMFeatureMocks.swift
DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift
DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/Utils/SnapshotTestCase.swift
DatadogSessionReplay/Sources/Feature/SessionReplayFeature.swift
DatadogSessionReplay/Sources/Feature/SessionReplayTelemetry.swift
DatadogSessionReplay/Sources/Recorder/Recorder.swift
DatadogSessionReplay/Sources/Recorder/RecordingCoordinator.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/Color+Reflection.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/CustomDump.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/DisplayList+Reflection.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/Image+Reflection.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/SwiftUIWireframesBuilder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/Text+Reflection.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIHostingViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotBuilder.swift
DatadogSessionReplay/Sources/SessionReplayConfiguration.swift
DatadogSessionReplay/Sources/Utilities/Queue.swift
DatadogSessionReplay/Sources/Utilities/ReflectionMirror.swift
DatadogSessionReplay/Sources/Utilities/Reflector.swift
DatadogSessionReplay/Tests/Feature/SessionReplayTelemetryTests.swift
DatadogSessionReplay/Tests/Mocks/RecorderMocks.swift
DatadogSessionReplay/Tests/Recorder/RecorderTests.swift
DatadogSessionReplay/Tests/Recorder/Utilties/ReflectionMirrorTests.swift
DatadogSessionReplay/Tests/Recorder/Utilties/ReflectorTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIHostingViewRecorderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotBuilderTests.swift
DatadogSessionReplay/Tests/Utilities/QueueTests.swift
TestUtilities/Mocks/TelemetryMocks.swift

Report telemetry while reflecting `SwiftUI` renderer.
Such report involved deduplication of telemetry messages.
The `Reflection` now takes a `Reflector` parameter to reflect descendant properties and report telemetry errors. This new container allow reflecting partial data - such as collection or dictionary - and still report failures.
This dedicated implementation of `Telemetry` offloads reports on a dedicated queue and deduplicate debug and error messages. The deduplication is important in the context of Session Replay as redundant errors can happen at each snapshot cycle. By deduplicated at the feature level, we prevent overloading the message-bus with telemetry messages.
The dedicated telemetry queue targets the processor's queue with lower QOS to minimise the telemetry impact on …

RUM-7309 [SR] Async and Deduplicate Telemetry

---

Datadog/Datadog.xcodeproj/project.pbxproj

📦 This PR upgrades the CI Test instrumentation to 2.5.3-beta1 (dogfooding).
The new version is expected to resolve the issue with [Test Impact Analysis](https://docs.datadoghq.com/tests/test_impact_analysis/) (TIA) which we had to disable in [#2108](https://github.com/DataDog/dd-sdk-ios/pull/2108).
- Upgraded the `dd-sdk-swift-testing` version.
- Enabled TIA in the [CI Test Optimization Settings](https://docs.datadoghq.com/tests/test_impact_analysis/setup/swift/#activate-intelligent-test-runner-for-the-test-service) for `dd-sdk-ios`.

chore: Upgrade `dd-sdk-swift-testing` to `2.5.3-beta1`

---

DatadogRUM/Sources/RUMMonitor/Scopes/RUMSessionScope.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMSessionScopeTests.swift

PerformanceMetric events are triggered automatically by some of the cross platform frameworks, and can result in log spam as views transition or if no view is active. Fix it so that the performance metric event doesn't send log spam.
refs: RUM-6138

fix: Don't send log spam for PerformanceMetric updates

---

CHANGELOG.md
DatadogSessionReplay/Sources/Processor/Builders/RecordsBuilder.swift
DatadogSessionReplay/Tests/Processor/Builders/RecordsBuilderTests.swift
DatadogSessionReplay/Tests/Processor/SnapshotProcessorTests.swift

This PR is essentially reverting https://github.com/DataDog/dd-sdk-ios/pull/1567. Assumption made was wrong. We can expect view that from the wireframe perspective have a different root view (it can be done by fully covering the root with nontransparent view, which will remove the root during flattening process).
The reverted code was fixing some minor edge cases in React Native, although it has a serious penalty of creating double fullsnapshots in others.

RUM-7205 Double full snapshot bug

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/SwiftUIWireframesBuilder.swift
DatadogSessionReplay/Sources/Utilities/Reflector.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/SwiftUIWireframesBuilderTests.swift

Return placeholder wireframe when an unknown SwiftUI content is encountered.

RUM-7484 Add placeholder for unknown SwiftUI content

---

CHANGELOG.md
Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/RUM/ViewLoadingMetricsTests.swift
DatadogCore/Tests/Datadog/Mocks/RUMFeatureMocks.swift
DatadogRUM/Sources/RUMMetrics/ITNVMetric.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMSessionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMUserActionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift
DatadogRUM/Tests/RUMMetrics/ITNVMetricTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMUserActionScopeTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift
TestUtilities/Helpers/SwiftExtensions.swift

📦⏱️ This PR introduces the **Interaction-to-Next-View** (ITNV) metric to measure the time between the last action in a previous view and the moment the next view is started. This metric provides valuable insights into the time it takes for a view to be prepared and displayed after user interaction.
The ITNV value is reported under the following conditions:
- The value is tracked only if a `.tap`, `.click`, or `.swipe` action occurred in the previous view, and the time between the last action and the start of the next view is less than 3 seconds
- For `.tap` and `.click`, the measurement starts at the action's start time.
- For `.swipe`, the measurement starts at the action's end time.
**Example:** In the scenario below, A2 is the last action in the "Previous View." It’s a `.tap` action …

RUM-7107 feat: Add Interaction To Next View metric in RUM 

---

DatadogCore/Tests/Datadog/TracerTests.swift
DatadogCore/Tests/Matchers/SpanMatcher.swift
DatadogTrace/Sources/Span/SpanEventEncoder.swift

This PR moves the `_dd.agent_psr` field from the span's root to the metrics map. 
Also removes the logic related to _dd at the root of the span as it was only used for this field and also because this field shouldn't be set at the root.
When looking to use a stricter json schema (see ticket) for the json payload parser, we noticed that some spans would be rejected due to invalid fields that didn't comply with the established schema. This is one of those spans.
This field was added in PR #1259 but I don't know how this was tested.
I am not familiar with this repository and swift. Feedback is welcome.

[APMTI-2602] Move the agent_psr from the root of the span to the metrics map

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/RUM/ViewLoadingMetricsTests.swift
DatadogCore/Tests/Datadog/Mocks/RUMFeatureMocks.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/RUMConfiguration.swift
DatadogRUM/Sources/RUMMetrics/NetworkSettledResourcePredicate.swift
DatadogRUM/Sources/RUMMetrics/TTNSMetric.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMResourceScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMScopeDependencies.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift
DatadogRUM/Tests/RUMMetrics/TTNSMetricTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift

📦 ⏱️ This PR introduces an API to customize the classification of resources for the **Time-to-Network-Settled (TTNS)** metric using a predicate-based strategy. The predicate allows users to define which resources should be considered for the TTNS calculation based on their own logic. 
This provides more flexibility in how the metric is computed, enabling users to customize resource classification for different use cases.
**Previously**, resources were included in TTNS calculation solely based on a fixed `100ms` threshold after the view starts:
**Now**, users can customize resource classification by implementing the `NetworkSettledResourcePredicate` protocol, allowing for flexible inclusion or exclusion of resources. For example:
Users can also use the default …

RUM-7103 feat: Add API for classifying resources in TTNS metric

---

tools/dogfooding/dogfood.sh

Update the `DogfoodingConfig.swift` path for the Datadog iOS app. See https://github.com/DataDog/datadog-ios/pull/1774
- Update the path to `Targets/Platform/DatadogObservability/DogfoodingConfig.swift`
- Remove the line that updates the `.package.resolved` in the root, as it is not needed.

[MOB-4625] Update `DogfoodingConfig.swift` path

---

CHANGELOG.md

🧽 `CHANGELOG.md` was not updated with 2.22.0 release.
Inserting `2.22.0` bar.

chore: Fix CHANGELOG after 2.22.0 release

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/RUM/ViewLoadingMetricsTests.swift
DatadogCore/Tests/Datadog/Mocks/RUMFeatureMocks.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/RUMConfiguration.swift
DatadogRUM/Sources/RUMMetrics/ITNVMetric.swift
DatadogRUM/Sources/RUMMetrics/NetworkSettledResourcePredicate.swift
DatadogRUM/Sources/RUMMetrics/NextViewActionPredicate.swift
DatadogRUM/Sources/RUMMetrics/TTNSMetric.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMScopeDependencies.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMSessionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMUserActionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift
DatadogRUM/Tests/RUMMetrics/ITNVMetricTests.swift
DatadogRUM/Tests/RUMMetrics/TTNSMetricTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMUserActionScopeTests.swift

📦 ⏱️ This PR introduces an API to customize the classification of interactions for the **Interaction-To-Next-View (ITNV)** metric using a predicate-based strategy. The predicate enables users to define which RUM actions in the previous view should be considered as the "last interaction" for calculating ITNV value (how long it takes to reach the next view).
This approach is similar to the TTNS metric API introduced in #2160.
**Previously**, ITNV was computed by fixed rules, always selecting the last "tap," "click," or "swipe" occurring within 3 seconds before the next view started. For example:
**Now**, with the `NextViewActionPredicate` protocol, developers can implement custom logic to classify the "last interaction." For example, they might choose actions based on a certain name:
Users …

RUM-7823 feat: Add API for classifying "last interaction" in ITNV metric

---

Datadog/IntegrationUnitTests/RUM/RUMAttributesIntegrationTests.swift
DatadogRUM/Sources/RUMMonitor/Monitor.swift

This PR resolves a flaky test issue that occurred when new commands were executed after stopping a session.
- The test validates that a View scope from a stopped session is immutable from other commands (e.g. adding new global attributes). 
- The test starts two sessions and asserts the attributes added to the view events.

RUM-3029: Fix flaky test while handling a stopped session

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogSessionReplay/Sources/Recorder/Utilities/Int64+SessionReplay.swift
DatadogSessionReplay/Sources/Recorder/Utilities/Xoshiro.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/SwiftUIWireframesBuilder.swift
DatadogSessionReplay/Tests/Utilities/XoshiroTests.swift

Session Replay of SwiftUI is generating staling views in replays, this is due to duplicate wireframe IDs between UIKit recorder and SwiftUI. UIKit recorders use incremental wireframe ids while SwiftUI is based on a `seed` value of the content, these value can overlap and create duplicates.
To avoid overlaps, we now use a seeded random generator to generate deterministic IDs base of the content's `seed` value.
The deterministic generator implements the [xoshiro256**](https://prng.di.unimi.it/xoshiro256starstar.c) generator for its speed and low memory footprint.

RUM-7937 [SR] Use Deterministic Random Wireframe ID

---

tools/utils/echo-color.sh

Super minor, but I couldn't help it :)
On iTerm there was an issue rendering the box.
Before:
After:

Fix echo box on iTerm

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/RUM/SDKMetrics/RUMSessionEndedMetricIntegrationTests.swift
Datadog/IntegrationUnitTests/RUM/SDKMetrics/RUMViewEndedMetricIntegrationTests.swift
DatadogCore/Tests/Datadog/Mocks/RUMFeatureMocks.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/RUMConfiguration.swift
DatadogRUM/Sources/RUMMetrics/INVMetric.swift
DatadogRUM/Sources/RUMMetrics/TNSMetric.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMScopeDependencies.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Sources/SDKMetrics/SessionEndedMetricController.swift
DatadogRUM/Sources/SDKMetrics/ViewEndedMetric.swift
DatadogRUM/Sources/SDKMetrics/ViewEndedMetricController.swift
DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift
DatadogRUM/Tests/RUMMetrics/INVMetricTests.swift
DatadogRUM/Tests/RUMMetrics/TNSMetricTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift
TestUtilities/Helpers/SwiftExtensions.swift

📦 🔭 Following the [spec](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/4534173727/RUM+View+Ended+Telemetry+-+Spec) (internal), this PR introduces "RUM View Ended" telemetry. The primary goal is to measure the quality of view timings (INV, TNS, and addViewLoadingTime()), laying the groundwork for overall view monitoring — similar to how ["RUM Session Ended"](https://github.com/DataDog/dd-sdk-ios/pull/1866) provides session insights.
First, this PR refactors `TNSMetric` and `INVMetric` to report their values through `Result<TimeInterval, NoValueReason>` rather than a simple `TimeInterval?`. This gives finer-grained insight into why a metric might be unavailable, using new enums `TNSNoValueReason` and `INVNoValueReason`:
```diff
// TNSMetric
- func value(with appStateHistory: …
```

RUM-7112 chore: Add "RUM View Ended" telemetry to track TNS' and INV's quality

---

CHANGELOG.md
Datadog/IntegrationUnitTests/RUM/RUMAttributesIntegrationTests.swift
DatadogCore/Tests/DatadogObjc/DDRUMMonitorTests.swift
DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDRUMMonitor+apiTests.m
DatadogObjc/Sources/RUM/RUM+objc.swift
DatadogRUM/Sources/RUMMonitor/Monitor.swift
DatadogRUM/Sources/RUMMonitorProtocol.swift
DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift
DatadogRUM/Tests/RUMMonitor/Monitor+GlobalAttributesTests.swift
api-surface-objc
api-surface-swift

This PR introduces a new interface to add and remove multiple attributes simultaneously. 
This enhancement reduces threading pressure on the Message Bus when handling multiple attributes at once.
The new interfaces to handle multiple attributes are:
```swift
func addAttributes(_ attributes: [AttributeKey: AttributeValue])
func removeAttributes(forKeys keys: [AttributeKey])
```

RUM-7691: Add `addAttributes` and `removeAttributes` APIs

---

DatadogTrace/Sources/OpenTracing/OTSpan.swift

The following statement in OpenTracing doc is not true: If span has `nil` parent, it becomes the child of the active span.
```swift
// As `span3` has the explicit parent (nil) it won't become the child of the active span:
let span3 = tracer.startSpan(operationName: "another root", childOf: nil)
```
Update the doc and mention `startRootSpan` instead.

Fix OpenTracing doc

---

DatadogCore/Private/ObjcAppLaunchHandler.m
DatadogCore/Private/include/ObjcAppLaunchHandler.h
DatadogCore/Sources/Core/Context/LaunchTimePublisher.swift
DatadogCore/Sources/Core/DatadogCore.swift
DatadogCore/Sources/Datadog.swift
DatadogCore/Tests/Datadog/CrashReporting/CrashContext/CrashContextProviderTests.swift
DatadogCore/Tests/Datadog/DatadogCore/Context/LaunchTimePublisherTests.swift
DatadogCore/Tests/Datadog/Mocks/CoreMocks.swift
DatadogCrashReporting/Sources/CrashContext/CrashContext.swift
DatadogInternal/Sources/Context/DatadogContext.swift
DatadogRUM/Sources/Instrumentation/AppHangs/FatalAppHangsHandler.swift
DatadogRUM/Sources/Instrumentation/WatchdogTerminations/WatchdogTerminationMonitor.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMApplicationScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMResourceScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMSessionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
TestUtilities/Mocks/DatadogContextMock.swift

📦 This is a refactoring PR that makes `context.launchTime` a non-optional property in `DatadogContext`:
```diff
- public var launchTime: LaunchTime?
+ public var launchTime: LaunchTime
```
The `LaunchTime` structure encapsulates key details about the application startup, including:
- Whether the app was pre-warmed.
- When the app was launched.
- How long the startup process took.
This refactoring streamlines and simplifies dependent SDK logic by eliminating multiple `if let` and `guard let` cases that previously led to unreachable control flows.
Units involved in this refactoring:
- `ApplicationLaunchHandler` – An Objective-C component that tracks key timestamps in the app launch sequence.
- `LaunchTimePublisher` – Listens for changes in `ApplicationLaunchHandler` and updates the SDK …

RUM-8371 chore: Make `context.launchTime` non-optional

---

DatadogRUM/Sources/Instrumentation/Actions/SwiftUI/SwiftUIActionModifier.swift

📦 ⛑️ We discovered that adding `.trackRUMTapAction()` modifier to a SwiftUI control inside a `List` causes gesture conflicts with SwiftUI’s built-in tap handling, leading to broken default behavior (e.g., `Button` actions or `NavigationLink` taps). 
We’ve filed a bug report with Apple ([FB16488816](https://openradar.appspot.com/FB16488816)), but no reliable workaround seems to exist.
Updated doc comments within `RUMTapActionModifier` and the `.trackRUMTapAction()` API to warn developers against using it in SwiftUI's `List`.

RUM-8504 chore: Warn about `.trackRUMTapAction()` usage inside SwiftUI `List`

---

DatadogCore/Sources/Core/Storage/Files/Directory.swift
DatadogCore/Sources/Core/Storage/FilesOrchestrator.swift
DatadogCore/Sources/SDKMetrics/BatchMetrics.swift
DatadogCore/Tests/Datadog/Core/Persistence/FilesOrchestrator+MetricsTests.swift

Add pending batches attribute to Batch Deleted Metric.
This attribute will help drawing distribution of pending batches throughout sessions.
`FilesOrchestrator` keeps track of pending batches and send it as part of `BatchDeletedMetric` telemetry.

RUM-8042 Add pending batches to batch deleted metric

---

DatadogCore/Sources/Core/Storage/Files/Directory.swift
DatadogCore/Sources/Core/Storage/FilesOrchestrator.swift

Follow up #2191
Count pending batches instead of reading the dir at each telemetry report.

RUM-8042 Count pending batches for telemetry

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Sources/Core/Upload/DataUploadStatus.swift
DatadogCore/Sources/Core/Upload/DataUploadWorker.swift
DatadogCore/Tests/Datadog/Core/Upload/DataUploadStatusTests.swift
DatadogCore/Tests/Datadog/Core/Upload/DataUploadWorkerTests.swift
DatadogInternal/Sources/SDKMetrics/SDKMetricFields.swift
DatadogInternal/Sources/SDKMetrics/UploadQualityMetric.swift
DatadogInternal/Sources/Telemetry/Telemetry.swift
DatadogRUM/Sources/Integrations/TelemetryInterceptor.swift
DatadogRUM/Sources/SDKMetrics/SessionEndedMetric.swift
DatadogRUM/Sources/SDKMetrics/SessionEndedMetricController.swift
DatadogRUM/Tests/Integrations/TelemetryInterceptorTests.swift
DatadogRUM/Tests/SDKMetrics/SessionEndedMetricControllerTests.swift
DatadogRUM/Tests/SDKMetrics/SessionEndedMetricTests.swift

Collect, aggregate, and report the Upload Quality Metric as specified in [RFC (internal)](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/4609049834/RFC+-+Additional+telemetry+for+uploader+improvements).
- The `DataUploadWorker` will report each upload cycle through 'Upload Quality' metric telemetry. This metric will include a failure description if applicable.
- The `TelemetryInterceptor` will intercept and forward the 'Upload Quality' metric's attributes to the `SessionEndedMetricController`.
- The `SessionEndedMetricController` will count upload cycle and failures to report the final `upload_quality` attribute of the 'RUM Session Ended' metric telemetry.

RUM-8042 Collect Upload Quality Metric

---

DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift

Fix mock view controller init.

RUM-7564 Fix Mock View Controller in Xcode 16

---

DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift

RUM backend has a special handling for `hasReplay` flag - once it is sent to true in any view update it cannot go back to false.
On the client side, however, we reduce the views, keeping only the last view update for a given `viewId` in the batch. If this view had originally `hasReplay: true` and then last view update has `hasReplay:false` (because by the time view update is sent session replay is disabled) we will miss session replay info for this view.
Introduction of a new private attribute `hasReplay` in the `RUMViewScope` class that is set each time a new View event is built. In the case that it has once been set to true, each following `RUMViewEvent` that is created will keep `hasReplay` set to true.

RUM-1871 Reduced view update may miss `hasReplay` flag set before

---

Cartfile
Cartfile.resolved
DatadogCrashReporting.podspec
DatadogCrashReporting/Sources/PLCrashReporterIntegration/PLCrashReporterIntegration.swift
DatadogCrashReporting/Tests/PLCrashReporterIntegration/DDCrashReportExporterTests.swift
Package.swift

It updates the version of PLCR to [1.12.0](https://github.com/microsoft/plcrashreporter/releases/tag/1.12.0).
Now it is possible to define dynamically the size of the crash report. It's 2MB as a default.
All package manager specifications (SPM, CocoaPods, Carthage) were updated to take this new version into consideration.

RUM-7419: Make crash report size configurable

---

DatadogCore/Sources/Core/Upload/DataUploadDelay.swift
DatadogCore/Sources/Core/Upload/DataUploadWorker.swift
DatadogCore/Tests/Datadog/Core/Upload/DataUploadDelayTests.swift
DatadogCore/Tests/Datadog/Core/Upload/DataUploadWorkerTests.swift

Reset upload delay when the SDK recovers from a backoff state (upload blocked).
More context in [RFC (internal)](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/4672979222/RFC+-+Mobile+uploader+improvements+to+reduce+batch+loss+rate)
Simply reset the delay to minimum after a successful upload.

RUM-8039 Reset Upload Delay After Backoff

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogInternal/Sources/Utils/CustomDump.swift
DatadogInternal/Sources/Utils/ReflectionMirror.swift
DatadogInternal/Sources/Utils/Reflector.swift
DatadogInternal/Tests/Utils/ReflectionMirrorTests.swift
DatadogInternal/Tests/Utils/ReflectorTests.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/Color+Reflection.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/DisplayList+Reflection.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/Image+Reflection.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/Text+Reflection.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIHostingViewRecorder.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/SwiftUIWireframesBuilderTests.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIHostingViewRecorderTests.swift

This PR moves the reflection logic in the `SessionReplay` module to the `Internal` module. The goal is to make this code available to both `SessionReplay` and `RUM` modules, in anticipation of the Auto-instrumentation work.
- Moving `Reflector` and `ReflectionMirror` to the internal module
- Making core reflection types and methods `public` where necessary

[RUM-8413] Move Reflection code to internal module

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/Public/WebLogIntegrationTests.swift
Datadog/IntegrationUnitTests/RUM/StartingRUMSessionTests.swift
Datadog/IntegrationUnitTests/RUM/WebEventIntegrationTests.swift
DatadogCore/Sources/Core/Context/ApplicationStatePublisher.swift
DatadogCore/Sources/Core/DatadogCore.swift
DatadogCore/Sources/Datadog.swift
DatadogCore/Tests/Datadog/CrashReporting/CrashContext/CrashContextProviderTests.swift
DatadogCore/Tests/Datadog/DatadogCore/Context/ApplicationStatePublisherTests.swift
DatadogCrashReporting/Sources/CrashContext/CrashContext.swift
DatadogCrashReporting/Sources/CrashReporting.swift
DatadogInternal/Sources/Concurrency/Threading.swift
DatadogInternal/Sources/Context/AppState.swift
DatadogInternal/Sources/Utils/Assert.swift
DatadogInternal/Tests/Context/AppStateHistoryTests.swift
DatadogLogs/Sources/Logs.swift
DatadogRUM/Sources/Instrumentation/WatchdogTerminations/WatchdogTerminationMonitor.swift
DatadogRUM/Sources/RUM.swift
DatadogRUM/Sources/RUMMetrics/TNSMetric.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMApplicationScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMSessionScope.swift
DatadogRUM/Tests/RUMMetrics/TNSMetricTests.swift
DatadogSessionReplay/Sources/SessionReplay.swift
DatadogTrace/Sources/Integrations/TracingURLSessionHandler.swift
DatadogTrace/Sources/Trace.swift
DatadogTrace/Tests/ContextMessageReceiverTests.swift
DatadogWebViewTracking/Sources/WebViewTracking.swift
DatadogWebViewTracking/Tests/WebViewTrackingTests.swift
TestUtilities/Mocks/DatadogContextMock.swift

📦 This PR refines how the SDK observes application state changes across Core and all Features. It streamlines this logic to ensure consistent state change notifications across different products
The main improvement ensures that all subsystems receive app state updates in a controlled order — **first Core, then Features**, respecting their `enable()` order. This is achieved by synchronizing initialization across all subsystems on the main thread, using a new helper in `DatadogInternal`:
```swift
/// Ensures the provided block is executed on the main thread, synchronously, rethrowing any error.
/// ...
public func runOnMainThreadSync<T>(_ block: () throws -> T) rethrows -> T {
if Thread.isMainThread {
return try block()
} else {
return try DispatchQueue.main.sync(execute: block)
}
}
```
⏱️ …

RUM-8371 chore: Synchronize app state observers across the SDK

---

BenchmarkTests/Benchmarks/Package.swift
CHANGELOG.md
Cartfile
Cartfile.resolved
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogTrace iOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogTrace tvOS.xcscheme
DatadogTrace.podspec
DatadogTrace/Sources/OpenTelemetry/NOPOTelSpan.swift
DatadogTrace/Sources/OpenTelemetry/NOPOTelSpanBuilder.swift
DatadogTrace/Sources/OpenTelemetry/OTelAttributeValue+Datadog.swift
DatadogTrace/Sources/OpenTelemetry/OTelSpan.swift
DatadogTrace/Sources/OpenTelemetry/OTelSpanBuilder.swift
DatadogTrace/Tests/OpenTelemetry/OTelAttributeValue+DatadogTests.swift
DatadogTrace/Tests/OpenTelemetry/OTelSpanTests.swift
Package.swift
SmokeTests/cocoapods/Podfile.src

📦 This PR updates `DatadogTrace` to use `OpenTelemetryApi` [**1.13.0**](https://github.com/DataDog/opentelemetry-swift-packages/releases/tag/1.13.0).
This addresses [#2190](https://github.com/DataDog/dd-sdk-ios/issues/2190).
The new `OpenTelemetryApi` version was published in [opentelemetry-swift-packages#27](https://github.com/DataDog/opentelemetry-swift-packages/pull/27), and this PR integrates it into `dd-sdk-ios`.
Since `1.6.0` (our previous `OpenTelemetryApi` dependency version), `open-telemetry-swift` introduced a breaking change in supported platforms, raising the minimum deployment targets from `.iOS(11)` and `.tvOS(11)` to `.iOS(13)` and `.tvOS(13)`. Because our SDK supports `.iOS(12)` and `.tvOS(12)`, this required adding a patch in `Package.swift` to conditionally adjust …

RUM-8558 Update DatadogTrace to OTel API `1.13.0`

---

BenchmarkTests/BenchmarkTests.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
BenchmarkTests/Runner/Scenarios/Logs/UI/LogsCustomContentView.swift
BenchmarkTests/Runner/Scenarios/Logs/UI/LogsHeavyTrafficContentView.swift
BenchmarkTests/Runner/Scenarios/Logs/UI/LogsUtils.swift

The `logLevel` and `payloadSize` pickers did not maintain a consistent order for their options, causing them to reorder each time the app was relaunched. This made running repeatable scenarios in Synthetics very tedious. This PR ensures a deterministic order for these pickers.

Fix non-deterministic order in pickers in Benchmark app

---

BenchmarkTests/BenchmarkTests.xcodeproj/project.pbxproj
BenchmarkTests/Benchmarks/Sources/Benchmarks.swift
BenchmarkTests/Benchmarks/Sources/Metrics.swift
BenchmarkTests/Runner/AppDelegate.swift
BenchmarkTests/Runner/BenchmarkMeter.swift
BenchmarkTests/Runner/BenchmarkProfiler.swift
DatadogCore/Sources/Core/Storage/Writing/FileWriter.swift
DatadogInternal/Sources/Benchmarks/BenchmarkProfiler.swift

To measure the upload capacity of the SDK, we plan to gather more metrics from its internals during benchmarking. This involves designing an interface to create simple meters during benchmark runs, allowing us to track internal metrics like bytes written per feature.
This update involves refactoring the [Benchmarks Library](BenchmarkTests/Benchmarks/Sources/Benchmarks.swift) to create only the `MetricProvider` and `TracerProvider` using the provided configuration.
Now, the CPU, Memory, and FPS measurements are handled by the `Runner` application using the created `MetricProvider`.
The `DatadogInternal` now provides the `BenchmarkMeter` protocol, which modules can use to create meters for specific metrics. The concrete implementation of `BenchmarkMeter` is accessible via the static …

RUM-8442 Add Benchmark Metric Meters

---

BenchmarkTests/BenchmarkTests.xcodeproj/project.pbxproj
BenchmarkTests/Benchmarks/Sources/Benchmarks.swift
BenchmarkTests/Benchmarks/Sources/MetricExporter.swift
BenchmarkTests/Benchmarks/Sources/Metrics.swift
BenchmarkTests/Runner/AppDelegate.swift
BenchmarkTests/Runner/BenchmarkMeter.swift
BenchmarkTests/Runner/BenchmarkProfiler.swift
DatadogCore/Sources/Core/Storage/Writing/FileWriter.swift
DatadogInternal/Sources/Benchmarks/BenchmarkProfiler.swift

Fix metrics tags issue introduced in https://github.com/DataDog/dd-sdk-ios/pull/2218
- Merge the Otel Metric Provider's resources with tags.
- Register the `MeterProvider` and `TracerProvider`

RUM-8442 Fix Benchmark Metrics Exporter

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/RUM/RUMViewHitchesIntegrationTests.swift
DatadogCore/Tests/Datadog/Mocks/RUM/RUMDataModelMocks.swift
DatadogObjc/Sources/RUM/RUMDataModels+objc.swift
DatadogRUM/Sources/DataModels/RUMDataModels.swift
DatadogRUM/Sources/FatalErrorBuilder.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/Integrations/CrashReportReceiver.swift
DatadogRUM/Sources/RUMConfiguration.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMScopeDependencies.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Sources/RUMVitals/RenderLoop/ViewHitchesReader.swift
DatadogRUM/Tests/Mocks/RUMDataModelMocks.swift
DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift
api-surface-objc
api-surface-swift

This PR updates the View events with information about View Hitches (Slow frames).
The proposed solution is defined in the [RFC (internal)](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/4722163962/RFC+-+UI+Slowness).
- Updates the RUM `DataModels` schema to have the View events with the `slow_frames` definition.
- Proposes a new configuration, `FeatureFlags`, to enable the capture of View Hitches.
- Populates the View events with View Hitches.
This is the second part of the Slow frames integration. The first PR focused on the engine to observe the render loop and can be found [here](https://github.com/DataDog/dd-sdk-ios/pull/2214).
This part focus on updating the View events with the observed Slow frames. The image below depicts the architecture of entities that capture the data …

RUM-8656: Update RUM schema and add App Hitches to View events

---

BenchmarkTests/Runner/BenchmarkMeter.swift
Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Sources/Core/Storage/Files/File.swift
DatadogCore/Sources/Core/Storage/FilesOrchestrator.swift
DatadogCore/Sources/Core/Upload/DataUploadWorker.swift
DatadogCore/Sources/Core/Upload/DataUploader.swift
DatadogCore/Sources/Core/Upload/FeatureUpload.swift
DatadogCore/Sources/Core/Upload/HTTPClient.swift
DatadogCore/Sources/Core/Upload/URLSessionClient.swift
DatadogCore/Sources/SDKMetrics/BenchmarkURLSessionTaskDelegate.swift
DatadogCore/Tests/Datadog/Core/Upload/DataUploadWorkerTests.swift
DatadogCore/Tests/Datadog/Core/Upload/DataUploaderTests.swift
DatadogCore/Tests/Datadog/Mocks/HTTPClientMock.swift
DatadogInternal/Sources/Benchmarks/BenchmarkProfiler.swift
Package.swift

Measure Upload Capacity during benchmarks.
Add custom metrics:
- Bytes Deleted Metric
- Request Count
- Batch Count
- Bytes Uploaded
- Response Latency

RUM-8448 Benchmarks Additional Metrics

---

DatadogRUM/Sources/Instrumentation/Views/SwiftUI/SwiftUIRUMViewsPredicate.swift

The default SwiftUI view predicate is missing a public initializer, making it unusable for RUM configuration. 
Adding public initializer.

Add public initializer for SwiftUI view predicate

---

DatadogRUM/Sources/Instrumentation/Views/RUMViewsHandler.swift
DatadogRUM/Tests/Instrumentation/Views/RUMViewsHandlerTests.swift
IntegrationTests/Runner/Scenarios/RUM/SwiftUIInstrumentation/SwiftUIRootViewController.swift

The logic to ignore modal presentation automatically seems wrong and prone to issue such as #2209.
Ignoring a view by returning `isUntrackedModal: true` in the predicate is correct but ignoring a view-controller automatically when it has `isModalInPresentation: true` is not.
From Apple documentation:
> The default value of this property is [false](https://developer.apple.com/documentation/swift/false). When you set it to [true](https://developer.apple.com/documentation/swift/true), UIKit ignores events outside the view controller's bounds and prevents the interactive dismissal of the view controller while it is onscreen.
The `isModalInPresentation` is about dismissal interaction, but the view-controller could be in any navigation stack. 
Remove ignoring view-controllers with …

RUM-8847 Remove automatic `RUMUntrackedModal`

---

BenchmarkTests/Benchmarks/Package.swift
CHANGELOG.md
Cartfile
Cartfile.resolved
DatadogTrace.podspec
Package.swift
SmokeTests/cocoapods/Podfile.src

📦 This PR updates `DatadogTrace` to OpenTelemetryApi 1.13.1 where we removed the enforcement of dynamic linking type for SPM. See: https://github.com/DataDog/opentelemetry-swift-packages/pull/28
This change will be shipped as `2.24.1` hotfix.
Bumping OTelApi version.

RUM-9224 Upgrade to OTelApi 1.13.1

---

BenchmarkTests/CatalogUIKit/Base.lproj/ActivityIndicatorViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/AlertControllerViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/ButtonViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/ColorPickerViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/CustomPageControlViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/CustomSearchBarViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/CustomToolbarViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/DatePickerController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/DefaultPageControlViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/DefaultSearchBarViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/DefaultToolbarViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/FontPickerViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/ImagePickerViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/ImageViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/Main.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/MenuButtonViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/PickerViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/PointerInteractionButtonViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/ProgressViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/SegmentedControlViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/SliderViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/StackViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/StepperViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/SwitchViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/SymbolViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/TextFieldViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/TextViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/TintedToolbarViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/VisualEffectViewController.storyboard
BenchmarkTests/CatalogUIKit/Base.lproj/WebViewController.storyboard

Some storyboards in `CatalogUIKit` were still targeting `UIKitCatalog` for classes, they should all use the `customModuleProvider="target"` attribute to look in the current target instead.

fix: Benchmark CatalogUIKit Storyboards

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
tools/release/build-xcframeworks.sh

This PR removes the `-allow-internal-distribution` flag from the XCFramework build script. This flag is likely causing Swift 6 compatibility issues with our pre-built frameworks, specifically with `DatadogCrashReporting`. Customers using Swift 6 are encountering build errors related to ABI compatibility between our frameworks (built with Swift 5.10) and their Swift 6 environment:
> Failed to build module 'DatadogCrashReporting'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)', while this compiler is 'Apple Swift version 6.1 effective-5.10 (swiftlang-6.1.0.110.21 clang-1700.0.13.3)'). Please select a toolchain which matches the SDK.
This flag was originally added to bypass ABI stability checks due to naming …

RUMS-4235 Remove `-allow-internal-distribution` flag to framework build script

---

CHANGELOG.md
DatadogRUM/Sources/Instrumentation/AppHangs/FatalAppHangsHandler.swift
DatadogRUM/Tests/Instrumentation/AppHangs/AppHangsMonitorTests.swift

After reporting the crash-error at launch, the AppHang report is never removed from the persistent DataStore. Meaning that the same error will be reported at each application launch, until the event expires after 18hrs, or until another report overrides it.
Fix #2158
Remove the stored App Hang after report at launch.

RUM-9395 fix: Fatal App Hang Duplicates

---

CHANGELOG.md
Datadog/Example/Debugging/DebugManualTraceInjectionViewController.swift
Datadog/IntegrationUnitTests/Trace/HeadBasedSamplingTests.swift
DatadogInternal/Sources/NetworkInstrumentation/B3/B3HTTPHeadersWriter.swift
DatadogInternal/Sources/NetworkInstrumentation/Datadog/HTTPHeadersWriter.swift
DatadogInternal/Sources/NetworkInstrumentation/W3C/W3CHTTPHeadersWriter.swift
DatadogObjc/Sources/Tracing/Propagation/B3HTTPHeadersWriter+objc.swift
DatadogObjc/Sources/Tracing/Propagation/HTTPHeadersWriter+objc.swift
DatadogObjc/Sources/Tracing/Propagation/W3CHTTPHeadersWriter+objc.swift
DatadogRUM/Sources/RUMConfiguration.swift
DatadogTrace/Sources/TraceConfiguration.swift
DatadogTrace/Tests/DDNoopTracerTests.swift
DatadogTrace/Tests/TraceTests.swift

- Use the `.sampled` context injection by default
- Use 100% tracing sampling rate by default

RUM-7746 Use sampled context injection by default

---

DatadogCore/Sources/Core/Context/LaunchTimePublisher.swift
DatadogCore/Sources/Core/DatadogCore.swift

📦 This PR updates the access-level used when importing the `DatadogPrivate` module in SPM builds.
It addresses [#2267](https://github.com/DataDog/dd-sdk-ios/issues/2267), where using a direct import DatadogPrivate in DatadogCore could lead to the error:
> "Missing required module 'DatadogPrivate'"
This may occur if `DatadogCore` is imported into a custom module within a client application (rather than the app target).
The fix introduces Swift version–aware access-level imports, following [SE-0409](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0409-access-level-on-imports.md). Specifically:
```swift
#if swift(>=6.0)
internal import DatadogPrivate
#else
@_implementationOnly import DatadogPrivate
#endif
```
This ensures that `DatadogPrivate` remains hidden from SDK …

GH-2277 Fix access level for `DatadogPrivate` imports

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/ExampleAppDelegate.swift
DatadogCore/Tests/Datadog/Tracing/TracingURLSessionHandlerTests.swift
DatadogInternal/Sources/NetworkInstrumentation/Datadog/HTTPHeadersWriter.swift
DatadogInternal/Sources/NetworkInstrumentation/DatadogURLSessionHandler.swift
DatadogInternal/Sources/NetworkInstrumentation/NetworkContext.swift
DatadogInternal/Sources/NetworkInstrumentation/NetworkContextProvider.swift
DatadogInternal/Sources/NetworkInstrumentation/NetworkInstrumentationFeature.swift
DatadogInternal/Sources/NetworkInstrumentation/TraceContext.swift
DatadogInternal/Sources/NetworkInstrumentation/W3C/W3CHTTPHeaders.swift
DatadogInternal/Sources/NetworkInstrumentation/W3C/W3CHTTPHeadersWriter.swift
DatadogInternal/Tests/NetworkInstrumentation/HTTPHeadersWriterTests.swift
DatadogInternal/Tests/NetworkInstrumentation/NetworkInstrumentationFeatureTests.swift
DatadogInternal/Tests/NetworkInstrumentation/W3CHTTPHeadersWriterTests.swift
DatadogRUM/Sources/Instrumentation/Resources/URLSessionRUMResourcesHandler.swift
DatadogRUM/Tests/Instrumentation/Resources/URLSessionRUMResourcesHandlerTests.swift
DatadogTrace/Sources/DDFormat.swift
DatadogTrace/Sources/Feature/MessageReceivers.swift
DatadogTrace/Sources/Integrations/TracingURLSessionHandler.swift
DatadogTrace/Tests/DatadogTracer+InjectAndExtract.swift
DatadogTrace/Tests/TracingURLSessionHandlerTests.swift
TestUtilities/Mocks/NetworkInstrumentationMocks.swift

Propagate the RUM Session ID in traced requests headeres (DD & W3C)
We use the `FeatureMessage` to track the current RUM Session ID and use it in the tags in DD and W3C headers.

RUM-8409 Propagate RUM session ID in request headers

---

DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshot.swift

Moved `resolveTextAndInputPrivacyLevel` and `resolveImagePrivacyLevel` methods to an `@_spi(Internal)` extension on `SessionReplayViewAttributes` in order to make these accessible for custom node resolvers provided from outside the sdk.

RUM-9608: Expose methods via @_spi extension on SessionReplayViewAttributes for cross module access

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Tests/DatadogObjc/DDRUMConfigurationTests.swift
DatadogCore/Tests/DatadogObjc/RUM/RUMDataModels+objcTests.swift
DatadogInternal/Sources/Models/RUM/RUMDataModels.swift
DatadogObjc/Sources/RUM/RUMDataModels+objc.swift
DatadogRUM/Sources/RUMConfiguration.swift
DatadogRUM/Sources/RUMContext/RUMContext.swift
DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationMocks.swift
DatadogRUM/Tests/RUMEvent/RUMEventBuilderTests.swift
DatadogRUM/Tests/SDKMetrics/SessionEndedMetricControllerTests.swift
DatadogRUM/Tests/SDKMetrics/SessionEndedMetricTests.swift
IntegrationTests/IntegrationScenarios/UITestsHelpers.swift
IntegrationTests/IntegrationTests.xcodeproj/project.pbxproj
TestUtilities/Sources/Matchers/RUMSessionMatcher.swift
TestUtilities/Sources/Mocks/DatadogInternal/RUMDataModelMocks.swift
TestUtilities/Sources/Mocks/DatadogRUM/RUMFeatureMocks.swift
tools/rum-models-generator/Sources/rum-models-generator/GenerateRUMModels.swift
tools/rum-models-generator/run.py

Models that are shared between modules must be shared in `DatadogInternal`. That is the case with RUM generated models.
This PR changes the generator destination for RUM schema.
- Change generator destination to `DatadogInternal` when generating RUM models.
- Update imports accordingly
- Re-export events used in mappers from RUM module.
- Move/Update mocks accordingly

RUM-9521 Move RUM models to DatadogInternal

---

DatadogInternal/Sources/NetworkInstrumentation/TracePropagationHeadersWriter.swift
DatadogInternal/Tests/NetworkInstrumentation/B3HTTPHeadersWriterTests.swift
DatadogInternal/Tests/NetworkInstrumentation/HTTPHeadersWriterTests.swift
DatadogInternal/Tests/NetworkInstrumentation/W3CHTTPHeadersWriterTests.swift

Uses the session id when available to compute the trace sampling on network traces.

RUM-9022 Session consistent trace sampling

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Tests/Datadog/CrashReporting/CrashReporterTests.swift
DatadogCore/Tests/Datadog/Logs/CrashLogReceiverTests.swift
DatadogCore/Tests/Datadog/RUM/Integrations/CrashReportReceiverTests.swift
DatadogCrashReporting/Sources/Integrations/CrashReportSender.swift
DatadogInternal/Sources/Models/CrashReporting/BinaryImage.swift
DatadogInternal/Sources/Models/CrashReporting/Crash.swift
DatadogInternal/Sources/Models/CrashReporting/DDCrashReport.swift
DatadogInternal/Sources/Models/CrashReporting/DDThread.swift
DatadogInternal/Sources/Models/RUM/RUMPayloadMessages.swift
DatadogLogs/Sources/Feature/MessageReceivers.swift
DatadogRUM/Sources/Integrations/CrashReportReceiver.swift
TestUtilities/Sources/Mocks/CrashReporting/CrashReportingFeatureMocks.swift

Following #2276 
Migrate Crash messages on the message-bus to the new strongly-typed `.payload`
- Create a shared `Crash` type.

RUM-9522 Migrate Crash messages to payload format

---

DatadogCore/Sources/Core/DatadogCore.swift
DatadogCore/Tests/Datadog/DatadogCore/Context/FeatureContextTests.swift
DatadogCrashReporting/Sources/Integrations/CrashReportSender.swift
DatadogInternal/Sources/Context/DatadogContext.swift
DatadogInternal/Sources/DatadogCoreProtocol.swift
DatadogInternal/Sources/MessageBus/FeatureBaggage.swift
DatadogInternal/Sources/Models/CrashReporting/LaunchReport.swift
DatadogInternal/Tests/DatadogCoreProtocolTests.swift
DatadogRUM/Sources/Instrumentation/WatchdogTerminations/WatchdogTerminationMonitor.swift
DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationMonitorTests.swift
TestUtilities/Sources/Mocks/DatadogInternal/FeatureRegistrationCoreMock.swift
TestUtilities/Sources/Mocks/DatadogInternal/FeatureScopeMock.swift
TestUtilities/Sources/Mocks/DatadogInternal/PassthroughCoreMock.swift
TestUtilities/Sources/Proxies/DatadogCoreProxy.swift

`FeatureBaggage` comes with perf implications, we are replacing loosely-typed baggages in core context by strongly-typed additional context.
Similar to `BaggageSharing` (now deprecated), add `AdditionalContextSharing` for sharing additional context from core and feature-scope.

RUM-9747 Add strongly-typed additional context to core

---

Datadog/IntegrationUnitTests/RUM/RUMAttributesIntegrationTests.swift
DatadogRUM/Sources/Instrumentation/Resources/URLSessionRUMResourcesHandler.swift
DatadogRUM/Sources/Instrumentation/Views/RUMViewsHandler.swift
DatadogRUM/Sources/RUMMonitor/Monitor.swift
DatadogRUM/Sources/RUMMonitor/RUMCommand.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMResourceScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMUserActionScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Sources/RUMMonitorProtocol+Internal.swift
DatadogRUM/Tests/Instrumentation/Views/RUMViewsHandlerTests.swift
DatadogRUM/Tests/RUMMonitor/Monitor+GlobalAttributesTests.swift
DatadogRUM/Tests/RUMMonitor/RUMCommandTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMResourceScopeTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMUserActionScopeTests.swift
TestUtilities/Sources/Mocks/DatadogRUM/RUMFeatureMocks.swift

This PR fixes the propagation of global attributes across dependent scopes.
It is part of a broader effort to ensure consistent attribute management across all SDKs (iOS, Android, Browser, etc.).
This is a task to handle the management of `View` attributes discussed in the  [RFC - internal](https://datadoghq.atlassian.net/wiki/x/QoFRGwE).
To ensure correct propagation of global attributes, they are stored in a single location within the environment (e.g. `Monitor`). Each time an event occurs, the global attributes are propagated via `RUMCommands` to create the event. This approach guarantees that global attributes remain separate from local ones, and that the environment is accurately captured at the moment the event occurs.
For example, this solution ensures that each `View` update has …

RUM-9066: Fix global attribute propagation in views

---

DatadogCrashReporting/Sources/Integrations/CrashReportSender.swift
DatadogInternal/Sources/Models/CrashReporting/LaunchReport.swift
DatadogRUM/Sources/Instrumentation/WatchdogTerminations/WatchdogTerminationMonitor.swift
DatadogRUM/Tests/Instrumentation/WatchdogTerminations/WatchdogTerminationMonitorTests.swift

Following: #2289
`FeatureBaggage` comes with perf implications, we are replacing loosely-typed baggages in core context by strongly-typed additional context.
Set `LaunchReport` as additional context instead of feature-baggage.

RUM-9747 Strongly-typed Crash Reporting Additional Context

---

DatadogCore/Tests/Datadog/DatadogCore/MessageBusTests.swift
DatadogInternal/Sources/MessageBus/FeatureMessage.swift
DatadogInternal/Tests/MessageBus/FeatureMessageReceiverTests.swift
DatadogRUM/Tests/Integrations/WebViewEventReceiverTests.swift
DatadogSessionReplay/Tests/Feature/RUMContextReceiverTests.swift
DatadogSessionReplay/Tests/Feature/WebViewRecordReceiverTests.swift
TestUtilities/Sources/Mocks/DatadogInternal/FeatureMessageMocks.swift

Remove `.baggage` message type following migration of:
- #2276
- #2277
- #2278
- #2279

RUM-9522 Remove `.baggage` message type from the bus

---

CHANGELOG.md
DatadogCore/Sources/PerformancePreset.swift
DatadogCore/Tests/Datadog/Core/PerformancePresetTests.swift
DatadogInternal/Sources/DatadogFeature.swift
DatadogInternal/Sources/Storage/PerformancePresetOverride.swift
DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Tests/RUMTests.swift

To reduce data loss, we want to extend the “max age” of uploaded RUM batches to 24h.
Provide Performance Override in RUM to increase the max file age for reading.

RUM-4236 Increase RUM batch ttl

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/AppRunner/AppRunStep+Fixtures.swift
Datadog/IntegrationUnitTests/AppRunner/AppRunner.swift
Datadog/IntegrationUnitTests/RUM/RUMSessionTestsBase.swift
Datadog/IntegrationUnitTests/RUM/RUMSessionTrackingTests.swift
DatadogInternal/Sources/Context/LaunchInfo.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMApplicationScope.swift
DatadogRUM/Sources/RUMMonitor/Scopes/Utils/LaunchReasonResolver.swift
DatadogRUM/Tests/RUMMonitor/Scopes/Utils/LaunchReasonResolverTests.swift

📦 This PR adjusts the timing of the "ApplicationLaunch" view for tvOS apps using `UISceneDelegate`. It ensures that user-initiated launches are correctly detected and that the view start aligns with the actual process start time.
This is a counterpart to https://github.com/DataDog/dd-sdk-ios/pull/2321. Unlike iOS, tvOS does not support the `task_role` API, so we cannot determine the launch reason at SDK init. Instead, we apply a **launch window heuristic** that defers `LaunchReason` resolution until enough information can be inferred from app state and lifecycle events.
The implementation follows the [RFC (internal)](https://datadoghq.atlassian.net/wiki/x/eQHZMAE). It introduces two main components that work together to resolve the launch reason and defer processing of early RUM commands: …

RUM-9997 Adjust "ApplicationLaunch" view for tvOS scene-based apps

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Tests/DatadogObjc/DDRUMMonitorTests.swift
DatadogCore/Tests/DatadogObjc/DDSwiftUIRUMActionsPredicateTests.swift
DatadogCore/Tests/DatadogObjc/DDSwiftUIRUMViewsPredicateTests.swift
DatadogObjc/Sources/RUM/RUM+objc.swift
DatadogObjc/Sources/RUM/SwiftUIRUMPredicate+objc.swift

This PR adds the ObjC APIs for SwiftUI Auto-instrumentation. See previous work in #2315 and #2237.
- Added `swiftUIViewsPredicate` and `swiftUIActionsPredicate` parameters to ObjC RUM configuration
- Created Swift bridges for both

RUM 8421 Add ObjC APIs for SwiftUI Auto-Tracking

---

tools/secrets/config.sh

Adding secrets that are necessary to obtain GitHub installation token that will be used instead of classical PAT. See [this](https://github.com/DataDog/dd-sdk-android/pull/2726) Android PR for details.
I'll actually upload the secrets when the PR is approved. Just in case I made a mistake.

RUM-10225: Add GitHub app secrets to Vault

---

CHANGELOG.md
DatadogAlamofireExtension.podspec
DatadogCore.podspec
DatadogCore/Sources/Versioning.swift
DatadogCrashReporting.podspec
DatadogInternal.podspec
DatadogLogs.podspec
DatadogObjc.podspec
DatadogRUM.podspec
DatadogSessionReplay.podspec
DatadogTrace.podspec
DatadogWebViewTracking.podspec
TestUtilities.podspec

It merges `release/2.29.0` to `develop` and is the counterpart of: 
- #2346

Merge `release/2.29.0` to `develop`

---

DatadogRUM/Sources/Instrumentation/Actions/SwiftUI/LegacySwiftUIComponentDetector.swift
DatadogRUM/Sources/Instrumentation/Actions/SwiftUI/ModernSwiftUIComponentDetector.swift
DatadogRUM/Sources/Instrumentation/Actions/SwiftUI/SwiftUIComponentDetector.swift
DatadogRUM/Sources/Instrumentation/Actions/UIKit/UIEventCommandFactory.swift
DatadogRUM/Tests/Instrumentation/Actions/SwiftUIComponentDetectorTests.swift
IntegrationTests/IntegrationScenarios/Scenarios/RUM/RUMSwiftUIAutoInstrumentationTests.swift

This PR improves SwiftUI automatic action tracking coverage by making the detection logic more generic and comprehensive. Previously, the SDK had limited detection for certain SwiftUI components (mainly `Button`, `NavigationLink`, `Link`) and relied on specific class name checks.
- Extended `bestActionTarget` to search for `UIControl` in the parent hierarchy, not just at the tapped view level
- Removed the special `SwiftUI_Toggle` detection logic (now tracked as `UISwitch`)
The generic parent hierarchy search now covers more SwiftUI and UIKit components naturally.

RUM-9988 Expand Action Tracking to other UI components

---

DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIHostingViewRecorder.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotBuilder.swift
DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIHostingViewRecorderTests.swift

The location of the `renderer` instance has changed in iOS 26. Session Replay depends on the `renderer` to record SwiftUI snapshots. This _partially fixes_ some issues found when capturing snapshots in iOS 26.
Instead of adding another subclass, I refactored the renderer extraction to take a key path as an input. This key path is based on the available iOS version:
- For iOS >= 26, `_base.viewGraph.renderer`
- For iOS >= 18.1, `_base.renderer`
- For iOS < 18.1, `renderer`

Refactor renderer extraction in `UIHostingViewRecorder` and add support for iOS 26

---

.github/chainguard/self.carthage.sts.yaml

Add policy for [dd-ocot-sts (internal)](https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/5138645099/User+guide+dd-octo-sts) to generate an token and increase rate limit when using `carthage`.
This policy must be present on the main branch before updating the CI configuration.
The OIDC trust policy:
- allow both `branch` and `tag` pipelines to get a GitHub tokens
- ensure only our official `.gitlab-ci.yml` can request tokens
- allow reading metadata only as we only need a low permission token

RUM-10225 Create carthage sts policy

---

.github/chainguard/self.release.sts.yaml

Add policy for [dd-ocot-sts (internal)](https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/5138645099/User+guide+dd-octo-sts) to generate an fined-grained, short-lived GH token to publish artefacts to GH release..
This policy must be present on the main branch before updating the CI configuration.
The OIDC trust policy:
- allow `tag` pipelines to get a GitHub tokens
- ensure only our official `.gitlab-ci.yml` can request tokens
- allow writing to contents to enable uploading to GH release.

RUM-10225 Create release sts policy

---

CHANGELOG.md
DatadogObjc/Sources/Logs/LogsDataModels+objc.swift
api-surface-objc

Account info property was missing in the ObjC API for Logs, this PR fixes that.

RUM-10486: Add `accountInfo` property to `DDLogEvent`

---

DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/Color+Reflection.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/Color.swift
DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/SwiftUI/DisplayList+Reflection.swift

iOS 26 introduces some structural changes in the `DisplayList` type we rely on for SwiftUI Session Replay:
- `ViewInfo.view` and `ViewInfo.container` can either be a `UIView` or a `CALayer` (the same as the `ViewInfo.layer` in this case)
- The payload for the `DisplayList.Content.Value.color` case is a `ColorView` instead of a `SwiftUI.Color._Resolved`.
We need to address these differences to improve SwiftUI Session Replay on iOS 26.
- Make the `ViewInfo.view` property reflection optional, falling back to a `CALayer` for `ViewInfo.container`
- Add an internal `ColorView` type with a `color` property, matching the structure for the payload on iOS 26.

RUM-10492: Refactor `DisplayList.ViewInfo` and `DisplayList.Content.Value` for iOS 26 support

---

.gitlab-ci.yml
Makefile
tools/clean.sh
tools/repo-setup/carthage-bootstrap.sh
tools/repo-setup/repo-setup.sh

Optimize build by caching the dependencies. This will reduce call to `carthage bootstrap`. The goal is also to reduce call to `dd-octo-sts` for requesting GH token.
~~Use [Gitlab CI Cache](https://docs.gitlab.com/ci/caching/#cache) for caching Carthage dependencies across jobs.~~
Use [Gitlab CI Artifacts](https://docs.gitlab.com/ci/jobs/job_artifacts/) for caching Carthage dependencies across jobs.

RUM-10225 Set gitlab cache for carthage dependencies

---

DatadogCore/Sources/Datadog.swift

📦 Restores the deprecated `setUserInfo()` API, which was removed in https://github.com/DataDog/dd-sdk-ios/pull/2361 without providing an alternative. This brings it back temporarily until a new API is introduced as part of `RUM-9263`.
Reintroduces the previously deprecated `setUserInfo()` method to avoid breaking changes, pending the implementation of the new replacement API.

chore: Restore `setUserInfo()` deprecation

---

.gitlab-ci.yml
tools/carthage-shim.sh
tools/env-check.sh

Remove use of Github PAT for running `carthage`.
Use `dd-octo-sts` to acquire a fine-grained, short-lived access-token

RUM-10225 Use dd-octo-sts for carthage bootstrap

---

tools/dogfooding/dogfood.sh

Remove use of Github PAT for dogfooding Mobile App.
Use `dd-octo-sts` to acquire a fine-grained, short-lived access-token.

RUM-10225 Use dd-octo-sts for Mobile App PR 

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/Public/NetworkInstrumentationIntegrationTests.swift
DatadogCore/Tests/Datadog/Tracing/TracingURLSessionHandlerTests.swift
DatadogInternal/Sources/Utils/DeterministicSampler.swift
DatadogInternal/Sources/Utils/Sampler.swift
DatadogInternal/Tests/Utils/DeterministicSamplerTests.swift
DatadogTrace/Sources/DatadogTracer.swift
DatadogTrace/Sources/Integrations/TracingURLSessionHandler.swift
DatadogTrace/Sources/Trace.swift
DatadogTrace/Tests/TraceTests.swift
DatadogTrace/Tests/TracingURLSessionHandlerTests.swift

This PR ensures that trace sampling is deterministic based on the `session.id` when the RUM feature is enabled.
This guarantees a consistent sampling decision for each session, which is important for features like RUM that rely on [head-based instrumentation](https://github.com/DataDog/dd-sdk-ios/blob/053b4d6b978ae9dba658b8e44a9212d36d1f5a7b/DatadogRUM/Sources/Instrumentation/Resources/URLSessionRUMResourcesHandler.swift#L168-L193) strategies.
A `DeterministicSampler` is introduced in the `TracingURLSessionHandler` to make trace sampling consistent per `session.id`. The `session.id` is extracted from the `RUMContext`, which implies that the RUM feature is enabled.
If RUM is not active, the sampling falls back to using the `traceID`.

RUM-10190: Sample traces according to `session.id`

---

DatadogRUM/Sources/Feature/RUMFeature.swift
DatadogRUM/Sources/RUMConfiguration.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMScopeDependencies.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMUserActionScopeTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift
TestUtilities/Sources/Mocks/DatadogRUM/RUMFeatureMocks.swift

Allow overriding the session type for demoing in synthetic environment.
Support a `DD_SESSION_TYPE` environment to override the session type in RUM

Allow session type override

---

DatadogRUM/Sources/RUMConfiguration.swift

As suggested in [this comment](https://github.com/DataDog/dd-sdk-ios/pull/2237#discussion_r2176723264), documentation about SwiftUI view tracking is misleading.
Updating comment.

[SwiftUI instru] Fix misleading doc comment

---

.github/workflows/stale.yml

This PR adds a GitHub Actions workflow to **automatically manage stale issues** that are waiting for responses. The goal is to keep the issue tracker clean by automatically closing issues with the `awaiting-response` label that have been inactive for 17 days (14 days to mark as stale with a message + 3 days to close). This helps maintain repository hygiene and ensures issues don't remain open indefinitely when waiting for user responses.
- Added `.github/workflows/stale.yml` using the [Stale Github Action](https://github.com/actions/stale)
- Targets only issues with the `awaiting-response` label
- Adds `stale` label when marking issues as stale and `automatically-closed` label when closing
- Automatically removes stale label when issues are updated
As a first step, the workflow:
- can …

RUM-8727 Automatically close stale issues

---

.github/workflows/stale.yml

This PR updates the stale issues workflow introduced in #2392 to enable production use. The workflow will now automatically mark issues with the `awaiting response` label as stale after 14 days of inactivity and close them 3 days later if there is no further activity.
- Set `debug-only: false` to allow the workflow to perform real actions (label, comment, close issues)
- Added the daily cron schedule to run the workflow automatically at 8:00 AM CET
- Corrected the targeted label from `awaiting-response` to `awaiting response` (the label was temporarily changed in the GitHub UI for testing and has since been reverted)

RUM-8727 Switch Stale Github Action to prod config

---

DatadogCore/Tests/Objc/DDRUMMonitorTests.swift
DatadogCore/Tests/Objc/ObjcAPITests/DDRUMMonitor+apiTests.m
DatadogRUM/Sources/RUM+objc.swift

The Objective-C RUM interface was missing support for the experimental API to report view loading times.
This PR adds the missing interface to ensure it is publicly available in both Swift and Objective-C.
It adds the following method to `DDRUMMonitor`:
```swift
public func addViewLoadingTime(overwrite: Bool)
```
This enables Objective-C calls to record view loading times.

RUM-1151: Update objc interface with RUM `addViewLoadingTime`

---

DatadogCrashReporting/Sources/PLCrashReporterIntegration/PLCrashReporterIntegration.swift
DatadogRUM/Sources/Instrumentation/AppHangs/AppHangsMonitor.swift

We are seeing telemetry errors implying that `PLCrashReporter` [fails to decode the protobuf encoded stacktrace](https://github.com/microsoft/plcrashreporter/blob/master/Source/PLCrashReport.m#L333) while generating App Hang backtraces.
App Hang is based on `PLCrashReporter`'s 'Live Report' to collect backtraces, Live Report feature will write a report on-disk like during a crash using protobuf serialization and then read the file to decode it. We are reaching the decoding point of failure, meaning that data was corrupted.
While we are not able to reproduce this issue, we have identified a thread-safety issue: Our Crash Context is [injected in the Live Report](https://github.com/microsoft/plcrashreporter/blob/master/Source/PLCrashReporter.m#L751-L754) for encoding but the `customData` …

RUM-10438 Improve backtrace collection and error messages

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/SessionReplay/WebRecordIntegrationTests.swift
DatadogInternal/Sources/Models/RUM/RUMCoreContext.swift
DatadogInternal/Sources/Models/RUM/RUMWebViewContext.swift
DatadogRUM/Sources/Integrations/WebViewEventReceiver.swift
DatadogSessionReplay/Sources/Feature/WebViewRecordReceiver.swift
DatadogSessionReplay/Tests/Feature/WebViewRecordReceiverTests.swift
TestUtilities/Sources/Mocks/DatadogRUM/RUMFeatureMocks.swift

This PR fixes a timing discrepancy that occurs between web-view RUM events and Session Replay records when NTP synchronization updates the server time offset after a web-view RUM view is created.
- `WebViewEventReceiver` caches `context.serverTimeOffset` when the first web-view event arrives
- `WebViewRecordReceiver` uses `rumContext.viewServerTimeOffset` which is frozen at native RUM view creation time
- If an NTP sync occurs between these two timing points, the receivers would apply different offsets to events from the same web-view, creating timing gaps between RUM events and Session Replay records
Both receivers now use the same cached offset per web-view ID, ensuring consistent timestamps across RUM events and Session Replay records for the same web-view.
- `WebViewEventReceiver` …

RUM-10572: Fix timestamp discrepancies in web-view session replay recordings

---

Datadog/IntegrationUnitTests/RUM/ViewLoadingMetricsTests.swift
DatadogRUM/Sources/RUMMetrics/TNSMetric.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMResourceScope.swift
DatadogRUM/Tests/RUMMetrics/TNSMetricTests.swift
TestUtilities/Sources/Mocks/DatadogRUM/RUMFeatureMocks.swift

The TNS (Time to Network Settled) measurement can be inaccurate when the instrumentation also captures `URLSessionTaskMetrics`. This is particularly common in hybrid mobile applications.
- TNS is primarily computed using the network call metrics wrapped in the `ResourceMetrics`, especially the `fetch` phase’s start and end timestamps.
- Additionally, TNS is still computed even if the view experienced an inactive app state during loading.
This state, where the app is in the foreground but not receiving user input (e.g., during an incoming phone call, Notification Center pulled down, etc.), should not delay or invalidate the completion of the view’s initial network calls.

RUM-10501: Improve TNS calculation

---

.github/chainguard/self.release.sts.yaml

Fix STS policy to publish the `xcframework` in GH release asset.

Fix release sts policy

---

DatadogCore/Tests/Datadog/TracerTests.swift
DatadogTrace/Sources/Span/SpanEventEncoder.swift

This PR fixes an issue with the ingestion of custom spans.
Previously, the `device` and `os` information was published without the correct schema alignment, which prevented these spans from being ingested properly.
The `device` and `os` fields are now prefixed with the `meta` namespace to comply with the expected span schema.

RUM-9494: Fix the propagation of `device` and `os` on spans

---

DatadogRUM/Sources/Instrumentation/Actions/SwiftUI/ModernSwiftUIComponentDetector.swift
DatadogRUM/Sources/Instrumentation/Actions/SwiftUI/SwiftUIComponentDetector.swift
DatadogRUM/Tests/Instrumentation/Actions/SwiftUIComponentDetectorTests.swift
IntegrationTests/IntegrationScenarios/Scenarios/RUM/RUMSwiftUIAutoInstrumentationTests.swift

We were mistakenly using `visionOS 18.0` instead of `visionOS 2.0` in availability checks.
Replace `visionOS 18.0` with `visionOS 2.0`

Fix visionOS availability checks

---

E2ETests/Runner/Scenarios/SessionReplayWebView/SessionReplayWebViewScenario.swift

It fixes a compilation error related with the `SessionReplay.Configuration` that is preventing the `e2e test upload` to run.
It updates the `SessionReplay.Configuration` by using the latest interface.

RUM-9495: Fix e2e test upload

---

.gitlab-ci.yml
.spi.yml
Makefile
tools/doc-build.sh

📦 This PR fixes [SPI documentation](https://swiftpackageindex.com/DataDog/dd-sdk-ios/develop/documentation) build failures by correcting target names in `.spi.yml` and adds a CI job to ensure ongoing compatibility with SPI doc builds.
Updates `.spi.yml` target names and introduces a script that runs SPI’s exact `xcodebuild docbuild` commands for each target, integrated into CI `lint` phase to catch regressions early.

chore: Fix SPI docs build and add CI check for SPI compatibility

---

.github/workflows/issue_notification.yml

Workflow failed with the following error: `Error: OPENAI_SYSTEM_PROMPT environment variable must be set`.
Switch from an environment `secret` to a `variable`.

Change prompt from secrets to vars

---

.github/workflows/stale.yml

Pinning action hash version for Stale Github Action

[Stale workflow] Pin action hash for action version

---

CHANGELOG.md
DatadogLogs/Sources/LogsDataModels+objc.swift
api-surface-objc
api-surface-swift

`LogEvent.accountInfo` property is nullable, so making `DDLogEvent.accountInfo` nullable as well.

Fix `DDLogEvent.accountInfo` initialization

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogCore/Sources/Core/Storage/Writing/AsyncWriter.swift
DatadogCore/Sources/Core/Storage/Writing/FileWriter.swift
DatadogCore/Tests/Datadog/Core/Persistence/Writing/FileWriterTests.swift
DatadogCore/Tests/Datadog/Mocks/RUM/RUMFeatureMocks.swift
DatadogCore/Tests/Objc/DDRUMMonitorTests.swift
DatadogCore/Tests/Objc/ObjcAPITests/DDRUMMonitor+apiTests.m
DatadogInternal/Sources/Concurrency/CompletionHandler.swift
DatadogInternal/Sources/Storage/Writer.swift
DatadogRUM/Sources/RUM+objc.swift
DatadogRUM/Sources/RUMMonitor/Monitor.swift
DatadogRUM/Sources/RUMMonitor/RUMCommand.swift
DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift
DatadogRUM/Sources/RUMMonitorProtocol+Internal.swift
DatadogRUM/Sources/RUMMonitorProtocol.swift
DatadogRUM/Tests/RUMMonitor/RUMCommandTests.swift
DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift
TestUtilities/Sources/Mocks/DatadogInternal/FeatureScopeMock.swift
TestUtilities/Sources/Mocks/DatadogInternal/FileWriterMock.swift
TestUtilities/Sources/Mocks/DatadogRUM/RUMFeatureMocks.swift
TestUtilities/Sources/Proxies/DatadogCoreProxy.swift

Cross-platform SDKs can report fatal errors before the native process crashes. However, RUM and the Core execute processing and write asynchronously, and the crash can suspend these executions, leading to the loss of the cross-platform error information.
We should let cross-platform SDKs to report error in sync, blocking the caller-thread.
The change involve changes at different layers:
Add `completion` argument to `Writer` interface. The completion callback is called when the data is written to disk.
Add `completionHandler` property to `RUMErrorCommand`. The `RUMViewScope` calls the completion handler after writing the error event and the view update.
The RUM Monitor now expose a method to report an error with a completion handler, The method is exposed using the `@_spi(Internal)` …

RUM-5176 [CP] Allow reporting RUM error in sync

---

DatadogLogs/Sources/ConsoleLogger.swift
DatadogLogs/Sources/LoggerProtocol+Internal.swift
DatadogLogs/Sources/LoggerProtocol.swift
DatadogLogs/Sources/Logs+objc.swift
DatadogLogs/Sources/RemoteLogger.swift
DatadogLogs/Tests/ConsoleLoggerTests.swift
DatadogLogs/Tests/LoggerTests.swift
DatadogLogs/Tests/RemoteLoggerTests.swift

Logs counter-part of #2180
Cross-platform SDKs can report fatal errors before the native process crashes. However, Logs execute processing and write asynchronously, and the crash can suspend these executions, leading to the loss of the cross-platform error information.
We should let cross-platform SDKs to report error in sync, blocking the caller-thread.
The change involve changes at different layers:
Add method to `InternalLoggerProtocol` for logging a critical entry with a `completionHandler`. The `RemoteLogger` and `ConsoleLogger` call the completion handler after writing the log.
```swift
/// Internal Logger for Cross-Platform access.
public protocol InternalLoggerProtocol {
/// Logs a critical entry then call completion.
///
/// This method is meant for non-native or cross platform …
```

RUM-5176 [CP] Allow reporting critical log in sync

---

DatadogSessionReplay/Sources/SessionReplay+objc.swift
DatadogSessionReplay/Tests/DDSessionReplayTests.swift
api-surface-objc
api-surface-swift

This PR removes the unused `objc_SessionReplayConfigurationPrivacyLevel`. 
It was the Objective-C counterpart of `SessionReplayPrivacyLevel`, which is used for fine-grained masking conversions between the Browser SDK and the `DatadogWebViewTracking`. Since only one structure is required for this purpose, the Objective-C version is no longer needed.

chore: Remove unused `objc_SessionReplayConfigurationPrivacyLevel`

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogProfiling/Mach/dd_pprof.cpp
DatadogProfiling/Mach/include/dd_pprof.h
DatadogProfiling/Mach/include/mach_profiler.h
DatadogProfiling/Mach/include/module.modulemap
DatadogProfiling/Mach/include/profile.h
DatadogProfiling/Mach/include/profile_pprof_packer.h
DatadogProfiling/Mach/mach_sampling_profiler.cpp
DatadogProfiling/Mach/profile.cpp
DatadogProfiling/Mach/profile_pprof_packer.cpp
DatadogProfiling/Sources/DatadogProfiling.swift
DatadogProfiling/Sources/MachProfiler.swift
DatadogProfiling/Sources/Profiler.swift
DatadogProfiling/Tests/MachProfilerTests.swift
DatadogProfiling/Tests/MachSamplingProfilerTests.swift
DatadogProfiling/Tests/MockProfiler.swift
DatadogProfiling/Tests/MockThread.swift
DatadogProfiling/Tests/ProfileCxxTests.swift
DatadogProfiling/Tests/ProfileMocks.swift
Makefile
tools/protoc-pprof.sh

This PR implements pprof data aggregation and serialization for Profiling. It adds the engine to collect, deduplicate, and serialize profiling samples into the standard pprof protobuf format, enabling ingestion from Profiling intake.
- Adds `profile` C++ class for sample aggregation with deduplication of strings, mappings, and locations
- Implements `profile_pprof_packer` to convert internal data structures to protobuf format
- Creates C API wrapper (`dd_pprof`) for Swift integration
- Updates `MachProfiler` to use the new aggregation system and generate pprof data
Uses Cxx interoperability feature introduced in Swift 5.9 for testing aggregation and serialization.

RUM-11048 Profile aggregation and serialization

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogFlags/Sources/FlagsClient.swift
DatadogFlags/Sources/Models/AnyValue.swift
DatadogFlags/Sources/Models/FlagAssignment.swift
DatadogFlags/Sources/Models/FlagDetails.swift
DatadogFlags/Tests/Feature/ExposureLoggerTests.swift
DatadogFlags/Tests/Feature/FlagsClientMocks.swift
DatadogFlags/Tests/FlagsClientTests.swift
DatadogFlags/Tests/Models/AnyValueTests.swift

This PR adds `getDetails` methods to the `FlagsClient` that return detailed flag evaluation information including variant, reason, and error details.
This allows users to access comprehensive flag metadata alongside the evaluated values, which is essential for debugging and advanced feature flag workflows.
The implementation adds:
- A new `FlagDetails<T>` model that wraps flag values with metadata
- Error handling via `FlagEvaluationError`, with `flagNotFound` and `typeMismatch` cases
- `getDetails<T>` method that evaluates flags and returns comprehensive details
- Maintains existing exposure logging behavior
- Comprehensive test coverage for the new methods and error scenarios

FFL-1065: Add `getDetails` methods

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogFlags/Sources/Feature/ExposureLogger.swift
DatadogFlags/Sources/Feature/ExposureRequestBuilder.swift
DatadogFlags/Sources/Feature/FlagsFeature.swift
DatadogFlags/Sources/FlagsClient.swift
DatadogFlags/Sources/FlagsStore.swift
DatadogFlags/Sources/FlagsTypes.swift
DatadogFlags/Sources/Models/AnyValue.swift
DatadogFlags/Sources/Models/ExposureEvent.swift
DatadogFlags/Sources/Models/FlagAssignment.swift
DatadogFlags/Sources/Models/FlagAssignmentsResponse.swift
DatadogFlags/Sources/Models/FlagDetails.swift
DatadogFlags/Sources/Models/FlagValue.swift
DatadogFlags/Tests/Feature/ExposureLoggerTests.swift
DatadogFlags/Tests/Feature/ExposureMocks.swift
DatadogFlags/Tests/Feature/ExposureRequestBuilderTests.swift
DatadogFlags/Tests/Feature/FlagsClientMocks.swift
DatadogFlags/Tests/FlagsClientTests.swift
DatadogFlags/Tests/FlagsTypesTests.swift
DatadogFlags/Tests/Models/AnyValueTests.swift
DatadogFlags/Tests/Resources/precomputed-v1.json

This PR implements the infrastructure for sending exposure events when feature flags are accessed. When users evaluate feature flags through the `FlagsClient`, exposure events are now automatically logged and sent to the corresponding intake endpoint for analytics and monitoring purposes.
This PR implements exposure event logging for the `DatadogFlags` module. When users evaluate feature flags through the `FlagsClient`, exposure events are now automatically logged and sent to the corresponding intake endpoint for analytics and monitoring.
The PR also includes several foundational improvements to support type-safe flag handling and performance optimizations.
- `ExposureEvent` model: Complete event structure with allocation, flag, variant, and subject information following the schema used …

FFL-1022: Send feature flag exposure events to intake

---

Datadog/Datadog.xcodeproj/project.pbxproj
DatadogFlags/Sources/Client/FlagsClient.swift
DatadogFlags/Sources/Client/FlagsClientProtocol.swift
DatadogFlags/Sources/Client/FlagsClientRegistry.swift
DatadogFlags/Sources/Feature/FlagsFeature.swift
DatadogFlags/Sources/Models/FlagDetails.swift
DatadogFlags/Tests/Client/FlagsClientTests.swift
DatadogFlags/Tests/Client/NOPFlagsClientTests.swift

This PR implements support for named `FlagsClient` instances, enabling SDK users to create and manage multiple independent feature flag clients with isolated data storage. This work continues the implementation started in #2489.
Core Implementation:
- Introduced `FlagsClientProtocol` to define the public interface for flag evaluation and define a consistent contract between `FlagsClient` and `NOPFlagsClient`
- Added `FlagsClient.create(name:with:in:)` to create new named client instances
- Added `FlagsClient.instance(named:in:)` to retrieve existing named clients from the registry
- Implemented `FlagsClientRegistry` to manage multiple client instances with thread-safe registration and retrieval
API Design:
- Default client name is `"default"` when no name is specified
- Creating a …

FFL-1016: Add support for multiple named clients

---

DatadogFlags/Sources/Client/FlagAssignmentsRequest.swift
DatadogFlags/Sources/Models/ExposureEvent.swift
DatadogFlags/Sources/Models/FlagsEvaluationContext.swift
DatadogFlags/Tests/Client/FlagAssignmentsRequestTests.swift
DatadogFlags/Tests/Client/RUMExposureLoggerTests.swift

This PR migrates the `FlagsEvaluationContext.attributes` property from `[String: String]` to `[String: AnyValue]` to support rich, typed attribute values in feature flag evaluation contexts.
Depends on #2502
The implementation changes the attributes type across the evaluation context pipeline:
- Core Model Changes:
- Updated `FlagsEvaluationContext.attributes` from `[String: String]` to `[String: AnyValue]`
- Updated `ExposureEvent.Subject.attributes` to use `AnyValue`
- Updated `FlagAssignmentsRequestBody.Subject.targetingAttributes` to use `AnyValue`
- Cross-Module Integration:
- Kept `RUMFlagExposureMessage.subjectAttributes` as `[String: any Encodable]` to avoid moving `AnyValue` to `DatadogInternal`

FFL-1144: Migrate `FlagsEvaluationContext` attributes to `AnyValue`

---

DatadogCore/Tests/Objc/DDRUMMonitorTests.swift
DatadogCore/Tests/Objc/ObjcAPITests/DDRUMMonitor+apiTests.m
DatadogRUM/Sources/RUM+objc.swift
api-surface-objc

This PR surfaces, to the Objective-C runtime, the new APIs to add View attributes.
It updates the `objc_RUMMonitor` class with the new interfaces:
```swift
public func addViewAttribute(forKey key: String, value: Any)
public func addViewAttributes(_ attributes: [String: Any])
public func removeViewAttribute(forKey key: String)
public func removeViewAttributes(forKeys keys: [String])
```

 chore: Surface view attributes' APIs to Objective-C

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/IntegrationUnitTests/Flags/FlagsRUMIntegrationTests.swift
DatadogCore/Sources/SDKMetrics/BatchMetrics.swift
DatadogInternal/Sources/Models/RUM/RUMPayloadMessages.swift
DatadogRUM/Sources/Integrations/FlagExposureReceiver.swift

This PR adds integration tests that verify the end-to-end communication between the `DatadogFlags` and `DatadogRUM` modules. These tests ensure that flag evaluations correctly trigger RUM events and that all metadata flows through the integration layer properly.
Created `Datadog/IntegrationUnitTests/Flags/FlagsRUMIntegrationTests.swift` with two test cases:
1. `testWhenFlagIsEvaluated_itAddsFeatureFlagToRUMView()`
- Verifies flag evaluations appear in `RUMViewEvent.featureFlags`
- Validates `RUMFlagEvaluationMessage` → `FlagEvaluationReceiver` integration
2. `testWhenFlagIsEvaluated_itCreatesRUMActionWithExposureDetails()`
- Verifies custom `__dd_exposure` RUM actions are created
- Validates `RUMFlagExposureMessage` → `FlagExposureReceiver` integration

FFL-1162: Flags / RUM integration tests

---

tools/issue_handler/src/analyze_issue.py
tools/issue_handler/src/openai_handler.py
tools/issue_handler/src/slack_handler.py
tools/issue_handler/tests/test_openai_handler.py

This PR updates the automation that post Slack notifications when a new Github issue is opened. 
- Edited response format; it now includes more fields: `problem`, `scope`, `category`, `confidence_level`, `next_steps`, `clarifying_questions`
- Added new environment variables so we can update these values directly in Github UI, without creating a new PR (`OPENAI_MAX_RESPONSE_TOKENS`, `OPENAI_MODEL`, `OPENAI_TEMPERATURE`, `OPENAI_MAX_RESPONSE_TOKENS`)
- Added some helper functions and constants to format the Slack message

Improve prompt and message

---

DatadogFlags/Sources/Client/FlagsClient.swift
DatadogFlags/Sources/Feature/FlagsFeature.swift
DatadogFlags/Tests/Client/FlagsClientTests.swift

This PR refactors the exposure logging dependency injection to improve testability and code quality:
- Removes test helper methods (`isUsingNOPExposureLogger`, `isUsingNOPRUMLogger`) in `FlagsClient`
- Replaces direct logger creation with factory pattern in `FlagsFeature`
- Implements proper behavioral tests that verify actual events/messages instead of implementation details

FFL-1161: Replace test helpers with behavioral tests
