Sources/Datadog/Logger.swift
Sources/Datadog/Logs/Log/LogBuilder.swift
Sources/Datadog/Logs/Log/LogEncoder.swift
Sources/DatadogObjc/Logger+objc.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogMocks.swift
Tests/DatadogTests/DatadogObjc/DDLoggerBuilderTests.swift
Tests/DatadogTests/Helpers/TestsDirectory.swift
instrumented-tests/Integration/IntegrationTests/LoggingIntegrationTests.swift

🚚 This PR adds `sendNetworkInfo(_ enabled: Bool)` to the `Logger.Builder`. Before, the network info was always associated with logs. Now it's `false` by default.
* New method was added to `Logger.Builder` public API - both Swift and Objective-C.
* I added additional set of unit tests for different `Logger` states - note, that I moved some existing tests from Swift API to Objective-C surface for wider coverage.
* Integration tests were updated.

RUMM-265 Network info can be added optionally

---

Datadog.podspec
DatadogObjc.podspec
Sources/Datadog/Datadog.swift

📦 This PR updates Cocoapod podspecs to target pre-release `1.0.0-beta1` tag.
The `1.0.0-beta1` tag will be created on `master` after this is merged.

RUMM-287 Mark 1.0.0-beta1 release

---

tools/xcode-templates/install-xcode-templates.sh

This PR fixes the error occurring during `make all` with fresh-installed Xcode
```
make all
...
Installing Xcode templates...
./tools/xcode-templates/install-xcode-templates.sh
cp: /Applications/Xcode.app/{...redacted...}/Datadog: Permission denied
```
Installation directory for Xcode templates are changed
• from: `/Applications/Xcode/...`
• to: `$HOME/Library/Xcode/...`
This fixes permission issues
Also, templates stay even Xcode gets updated

RUMM-305 Make command fails at fresh install

---

Sources/Datadog/Core/Upload/DataUploadWorker.swift
Sources/Datadog/Logger.swift
Sources/Datadog/Utils/InternalLoggers.swift
Tests/DatadogTests/Datadog/Core/Persistence/FileWriterTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogMocks.swift
Tests/DatadogTests/Datadog/Mocks/FoundationMocks.swift

📦 This fixes #47 
`Logger` tags and attributes were not thread safe, so when mutated parallelly by different threads, the SDK was resulting with a crash on `loggerTags` and `loggerAttributes` access.
I added basic thread safety using logger-specific `DispatchQueue` with `.sync {}` (writes) and `.async {}` (reads) synchronization.
Following this great [post from Matt Gallagher](http://www.cocoawithlove.com/blog/2016/06/02/threads-and-mutexes.html) this might be not the most performant way of synchronization, but I checked benchmark results and they are still acceptable:

RUMM-290 Make `Logger` tags and attributes thread safe

---

.gitignore
Cartfile
Cartfile.resolved
Datadog.podspec
Datadog/Datadog.xcodeproj/project.pbxproj
Makefile
Package.resolved
Package.swift
Sources/Datadog/DDTracer.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/Traces/DDNoOps.swift
Sources/Datadog/Traces/DDSpan.swift
Sources/Datadog/Traces/DDSpanContext.swift
Sources/Datadog/Traces/SpanOutputs/SpanFileOutput.swift
Sources/Datadog/Traces/SpanOutputs/SpanOutput.swift
Sources/Datadog/Traces/Utils/UUID.swift
Tests/DatadogTests/Datadog/DDTracerTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogMocks.swift
Tests/DatadogTests/Datadog/Mocks/DatadogTracingMocks.swift
Tests/DatadogTests/Datadog/Mocks/LogsMocks.swift
Tests/DatadogTests/Datadog/Mocks/SpansMocks.swift
Tests/DatadogTests/Datadog/Traces/DDSpanTests.swift
Tests/DatadogTests/Datadog/Traces/Utils.swift
Tests/DatadogTests/Datadog/Utils/InternalLoggersTests.swift
Tests/DatadogTests/DatadogObjc/DDLoggerBuilderTests.swift
dependency-manager-tests/carthage/Makefile
examples/iOS-app-example-cocoapods/Podfile

📦 This PR introduces a foundation for implementing OT Tracer for Datadog.
Following [Open Tracing Specification](https://github.com/opentracing/specification/blob/master/specification.md), it addresses following behaviours:
* `Tracer`: Start a new `Span`;
* `Span`: Overwrite the operation name;
* `Span`: Finish the `Span`;
* `NoopTracer` no-op implementation of `OpenTracing.Tracer`.
1/ Carthage support was added to [our fork](https://github.com/DataDog/opentracing-swift) of [`opentracing-swift`](https://github.com/opentracing/opentracing-swift).
2/ `OpenTracing.framework` was linked to both `Datadog` and `DatadogTests`.
3/ `DDTracer`, `DDSpan` and few other OT types were implemented.
When implementing `DDTracer`, I followed similar architecture to what we use for `Logger`, so:
* …

RUMM-293 Create OT Tracer foundation

---

Makefile
bitrise.yml

🚚 This PR updates CI configuration to read our workflows from repository. This enables version control for CI setup and allows modeling branch-specific pipelines.
Following [this article from Bitrise](https://devcenter.bitrise.io/tips-and-tricks/use-bitrise-yml-from-repository/), CI was configured to execute `bitrise run push_to_any_branch` in repository. This launches set of workflows defined in `bitrise.yml`.
It's also possible to test workflows locally, by installing [Bitrise CLI](https://devcenter.bitrise.io/bitrise-cli/index/):
```bash
$ bitrise run <workflow-id>
```

RUMM-283 Use `bitrise.yml` from repository

---

docs/log_collection.md

Fixes layout of doc for the public doc: https://github.com/DataDog/documentation/pull/7044

Fixing layout for import in public doc

---

Makefile
bitrise.yml
dependency-manager-tests/cocoapods/.gitignore
dependency-manager-tests/cocoapods/CPProject.xcodeproj/project.pbxproj
dependency-manager-tests/cocoapods/CPProject.xcodeproj/project.xcworkspace/contents.xcworkspacedata
dependency-manager-tests/cocoapods/CPProject.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
dependency-manager-tests/cocoapods/CPProject.xcodeproj/xcshareddata/xcschemes/CPProject.xcscheme
dependency-manager-tests/cocoapods/CPProject.xcworkspace/contents.xcworkspacedata
dependency-manager-tests/cocoapods/CPProject.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
dependency-manager-tests/cocoapods/CPProject/AppDelegate.swift
dependency-manager-tests/cocoapods/CPProject/Base.lproj/LaunchScreen.storyboard
dependency-manager-tests/cocoapods/CPProject/Base.lproj/Main.storyboard
dependency-manager-tests/cocoapods/CPProject/Info.plist
dependency-manager-tests/cocoapods/CPProject/SceneDelegate.swift
dependency-manager-tests/cocoapods/CPProject/ViewController.swift
dependency-manager-tests/cocoapods/CPProjectUITests/CPProjectUITests.swift
dependency-manager-tests/cocoapods/CPProjectUITests/Info.plist
dependency-manager-tests/cocoapods/Makefile
dependency-manager-tests/cocoapods/Podfile.src
dependency-manager-tests/spm/Makefile

📦 This PR adds Cocoa Pods installation test.
`make test-cocoapods` sources `Podfile.src` by injecting current git branch name, then `pod update` is called. After this, Bitrise runs UITests for this `CPProject.xcworkspace`.
I also update `SPMProject` to run UITests from `bitrise.yml` instead of `xcodebuild` in `Makefile`. This has few benefits:
- cleaner build log on Bitrise thanks to `xcpretty`;
- `SPMProject-ui-test` artifact is exported on Bitrise;
- build-related logic is centralized in single place (`bitrise.yml`).

RUMM-346 Add Cocoa Pods dependency manager test

---

Datadog.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Datadog/DatadogPrivate/module.modulemap
Datadog/DatadogPrivate/module.private.modulemap
DatadogSDK.podspec

DDPrivate module is created to use ObjC from Swift
It is not intended for public use
We used private.modulemap to hide it from public

RUMM-346 DatadogPrivate module is hidden from public

---

.gitignore
Datadog.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/DatadogPrivate/ObjcExceptionHandler.h
Datadog/DatadogPrivate/ObjcExceptionHandler.m
Datadog/DatadogPrivate/include/SPMHeaders.h
Datadog/DatadogPrivate/module.modulemap
Datadog/DatadogPrivate/module.private.modulemap
DatadogSDK.podspec
Package.swift
Sources/Datadog/Core/Persistence/FileWriter.swift
Sources/Datadog/Core/Persistence/Files/File.swift
Sources/Datadog/Logs/LogOutputs/LogConsoleOutput.swift
Sources/Datadog/Utils/Globals.swift
Tests/DatadogTests/Datadog/Core/Persistence/FileReaderTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/FileWriterTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Files/FileTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/FilesOrchestratorTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogPrivateMocks.swift
Tests/DatadogTests/DatadogPrivate/ObjcExceptionHandlerTests.swift
instrumented-tests/Benchmark/Benchmark.xcodeproj/project.pbxproj

🚚 This PR provides a fix for crash reported in #58 where [`NSFileHandleOperationException`](https://developer.apple.com/documentation/foundation/nsfilehandleoperationexception?language=objc) was thrown on devices with high memory and disk pressure when writing the log to file.
The exception was thrown when calling `write(_ data:)` method on `FileHandle`. This was expected behaviour [described by Apple](https://developer.apple.com/documentation/foundation/filehandle/1410936-write):
> This method raises an exception if (...) no free space is left on the file system, or if any other writing error occurs.
Unfortunately Apple doesn't provide `throwable` variant of `fileHandle.write(_:)` so we have to catch this error from Objective-C code (until [better API is provided in iPhone …

RUMM-346 Fix "device out of memory" crash

---

Cartfile.resolved
Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/DDTracer.swift
Sources/Datadog/Traces/DDSpan.swift
Sources/Datadog/Traces/Propagation/HTTPHeadersWriter.swift
Sources/Datadog/Traces/Utils/Casting.swift
Sources/Datadog/Traces/Utils/Warnings.swift
Tests/DatadogTests/Datadog/DDTracerTests.swift
Tests/DatadogTests/Datadog/Mocks/SpansMocks.swift
Tests/DatadogTests/Datadog/Traces/Utils/UUID.swift
Tests/DatadogTests/Datadog/Traces/Utils/WarningsTests.swift

📦 This PR implements _"Inject a `SpanContext` into a carrier"_ part of [OT specification](https://github.com/opentracing/specification/blob/master/specification.md#inject-a-spancontext-into-a-carrier).
This means enabling users to pass trace information within HTTP headers to a backend that supports Datadog instrumentation for OT.
This is what users will need to do in order to propagate trace information:
```swift
import OpenTracing
import Datadog
let request: URLRequest = ...
// ...
let traceHeaders = DDHTTPHeadersWriter()
Global.sharedTracer.inject(spanContext: span, writer: traceHeaders)
request.allHTTPHeaderFields += traceHeaders.tracePropagationHTTPHeaders
// ...
send(request)
```
After this, the HTTP request will be set with those two additional headers:
```
"x-datadog-trace-id": …
```

RUMM-294 Implement "Inject a `SpanContext` into a carrier" part of OT interface

---

Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogMocks.swift
Tests/DatadogTests/Datadog/Utils/InternalLoggersTests.swift
Tests/DatadogTests/DatadogObjc/DDLoggerBuilderTests.swift

⚙️ This PR cherry-picks "no-op" mocks for `Datadog` that were created on `tracing` branch. This is to avoid conflicts between `master` and `tracing` when development continuous on both branches.
I just cherry-pick a commit from `tracing` that modifies mocks available also on `master`.
We need explicit "no-op" mock on `tracing` branch to disable logging feature entirely in unit tests for tracing.
I will rebase `tracing` branch onto `master` after this is merged.

RUMM-292 Cherry pick explitic no-op `Datadog` mocks from `tracing` branch

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/DDTracer.swift
Sources/Datadog/Traces/DDSpan.swift
Tests/DatadogTests/Datadog/DDTracerTests.swift
Tests/DatadogTests/Datadog/Mocks/SpansMocks.swift
Tests/DatadogTests/Datadog/Traces/DDSpanTests.swift
Tests/DatadogTests/Datadog/Traces/Utils/Casting.swift

📦 This PR allows adding tags to a `Span`, so _"Set a `Span` tag"_ part of [OT spec](https://github.com/opentracing/specification/blob/master/specification.md#set-a-span-tag).
According to OT spec, tags can be associated with `Span` in two ways:
* when starting the span with `Tracer`:
```swift
let span = tracer.startSpan(
operationName: "operation", 
tags: ["tag1": "value1"]
)
```
* when span already exists:
```swift
span.setTag(key: "key1", value: "value1")
```
💡 In this PR I don't implement any thread-safety for `span.tags` dictionary, as this will come later in `RUMM-340`. The reason for this is that I'm not sure about the impact of span serialization on the threading model for `DDTracer` and `DDSpan`. A lot of things might change when implementing span writer, so instead of doing …

RUMM-296 Implement "Set a `Span` tag" part of OT interface

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Upload/DataUploader.swift
Sources/Datadog/DDTracer.swift
Sources/Datadog/Logs/Log/LogBuilder.swift
Sources/Datadog/Tracing/DDNoOps.swift
Sources/Datadog/Tracing/DDSpan.swift
Sources/Datadog/Tracing/DDSpanContext.swift
Sources/Datadog/Tracing/Span/SpanBuilder.swift
Sources/Datadog/Tracing/Span/SpanEncoder.swift
Sources/Datadog/Tracing/SpanOutputs/SpanFileOutput.swift
Sources/Datadog/Tracing/SpanOutputs/SpanOutput.swift
Sources/Datadog/Tracing/Utils/UUID.swift
Sources/Datadog/Utils/SwiftExtensions.swift
Tests/DatadogTests/Datadog/DDTracerTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogTracingMocks.swift
Tests/DatadogTests/Datadog/Mocks/SpansMocks.swift
Tests/DatadogTests/Datadog/Tracing/Span/SpanBuilderTests.swift
Tests/DatadogTests/Datadog/Tracing/SpanOutputs/SpanFileOutputTests.swift
Tests/DatadogTests/Datadog/Tracing/Utils/Casting.swift
Tests/DatadogTests/Datadog/Tracing/Utils/UUIDTests.swift
Tests/DatadogTests/Datadog/Utils/SwiftExtensionsTests.swift
Tests/DatadogTests/Matchers/JSONDataMatcher.swift
Tests/DatadogTests/Matchers/LogMatcher.swift
Tests/DatadogTests/Matchers/SpanMatcher.swift

🚚 This PR enables writing OT spans to files. Later, those files will be uploaded to Datadog backend 🚀.
The Tracing architecture for spans serialization follows the one already done for Logging.
`Log` serialization:
* `LogFileOutput` bundles `LogBuilder` and `FileWriter`;
* `LogBuilder` creates the `Log: Encodable` object;
* `FileWriter` writes the `Log` to underlying file.
`Span` serialization:
* `SpanFileOutput` bundles `SpanBuilder` and `FileWriter`;
* `SpanBuilder` creates the `Span: Encodable` object;
* `FileWriter` writes the `Span` to underlying file.
Both `Log` and `Span` implement custom serialization in `LogEncoder` and `SpanEncoder`. Serialized span looks like this:
```json
{
"trace_id": "1D",
"span_id": "1",
"parent_id": "13E",
"name": "operation",
"duration": 500000000, …
```

RUMM-298 Write spans to file

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Persistence/FileWriter.swift
Sources/Datadog/Core/Utils/ISO8601DateFormatter.swift
Sources/Datadog/Core/Utils/JSONEncoder.swift
Sources/Datadog/Logs/LogOutputs/LogConsoleOutput.swift
Sources/Datadog/Utils/InternalLoggers.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Logs/LogOutputs/LogConsoleOutputTests.swift
Tests/DatadogTests/Datadog/Utils/EncodingTests.swift
Tests/DatadogTests/Datadog/Utils/InternalLoggersTests.swift
Tests/DatadogTests/DatadogObjc/DDLoggerTests.swift
Tests/DatadogTests/Matchers/LogMatcher.swift

Closes #95 
SDK collects `Log`s and writes them onto disk, then uploads them as raw data
It relies on `JSONEncoder` with `dateEncodingStrategy = .iso8601`
However, it turns out `IS08601` doesn't enforce miliseconds and `JSONEncoder` omits them
```swift
let date = {2020-05-04T18:19:57.109Z}
jsonEncoder.dateEncodingStrategy = .iso8601
jsonEncoder.encode(date) // becomes {2020-05-04T18:19:57Z}
```
The result is very well described in the original issue #95
There are 2 main solutions:
🍎 Apple recommends using `ISO8601DateFormatter` when dealing with `ISO8601` format.
❌ However, that enforces us to use `dateEncodingStrategy = .custom`
Because the logical strategy option, `.formatted(DateFormatter)`, doesn't accept it as it's not a subclass of `DateFormatter`
Although this is not the official …

RUMM-437 Encoding doesn't ignore miliseconds anymore

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogIntegrationTests.xcscheme
Datadog/Example/AppConfig.swift
Datadog/Example/AppDelegate.swift
Datadog/Example/Base.lproj/Main.storyboard
Datadog/Example/IntegrationTestFixtures/SendLogsFixtureViewController.swift
Datadog/Example/IntegrationTestFixtures/SendTracesFixtureViewController.swift
Tests/DatadogIntegrationTests/LoggingIntegrationTests.swift
Tests/DatadogIntegrationTests/TracingIntegrationTests.swift
Tests/DatadogIntegrationTests/UITestsHelpers.swift
Tests/DatadogTests/Helpers/TestsDirectory.swift
Tests/DatadogTests/Matchers/SpanMatcher.swift
instrumented-tests/http-server-mock/Sources/HTTPServerMock/ServerMock.swift
instrumented-tests/http-server-mock/Sources/HTTPServerMock/ServerSession.swift
instrumented-tests/http-server-mock/python/start_mock_server.py

🧪 This PR adds integration test for the Tracing feature.
It leverages the setup introduced in #97.
`SendTracesFixtureViewController` was added to the `Example` app. The UI tests runner in `TracingIntegrationTests` launches the app and navigates to _"Send traces for UI Tests"_ screen:
In that view controller, `viewDidLoad()`, `viewWillAppear()` and `viewDidAppear()` methods are instrumented to generate trace information:
Trace data is send to the `HTTPServerMock` and asserted in `TracingIntegrationTests `.
Same thing was also done to Logging feature integration test - log fixtures were moved to view controller in `Example` app and only asserted in `LoggingIntegrationTests`.
This of course requires passing the mock server url from the `DatadogIntegrationTests` target to `Example` app. This …

RUMM-299 Add Tracing integration tests

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/AppDelegate.swift
Shopist/Shopist/AppDelegate.swift
Sources/Datadog/DDTracer.swift
Sources/Datadog/DDTracerConfiguration.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/Logger.swift
Tests/DatadogIntegrationTests/TracingIntegrationTests.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploaderTests.swift
Tests/DatadogTests/Datadog/DDTracerConfigurationTests.swift
Tests/DatadogTests/Datadog/DDTracerTests.swift
Tests/DatadogTests/Datadog/Tracing/TracingFeatureTests.swift

📦 This PR adds the `public` way of initializing the `DDTracer`
Following API was introduced:
```swift
let tracer = DDTracer.initialize(
configuration: DDTracer.Configuration(
serviceName: "app-tracer"
)
)
```
As default `serviceName` will soon (`RUMM-409`) come from `Datadog.Configuration`, the defaults resolution was decoupled to a separate `internal` type:
```swift
ResolvedConfiguration(tracerConfiguration: Configuration)
```
After default service name is provided by `Datadog.Configuration`, it will become:
```swift
ResolvedConfiguration(
tracerConfiguration: Configuration, 
defaultConfiguration: datadog.instance.configuration
)
```

RUMM-332 Add public initializer for `DDTracer`

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/IntegrationTestFixtures/SendLogsFixtureViewController.swift
Datadog/Example/IntegrationTestFixtures/SendTracesFixtureViewController.swift
Sources/Datadog/Core/Utils/EncodableValue.swift
Sources/Datadog/Tracing/Span/SpanBuilder.swift
Sources/Datadog/Tracing/Span/SpanEncoder.swift
Tests/DatadogIntegrationTests/LoggingIntegrationTests.swift
Tests/DatadogIntegrationTests/TracingIntegrationTests.swift
Tests/DatadogTests/Datadog/Core/Utils/EncodableValueTests.swift
Tests/DatadogTests/Datadog/DDTracerTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Matchers/JSONDataMatcher.swift
Tests/DatadogTests/Matchers/SpanMatcher.swift

🚚 This PR adds support to `Span` tags. Tags can be specified when starting the span:
```swift
let span = tracer.startSpan(..., tags: ["foo": "bar"], ...)
```
or anytime on the `Span` object:
```swift
span.setTag(key: "number", value: 10)
```
Tag consist of a `String` key and value which can be any `Codable` type - `String`, `Int`, `URL`, custom `Codable` structure etc.
APM API enforces that all tags are encoded as `span.meta.*` JSON attributes **with `String` values**. This means that whatever `Codable` we get from the user, we must translate it into `String`.
This `Codable` → `String` translation happens in `JSONStringEncodableValue`. It turns `Codable` values into their JSON string representation. Given this:
```swift
span.setTag(key: "string", value: "abc")
span.setTag(key: "number", …
```

RUMM-403 Add tags to span

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/DDTracer.swift
Sources/Datadog/Logger.swift
Sources/Datadog/Tracing/DDSpan.swift
Sources/Datadog/Tracing/Span/SpanBuilder.swift
Sources/Datadog/Tracing/UUIDs/TracingUUIDGenerator.swift
Sources/Datadog/Tracing/Utils/Warnings.swift
Tests/DatadogTests/Datadog/DDTracerTests.swift
Tests/DatadogTests/Datadog/Mocks/FoundationMocks.swift
Tests/DatadogTests/Datadog/Tracing/UUIDs/TracingUUIDGeneratorTests.swift

📮 This PR adds additional thread-safety to `public` APIs exposed by Tracing feature.
I added unit test to randomly and call various public APIs from concurrent threads. Later, fixed all the crashes and Thread Sanitizer issues by using synchronization queue inside `DDTracer`.
This is a counterpart to thread safety done in logging feature, where the `Logger` owns a `DispatchQueue` used to synchronize its public interface.

RUMM-340 Add thread safety to Tracing API

---

Sources/Datadog/Core/Upload/DataUploader.swift
Tests/DatadogIntegrationTests/Integration/LoggingIntegrationTests.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploaderTests.swift

🚚 To unify the "source" concept across different Datadog products, we want to change `ddsource` value from `mobile` to `ios`.
From now, all data send with iOS SDK will be tagged `source=ios` at [app.datadoghq.com](https://app.datadoghq.com/). A corresponding change [was already applied to `dd-sdk-android`](https://github.com/DataDog/dd-sdk-android/pull/239).
In Logging feature, `source` is send through HTTP query parameter. I just updated the value and corresponding tests.

RUMM-408 Change `ddsource` to `ios` for logs

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/System/NetworkConnectionInfoProvider.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/Logs/Attributes/UserInfo.swift
Sources/Datadog/Tracing/Utils/MethodSwizzler.swift
Sources/Datadog/Tracing/Utils/URLSessionSwizzler.swift
Tests/DatadogTests/Datadog/Tracing/Utils/MethodSwizzlerTests.swift
Tests/DatadogTests/Datadog/Tracing/Utils/URLSessionSwizzlerTests.swift
Tests/DatadogTests/Matchers/LogMatcher.swift
tools/lint/sources.swiftlint.yml
tools/lint/tests.swiftlint.yml

We needed to change the behavior of `URLSession` instances so that our users will be able to trace network calls automatically.
We considered 3 different solutions, this is the 3rd one.
A custom `URLProtocol` allows us to detect new network requests, change them and detect when the operation is finished.
However, `URLProtocol` isn't designed to be an observer; it needs to do the actual work by starting the operation. If our custom protocol claims responsibility for a given request, we can't use default protocols (such as `HTTPURLProtocol`) anymore.
https://github.com/DataDog/dd-sdk-ios/pull/91
```swift
let tracedSession = URLSession.traced(session)
```
`URLSession.traced(:)` takes an actual `URLSession` instance, wraps it into a proxy type (eg: `DDURLSessionProxy`) and `unsafeBitcast` it …

RUMM-300 Method swizzling

---

Sources/Datadog/Core/Upload/DataUploader.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/Tracing/Span/SpanEncoder.swift
Tests/DatadogIntegrationTests/LoggingIntegrationTests.swift
Tests/DatadogIntegrationTests/TracingIntegrationTests.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploaderTests.swift
Tests/DatadogTests/Datadog/DDTracerTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogMocks.swift

📦 This is #111's counterpart for Tracing feature. We change `ddsource` span attribute's value from `mobile` to `ios`.
The difference between Logging and Tracing in context of `ddsource` is that:
* for logs, the `ddsource` is sent as HTTP query `?ddsource=ios`,
* for spans, the `ddsource` is encoded as `meta._dd.source` json attribute.
This PR makes the upload URL query items customizable and provides different items for each feature. It also centralizes the `ddsource` value declaration to `Datadog.Constants.ddsource`.

RUMM-408 Change `ddsource` to `ios` for traces

---

Sources/Datadog/Datadog.swift
Sources/Datadog/Tracing/Propagation/HTTPHeadersWriter.swift

📦 This PR brings necessary changes to start dogfooding Tracing product.
First, it updates the `sdkVersion` so we can differentiate data in Dashboard.
Second, it adds missing public initializer to `DDHTTPHeadersWriter`.

RUMM-442 Tracing dogfooding

---

Datadog/Example/Base.lproj/Main.storyboard
Shopist/Shopist/Resources/Main.storyboard

🏄‍♂️ This PR upgrades our toolset to Xcode 11.5.
In our code - I only upgraded `toolsVersion` in IB files, but on Bitrise, I updated the default stack to use Xcode 11.5. 
I also wanted to declare the stack in the `bitrise.yml` stored in repo, but this [seems to be not possible](https://discuss.bitrise.io/t/trigger-workflow-with-different-stack/10014). I asked Bitrise Support if they plan to handle this (**update:** they said it's not possible and no time-fixed plans to support this).
I made sure both `tracing` and `master` branch are green with the new stack:
~~- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)~~

RUMM-474 Upgrade to Xcode 11.5

---

bitrise.yml
tools/license/check-license.sh

⚙️ The `run_linter` CI job was not failing when license header was not found.
The `exit 1` was not properly evaluated in `check-license.sh` script. I made the bash script more straightforward by removing the `while` loop nested with pipe operator `|`.
~~- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)~~

RUMM-341 Fix linter not failing on missing license header

---

Datadog/Example/AppDelegate.swift
Sources/Datadog/DDTracer.swift
Sources/Datadog/DDTracerConfiguration.swift
Sources/Datadog/Tracing/Span/SpanBuilder.swift
Tests/DatadogTests/Datadog/DDTracerConfigurationTests.swift
Tests/DatadogTests/Datadog/DDTracerTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift

📦 Same as for `Logger`, the network information attached to `Span` and `Span` logs is now disabled by default for `DDTracer`.
The `sendNetworkInfo` option is added to `DDTracer.Configuration`:
```swift
DDTracer.Configuration(
serviceName: ...,
sendNetworkInfo: true
)
```

RUMM-422 Disable network info by default in tracing

---

Datadog/Example/Base.lproj/Main.storyboard
Datadog/Example/Debugging/DebugTracingViewController.swift
Datadog/Example/IntegrationTestFixtures/SendTracesFixtureViewController.swift
Sources/Datadog/Tracing/Span/SpanBuilder.swift
Sources/Datadog/Tracing/Span/SpanTagsReducer.swift
Tests/DatadogIntegrationTests/TracingIntegrationTests.swift
Tests/DatadogTests/Datadog/DDTracerTests.swift
Tests/DatadogTests/Datadog/Tracing/Span/SpanBuilderTests.swift

📦 This PR adds support to custom `resource.name` tag for `Span`. Doing this, results with a proper value being rendered in the **RESOURCE** column on [app.datadoghq.com](https://app.datadoghq.com):
```swift
span.setTag(key: "resource.name", value: "GET /api/users/123-456")
```
The `resource.name` tag is another example of information received from the user, which requires special encoding (different than `span.meta.*` used for custom tags). To handle `resource.name`, another reducer was added to `SpanTagsReducer` introduced in #120.
Right now, the `resource.name` tag has zero discovery for the user, but this will change in `RUMM-390` where we will think of exposing supported span tags and log fields as `public`.
In addition to unit and integration tests, I also added a new text field to …

RUMM-400 Add support to custom `resource.name` span tag

---

DatadogSDK.podspec
DatadogSDKObjc.podspec
Sources/Datadog/Core/Utils/ISO8601DateFormatter.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/Logs/LogOutputs/LogConsoleOutput.swift
Tests/DatadogTests/Matchers/LogMatcher.swift

🔥 Fixes #126 
The `.withFractionalSeconds` used for `ISO8601DateFormatter` results with a crash on `iOS 11.0` and `11.1`. This is [a known bug](https://openradar.appspot.com/35660658), fixed by Apple in `iOS 11.2`.
Reproduced by running unit tests on `iOS11.1` - it was crashing.
This hotfix drops the millisecond precision on `iOS 11.0-.11.1`, falling back to the behaviour from before `1.2.0`. We will bring the milliseconds support for `iOS 11.0-.11.1` back in `RUMM-494`, within a next release.
With the precision dropped, some time-format related tests fail on `11.1`. Because we don't yet run tests on earlier iOS versions, this doesn't block the workflow. Those tests will be fulfilled in `RUMM-494`, where the precision is added again for `iOS 11.1`.
~- [] Feature or bugfix MUST have …

RUMM-494 Hotfix for crash on iOS 11.0 - 11.1

---

DatadogSDK.podspec
DatadogSDKObjc.podspec
Sources/Datadog/Core/Persistence/FileWriter.swift
Sources/Datadog/Datadog.swift
Tests/DatadogTests/Datadog/Core/Persistence/FileWriterTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogPrivateMocks.swift

🐛  Some payloads send from SDK were malformed.
The reason was not performing writes atomically:
```swift
// pseudo-code
let separatorData = ",".utf8Data
try writer.write(separatorData)
try writer.write(logData)
```
In rare cases, when the `I/O` exception was thrown for the second write, it was leaving the file's content malformed.
The fix is to perform atomic writes:
```swift
// pseudo-code
let logWithSeparatorData = ",".utf8Data + logData
try writer.write(logWithSeparatorData)
```
The red unit test for payload malformation was added, then it was made green with a fix.
The `File` interface is not resistant for this sort of bugs, as it doesn't perform transactional write even if it looks like:
```swift
// FileTests.swift
try file.append { write in
try write(Data([0x42, 0x42, 0x42, 0x42, …
```

RUMM-506 Prevent malforming payload due to I/O exception 

---

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog.xcscheme
Sources/Datadog/DDTracer.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/Logger.swift
Sources/Datadog/Tracing/DDSpan.swift
Sources/Datadog/Tracing/TracingFeature.swift
Sources/Datadog/Utils/InternalLoggers.swift
Tests/DatadogTests/Datadog/DDTracerConfigurationTests.swift
Tests/DatadogTests/Datadog/DDTracerTests.swift
Tests/DatadogTests/Datadog/DatadogConfigurationTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/LoggerBuilderTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogMocks.swift
Tests/DatadogTests/Datadog/Mocks/DatadogTracingMocks.swift
Tests/DatadogTests/Datadog/Mocks/SpansMocks.swift
Tests/DatadogTests/Datadog/Mocks/TracingFeatureMocks.swift
Tests/DatadogTests/Datadog/Tracing/Span/SpanBuilderTests.swift
Tests/DatadogTests/Datadog/Utils/InternalLoggersTests.swift

📦 This PR adds two public methods to toggle logging and tracing features:
```swift
/// Enables or disables the logging feature.
///
/// This option is meant to opt-out from using Datadog Logging entirely, no matter of your environment or build configuration. If you need to
/// disable logging only for certain scenarios (e.g. in `DEBUG` build configuration), use `sendLogsToDatadog(false)` available
/// on `Logger.Builder`.
///
/// If `enableLogging(false)` is set, the SDK won't instantiate underlying resources required for
/// running the logging feature. This will give you additional performance optimization if you only use tracing, but not logging.
///
/// **NOTE**: If you use logging for tracing (`span.log(fields:)`) keep the logging feature enabled. Otherwise the logs
/// you send for …
```

RUMM-468 Add public api to enable / disable features

---

Sources/Datadog/Tracing/UUIDs/TracingUUIDGenerator.swift
Tests/DatadogTests/Datadog/Tracing/UUIDs/TracingUUIDGeneratorTests.swift

📦 This PR adds boundaries to the generated `trace_id` and `span_id` so it stays compatible with Datadog infrastructure.
Following the [dd-trace-java/DDId.java](https://github.com/DataDog/dd-trace-java/blob/master/dd-trace-api/src/main/java/datadog/trace/api/DDId.java) implementation, the boundaries are:
* the `id` should be higher or equal `1`,
* the `id` should be less or equal `2 ^ 63 - 1`.

RUMM-333 Set boundaries for trace and span ID generation

---

Sources/Datadog/Logger.swift
Tests/DatadogTests/Datadog/LoggerTests.swift

🚚 This PR addresses #127 and #142 where compiler ambiguity is reported in projects defining their own `Logger` class.
A public `DDLogger` typealias is exposed and can be used in projects which define their own `Logger` class.

RUMM-501 Add `DDLogger` typealias to avoid compiler ambiguity

---

docs/trace_collection.md

📦 This PR fixes issues I spotted when previewing the `trace_collection.md` on the website.
* The "support team" link was broken:
* The Cocoapods installation snippet was not listing necessary `opentracing-swift` dependency.
* Network requests instrumentation part was missing the `span.finish()` mention.

RUMM-500 Fix `trace_collection.md`

---

Sources/Datadog/Logging/Log/LogEncoder.swift
Tests/DatadogIntegrationTests/LoggingIntegrationTests.swift
Tests/DatadogIntegrationTests/TracingIntegrationTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/DatadogObjc/DDLoggerTests.swift

📦 With this PR and its counterpart DataDog/dd-sdk-android#288, we're changing log levels send from mobile SDKs to be lowercased strings.
Internal change to `LogEncoder` and appropriate tests.

RUMM-492 Encode log levels as lowercase strings

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog.xcscheme
Sources/Datadog/Core/Utils/EncodableValue.swift
Tests/DatadogIntegrationTests/TracingIntegrationTests.swift
Tests/DatadogTests/Datadog/Core/Utils/EncodableValueTests.swift
Tests/DatadogTests/Datadog/Core/Utils/JSONEncoderTests.swift
Tests/DatadogTests/Helpers/DatadogExtensions.swift
Tests/DatadogTests/Helpers/Encoding.swift

📦 Prior to `iOS13.0` the SDK was unable to send traces, as `Span` serialization was always failing. This PR fixes the behaviour on `iOS11` and `iOS12`.
As discussed in https://bugs.swift.org/browse/SR-6163, the `JSONEncoder` doesn't support primitive types encoding. This was fixed in `iOS13`.
We need primitive types encoding to make following part of Open Tracing interface compatible with Intake requirement: _"all tags must be send as `String` values"_.
```swift
func setTag(key: String, value: Codable)
```
As we can't fix `JSONEncoder`, a workaround was added - the tag `value` is encoded as array and two surrounding bytes are removed from encoded `Data`. This is the fastest and most performant workaround that I found.
This PR is part of `RUMM-486`, so I made all production-code unit tests …

RUMM-486 Fix span encoding error on iOS versions prior to 13.0

---

DatadogSDK.podspec
DatadogSDKObjc.podspec
Sources/Datadog/Datadog.swift

📦 This PR bumps the SDK version to `1.3.0-beta1` so we can release tracing `-beta1`.
I bumped both `sdkVersion` and `.podspecs`, although `.podspecs` won't be pushed to `pod trunk` until it's official `1.3.0`. Also, I'm going to create a `pre-release` tag.

RMM-500 Bump sdk version to `1.3.0-beta1`

---

docs/trace_collection.md

📦 Until our contribution in  https://github.com/opentracing/opentracing-swift/pull/11 is considered OR we go with another `.podspec` for our [OT fork](https://github.com/DataDog/opentracing-swift), the classic `pod DatadogSDK` installation will not work. We need a workaround.
The workaround is to reference `OpenTracingSwift` and `DatadogSDK` using `git` + `tag` syntax in `Podfile`.
@DataDog/documentation - it's purely technical update, nothing to review 🙂.

RUMM-500 Fix pod installation snippet

---

Sources/Datadog/Core/Persistence/Files/File.swift

📦 The new `FileHandle` throwing API crashes on `iOS 13.0`, `13.1`, `13.2` and `13.3`.
Even though the [documentation says](https://developer.apple.com/documentation/foundation/filehandle/3516319-seektoend) some of the new `FileHandle` throwing APIs should be available since `iOS 13.0`, they are crashing on versions prior to `13.4`, e.g.:
```
Symbol not found: _$sSo12NSFileHandleC10FoundationE9seekToEnds6UInt64VyKF
Symbol not found: _$sSo12NSFileHandleC10FoundationE9readToEndAC4DataVSgyKF
```
In this PR, I roll back to using the old APIs on versions prior to `13.4`.
I filled a bug report to Apple. 
Radar: https://openradar.appspot.com/radar?id=4998297672482816

RUMM-486 Fix `FileHandle` crash on iOS 13.0-13.3

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/IntegrationTestFixtures/SendTracesFixtureViewController.swift
Sources/Datadog/DDTracer.swift
Sources/Datadog/Tracing/DDSpan.swift
Sources/Datadog/Tracing/DDSpanContext.swift
Sources/Datadog/Tracing/Span/SpanBuilder.swift
Tests/DatadogIntegrationTests/TracingIntegrationTests.swift
Tests/DatadogTests/Datadog/DDTracerTests.swift
Tests/DatadogTests/Datadog/Mocks/TracingFeatureMocks.swift
Tests/DatadogTests/Datadog/Tracing/DDSpanContextTests.swift
Tests/DatadogTests/Datadog/Tracing/DDSpanTests.swift

📦 This PR adds implementation to following Open Tracing interfaces:
```swift
// OpenTracing
public protocol Span {
func setBaggageItem(key: String, value: String)
func baggageItem(withKey key: String) -> String?
}
public protocol SpanContext {
func forEachBaggageItem(callback: (_ key: String, _ value: String) -> Bool)
}
```
The baggage item can be set on `span`:
```swift
span.setBaggageItem(key: "foo", value: "bar")
```
and will be propagated to all it's descendants spans, so given this:
```swift
let childSpan = tracer.startSpan(operationName: ..., childOf: span.context)
let grandchildSpan = tracer.startSpan(operationName: ..., childOf: childSpan.context)
```
both, `childSpan` and `grandchildSpan` will contain the `"foo" : "bar"` baggage item.
Internally, baggage items are encoded as …

RUMM-297 Implement Baggage Item interface

---

tools/all-platform-tests/bitrise-test-all-platforms.yml

📦 This PR adds CI configuration to run tests on as many iOS versions as possible. Right now the trigger is fully manual, and a branch must be scheduled to run with `trigger_all_platform_tests` on Bitrise:
The automation is a distinct thing and will come with a next PR.
I created a separate `bitrise-test-all-platforms.yml` CI configuration, which runs tests on all key `device` + `iOS version` configurations for [given Bitrise stack](https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xcode-11.5.x.log).
Unfortunatelly, Bitrise comes with a limitation - we can only use devices and runtimes provided by the stack. This means, for [osx-xcode-11.5.x.log](https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xcode-11.5.x.log) we can only automate:
```
iOS …
```

RUMM-486 Run CI tests on all supported iOS versions

---

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog.xcscheme
Sources/Datadog/Core/AutoInstrumentation/MethodSwizzler.swift
Sources/Datadog/Core/AutoInstrumentation/URLSessionSwizzler.swift
Tests/DatadogTests/Datadog/Core/AutoInstrumentation/MethodSwizzlerTests.swift
Tests/DatadogTests/Datadog/Core/AutoInstrumentation/URLSessionSwizzlerTests.swift

We swizzle `dataTaskWithURL` and `dataTaskWithRequest` as part of auto-instrumentation. 
iOS 11/12 calls `dataTaskWithRequest` FROM `dataTaskWithURL`, that leads to duplicate execution of our swizzled implementation.
This case was not handled ❌ 
This PR contains 
1. the fix for the problem
2. also some minor refactoring based on https://github.com/DataDog/dd-sdk-ios/pull/139
We didn't need any change in `dataTaskWithRequest` implementation.
Now, in `dataTaskWithURL`, after creating the `task` object we check if `task.originalRequest` has interception headers.
If it has then that means **the task is already intercepted and we should not intercept it once again.**
```swift
/// dataTaskWithURL
let task = currentTypedImp(impSelf, Self.selector, impURL, modifiedCompletion)
if var request = …
```

RUMM-541 Fix: URLSessionSwizzler in iOS11/12

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/AppConfig.swift
Datadog/Example/IntegrationTestFixtures/SendTracesFixtureViewController.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/Tracer.swift
Sources/Datadog/Tracing/Propagation/HTTPHeadersWriter.swift
Sources/Datadog/Tracing/Span/SpanTagsReducer.swift
Sources/Datadog/Tracing/TracingAutoInstrumentation.swift
Tests/DatadogIntegrationTests/TracingIntegrationTests.swift
Tests/DatadogIntegrationTests/UITestsHelpers.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/Tracing/TracingAutoInstrumentationTests.swift

We need to trace every network request automatically as part of auto-instrumentation feature.
[First](https://github.com/DataDog/dd-sdk-ios/pull/113) and [second](https://github.com/DataDog/dd-sdk-ios/pull/116) parts are already implemented.
This is the last part of tracing auto-instrumentation.
With previous PRs we implemented a way to inject our custom code into `URLSession` methods.
Now we inject the code to:
1. create&inject tracing headers to network requests
2. create span context at network task creation `dataTaskWithURL/Request`
3. create span at starting network operation `task.resume`

RUMM-489 TracingRequestInterceptor added

---

Datadog/Datadog.xcodeproj/xcshareddata/xcbaselines/61441C6724619FE4003D8BB8.xcbaseline/7C373BCE-2B91-4706-AD99-F9FD342891D3.plist
Datadog/Datadog.xcodeproj/xcshareddata/xcbaselines/61441C6724619FE4003D8BB8.xcbaseline/Info.plist
Sources/Datadog/FeaturesIntegration/LoggingForTracingAdapter.swift
Sources/Datadog/Logger.swift
Sources/Datadog/Logging/Log/LogBuilder.swift
Sources/Datadog/Logging/Log/LogEncoder.swift
Sources/Datadog/Logging/Log/LogSanitizer.swift
Sources/Datadog/Logging/LogOutputs/LogConsoleOutput.swift
Sources/Datadog/Logging/LogOutputs/LogFileOutput.swift
Sources/Datadog/Logging/LogOutputs/LogOutput.swift
Sources/Datadog/Logging/LogOutputs/LogUtilityOutputs.swift
Tests/DatadogBenchmarkTests/LoggingStorageBenchmarkTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/LoggingForTracingAdapterTests.swift
Tests/DatadogTests/Datadog/Logging/Log/LogBuilderTests.swift
Tests/DatadogTests/Datadog/Logging/Log/LogSanitizerTests.swift
Tests/DatadogTests/Datadog/Logging/LogOutputs/LogConsoleOutputTests.swift
Tests/DatadogTests/Datadog/Logging/LogOutputs/LogFileOutputTests.swift
Tests/DatadogTests/Datadog/Logging/LogOutputs/LogUtilityOutputsTests.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Datadog/TracerTests.swift

📦 The SDK [performs sanitization](https://github.com/DataDog/dd-sdk-ios/blob/master/Sources/Datadog/Logging/Log/LogSanitizer.swift) for `Log` attributes created by the user. This includes list of reserved attributes, that get removed when given by the user. This PR adds `dd.trace_id` and `dd.span_id` to that list.
The reason why it was not done in #117 is that this includes additional refactoring. It is the subject of this PR.
The `LogOutput` was not differentiating if the attribute comes from the user, or is set internally by the `LoggingForTracingAdapter`:
```swift
internal protocol LogOutput {
func writeLogWith(level: LogLevel, message: String, date: Date, attributes: [String: Encodable], tags: Set<String>)
}
```
This is now changed by introducing `LogAttributes` type:
```swift …
```

RUMM-478 Skip sanitization of log attributes created by Tracing

---

Sources/DatadogObjc/DatadogConfiguration+objc.swift
Tests/DatadogTests/Datadog/Core/AutoInstrumentation/URLSessionSwizzlerTests.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift

🚚 This PR exposes new tracing configuration APIs to Objective-C.
Two APIs were exposed using our way of Objective-C → Swift bridging:
```swift
.enableTracing(_ enabled:)
.set(tracesEndpoint:)
```

RUMM-339 Expose tracing-related configuration for Objective-C

---

Tests/DatadogTests/Datadog/Core/AutoInstrumentation/URLSessionSwizzlerTests.swift

We use URLs such as "https://foo.bar" in those tests.
They don't resolve to a real address, so they only result in DNS queries, not actual HTTPS connections.
However, those DNS queries are actual connections anyway and they cause flakiness in unit tests.
[Origin of the issue](https://github.com/DataDog/dd-sdk-ios/pull/157#discussion_r448234067)
Now we use unsupported protocols in tests.
Those tasks go through session's `URLProtocol` chain and returns immediately with "unsupported URL" error.
That prevents actual network traffic in unit tests.
We could also use custom `URLProtocol`s to achieve the same result (as we did in other test cases)
but that wouldn't work in case of `URLSession.shared`
If we notice weird behavior in swizzling tests again, we may want to verify if …

RUMM-575 URLSessionSwizzlerTests flakiness

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/TargetSupport/DatadogTests/DatadogTests-Bridging-Header.h
Sources/Datadog/Core/AutoInstrumentation/URLSessionSwizzler.swift
Sources/DatadogObjc/DatadogConfiguration+objc.swift
Tests/DatadogTests/Datadog/Core/AutoInstrumentation/NSURLSessionBridge.h
Tests/DatadogTests/Datadog/Core/AutoInstrumentation/NSURLSessionBridge.m
Tests/DatadogTests/Datadog/Core/AutoInstrumentation/URLSessionSwizzlerTests.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift
Tests/DatadogTests/DatadogObjc/DDDatadogTests.swift

`DatadogObjc` needs to provide auto-instrumentation for Tracing as `Datadog` already does
We provide `set(tracedHosts: Set<String>)` in `DDConfigurationBuilder` interface.
This method sets `tracedHosts` in `Datadog.Configuration` which leads to automatic tracing in given hosts, just as `Datadog` does in Swift
Unlike in Swift, we can pass `nil` as `url`, `request` and/or `completionHandler` to swizzled methods in ObjC.
Although this never should happen, if that happens the app crashes with only `exc_bad_access`: our users won't even have a clue what went wrong!
We fixed that by changing the method signature in swizzle implementation
```swift
// before
(URLSession, Selector, URL, @escaping CompletionHandler)
// after
(URLSession, Selector, URL?, CompletionHandler?)
```
This change doesn't …

RUMM-555 Auto-tracing for Objective-C added

---

Tests/DatadogBenchmarkTests/LoggingStorageBenchmarkTests.swift
Tests/DatadogIntegrationTests/IntegrationTests.swift
Tests/DatadogIntegrationTests/TracingIntegrationTests.swift
Tests/DatadogTests/Datadog/Core/AutoInstrumentation/URLSessionSwizzlerTests.swift

Use `setUpWithError()` or `tearDownWithError()` in test setups that can throw, it allows properly handling of errors
Clean all `try!` uses in the test code since can be handled as error instead of crashes
Just replaced  `setUp()` with `setUpWithError()` and `tearDown()`  with `tearDownWithError()`  in those methods that were using methods that could throw

RUMM-266 Use setUpWithError or tearDownWithError in tests

---

Tests/DatadogIntegrationTests/LoggingIntegrationTests.swift
Tests/DatadogIntegrationTests/TracingIntegrationTests.swift
instrumented-tests/http-server-mock/Package.swift
instrumented-tests/http-server-mock/Sources/HTTPServerMock/ServerSession.swift
instrumented-tests/http-server-mock/Tests/HTTPServerMockTests/HTTPServerMockTests.swift

This PR avoid waiting more than necessary in integration tests, so can be run faster
Creates a method in ServerSession to actively check for a fixed number of recorded POST requests. This method waits for a specific number of recorded post requests and returns, or timeouts and returns existing recorded requests 
This method is used in some integration tests that were waiting a fixed time (higher than ecessary)

RUMM-565 Make integration tests execute faster

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/Tracing/TracingAutoInstrumentation.swift
Sources/Datadog/Tracing/Utils/URLFilter.swift
Tests/DatadogTests/Datadog/Core/AutoInstrumentation/URLSessionSwizzlerTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/Tracing/TracingAutoInstrumentationTests.swift
Tests/DatadogTests/Datadog/Utils/URLFilterTests.swift

During shipping beta 3, we noticed that we should exclude certain URLs from autoinstrumentation in order to avoid tracing the trace requests.
`URLFilter` is refactored out from `TracingAutoInstrumentation`
It takes `includedHosts` and `excludedURLs`:
• `includedHosts` include themselves and their subdomains
• `excludedURLs` exclude URLs which contain any of them

RUMM-566 Exclude URLs from auto-tracing

---

.github/workflows/all-platform-tests.yml

📦 This PR fixes the `test-all-platforms.yml` CI job to pick the right git branch when triggered from a PR comment.
The GH workflow was configured to either:
* run if `@test-all-platforms` is mentioned in PR description,
* run if `@test-all-platforms` is mentioned in PR comment.
The first scenario used to work fine and is not changed 👌. The second scenario was buggy: because of how GH `issue_comment` trigger works, the workflow was always triggered on the `master` branch, resulting with CI picking the `master` for its job.
I changed the behaviour of `Trigger Bitrise build` step to get the branch name from PR comment. **From now, the expected syntax for running `test-all-platforms.yml` CI job from PR comment is**:
```
@test-all-platforms <branch-name>
```
e.g.:
```
"@test-all-platforms …
```

RUMM-486 Fix `test-all-platforms` trigger

---

LICENSE-3rdparty.csv
Makefile
api-surface-objc
api-surface-swift
instrumented-tests/http-server-mock/README.md
instrumented-tests/http-server-mock/Tests/HTTPServerMockTests/HTTPServerMockTests.swift
tools/api-surface/.gitignore
tools/api-surface/.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
tools/api-surface/Fixtures/.gitignore
tools/api-surface/Fixtures/.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
tools/api-surface/Fixtures/Package.swift
tools/api-surface/Fixtures/Sources/Fixtures/Fixture1.swift
tools/api-surface/Package.resolved
tools/api-surface/Package.swift
tools/api-surface/README.md
tools/api-surface/Sources/APISurfaceCore/APISurface.swift
tools/api-surface/Sources/APISurfaceCore/ModuleInterface.swift
tools/api-surface/Sources/APISurfaceCore/Parsing.swift
tools/api-surface/Sources/APISurfaceCore/Printing.swift
tools/api-surface/Sources/api-surface/main.swift
tools/api-surface/Tests/api-surfaceTests/api_surfaceTests.swift
tools/lint/sources.swiftlint.yml
tools/lint/tests.swiftlint.yml

📦 This PR adds `api-surface-swift` and `api-surface-objc` files, both listing the `public` interfaces from SDK.
I created a command-line tool, `api-surface`. It uses [SourceKitten](https://github.com/jpsim/SourceKitten) package to generate documentation for SDK and parses its intermediate output to only list interesting things from publicly available interface.
This tool is used in `Makefile`, so we can re-create api-surfaces using `make api-surface`:
```make
api-surface:
@cd tools/api-surface/ && swift build --configuration release
@echo "Generating api-surface-swift"
./tools/api-surface/.build/x86_64-apple-macosx/release/api-surface workspace --workspace-name Datadog.xcworkspace --scheme Datadog --path . > api-surface-swift
@echo "Generating api-surface-objc" …
```

RUMM-563 Generate api-surface-swift and api-surface-objc

---

Sources/Datadog/Tracer.swift
Sources/Datadog/TracerConfiguration.swift
Tests/DatadogTests/Datadog/Mocks/TracingFeatureMocks.swift
Tests/DatadogTests/Datadog/TracerTests.swift

It let users add global tags on Tracer
The desired tags must be set set in TracerConfiguration before initializing the tracer and will be copied to all created spans

RUMM-571 Let users add global tags on Tracer

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Upload/DataUploader.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/Logging/LoggingFeature.swift
Sources/Datadog/RUM/RUMFeature.swift
Sources/Datadog/Tracing/TracingAutoInstrumentation.swift
Sources/Datadog/Tracing/TracingFeature.swift
Tests/DatadogIntegrationTests/IntegrationTests.swift
Tests/DatadogTests/Datadog/DatadogConfigurationTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/Logging/LoggingFeatureTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/TracingFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMFeatureTests.swift
Tests/DatadogTests/Datadog/Tracing/TracingAutoInstrumentationTests.swift
Tests/DatadogTests/Datadog/Tracing/TracingFeatureTests.swift

📦 This PR configures `RUMFeature` so it can upload data to RUM Intake
I added `RUMFeature` with `Storage` and `Upload` stacks and configured them to use the expected RUM HTTP message format.
RUM uses `text/plain;charset=UTF-8` content type with RUM events encoded as newline-separated JSONs:
```http
POST <rum-intake-url>/<access-token>?ddsource=ios&batch_time=<timestamp in milliseconds>&ddtags=service:<service-name>,version:<app-version>,sdk_version:<sdk-version>,env:<environment-name>
Content-Type: text/plain;charset=UTF-8
rumEventJSON1
rumEventJSON2
rumEventJSON3
```
Except unit tests, to additionally test if all works fine, I've send a fake data to RUM Explorer (I will add this debug utility in a next PR, so we can use it when iterating further on RUM feature):

RUMM-515 RUM data is uploaded to server

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/AppConfig.swift
Datadog/Example/AppDelegate.swift
Datadog/Example/Base.lproj/Main.storyboard
Datadog/Example/Debugging/DebugRUMViewController.swift
Datadog/TargetSupport/Example/Info.plist
Sources/Datadog/RUM/DataModels/RUMViewEvent.swift
Sources/Datadog/RUMMonitor.swift
xcconfigs/Datadog.xcconfig

🚚 This PR adds "Debug RUM" screen in Example app. It can be used to send events to RUM Explorer:
As RUM data upload was done in #174, in this PR I just pass the `RUMViewEvent` encodable model to RUM's `fileWriter`, so it gets uploaded by the RUM's upload worker.
To not block RUM development by _"`RUM-517` RUM data models are auto generated"_, we can keep crafting `RUMDataModels` manually (as I did for `RUMViewEvent`). After `RUM-517` is done, we will just replace them.
For RUM, we have to update the `.xcconfig` file. Now, next to `DATADOG_CLIENT_TOKEN` it also takes `RUM_APPLICATION_ID`:
```
RUM_APPLICATION_ID=// use your own RUM Application ID obtained on datadoghq.com
DATADOG_CLIENT_TOKEN=// use your own Client Token, generated for RUM_APPLICATION_ID
```
RUM application needs a separate …

RUM-515 Add "Debug RUM" screen in Example app

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/RUM/DataModels/RUMDataModel.swift
Sources/Datadog/RUM/DataModels/RUMViewEvent.swift
Sources/Datadog/RUM/RUMEvent/RUMEventBuilder.swift
Sources/Datadog/RUM/RUMEvent/RUMEventEncoder.swift
Sources/Datadog/RUM/RUMEventOutputs/RUMEventFileOutput.swift
Sources/Datadog/RUM/RUMEventOutputs/RUMEventOutput.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMEvent/RUMEventBuilderTests.swift
Tests/DatadogTests/Datadog/RUM/RUMEventOutputs/RUMEventFileOutputTests.swift
Tests/DatadogTests/Datadog/RUM/RUMFeatureTests.swift
Tests/DatadogTests/Matchers/LogMatcher.swift
Tests/DatadogTests/Matchers/RUMEventMatcher.swift
Tests/DatadogTests/Matchers/SpanMatcher.swift

📦 This PR adds more information to events send to RUM Explorer:
* network information,
* mobile carrier information,
* user info,
* custom attributes.
Following the RFC, this part is structured as a data stream:
* `RUMDataModel` is created in `RUMMonitor`,
* `RUMEventBuilder` transforms `RUMDataModel` into `RUMEvent<DM: RUMDataModel>` and bundles all the extra information in it,
* `RUMEvent<DM>` is passed to `RUMEventFileOutput` which writes it to the file.
All the extra attributes are encoded at the root level of RUM event JSON:
```swift
{
/* `RUMDataModel` attributes */
"attribute": "foo",
/* Extra info attributes added by `RUMEventBuilder` */
"custom.attribute": "value",
"usr.email": "foo@bar.com",
"usr.id": "abc-123",
"usr.name": "bar"
}
```
Unit tests in `RUMEventFileOutput` provide …

RUMM-596 Enrich RUM Event with internal and custom attributes

---

Datadog/Datadog.xcodeproj/project.pbxproj

🐛 This PR is addressing #177 where App Store Connect validation issues are reported when uploading the app that links `DatadogObjc` with Carthage:
The reason of duplicated framework and colliding `com.datadoghq.Datadog` bundle identifier was a mistaken configuration of `DatadogObjc` "Frameworks and Libraries", where `Datadog.framework` was embedded and signed.
I changed it to **not embed** the `Datadog.framework` (as Carthage users do embed it through Carthage script):
I made sure that Objective-C app linking this branch with Carthage passes the ASC validation:

RUMM-611 Hotfix App Store submission issues for `DatadogObjc`

---

Sources/Datadog/Core/Upload/HTTPClient.swift

🐛 This hotfix is addressing  #178 - where constantly growing memory usage is reported due to intensive logging.
With intensive logging comes frequent upload... and what I noticed is that every upload results with a memory leak. Here, allocations graph for 10 uploads (each batch was `~1MB`):
The reason of this leak, was an internal caching applied by the `URLSession` - by default, the session's `configuration.urlCache` is not `nil`, which results with some representation of the `URLRequest` being kept in memory (together with its `.httpBody`):
This started being visible after #65, where the `?batch_time=` query parameter was introduced and cache keys become unique for every new request.
The fix is simple - we need to opt-out from using the `.urlCache` for the `URLSession`. After this, the …

RUMM-610 Hotfix for memory leaks on data upload

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/Debugging/DebugRUMViewController.swift
Sources/Datadog/Attributes.swift
Sources/Datadog/Logger.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUM/RUMMonitor/RUMContext.swift
Sources/Datadog/RUM/RUMMonitor/RUMMonitorInternal.swift
Sources/Datadog/RUM/RUMMonitor/RUMScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorConfigurationTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

📦 This PR grounds necessary foundation for RUM Data Collection, including:
- `RUMMonitor` class conforming to `RUMInternal`
- `RUMScope` protocol
- `RUMCommand` enum
- `RUMContext` struct
- `RUMApplicationScope`
The `RUMMonitor` interface follows the RFC with only one difference: it is not possible to identify resources by `Hashable` value as proposed:
```swift
// Compiler error: Protocol 'Hashable' can only be used as a generic constraint
func start(resource id: Hashable, name: String, ..., attributes: [String: Encodable])
```
Instead, I decided to identify resources by `String` ([as we do in `dd-sdk-android`](https://github.com/DataDog/dd-sdk-android/blob/0153e4211d457d2739e6938e0c7598e9f9f7fe79/dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt# …

RUMM-526 Add `RUMMonitor` foundations

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/AppConfig.swift
Datadog/Example/AppDelegate.swift
Datadog/Example/Base.lproj/Main.storyboard
Datadog/Example/Debugging/DebugRUMViewController.swift
Datadog/Example/IntegrationTestFixtures/SendRUMFixture1ViewController.swift
Sources/Datadog/RUM/DataModels/RUMActionEvent.swift
Sources/Datadog/RUM/RUMMonitor/RUMScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogIntegrationTests/LoggingIntegrationTests.swift
Tests/DatadogIntegrationTests/RUMIntegrationTests.swift
Tests/DatadogIntegrationTests/TracingIntegrationTests.swift
Tests/DatadogIntegrationTests/UITestsHelpers.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/ServerMock.swift
Tests/DatadogTests/Datadog/RUM/RUMFeatureTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorConfigurationTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Matchers/RUMEventMatcher.swift

📦 This PR adds RUM session monitoring.
The RUM Session monitoring has 3 requirements:
* the initial Session is started with the first View,
* if Session duration exceeds `4h`, a new one is started,
* if no interaction is observed for more than `15min`, a new Session is started.
This logic is implemented in two scopes:
* `RUMSessionScope` tracks the activity time and returns `true` from `process(command:)` on expiration or timeout.
* `RUMApplicationScope` manages creation and re-start of the `RUMSessionScope`.
When the RUM Session is started for the first time, the `application_start` RUM Action is sent. Right now, this is implemented in `RUMSessionScope`, but will be moved to `RUMViewScope` in `RUMM-519`. The test is already added and won't change: …

RUMM-518 Add user Session monitoring

---

Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/RUMScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

⚙️ This is purely a refactoring PR. It changes the `RUMCommand` to be `protocol`, not `enum`.
Modelling commands as `enum` resulted with their associated values being widely repeated in the codebase, so adding a new value become very tedious:
```swift
// In definition:
enum RUMCommand {
// ...
case startResource(name: String, time: Date, url: String, resourceCode: Int, ...)
// ...
}
// During propagation:
switch command {
// ...
case .startResource(let name, let time, let url, let resourceCode, ...):
startResourceScope(name: name, time: time, url: url, resourceCode: resourceCode, ...)
// ...
}
// In handler definition
private func startResourceScope(name: String, time: Date, url: String, resourceCode: Int, ...) {
// ...
}
```
By using the `RUMCommand` protocol, now there is only one place …

RUMM-520 Abstract `RUMMCommand` as protocol, not enum

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/Base.lproj/Main.storyboard
Datadog/Example/Debugging/DebugRUMViewController.swift
Datadog/Example/IntegrationTestFixtures/SendRUMFixture1ViewController.swift
Datadog/Example/IntegrationTestFixtures/SendRUMFixture2ViewController.swift
Datadog/Example/IntegrationTestFixtures/SendRUMFixture3ViewController.swift
Sources/Datadog/RUM/DataModels/RUMErrorEvent.swift
Sources/Datadog/RUM/DataModels/RUMResourceEvent.swift
Sources/Datadog/RUM/RUMEventOutputs/RUMEventFileOutput.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUM/RUMMonitor/RUMMonitorInternal.swift
Sources/Datadog/RUM/RUMMonitor/RUMScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUM/UUIDs/RUMUUID.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogIntegrationTests/RUMIntegrationTests.swift
Tests/DatadogIntegrationTests/UITestsHelpers.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/RUMScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Matchers/RUMEventMatcher.swift

📦 This PR adds RUM Resources monitoring.
To keep this PR relatively small, Resource timing details were detached to `RUMM-633 Add Resource type and size`.
Public APIs added to `RUMMonitor`:
```swift
/// Notifies that the Resource starts being loaded.
/// - Parameters:
///   - resourceName: the name representing this Resource - must be unique among all Resources currently being loaded.
///   - request: the `URLRequest` issued for this Resource
///   - attributes: custom attributes to attach to the Resource.
public func startResourceLoading(resourceName: String, request: URLRequest, attributes: [AttributeKey: AttributeValue]? = nil)
/// Notifies that the Resource stops being loaded.
/// - Parameters:
///   - resourceName: the name representing this Resource - must match the one used in …
```

RUMM-520 Add Resources monitoring

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/Debugging/DebugRUMViewController.swift
Sources/Datadog/RUM/DataModels/RUMActionEvent.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUM/RUMMonitor/RUMMonitorInternal.swift
Sources/Datadog/RUM/RUMMonitor/RUMScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogIntegrationTests/RUMIntegrationTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/RUMScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Matchers/RUMEventMatcher.swift

🚚 This PR adds User Actions monitoring.
To keep this PR relatively small, additional User Action details were detached to `RUMM-642 Add more User Action information`.
Public APIs added to `RUMMonitor`:
```swift
/// Notifies that the User Action has started.
/// This is used to track long running user actions (e.g. "scroll").
/// Such an User Action must be stopped with `stopUserAction(type:)`, and will be stopped automatically if it lasts more than 10 seconds.
/// - Parameters:
///   - type: the User Action type
///   - attributes: custom attributes to attach to the User Action.
public func startUserAction(type: RUMUserActionType, attributes: [AttributeKey: AttributeValue]? = nil) {
start(userAction: type, attributes: attributes)
}
/// Notifies that the User Action has stopped.
/// This …
```

RUMM-521 Add User Actions monitoring

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/Base.lproj/Main.storyboard
Datadog/Example/IntegrationTestFixtures/SendRUMFixture1ViewController.swift
Tests/DatadogIntegrationTests/RUMIntegrationTests.swift
Tests/DatadogIntegrationTests/UITestsHelpers.swift

🧪 This PR adds User Action scenario to RUM Integration tests fixtures.
When RUM Fixture 1 screen is opened, it shows only one button:
Tapping that button registers the "tap" User Action and simulates Resource loading which shows next button on completion:
Then the UITest runner proceeds to the next screen.
I added an assertion for the new RUM Event sent (`RUMActionEvent`).

RUMM-521 Add integration test fixtures for User Action

---

Makefile

📦 This PR fixes the `make ship` command.
The Swift `.pospec` must be pushed to pod Specs repo before validating Objc `.podspec`.
~- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)~

RUM-621 Fix `make ship` command

---

Shopist/Shopist.xcodeproj/project.pbxproj
Shopist/Shopist/API.swift
Shopist/Shopist/AppConfig.swift
Shopist/Shopist/AppDelegate.swift
Shopist/Shopist/Info.plist
Shopist/Shopist/Scenes/CartViewController.swift
Shopist/Shopist/Scenes/CategoriesViewController.swift
Shopist/Shopist/Scenes/ListViewController.swift
Shopist/Shopist/Scenes/ProductDetailViewController.swift
Shopist/Shopist/Scenes/ProductsViewController.swift
xcconfigs/Shopist.xcconfig

Until auto-instrumentation for RUM arrives, we add manual instrumentation calls to a few places in Shopist app
1. View tracking:
* `Categories`, `Products`, `ProductDetails` and `Cart` view controllers are tracked
2. Resources
* `GET` requests made from `Categories` and `Products` are tracked
3. User Actions
* Cell taps in `Categories` and `Products`, pay action in `Cart` are tracked
During this task, we noticed that discrete user actions are not tracked properly due to their timeout requirement.
This PR should be merged after a fix 🔜 
I'll add visuals from RUM Explorer after the fix too

RUMM-656 Shopist: Manual RUM events

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/FeaturesIntegration/LoggingForTracingAdapter.swift
Sources/Datadog/FeaturesIntegration/LoggingWithRUMIntegration.swift
Sources/Datadog/FeaturesIntegration/RUMIntegrations.swift
Sources/Datadog/FeaturesIntegration/TracingWithRUMIntegration.swift
Sources/Datadog/Logger.swift
Sources/Datadog/Logging/Log/LogSanitizer.swift
Sources/Datadog/Logging/LogOutputs/LogFileOutput.swift
Sources/Datadog/Tracer.swift
Sources/Datadog/TracerConfiguration.swift
Sources/Datadog/Tracing/Span/SpanBuilder.swift
Sources/Datadog/Tracing/SpanOutputs/SpanFileOutput.swift
Sources/Datadog/Utils/InternalLoggers.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMIntegrationsTests.swift
Tests/DatadogTests/Datadog/LoggerBuilderTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Logging/LogOutputs/LogFileOutputTests.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/TracingFeatureMocks.swift
Tests/DatadogTests/Datadog/TracerConfigurationTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/Tracing/Span/SpanBuilderTests.swift

🚚  This PR Adds RUM with Tracing integration, so users can see in RUM Explorer which spans were produced while given View was being displayed:
Also, when `Span` is marked as error, the RUM Error is produced and added to the active RUM View. This can happen in two ways:
1/ Setting `Span` as error:
```swift
let span = tracer.startSpan(operationName: "Span with error log")
span.setTag(key: OTTags.error, value: true)
span.finish()
```
2/ Logging an error from `Span` (through existing Tracing with Logging integration):
```swift
let span = tracer.startSpan(operationName: "Span with error")
span.log(
fields: [
OTLogFields.event: "error",
OTLogFields.errorKind: "Swift error",
OTLogFields.message: "error message",
OTLogFields.stack: "Foo.swift:123"
]
)
span.finish()
```
In the second case, Open …

RUMM-522 Add RUM with Tracing integration

---

Sources/DatadogObjc/OpenTracing/OTGlobal+objc.swift
Sources/DatadogObjc/OpenTracing/OTNoop.swift
Sources/DatadogObjc/OpenTracing/OTSpan+objc.swift
Sources/DatadogObjc/OpenTracing/OTSpanContext+objc.swift
Sources/DatadogObjc/OpenTracing/OTTracer+objc.swift
Sources/DatadogObjc/Tracer+objc.swift
Sources/DatadogObjc/TracerConfiguration+objc.swift
Sources/DatadogObjc/Tracing/DDSpan+objc.swift
Sources/DatadogObjc/Tracing/DDSpanContext+objc.swift
Sources/DatadogObjc/Tracing/Propagation/HTTPHeadersWriter+objc.swift
dependency-manager-tests/spm/SPMProject.xcodeproj.src/project.pbxproj
dependency-manager-tests/spm/SPMProject/ViewController.swift

`DatadogObjC` wasn't compiling with _@objc attribute used without importing module 'Foundation'_ errors
This only happens in Swift Package Manager; other dependency managers work fine
For more info: https://github.com/DataDog/dd-sdk-ios/issues/218
I added `import Foundation` lines to source files.
I also made dep-manager-test/spm import `DatadogObjC` instead of `Datadog`, this should test both targets at once.
Note: I'm still investigating how come Xcode manages to build the project without those imports 🤔 
Release info
This PR is branched off from 1.3.0 tag and to be merged into master
We will ship this change as a hotfix once it is merged

RUMM-671 DatadogObjC target is fixed for SPM

---

Sources/Datadog/Core/AutoInstrumentation/MethodSwizzler.swift
Sources/Datadog/Core/AutoInstrumentation/URLSessionSwizzler.swift
Sources/Datadog/Core/Persistence/Files/File.swift
Tests/DatadogTests/Datadog/Core/AutoInstrumentation/MethodSwizzlerTests.swift

Xcode 11.3.1 doesn't have iOS 13.4 as base SDK
therefore `#available(iOS 13.4)` closures don't compile
For more: https://github.com/DataDog/dd-sdk-ios/issues/214
We added compiler version macros as workaround
```swift
#if compiler(>=5.2)
if #available(iOS 13.4, *) { newMethod() }
else { legacy() }
#else
legacy()
#endif
```
_Note:_ It's not trivial to run our tests in different Xcode versions with our CI provider
This PR is branched off from `1.3.0` tag and to be merged into `master`
We will ship this change as a hotfix once it is merged

RUMM-669 Xcode 11.3.1 compilation fix

---

Sources/Datadog/OpenTracing/OTSpan.swift
Sources/Datadog/OpenTracing/OTTracer.swift
Sources/Datadog/Tracing/DDNoOps.swift
Sources/Datadog/Tracing/DDSpan.swift
Sources/Datadog/Tracing/Utils/ActiveSpansPool.swift
Sources/DatadogObjc/OpenTracing/OTNoop.swift
Sources/DatadogObjc/OpenTracing/OTSpan+objc.swift
Sources/DatadogObjc/Tracing/DDSpan+objc.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/Tracing/Utils/ActiveSpansPoolTests.swift
Tests/DatadogTests/DatadogObjc/DDTracerTests.swift

Fix the active span concept to let create several root spans on the same thread. Previous to this change with this code:
````
let job1Span = tracer.startSpan("async work 1”)
doSomethingAsynchronously(completion: { job1Span.finish() })
let job2Span = tracer.startSpan("async work 2")
doSomethingAsynchronously(completion: { job2Span.finish() })
````
`job2Span` would be assigned as child of` job1Span`
With this change both spans will have the same parent (the `activeSpan` or none if there is no `activeSpan`). 
For job2Span to be child of job1span you must now set it explicitly as its parent:
````
let job1Span = tracer.startSpan("async work 1”)
doSomethingAsynchronously(completion: { job1Span.finish() })
let job2Span = tracer.startSpan("async work 2", childOf: job1Span) …
```

RUMM-670 Fix the active span concept to let create several root spans on the same thread

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Matchers/RUMEventMatcher.swift

📦 This PR makes the Resources and User Actions being associated with the active View.
This corresponds to the case where multiple Views are started at a time, for example:
```swift
monitor.startView(viewController: master)
monitor.startView(viewController: details)
monitor.startResourceLoading(resourceName: "/resource/1")
```
In such case, prior to this PR, the `/resource/1` would appear in both, "master" and "details" Views in RUM Explorer. This PR updates this behaviour, and the Resource will be linked only to the "details" View.
This also solves the range of errors with manual (and further: auto) instrumentation, where `startView()` and `stopView()` are called from different `UIViewController` lifecycle callbacks, i.e. when calling "start" from `viewDidLoad()` and "stop" from …

RUMM-535 Resources and User Actions are linked with the active View

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Matchers/RUMEventMatcher.swift

📦 This PR makes the View wait for all its pending Resources until it gets finished.
The `RUMViewScope` is marked `didReceiveStopCommand` on `stopView()`, but it remains in memory until its Resources count goes down to `0`.
Also, the corresponding behaviour test was added to `RUMMonitorTests`:
* `testStartingLoadingResourcesFromTheFirstView_thenStartingAnotherViewWhichAlsoLoadsResources`

RUMM-636 Resources loading can exceed the View lifespan

---

Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/FeaturesIntegration/RUMIntegrations.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogBenchmarkTests/BenchmarkMocks.swift
Tests/DatadogTests/Datadog/DatadogConfigurationTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMIntegrationsTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMContext/RUMCurrentContextTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScopeTests.swift
Tests/DatadogTests/Datadog/Tracing/TracingAutoInstrumentationTests.swift

📦 This PR adds the option to sample RUM Sessions.
The public API was added to `Datadog.Configuration` builder:
```swift
/// Sets the sampling rate for RUM Sessions.
///
/// - Parameter rumSessionsSamplingRate: the sampling rate must be a value between `0.0` and `100.0`. A value of `0.0`
/// means no RUM events will be sent, `100.0` means all sessions will be kept (default value is `100.0`).
public func set(rumSessionsSamplingRate: Float)
```
RUM Events from sampled-out session are not send to Datadog. Such session's scope is marked as `shouldBeSampledOut` and it doesn't create any child scopes.
When RUM Session is sampled, `RUMContext` attributes are not added to Logs nor Traces.

RUMM-590 Add RUM Sessions sampling

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/RUM/RUMEvent/RUMConnectivityInfoProvider.swift
Sources/Datadog/RUM/RUMEvent/RUMEventBuilder.swift
Sources/Datadog/RUM/RUMEvent/RUMEventEncoder.swift
Sources/Datadog/RUM/RUMEvent/RUMUserInfoProvider.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMEvent/RUMConnectivityInfoProviderTests.swift
Tests/DatadogTests/Datadog/RUM/RUMEvent/RUMEventBuilderTests.swift
Tests/DatadogTests/Datadog/RUM/RUMEvent/RUMUserInfoProviderTests.swift
Tests/DatadogTests/Datadog/RUM/RUMEventOutputs/RUMEventFileOutputTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorConfigurationTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Matchers/RUMEventMatcher.swift

📦 This PR changes from encoding user, network and carrier info attributes at the root level of RUM event JSON to using dedicated `event.usr` and `event.connectivity` types.
The network and carrier info retrieved from `NetworkInfoProvider` and `CarrierInfoProvider` go through `RUMConnectivityInfoProvider` and are mapped to single `RUMConnectivity`.
The user info retrieved from `UserInfoProvider` goes through `RUMUserInfoProvider` and is mapped to `RUMUSR`.
```swift
RUMUserInfoProvider(userInfoProvider:).current → RUMUSR?
RUMConnectivityInfoProvider(networkInfoProvider:carrierInfoProvider:).current → RUMConnectivity?
```

RUMM-630 Encode network and user info attributes using `rum-events-format`

---

Datadog/Example/Debugging/DebugRUMViewController.swift
Datadog/Example/IntegrationTestFixtures/SendRUMFixture1ViewController.swift
Shopist/Shopist/Scenes/CartViewController.swift
Shopist/Shopist/Scenes/CategoriesViewController.swift
Shopist/Shopist/Scenes/ProductsViewController.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

User Actions have Names in RUM Explorer as in the visual below
1. Name is added to `RUMMonitor` public interface
2. `UserAction` related commands have `name` property to carry data from `RUMMonitor` to RUM events
3. `UserAction` starts with a name and can end with a different name which overrides the initial name

RUMM-678 UserActions has Name property

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

🐞 This PR fixes the bug with discrete User Action event not being send when the UA expires and the next propagated command is `RUMStartUserActionCommand` or `RUMAddUserActionCommand`.
To reproduce the bug:
```swift
monitor.startView(viewController: mockView)
// wait 1s
monitor.registerUserAction(type: .tap, name: "1st action")
// wait 1s
monitor.registerUserAction(type: .swipe, name: "2nd action")
```
I added unit test to reproduce the bug and fixed it by enforcing the command processing in UA scope before it gets replaced with the next instance.

RUMM-677 Fix bug with User Action not being send

---

Sources/Datadog/DDRUMMonitor.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

Users may want to use common attributes in their RUM events
We should provide them a convenient way to set those attributes
Now users can add, update or remove global attributes in their `RUMMonitor` instances
```swift
rumMonitor.setAttribute(forKey: "some key", value: "some value") // adds an attribute
rumMonitor.setAttribute(forKey: "some key", value: "some other value") // updates the value
rumMonitor.setAttribute(forKey: "some key", value: nil) // removes the key
let globalAttrs = rumMonitor.attributes // returns current global attributes to be added to events
```
Note: `attributes` is thread-safe

RUMM-638 Global RUM attributes

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift

Expected behavior is resource being associated with the action which caused/triggered the resource
Resource scope was getting active user action from the current context at `sendEvent` phase
This resulted in unexpected behavior
Now resource scope keeps the active user action info at its `init`
If active user action changes during the lifetime of the resource, it doesn't change resource event's action

RUMM-682 Resources are associated with actions at init

---

Sources/Datadog/DatadogConfiguration.swift
Sources/DatadogObjc/DatadogConfiguration+objc.swift
Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift

Datadog adds a new service: GovCloud
It is quite different than our US and EU datacenters
SDK adds GovCloud endpoints to Logs, Traces and RUM features

RUMM-659 GovCloud endpoints added

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/AppDelegate.swift
Sources/Datadog/DDRUMMonitor.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/RUM/Debugging/RUMDebugging.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/Debugging/RUMDebuggingTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

🐣 This PR fixes 3 first issues noticed when early dogfooding the RUM feature in Datadog mobile app.
While installing the RUM feature in mobile app I noticed 3 main problems:
* It wasn't possible to infer a meaningful name for the RUM Views as our Datadog mobile app heavily uses generic view controllers.
* It wasn't possible to match each `startView()` call with the corresponding `stopView()` for all view controllers because our Datadog mobile app uses `UISearchController` which follows `viewWillAppear()` / `didDisappear()` differently.
* Because of the 2nd, it wasn't easy to debug the current state of the `RUM` feature, mainly active / inactive RUM Views.
Each problem lead to a separate solution / improvement, respectively:
To fix the first issue, new `path: String?` parameter was added …

RUMM-672 Add improvements noticed in RUM dogfooding

---

Sources/Datadog/OpenTracing/OTTracer.swift
Sources/Datadog/Tracer.swift
Tests/DatadogTests/Datadog/TracerTests.swift

📦 This PR adds the `startRootSpan()` API to `Datadog.Tracer`. 
This API enables using `setActive()` span in asynchronous jobs, e.g.:
```swift
func makeAPIRequest(on queue: DispatchQueue, completion: @escaping () -> Void) {
let requestSpan = tracer
.startRootSpan(operationName: "request")
.setActive() // set active, so the asynchronous job can continue the trace without the span reference
queue.asyncAfter(deadline: .now() + 1) {
let responseDecodingSpan = tracer.startSpan(operationName: "response decoding")
responseDecodingSpan.finish()
requestSpan.finish()
completion()
}
}
makeAPIRequest(on: queue) {}
makeAPIRequest(on: queue) {}
```
which results with two root "request" spans, each having "response decoding" child span.
New API was introduced:
```swift
/// Start a new root span with the …
```

RUMM-675 Add `tracer.startRootSpan()` API

---

Sources/Datadog/RUM/Debugging/RUMDebugging.swift

`Datadog.debugRUM = true` within `AppDelegate.didFinishLaunching...` doesn't work
this call must be made once the app has a window
Now `RUMDebugging` adds itself to the screen lazily
It checks if this is needed at every render pass
`RUMDebugView` remains at background if a VC is presented modally
`RUMDebugging` calls `bringSubviewToFront(self)` on its superview at every render pass
This call does not have an effect if it is already topmost subview
I couldn't find a way to write failing tests for these bugs, open to ideas 👂

RUMM-698/699 RUM Debugging UI fixes

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/FeaturesIntegration/LoggingWithRUMIntegration.swift
Sources/Datadog/FeaturesIntegration/RUMIntegrations.swift
Sources/Datadog/FeaturesIntegration/TracingWithRUMIntegration.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMIntegrationsTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/TracingWithRUMErrorsIntegrationTests.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/RUMCommandTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift

📦 This PR updates the way we encode `Span` error attributes for RUM Errors in "Tracing with RUM" integration. 
This unifies the data of RUM Errors on Android and iOS when user marks the `Span` as error (either directly or through `span.log()` integration). Counterpart of https://github.com/DataDog/dd-sdk-android/pull/351
Before, the error attributes were encoded at the root level of RUM event JSON using 3 custom fields:
```diff
-        static let spanErrorMessage = "span.error_message"
-        static let spanErrorType = "span.error_type"
-        static let spanErrorStack = "span.error_stack"
```
From now, span's `errorMessage`, `errorType` and `errorStack` are encoded into `RUMError` object directly:
```swift
// RUMViewScope.swift
let eventData = RUMError(
// ...
error: .init(
message: …
```

RUMM-679 Encode Span error attributes in RUM Error fields

---

DatadogSDK.podspec
DatadogSDKObjc.podspec
Sources/Datadog/Versioning.swift
Tests/DatadogIntegrationTests/RUMIntegrationTests.swift

📦 This PR bumps the SDK version to `1.4.0-alpha1` so it can be updated in the Datadog mobile app.
`make bump & 1.4.0-alpha1`. No `make ship` as we're not yet releasing.

RUMM-710 Prepare `-alpha1` dogfooding release

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/FeaturesIntegration/LoggingWithActiveSpanIntegration.swift
Sources/Datadog/FeaturesIntegration/LoggingWithRUMIntegration.swift
Sources/Datadog/FeaturesIntegration/TracingWithRUMIntegration.swift
Sources/Datadog/Logger.swift
Sources/Datadog/Logging/Log/LogSanitizer.swift
Sources/Datadog/Logging/LoggingFeature.swift
Sources/Datadog/RUM/RUMFeature.swift
Sources/Datadog/Tracer.swift
Sources/Datadog/Tracing/TracingFeature.swift
Sources/Datadog/Utils/InternalLoggers.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/LoggerBuilderTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Datadog/TracerConfigurationTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift

📦 This PR adds Logging with Tracing integration. When there is an active span registered, its attributes are added to the produced `Log`.
This enables two-way integration between Logging and APM:
```swift
let span = Global.sharedTracer.startSpan("logs containing span").setActive()
logger.warn("warn message")
logger.error("error message")
logger.critical("critical message")
span.finish()
```
New public API was added to `Logger.Builder`:
```swift
/// Enables the logs integration with active span API from Tracing.
/// If enabled all the logs will be bundled with the `Global.sharedTracer.activeSpan` trace and
/// it will be possible to see all the logs sent during that specific trace.
/// - Parameter enabled: `true` by default
public func bundleWithTrace(_ enabled: Bool) -> Builder
```
it's a …

RUMM-657 Add Active Span attributes to Logs

---

Shopist/Shopist/AppDelegate.swift
Sources/Datadog/Core/FeaturesConfiguration.swift
Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift

There was a discrepancy between Android's environment validation rule and ours.
For instance, `shop.ist` was invalid for us whereas it was valid for Android and more importantly valid for RUM Explorer.
Now we use Android's regex, which allows "_./-" as non-alphanumerics.

RUMM-700 Environment regex changed

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/PerformancePreset.swift
Sources/Datadog/Core/Upload/DataUploadDelay.swift
Sources/Datadog/Core/Upload/DataUploadWorker.swift
Sources/Datadog/Core/Upload/DataUploader.swift
Sources/Datadog/Core/Upload/HTTPClient.swift
Tests/DatadogTests/Datadog/Core/PerformancePresetTests.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploadDelayTests.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploadWorkerTests.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploaderTests.swift
Tests/DatadogTests/Datadog/Logging/LoggingFeatureTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMFeatureTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/Tracing/TracingFeatureTests.swift

SDK was decreasing upload interval as long as there is a batch to upload
That caused problems in case of network errors
Example case: the device can't resolve upload URL for some reason, yet SDK keeps trying to upload at short intervals.
Now if there is a network error or client token error, interval increases (interval used to decrease in that case)

RUMM-709 Upload delay increases in case of network error

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
Datadog/Example/Scenarios/RUM/NavigationController/RUMNCSScreen3ViewController.swift
Datadog/Example/Scenarios/RUM/NavigationController/RUMNavigationControllerScenario.storyboard
Datadog/Example/TestScenarios.swift
Sources/Datadog/Core/AutoInstrumentation/MethodSwizzler.swift
Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/RUM/AutoInstrumentation/RUMAutoInstrumentation.swift
Sources/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsHandler.swift
Sources/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsPredicate.swift
Sources/Datadog/RUM/AutoInstrumentation/Views/UIViewControllerSwizzler.swift
Sources/Datadog/Tracing/AutoInstrumentation/TracingAutoInstrumentation.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMNavigationControllerScenarioTests.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/RUMAutoInstrumentationTests.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsHandlerTests.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Views/UIViewControllerSwizzlerTests.swift
Tests/DatadogTests/Matchers/RUMEventMatcher.swift
Tests/DatadogTests/Matchers/RUMSessionMatcher.swift

📦 This PR adds auto instrumentation for monitoring RUM Views in `UINavigationController`.
Following the RFC, new public APIs were introduced:
```swift
// On Datadog.Configuration.Builder:
public func trackUIKitRUMViews(using predicate: UIKitRUMViewsPredicate) -> Builder
// In UIKitRUMViewsPredicate.swift:
public protocol UIKitRUMViewsPredicate {
func rumView(for viewController: UIViewController) -> RUMViewFromPredicate?
}
```
The `UIViewControllerSwizzler` was implemented. It swizzles two VC lifecycle methods:
```swift
func viewWillAppear(_:)
func viewWillDisappear(_:)
```
to notify the `UIKitRUMViewsHandler` on VC presentation start / end. The handler uses `UIKitRUMViewsPredicate` to ask the user if given view controller should be accepted as the RUM View. Handler talks to the …

RUMM-713 Add RUM Views auto instrumentation for navigation controller

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/Scenarios/RUM/TapActionAutoInstrumentation/RUMTapActionScenario.storyboard
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMCommonAsserts.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMManualInstrumentationScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMNavigationControllerScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMTapActionScenarioTests.swift

📦 This PR adds integration test for RUM Actions auto instrumentation.
Test runner goes through the test scenario UI introduced in #254. RUM requests are send to the Python server, then retrieved and inspected with `RUMSessionMatcher`.
I also decoupled the common assertions for HTTP message format (path and headers), so it's now applied to all RUM integration tests.

RUMM-717 Add integration test for RUM Actions instrumentation

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
Datadog/Example/Scenarios/RUM/TabBarAutoInstrumentation/RUMTabBarAutoInstrumentationScenario.storyboard
Datadog/Example/TestScenarios.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMTabBarControllerScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMTapActionScenarioTests.swift

📦 This PR adds RUM Views auto instrumentation for tab bar.
The `UIViewController` callbacks instrumented in #252 were sufficient to cover interactions with `UITabBarController`, so this PR only adds the test scenario and integration test.
The integration test navigates through hierarchy of `UITabBarController` and 3 `UINavigationControllers`, which is a common configuration for tab bar based applications:

RUMM-714 Add RUM Views auto instrumentation for tab bar

---

Tests/DatadogTests/Datadog/Core/Upload/DataUploaderTests.swift
Tests/DatadogTests/Datadog/Core/Upload/HTTPClientTests.swift
Tests/DatadogTests/Datadog/Mocks/ServerMock.swift

`URLProtocol` doesn't give what you set anymore
It envelopes what you give in an `NSURLError` instance
That breaks one of our test cases ❌ 
Now we give `NSError` to `URLProtocol`, that way we can preserve `localizedDescription` and assert on it

RUMM-739 Fix: URLProtocol alters error in iOS 14

---

Tests/DatadogTests/Datadog/Core/Upload/DataUploadWorkerTests.swift

`DataUploadWorkerTests` became more flaky after adding tests for interval logic
`DataUploadWorkerTests` uses `MockDelay` to test interval logic
In fact, tests assert on the first interval logic command only
However, `MockDelay` was executing assertions on every command
That probably caused wrong assertions on wrong commands in which case there were multiple commands sent
Now `MockDelay` ignores the commands after the first one ✅ 
Hopefully that will improve the situation.

RUMM-737 Fix: Tests flakiness

---

Tests/DatadogIntegrationTests/Scenarios/RUM/RUMTapActionScenarioTests.swift

iOS 13 Swipe Typing feature blocks software keyboard with onboarding
We must tap Continue button in order to get the real keyboard
Now UI Test tries to tap on `Continue` button if exists before typing given letters
(For demonstration video check out jira ticket 🎥 )

RUMM-740 Fix: UI Test software keyboard issue

---

dependency-manager-tests/carthage/Makefile
dependency-manager-tests/carthage/tmp.xcconfig

Carthage has an known issue with Xcode 12
For more: https://github.com/Carthage/Carthage/issues/3019
This workaround excludes ARM arches from carthage build
It fixes our build failure as lipo doesn't merge x86 and ARM anymore
Source: https://github.com/Carthage/Carthage/issues/3019#issuecomment-664099506

RUMM-759 Workaround for Carthage&Xcode 12 issue

---

Shopist/Shopist/API.swift
Shopist/Shopist/Extensions/UIImageView+Network.swift
Shopist/Shopist/Scenes/CheckoutViewController.swift
Shopist/ShopistUITests/ShopistUITestHelpers.swift
Shopist/ShopistUITests/ShopistUITests.swift

Shopist events were not aligned with its build triggers.
1. Runs are triggered once in every 30mins
2. Yet, runs usually take less than 30mins: sometimes takes 15mins sometimes 25mins
That leaves gaps in timeseries of events in RUM Explorer, which is not desired.
Now we run until the given target duration is reached.
Shopist continues running for 27.5 minutes regardless of session count.

RUMM-738 Shopist: Run is bound to time limit instead of session count

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
Datadog/Example/Scenarios/RUM/ModalViewsAutoInstrumentation/RUMMVSModalViewController.swift
Datadog/Example/Scenarios/RUM/ModalViewsAutoInstrumentation/RUMMVSViewController.swift
Datadog/Example/Scenarios/RUM/ModalViewsAutoInstrumentation/RUMModalViewsAutoInstrumentationScenario.storyboard
Datadog/Example/TestScenarios.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMModalViewsScenarioTests.swift

📦 This is the initial PR for modal view controllers auto instrumentation with RUM Views. It adds the test scenario fixture for developing, debugging and testing (with integration test) this feature.
I added a simple storyboard composed of 2 VCs. The first one presents the second modally. The integration test (yet with no assertions) runs 6 behaviours:
* presenting modal VC using storyboard segue,
* presenting modal VC using `present(_:animated:)`,
* dismissing modal VC using `self.dismiss(animated:)`,
* dismissing modal VC using `presentingViewController.dismiss(animated:)`,
* dismissing modal VC using interactive "pull down" gesture,
* cancelling modal VC dismissal by cancelling the interactive "pull down" gesture.
In the next PRs I'll be adding necessary implementation for instrumenting …

RUMM-715 RUM Views - modal presentation instrumentation - part 1

---

Tests/DatadogTests/Datadog/Core/Persistence/FileWriterTests.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploadWorkerTests.swift
Tests/DatadogTests/Datadog/Mocks/ServerMock.swift
bitrise.yml

⚙️ This PR fixes recent flakiness observed on CI.
When analysing failed job reports, I observed two main sources of the flakiness:
* too optimistic timeouts,
* failed preconditions in `ServerMock`.
The conclusion made back in #72 was that for some complex tests, CI needs the timeout of 40x more than the test execution in local. I bumped recently failing timeouts to level close to this.
With the introduction of `URLSessionDelegate`, we no longer make blocking `expectation.fulfill()` for all `URLSessionTask` completions (the one received on delegate are not blocking). This makes some of the original assumptions included in `ServerMock` invalid. I changed them to print warning, instead of failing the test.
More in description of each commit.
I ran unit tests successfully 20 times in a row on …

RUMM-801 Fix tests flakiness on CI

---

Tests/DatadogTests/Datadog/Core/Upload/DataUploadWorkerTests.swift

⚙️ This PR fixes the tests compilation issue in Xcode 11.5.
This seems to be a compiler bug fixed in Xcode 11.6

RUMM-801 Fix unit tests compilation for Xcode 11.5

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/Scenarios/RUM/ModalViewsAutoInstrumentation/RUMModalViewsAutoInstrumentationScenario.storyboard
Datadog/Example/Scenarios/URLSession/NSURLSessionAutoInstrumentation/ObjcSendFirstPartyRequestsViewController.m
Datadog/Example/Scenarios/URLSession/NSURLSessionAutoInstrumentation/ObjcSendThirdPartyRequestsViewController.m
Datadog/Example/Scenarios/URLSession/URLSessionAutoInstrumentation/SendFirstPartyRequestsViewController.swift
Datadog/Example/Scenarios/URLSession/URLSessionAutoInstrumentation/SendThirdPartyRequestsViewController.swift
Sources/Datadog/RUM/AutoInstrumentation/Views/UIKitHierarchyInspection/UIKitHierarchyInspector.swift
Sources/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsHandler.swift
Sources/Datadog/RUM/AutoInstrumentation/Views/UIViewControllerSwizzler.swift
Tests/DatadogIntegrationTests/RUMM742Workaround.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMModalViewsScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMTabBarControllerScenarioTests.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Actions/UIKitRUMUserActionsHandlerTests.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Resources/URLSessionRUMResourcesHandlerTests.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Views/UIKitHierarchyInspection/UIKitHierarchyInspectorTests.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsHandlerTests.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Views/UIViewControllerSwizzlerTests.swift
Tests/DatadogTests/Datadog/RUM/RUMContext/RUMCurrentContextTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift

🚚 This PR updates RUM Views auto instrumentation to also cover modal view controller presentation.
As discussed, we intercept significant `UIViewController` callbacks:
* `viewDidAppear()`
* `viewDidDisappear()`
and decide on started / stopped RUM View by inspecting the `UIKit` views hierarchy.
I've also updated the integration test, to cover 2 different `modalPresentationStyles`: `.fullScreen` and `.pageSheet`, as both lead to receiving different `UIViewController` callbacks.

RUMM-715 RUM Views auto instrumentation - modal presentation

---

Sources/Datadog/Core/System/CarrierInfoProvider.swift
Sources/Datadog/Datadog.swift
bitrise.yml
dependency-manager-tests/cocoapods/CPProject.xcodeproj/project.pbxproj
dependency-manager-tests/spm/SPMProject.xcodeproj.src/project.pbxproj

With this PR the SDK compiles for Catalyst, yet we do not guarantee its correctness at runtime at the moment
Official Catalyst support is in our roadmap and we will announce it once it's done
As #274 points out, our users may need to compile their app target for Mac Catalyst too
Since our SDK doesn't compile for Catalyst, either our users need to duplicate their app target for Catalyst without linking Datadog SDK or add the framework conditionally via linker flags (which may be tricky or impossible with Swift Package Manager though)
SDK codebase doesn't depend on iOS-only frameworks, except `CoreTelephony`
We used `#if targetEnvironment(macCatalyst)` to disable `CoreTelephony`-dependent code from compiling

RUMM-816 SDK is made compile for Catalyst

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegate.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegateAsSuperclassTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegateTests.swift

`DDURLSessionDelegate` is supposed to be subclassable
The users may need to change its behavior to their own needs
Yet, it was not possible to subclass it practically due to lack of public designated initilalizer
It was possible to create a new class `class MyDelegate: DDURLSessionDelegate { ... }`
It was not possible to create an instance of it:
```swift
delegate = MyDelegate() // cannot be constructed because it has no accessible initializers
```
It was also not possible to override `init` methods because
1. superclass does not have a public designated init
2. overridden init needs to call super's designated init at some point
`DDURLSessionDelegate` now has a `public` (also overrideable) designated initializer

RUMM-812 DDURLSessionDelegate is made subclassable

---

bitrise.yml

🧪 This PR addresses recent tests flakiness by enabling `retry_test_on_fail` flag in Bitrise config. This is only a quick fix to solve the problem until we develop the solution to measure and fix flaky tests one by one (`RUMM-839`).
I enabled the `should_retry_test_on_fail` flag ([doc](https://github.com/bitrise-steplib/steps-xcode-test/blob/c5bca453fef5ea652139eb3ea0e41f594fc2a51d/step.yml#L262-L271)).
For the record - I also tried disabling the [`headless_mode` flag](https://github.com/bitrise-steplib/steps-xcode-test/blob/c5bca453fef5ea652139eb3ea0e41f594fc2a51d/step.yml#L169-L181), but the improvement was not very visible:
* `headless_mode: yes` → 5 failures / 60 runs,
* `headless_mode: no` → 3 failures / 60 runs.
For what I observed, consecutive test runs in a workflow are quite …

RUMM-801 Mute flakiness by retrying unit tests once after first failure

---

Sources/Datadog/RUM/AutoInstrumentation/Resources/URLSessionRUMResourcesHandler.swift
Sources/Datadog/RUM/DataModels/RUMDataModels.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUMMonitor.swift
Sources/Datadog/Tracing/AutoInstrumentation/URLSessionTracingHandler.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/TaskInterception.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptor.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMResourcesScenarioTests.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Resources/URLSessionRUMResourcesHandlerTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/Tracing/Autoinstrumentation/URLSessionTracingHandlerTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptorTests.swift
Tests/DatadogTests/Helpers/SwiftExtensions.swift
Tests/DatadogTests/Matchers/RUMSessionMatcher.swift

🚚 This PR adds `trace_id`, `span_id` and `id` information to RUM Resource events. Soon (`RUMM-696`) the `Span` won't be sent from the mobile SDK, but instead the RUM backend will generate it.
Recap: session interceptor manages the `URLRequest` mutation and notifies both, tracing and RUM handlers with different states of the `TaskInterception`.
Now,  the `SpanContext` is attached to `TaskInterception`. Each handler reads the `SpanContext` and processes it accordingly (tracing handler sends the `Span`, RUM handler encodes `trace_id` and `span_id` in RUM Resource event).
This required updating data models to recent `rum-events-format`.

RUMM-694 Add Trace information to RUM Resources

---

Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/Mocks/URLSessionAutoInstrumentationMocks.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/URLSessionAutoInstrumentationTests.swift

`URLSessionSwizzlerTests` started giving non-deterministic results.
Problems:
1. According to logs, some expectations are fulfilled multiple times.
2. `interceptor.tasksCompleted.count` is 3 during assertion (it must be 4) but a few lines later it becomes 4
Reasons:
1. In another, unrelated place SDK swizzles a method without unswizzling it later. Then, when this particular test case swizzles it becomes double-swizzled.
2. `InterceptorMock` fulfills its expectation before adding new item to its storage
Reasons are fixed

RUMM-851 Fix: Tests flakiness

---

Datadog/Example/TestScenarios.swift
Shopist/Shopist/AppDelegate.swift
Sources/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsHandler.swift
Sources/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsPredicate.swift
Sources/Datadog/RUM/DataModels/RUMDataModels.swift
Sources/Datadog/RUM/DataModels/RUMDataModelsMapping.swift
Sources/Datadog/RUM/RUMEvent/RUMConnectivityInfoProvider.swift
Sources/Datadog/RUM/RUMEvent/RUMUserInfoProvider.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogIntegrationTests/UITestsHelpers.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMIntegrationsTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/TracingWithRUMErrorsIntegrationTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMEvent/RUMConnectivityInfoProviderTests.swift
Tests/DatadogTests/Datadog/RUM/RUMEvent/RUMUserInfoProviderTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Matchers/RUMSessionMatcher.swift
api-surface-swift
docs/rum_collection.md
tools/generate-models/run.sh

We had `RUMViewFromPredicate` type in our public API
This was not the ideal name for this type, it was supposed to be `RUMView` yet this name was taken by a `RUMDataModel`
We make this change in order to improve our public API
We rename related types
Prefix in `RUMDataModels.swift`: `RUM` -> `RUMData` (eg: `RUMView` -> `RUMDataView`)
Type name: `RUMViewFromPredicate` -> `RUMView`
CI will probably fail now but this will be fixed by https://github.com/DataDog/dd-sdk-ios/pull/290

RUMM-726: Renaming RUM models

---

Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/URLSessionSwizzlerTests.swift

`testGivenSuccessfulTask_whenUsingSwizzledAPIs_itPassessAllValuesToTheInterceptor` case wasn't waiting for 4 task completions.
As the test continues without that expectation, `interceptor.tasksCompleted.count == 4` assertion was failing; although `tasksCompleted[3]` was not causing index out of range right after `count` assertion because it was just a matter of time for tasks to be completed.
Missing expectation added

RUMM-851 Missing expectation added to flaky test case

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/TaskInterception.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMResourcesScenarioTests.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift
Tests/DatadogTests/Datadog/Mocks/URLSessionAutoInstrumentationMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift
Tests/DatadogTests/Datadog/Tracing/Autoinstrumentation/URLSessionTracingHandlerTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/TaskInterceptionTests.swift

📦 This PR adds collection of advanced temporal metrics for auto-instrumented RUM Resources. Example:
More values are captured from `URLSessionTaskMetrics` object. If task execution required more than one transaction, the last transaction is used to compute detailed values and all leading transactions are described as "redirection" phase, e.g. in such case:
```bash
→ Transaction 1: 301 redirect
→ Transaction 2: 301 redirect
→ Transaction 3: 200 OK
```
the "redirection" phase spans from T1 start to T2 end and T3 is used to track `dns`, `connect`, ...

RUMM-719 Collect advanced temporal metrics for RUM Resources

---

docs/trace_collection.md

Duplicate of https://github.com/DataDog/dd-sdk-ios/pull/296
Original PR didn't trigger CI, I'm duplicating it from the upstream

remove beta warning from tracing docs

---

Datadog/Example/Debugging/DebugLoggingViewController.swift
Sources/Datadog/Logger.swift
Sources/Datadog/Logging/Log/LogSanitizer.swift
Sources/DatadogObjc/Logger+objc.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Logging/Log/LogSanitizerTests.swift
Tests/DatadogTests/DatadogObjc/DDLoggerTests.swift

fix #276 
There was no way to log an `Error`
1. `Error` parameter added to logging methods
2. `error.stack/kind/message` keywords are removed from `reservedAttributes` set

RUMM-817 Error can be logged

---

Sources/Datadog/RUM/RUMEvent/RUMEventEncoder.swift
Tests/DatadogTests/Datadog/RUM/RUMEventOutputs/RUMEventFileOutputTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

RUM v2 requires all custom attributes to be within `context` key in json
We keep the current data model as is
We add `context.*` prefix during encoding of the data model

RUMM-880 RUM attributes moved under context key

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/Scenarios/URLSession/NSURLSessionAutoInstrumentation/NSURLSessionScenario.storyboard
Datadog/Example/Scenarios/URLSession/URLSessionAutoInstrumentation/URLSessionScenario.storyboard
Datadog/Example/TestScenarios.swift
Sources/Datadog/RUM/AutoInstrumentation/Actions/UIKitRUMUserActionsHandler.swift
Sources/Datadog/RUM/AutoInstrumentation/Resources/URLSessionRUMResourcesHandler.swift
Sources/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsHandler.swift
Sources/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsPredicate.swift
Sources/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegate.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMResourcesScenarioTests.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/UIKitMocks.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsHandlerTests.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsPredicateTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegateTests.swift
api-surface-swift
docs/rum_collection.md

📦 This PR applies bunch of small improvements noticed when testing our SDK in open source projects.
Each improvement is delivered in a separate commit:
* Do not duplicate calls to `UIKitRUMViewsPredicate` when hierarchy's top view does not change.
* Add `DefaultUIKitRUMViewsPredicate` which names RUM Views by the class name.
* Print the console warning if any RUM View / Resource / Action is noticed but `Global.rum` is not registered.
* Make it cleaner in `rum_collecting.md` that `Global.rum` must be registered for each auto instrumentation.
* Improve the `DDURLSessionDelegate` initialisation warning if it's initialised before `Datadog.initialize()` is called.

RUMM-882 Improve documentation and console warnings

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogIntegrationTests.xcscheme
Datadog/TargetSupport/Example/Example.xcconfig
Makefile
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMResourcesScenarioTests.swift

This PR updates the current version of the sdk to monitor testing to version 0.3.0
* We link with the 0.3.0 version of the testing sdk
* We link Example app also with the sdk, so it is also instrumented while running UI tests.
* Enabled network instrumentation for tests in UITests (disabled temporarily two checks  in `testRUMResourcesScenario()` that fails because of the testing sdk).
* We dont enable network instrumentation in other tests because of another issue in the testing sdk
Test results:
[Link](https://app.datadoghq.com/ci/test-executions?query=%40git.commit_sha%3A13bf7c9d0a9a1329f2c7282e698fc5295b6c93f7%20service%3Add-sdk-ios%20%40git.repository_url%3A%22git%40github.com%3ADataDog%2Fdd-sdk-ios.git%22%20env%3Aci%20%40git.branch%3A%22nachoBonafonte%2Fupdate-to-0.3.0-testing-sdk%22% …

Update to 0.3.0 version of testing sdk

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/TestScenarios.swift
Sources/Datadog/RUM/AutoInstrumentation/Resources/URLSessionRUMResourcesHandler.swift
Sources/Datadog/Tracing/AutoInstrumentation/URLSessionTracingHandler.swift
Sources/Datadog/Tracing/Propagation/TracingHTTPHeaders.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/TaskInterception.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptionHandler.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptor.swift
Sources/Datadog/URLSessionAutoInstrumentation/URLSessionAutoInstrumentation.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMResourcesScenarioTests.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Resources/URLSessionRUMResourcesHandlerTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/Tracing/Autoinstrumentation/URLSessionTracingHandlerTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/TaskInterceptionTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptorTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/URLSessionAutoInstrumentationTests.swift

🚚 This PR changes the logic of auto-instrumented, network `Span` generation depending of which feature (RUM or Tracing) is enabled. This is because recently our RUM backend started generating spans for RUM Resources on behalf of the SDK.
New behaviour, assuming that `set(firstPartyHosts:)` is set and `DDURLSessionDelegate()` is installed:
| Tracing feature  | RUM feature | `Global.sharedTracer` | `Global.rum` | 1st party request | 3rd party request |
| :--------------: | :----------: | :--------: | :-------------: | :----------------: | :----------------: |
| ✅ | ❌ | registered | - | send `Span` + inject tracing headers | - |
| ❌ | ✅ | - | registered | send RUM Resource | send RUM Resource |
| ✅ | ✅ | registered | registered | send RUM Resource with `trace_id` and `span_id` + inject …

RUMM-696 Stop sending tracing `Span` for RUM Resources

---

Sources/Datadog/Core/Upload/DataUploader.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploaderTests.swift

Fixes #316 
Wrong property of `URLComponents` (`percentEncodedQueryItems`) was used in `URLProvider`
It is fixed by being replaced with the correct method (`queryItems`)

RUMM-894 URLProvider fixed for illegal chars

---

Sources/Datadog/Core/Upload/DataUploadConditions.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploadConditionsTests.swift

🚚 This PR fixes an issue reported as data being not uploaded from iPad (6th gen) iOS 14.0.1, when it is connected to MacBook through a lightning cable.
The investigation nailed this issue down to receiving `batteryStatus: unknown` with `batteryLevel: -1`. Given existing logic in `DataUploadConditions`, this clearly evaluated to `false` (no upload).
This fix returns arbitrary `true` value if battery status is undetermined. As we can see from RUMS-132, this may lead to making assumptions on unreliable values.

RUMS-132 Allow data uploads if battery status is `.unknown`

---

.gitignore
Cartfile
Cartfile.resolved
Datadog/Datadog.xcodeproj/project.pbxproj
DatadogSDK.podspec
DatadogSDK.podspec.src
LICENSE-3rdparty.csv
Makefile
Package.swift
Sources/Datadog/Datadog.swift
bitrise.yml
dependency-manager-tests/carthage/CTProject.xcodeproj/project.pbxproj
dependency-manager-tests/carthage/Makefile
dependency-manager-tests/cocoapods/Makefile
dependency-manager-tests/spm/Makefile
xcconfigs/Base.xcconfig
xcconfigs/Datadog.xcconfig

📦 We want to use NTP to compute the real time of writing events (logs, spans, rum). In this PR I'm adding the [lyft/Kronos](https://github.com/lyft/Kronos) dependency which does the NTP sync. It is not yet used in SDK code, as I wanted to separate project configuration from the actual work in SDK. This PR is not targeting the `master` branch yet.
**Cocoapods** :
```ruby
s.dependency 'Kronos', '~> 4.1'
```
**SPM**:
```swift
// Package.swift
.package(url: "https://github.com/lyft/Kronos.git", .upToNextMinor(from: "4.1.0"))
```
**Carthage** required few changes to the project (and the update in `dependency-manager-tests/carthage/CTProject`). As it was quite strenuous, I'm leaving the note on what was changed (it's also written in commit messages):
Things change fast in Carthage (their guides …

RUMM-655 Add `lyft/Kronos` dependency for NTP time sync

---

Datadog/Example/Debugging/DebugRUMViewController.swift
Datadog/Example/ExampleAppDelegate.swift
Sources/Datadog/Core/Attributes/UserInfoProvider.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/Logging/Log/LogEncoder.swift
Sources/Datadog/RUM/RUMEvent/RUMEventBuilder.swift
Sources/Datadog/RUM/RUMEvent/RUMEventEncoder.swift
Sources/Datadog/RUMMonitor.swift
Sources/Datadog/Tracing/Span/SpanBuilder.swift
Sources/Datadog/Tracing/Span/SpanEncoder.swift
Tests/DatadogBenchmarkTests/DataStorage/LoggingStorageBenchmarkTests.swift
Tests/DatadogBenchmarkTests/DataStorage/RUMStorageBenchmarkTests.swift
Tests/DatadogBenchmarkTests/DataStorage/TracingStorageBenchmarkTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMEvent/RUMEventBuilderTests.swift
Tests/DatadogTests/Datadog/RUM/RUMEvent/RUMUserInfoProviderTests.swift
Tests/DatadogTests/Datadog/RUM/RUMEventOutputs/RUMEventFileOutputTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Matchers/LogMatcher.swift

`Datadog.UserInfo` has arbitrary attributes via `extraInfo`
`UserInfoProvider` keeps `extraInfo` dictionary along with `userInfo`
Features (Logs, APM and RUM) encode `extraInfo` according to their own rules
```swift
extraInfo: ["key": "value"] -> "usr.key: value"
```
```swift
extraInfo: ["key": "value"] -> "meta.usr.key: value"
```
```swift
extraInfo: ["key": "value"] -> "context.usr.key: value"
```
In this PR, I put `usr.` prefix to `extraInfo` within `UserInfoProvider` and pass it to features as regular attributes.
But `UserInfoProvider` passes `UserInfo` value without encoding and the features (`LogEncoder` and `SpanEncoder`) are responsible for its encoding.
This is some sort of inconsistency in `UserInfoProvider`, I didn't like that ❌ 
Can't we make `UserInfo: Encodable` to …

RUMM-886 `setUserInfo(..., extraInfo)` added

---

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogBenchmarkTests.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogIntegrationTests.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc.xcscheme
Makefile
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMResourcesScenarioTests.swift
tools/license/check-license.sh

Update to DataDogSDKTesting 0.4.0
* Update to DataDogSDKTesting 0.4.0
* Modify makefile for XCFramework format
* Modify check-license for change to xcframework
* Update Bitrise environment variables
* Don't disable network instrumentation in Datadog and DatadogObjc
* Re-enable test that was not working with previous version

Update to DataDogSDKTesting 0.4.0

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Feature.swift
Sources/Datadog/Core/Persistence/Privacy/ConsentAwareDataWriter.swift
Sources/Datadog/Core/Persistence/Privacy/TrackingConsent.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/Logging/LoggingFeature.swift
Sources/Datadog/RUM/RUMFeature.swift
Sources/Datadog/Tracing/TracingFeature.swift
Tests/DatadogBenchmarkTests/DataStorage/LoggingStorageBenchmarkTests.swift
Tests/DatadogBenchmarkTests/DataStorage/RUMStorageBenchmarkTests.swift
Tests/DatadogBenchmarkTests/DataStorage/TracingStorageBenchmarkTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Privacy/ConsentAwareDataWriterTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMIntegrationsTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/TracingWithRUMErrorsIntegrationTests.swift
Tests/DatadogTests/Datadog/LoggerBuilderTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Logging/LoggingFeatureTests.swift
Tests/DatadogTests/Datadog/Mocks/DataUploadWorkerMock.swift
Tests/DatadogTests/Datadog/Mocks/FeatureDirectoriesMock.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/TracingFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMFeatureTests.swift
Tests/DatadogTests/Datadog/RUMMonitorConfigurationTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/TracerConfigurationTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/Tracing/TracingFeatureTests.swift
Tests/DatadogTests/DatadogObjc/DDLoggerTests.swift
Tests/DatadogTests/DatadogObjc/DDTracerTests.swift

📦 As the first part of tracking consent feature, this PR introduces the `ConsentAwareDataWriter`.
Each feature is now configured with two distinct directories, instead of one:
```swift
internal struct FeatureDirectories {
let unauthorized: Directory
let authorized: Directory
}
```
This is followed by the update to storage layer: `Feature` → `FeatureStorage` → `FileWriter: FileWriterType`,
which was was replaced with: `Feature` → `FeatureStorage` → `ConsentAwareDataWriter: FileWriterType`.
The `ConsentAwareDataWriter` will manage different instances of `FileWriter`, each writing to different directory.
In next PRs, more components will be added, towards the model we use in `dd-sdk-android`.

RUMM-829 Add consent-aware data writer

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Feature.swift
Sources/Datadog/Core/Persistence/Privacy/ConsentAwareDataWriter.swift
Sources/Datadog/Core/Persistence/Privacy/ConsentProvider.swift
Tests/DatadogTests/Datadog/Core/Persistence/Privacy/ConsentAwareDataWriterTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Privacy/ConsentProviderTests.swift

📦 As the next part of tracking consent feature, this PR introduces the `ConsentProvider`.
`ConsentProvider` implements basic subscription model. The `ConsentAwareDataWriter` reads the consent value and subscribes to its updates.

RUMM-830 Add consent provider

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Feature.swift
Sources/Datadog/Core/Persistence/Reading/DataReader.swift
Sources/Datadog/Core/Persistence/Reading/FileReader.swift
Sources/Datadog/Core/Persistence/Reading/Reader.swift
Sources/Datadog/Core/Persistence/Writting/ConsentAwareDataWriter.swift
Sources/Datadog/Core/Persistence/Writting/FileWriter.swift
Sources/Datadog/Core/Persistence/Writting/Processing/DataProcessor.swift
Sources/Datadog/Core/Persistence/Writting/Writer.swift
Sources/Datadog/Core/Upload/DataUploadWorker.swift
Sources/Datadog/Logging/LogOutputs/LogFileOutput.swift
Sources/Datadog/Tracing/SpanOutputs/SpanFileOutput.swift
Tests/DatadogBenchmarkTests/DataStorage/LoggingStorageBenchmarkTests.swift
Tests/DatadogBenchmarkTests/DataStorage/RUMStorageBenchmarkTests.swift
Tests/DatadogBenchmarkTests/DataStorage/TracingStorageBenchmarkTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Reading/FileReaderTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Writting/ConsentAwareDataWriterTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Writting/FileWriterTests.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploadWorkerTests.swift
Tests/DatadogTests/Datadog/Logging/LogOutputs/LogFileOutputTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/DataUploadWorkerMock.swift
Tests/DatadogTests/Datadog/RUM/RUMEventOutputs/RUMEventFileOutputTests.swift
Tests/DatadogTests/Datadog/Tracing/SpanOutputs/SpanFileOutputTests.swift

📦 As the next part of tracking consent feature, this PR introduces the `DataProcessor`.
In its current shape, `DataProcessor` may look unnecessary, as it just duplicates the interface of `Writer` and delegates the call to writer. The main motivation of introducing it now is to:
* stay aligned with Android SDK delayed batching architecture,
* have the same foundation as Android SDK for implementing upcoming processing pipelines (scrubbing / sampling).
Another important thing in this PR is the change of `FileWriter` and `FileReader` synchronisation. Before, both were using single `queue` to make sure their calls are synchronised. This was changed towards having synchronous, but not synchronised writers. The synchronisation is now done in `DataWriter` and `DataReader` using shared `queue`: …

RUMM-831 Add `DataProcessor`

---

Sources/Datadog/Global.swift
Tests/DatadogTests/Datadog/GlobalTests.swift
api-surface-swift

📦 This PR introduces `DDGlobal` convenience typealias, to avoid compiler ambiguity with user-defined `Global` constructs.
Solves #333 
```swift
/// Because `Global` is a common name widely used across different projects,
/// `DDGlobal` typealias can be used to avoid compiler ambiguity.
public typealias DDGlobal = Global
```

RUMM-921 Add `DDGlobal` typealias to avoid compiler ambiguity

---

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogBenchmarkTests.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogIntegrationTests.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc.xcscheme
Makefile

Update to dd-sdk-testing-swift version 0.5.0
Updated version number to 0.5.0
Added Environment variables to disable functionality that would break own tests

Update to dd-sdk-testing-swift version 0.5.0

---

Sources/Datadog/DatadogConfiguration.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
api-surface-swift

📦 To simplify the usage of `DefaultUIKitRUMViewsPredicate`, this PR mades it a default value for `trackUIKitRUMViews()` API.
Instead of calling:
```swift
.trackUIKitRUMViews(using: DefaultUIKitRUMViewsPredicate())
```
now, users just use:
```swift
.trackUIKitRUMViews()
```
when initialising the SDK.
Customisation is still possible:
```swift
.trackUIKitRUMViews(using: MyCustomPredicate())
```

RUMM-927 Use default value for `trackUIKitRUMViews()` public API

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Feature.swift
Sources/Datadog/Core/Persistence/Files/Directory.swift
Sources/Datadog/Core/Persistence/Migrating/DataMigrator.swift
Sources/Datadog/Core/Persistence/Migrating/DeleteAllDataMigrator.swift
Sources/Datadog/Core/Persistence/Migrating/MoveDataMigrator.swift
Sources/Datadog/Core/Persistence/Writting/ConsentAwareDataWriter.swift
Sources/Datadog/Core/Utils/Retrying.swift
Sources/Datadog/Datadog.swift
Tests/DatadogBenchmarkTests/BenchmarkMocks.swift
Tests/DatadogBenchmarkTests/DataStorage/DataMigratorBenchmarkTests.swift
Tests/DatadogTests/Datadog/Core/FeatureTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Files/DirectoryTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Migrating/DeleteAllDataMigratorTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Migrating/MoveDataMigratorTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Writting/ConsentAwareDataWriterTests.swift
Tests/DatadogTests/Datadog/Core/Utils/RetryingTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Helpers/TestsDirectory.swift

📦 As part of tracking consent feature, this PR makes sure that only authorized data can be uploaded. This means:
* all data collected with `.granted` consent,
* all data collected with `.pending` consent if it was then changed to `.granted`.
As in `dd-sdk-android`, `DataMigrator` type is introduced. There are two migrators implemented:
* `DeleteAllDataMigrator` - deletes all data in given folder,
* `MoveDataMigrator` - moves all data from source directory do destination folder.
Migrators are resolved in `ConsentAwareDataWriter` and their `migrate()` work is dispatched to the read/write queue, which keeps all writes (on collection) and reads (on upload) synchronized on the background thread.

RUMM-832 Only authorized data can be uploaded

---

Datadog/Example/ExampleAppDelegate.swift
Sources/Datadog/Core/Persistence/Privacy/TrackingConsent.swift
Sources/Datadog/Datadog.swift
Sources/DatadogObjc/Datadog+objc.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/Utils/InternalLoggersTests.swift
Tests/DatadogTests/DatadogObjc/DDDatadogTests.swift
api-surface-objc
api-surface-swift

📦 This PR adds the public API for configuring tracking consent:
```swift
Datadog.initialize(
appContext: ...,
trackingConsent: .pending,
configuration: ....
)
Datadog.set(trackingConsent: .granted)
```
New public APIs were introduced both for `Datadog` and `DatadogObjc`. 
The previous variant of `Datadog.initialize()` is marked deprecated.
I also added tests for `Logger`, `Tracer` and `RUMMonitor` to assert they respect the consent value when collecting data.

RUMM-833 Add public API for Data Tracking Consent

---

Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift

⚙️ This PR fixes unit tests compilation issue after merging #347.
Recently merged #347 was quite outdated comparing to the main branch, and it was not rebased before the merge. Because of this, updates to unit tests API introduced in NTP time sync feature were not applied in #347, causing the compiler issue on `master`.
~- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference~

Fix unit tests compilation after merging Tracking Consent feature

---

Datadog/Datadog.xcodeproj/project.pbxproj

Building `Example` gives
```
...../dd-sdk-ios/Datadog/Datadog.xcodeproj Building for iOS Simulator, but the linked and embedded framework 'Kronos.framework' was built for iOS + iOS Simulator.
```
Previous Xcode versions don't have this problem
Fix source: https://github.com/AFNetworking/AFNetworking/issues/4618#issuecomment-745314301

RUMM-946 Example app target doesn't compile Xcode 12.3

---

Sources/Datadog/Core/FeaturesConfiguration.swift
Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift

📦 This PR adds additional check to the `firstPartyHosts` configured by the user. If the host is invalid, it may get sanitized or dropped - both with appropriate warning.
Similar to https://github.com/DataDog/dd-sdk-android/pull/447 URL, host and IP regexes were used to validate the input `host`.
Example behaviours:
```swift
"https://first-party.com", // sanitize to → "first-party.com"
"http://api.first-party.com", // sanitize to → "api.first-party.com"
"https://first-party.com/v2/api", // sanitize to → "first-party.com"
"https://192.168.0.1/api", // sanitize to → "192.168.0.1"
"https://192.168.0.2", // sanitize to → "192.168.0.2"
"invalid-host-name", // drop
"192.168.0.3:8080", // drop
"", // drop
"localhost", // accept
"192.168.0.4", // accept
"valid-host-name.com", // accept
```

RUMM-904 First party hosts are sanitized

---

DatadogSDKAlamofireExtension.podspec
README.md
Sources/Datadog/FeaturesIntegration/EnvironmentSpanIntegration.swift
Sources/Datadog/TracerConfiguration.swift
Sources/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegate.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptor.swift
Sources/Datadog/URLSessionAutoInstrumentation/URLSessionSwizzler.swift
Sources/DatadogExtensions/Alamofire/DatadogAlamofireExtension.swift
Sources/DatadogExtensions/Alamofire/README.md
Tests/DatadogTests/Datadog/Mocks/URLSessionAutoInstrumentationMocks.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegateTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptorTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/URLSessionAutoInstrumentationTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/URLSessionSwizzlerTests.swift
api-surface-swift
dependency-manager-tests/cocoapods/CPProject/ViewController.swift
dependency-manager-tests/cocoapods/Podfile.src

📦 This PR makes it possible to add integrations with 3rd party networking libraries (including [Alamofire](https://github.com/Alamofire/Alamofire)).
Our network interceptor is pretty straightforward and follows the interception model in Alamofire:
* modify request;
* process task creation;
* process task metrics;
* process task completion (with optional error).
By polishing its interface and making the `URLSessionInterceptor` public, now it is possible to use our SDK with `Alamofire` by implementing custom AF's `EventMonitor` (for task start, metrics and completion) and AF's `RequestInterceptor` (for request modification).
Implementations of `DDEventMonitor` and `DDRequestInterceptor` are provided in `Sources/DatadogExtensions/Alamofire/`.
Those implementations are delivered in …

RUMM-883 Add support for 3rd party networking libraries (including Alamofire)

---

Sources/DatadogObjc/RUMMonitor+objc.swift
Tests/DatadogTests/DatadogObjc/DDRUMMonitorTests.swift

🐞 The `[DDGlobal.rum stopResourceLoadingWithResourceKey:response:attributes:]` public API was not visible for Objective-C.
This API was using `size: Int64?` parameter which can't be translated to Objective-C so it was not generated into Obj-C interface. I removed it, as we infer this information any way from the `HTTPURLResponse`.

RUMM-917 Fix Objc API visibility in `RUMMonitor`

---

Datadog/Example/AppConfiguration.swift
Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/Core/PerformancePreset.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/DatadogObjc/DatadogConfiguration+objc.swift
Tests/DatadogBenchmarkTests/BenchmarkMocks.swift
Tests/DatadogBenchmarkTests/DataStorage/LoggingStorageBenchmarkTests.swift
Tests/DatadogBenchmarkTests/DataStorage/RUMStorageBenchmarkTests.swift
Tests/DatadogBenchmarkTests/DataStorage/TracingStorageBenchmarkTests.swift
Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift
Tests/DatadogTests/Datadog/Core/PerformancePresetTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/FilesOrchestratorTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Writting/FileWriterTests.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Tracing/SpanOutputs/SpanFileOutputTests.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift
Tests/DatadogTests/Helpers/SwiftExtensions.swift
api-surface-objc
api-surface-swift

📦 This PR adds two new public APIs, so that the user can customize the size and frequency of requests made by the SDK.
The write / upload settings were already abstracted by `PerformancePreset` type, so this PR just configures its values depending on the `BatchSize` and `UploadFrequency` received from the user with two new public APIs:
```swift
public func set(batchSize: BatchSize)
public func set(uploadFrequency: UploadFrequency)
```
Because the iOS SDK provides different presets for iOS apps and iOS app extensions, the values computed for `PerformancePreset` are additionally customized to work well in short-lived app extension environment.
The `PerformancePreset` computed for iOS app is unified with the values introduced for Android SDK https://github.com/DataDog/dd-sdk-android/pull/454 …

RUMM-824 Add API for customizing batch size and upload frequency

---

Sources/DatadogObjc/Datadog+objc.swift
Sources/DatadogObjc/DatadogConfiguration+objc.swift
Sources/DatadogObjc/Global+objc.swift
Sources/DatadogObjc/Logger+objc.swift
Sources/DatadogObjc/OpenTracing/OTSpan+objc.swift
Sources/DatadogObjc/OpenTracing/OTSpanContext+objc.swift
Sources/DatadogObjc/OpenTracing/OTTracer+objc.swift
Sources/DatadogObjc/RUMMonitor+objc.swift
Sources/DatadogObjc/Tracer+objc.swift
Sources/DatadogObjc/TracerConfiguration+objc.swift
Sources/DatadogObjc/Tracing/Propagation/HTTPHeadersWriter+objc.swift
Tests/DatadogTests/Datadog/Core/Swizzling/MethodSwizzlerTests.swift
Tests/DatadogTests/DatadogObjc/DDTracerTests.swift

@objcMembers tries to expose all members; in case of failure, fails silently.
As we don't have tests calling the API from ObjC, we don't make sure `DatadogSDKObjc` is exposed to Obj-C
@objc doesn't compile in case of failure and gives errors
`public let OTFormatHTTPHeaders = "OTFormatHTTPHeaders"` is exposed as `OT.formatTextMap`

RUMM-917 Non-exposed ObjC public API is fixed

---

DatadogSDK.podspec
DatadogSDKAlamofireExtension.podspec
DatadogSDKObjc.podspec
DatadogSDKObjc.podspec.src
Sources/Datadog/Versioning.swift
Sources/DatadogExtensions/Alamofire/README.md
api-surface-objc

We need this alpha version for other internal projects until public release
After approval, `make ship` will be run
This new pod is being shipped with `DatadogSDK: 1.5.0-alpha1` and `Alamofire: 5.0` dependencies.

RUMM-917 Release version 1.5.0-alpha1

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/Scenarios/RUM/ManualInstrumentation/SendRUMFixture3ViewController.swift
Sources/Datadog/DDRUMMonitor.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewIdentity.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUMMonitor.swift
Sources/DatadogObjc/RUMMonitor+objc.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsHandlerTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewIdentityTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/DatadogObjc/DDRUMMonitorTests.swift
api-surface-objc
api-surface-swift

📦 This PR introduces two additional APIs for RUM Views manual instrumentation. Now it is possible to use `String` key to mark the view start and view end:
```swift
// New APIs:
Global.rum.startView(key: "view1", path: "NameOfTheView")
Global.rum.stopView(key: "view1")
```
This builds up an alternative for use cases where `UIViewController` cannot be referenced using existing APIs:
```swift
// Existing APIs
Global.rum.startView(viewController: self, path: "NameOfTheView")
Global.rum.stopView(viewController: self)
```
I introduced a single interface for any kind of RUM View reference:
```swift
internal protocol RUMViewIdentifiable {
func equals(_ otherIdentifiable: RUMViewIdentifiable) -> Bool
}
```
It's implemented by `UIViewController` and `String` types and can be extended any further in …

RUMM-974 Allow referencing RUM Views by String key

---

Sources/Datadog/Tracing/DDSpanContext.swift
Tests/DatadogTests/Datadog/Tracing/DDSpanContextTests.swift

Fixes #363 
Baggage items were not propagated to span's children
A great explanation can be found in #363 
Now `BaggageItems.get(key)` searches in `parent.baggageItems` recursively

RUMM-976 GH Issue #363

---

Sources/Datadog/RUM/DataModels/RUMDataModels.swift
api-surface-objc
api-surface-swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/Swift/SwiftTypeReader.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Output/Printing/SwiftPrinter.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Input/SwiftTypeReaderTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Output/SwiftPrinterTests.swift

📦 This PR updates the `rum-models-generator` to generate models with `public` (instead of `internal`) access level. This will let us expose those models in the public interface of the SDK.
In addition to replacing `internal` with `public`, this PR also updates `rum-models-generator's` mutability signature generation for nested types.
Before, nested properties were not mutable:
```swift
struct Foo {
struct Bar {
let bizz: String
var buzz: String // ⚠️ this can't be mutated as `bar` is immutable
}
let bar: Bar
}
```
Now, this is fixed:
```swift
struct Foo {
struct Bar {
let bizz: String
var buzz: String
}
var bar: Bar // 💫 fix, now `bar.buzz` can be mutated
}
```

RUMM-788 Prepare RUM models for data scrubbing API

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Feature.swift
Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/Core/Persistence/Writting/Processing/DataProcessor.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/Logging/LoggingFeature.swift
Sources/Datadog/RUM/RUMEvent/RUMEventEncoder.swift
Sources/Datadog/RUM/RUMFeature.swift
Sources/Datadog/RUM/Scrubbing/RUMEventsMapper.swift
Sources/Datadog/Tracing/TracingFeature.swift
Tests/DatadogBenchmarkTests/DataStorage/RUMStorageBenchmarkTests.swift
Tests/DatadogTests/Datadog/Core/FeatureTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Writting/ConsentAwareDataWriterTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Writting/Processing/DataProcessorTests.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift
Tests/DatadogTests/Datadog/Mocks/TracingFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMEvent/RUMConnectivityInfoProviderTests.swift
Tests/DatadogTests/Datadog/RUM/RUMEvent/RUMUserInfoProviderTests.swift
Tests/DatadogTests/Datadog/RUM/Scrubbing/RUMEventsMapperTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

🚚 This PR adds RUM events scrubbing feature with set of 4 new public APIs:
```swift
public func setRUMViewEventMapper(_ mapper: @escaping (RUMViewEvent) -> RUMViewEvent?)
public func setRUMResourceEventMapper(_ mapper: @escaping (RUMResourceEvent) -> RUMResourceEvent?)
public func setRUMActionEventMapper(_ mapper: @escaping (RUMActionEvent) -> RUMActionEvent?)
public func setRUMErrorEventMapper(_ mapper: @escaping (RUMErrorEvent) -> RUMErrorEvent?)
```
Each API allows the user to inspect and modify RUM events before they get send. Returning `nil` drops the event.
A basic interface of `EventMapper` is introduced:
```swift
internal protocol EventMapper {
func map<T: Encodable>(event: T) -> T?
}
```
and plugged into `DataProcessor's` pipeline, just before writing the event to the file.
It is …

RUMM-788 Add data scrubbing API

---

Sources/Datadog/DDRUMMonitor.swift
Sources/Datadog/RUM/AutoInstrumentation/Resources/URLSessionRUMResourcesHandler.swift
Sources/Datadog/RUM/DataModels/RUMDataModelsMapping.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Sources/Datadog/RUMMonitor.swift
Sources/DatadogObjc/RUMMonitor+objc.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Resources/URLSessionRUMResourcesHandlerTests.swift
Tests/DatadogTests/Datadog/RUM/DataModels/RUMDataModelsMappingTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/DatadogObjc/DDRUMMonitorTests.swift
api-surface-objc
api-surface-swift

Those methods are needed for internal usage
```swift
func addError(message: String,source: RUMErrorSource = .custom,stack: String? = nil,attributes: [AttributeKey: AttributeValue] = [:],file: StaticString? = #file,line: UInt? = #line)
func startResourceLoading(resourceKey: String,httpMethod: String,urlString: String,kind: RUMResourceKind,attributes: [AttributeKey: AttributeValue] = [:])
func stopResourceLoading(resourceKey: String,statusCode: Int?,kind: RUMResourceKind = .other,size: Int64? = nil,attributes: [AttributeKey: AttributeValue] = [:])
enum RUMResourceKind
```
```swift
func addError(message: String,source: DDRUMErrorSource,stack: String?,attributes: [String: Any])
func startResourceLoading(resourceKey: String,httpMethod: String,urlString: String,kind: …
```

RUMM-952 Missing RUM API added

---

Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUMMonitor.swift
Sources/Datadog/Utils/SwiftExtensions.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/Utils/SwiftExtensionsTests.swift

In some special cases, `RUMMonitor` should let the caller feed event time explicitly
We use `_dd.timestamp` special attribute for such cases.
`RUMMonitor` extracts and removes it from `attributes` and use it as `command.time`.
This attribute overwrites default `command.time: Date()` behavior.

RUMM-990 Special InternalTimestamp attribute is handled

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
Datadog/Example/Scenarios/RUM/RUMScenarios.swift
Datadog/Example/Scenarios/RUM/Scrubbing/RUMScrubbingScenario.storyboard
Datadog/Example/Scenarios/RUM/Scrubbing/RUMScrubbingViewController.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMScrubbingScenarioTests.swift

🧪 This PR adds `RUMScrubbingScenario` integration test for data scrubbing.
The `RUMScrubbingScenario` consists of a single view controller:
sending bunch of RUM events. Each event contains "sensitive" information in form of `"sensitive"` text, e.g.:
```swift
Global.rum.addError(message: "Error message (sensitive detail).", source: .source)
```
This information is later redacted using data scrubbing API, e.g:
```swift
configurationBuilder
.setRUMErrorEventMapper { errorEvent in
var errorEvent = errorEvent
errorEvent.error.message = redacted(errorEvent.error.message)
// ...
return errorEvent
}
func redacted(_ string: String) -> String {
return string.replacingOccurrences(of: "sensitive", with: "REDACTED")
}
```
The integration test retrieves events from Python server and asserts that …

RUMM-788 Add data scrubbing integration test

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/RUM/AutoInstrumentation/Views/UIKitHierarchyInspection/UIKitHierarchyInspector.swift
Sources/Datadog/RUM/Debugging/RUMDebugging.swift
Sources/Datadog/Utils/UIKitExtensions.swift
bitrise.yml
tools/lint/sources.swiftlint.yml

🔧 When compiling the SDK for some app extension types (e.g. Notification Service Extension), compiler error is issued:
> `'shared'` is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead
Solves #370, qualifies for `1.4.1` hotfix.
There is no [compiler control statement](https://docs.swift.org/swift-book/ReferenceManual/Statements.html#ID538) to exclude [`UIApplication.shared`](https://developer.apple.com/documentation/uikit/uiapplication/1622975-shared) usage in iOS app extension, so I used a known workaround (https://github.com/slackhq/PanModal/pull/81) of referencing it using key-path.
Convenient extension of `UIApplication.managedShared: UIApplication?` is created and swift-lint rule is added to enforce its usage. This required …

RUMM-989 Fix compiler error in Notification Service Extension

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Attributes/Attributes.swift
Sources/Datadog/Core/Attributes/AttributesSanitizer.swift
Sources/Datadog/Logging/Log/LogEncoder.swift
Sources/Datadog/Logging/Log/LogSanitizer.swift
Sources/Datadog/RUM/RUMEvent/RUMEventEncoder.swift
Sources/Datadog/RUM/RUMEvent/RUMEventSanitizer.swift
Sources/Datadog/Tracing/Span/SpanBuilder.swift
Sources/Datadog/Tracing/Span/SpanEncoder.swift
Sources/Datadog/Tracing/Span/SpanSanitizer.swift
Tests/DatadogBenchmarkTests/DataStorage/TracingStorageBenchmarkTests.swift
Tests/DatadogTests/Datadog/Logging/Log/LogSanitizerTests.swift
Tests/DatadogTests/Datadog/Mocks/TracingFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMEvent/RUMEventSanitizerTests.swift
Tests/DatadogTests/Datadog/Tracing/Span/SpanSanitizerTests.swift

📦 This PR adds `Span` and `RUMEvent` attributes sanitization as it exists for `Logs`. The same rules were applied, unified with `dd-sdk-android` (https://github.com/DataDog/dd-sdk-android/pull/427).
Similar to `LogSanitizer`, two new sanitizers are introduced:
* `SpanSanitizer`,
* `RUMEventSanitizer`.
All three share common `AttributesSanitizer` which applies equal rules to all attributes with dynamic count:
* `Span` tags,
* `Span` meta information coming from `UserInfo.extraInfo`,
* `RUMEvent<DM>` attributes,
* `RUMEvent<DM>` attributes coming from `UserInfo.extraInfo`,
* `RUMEvent<DM>` custom view timings.
Only two rules are shared:
* attribute key may contain up to 8 nested levels (`"one.two.(...).eight"`),
* there can be up to `128` attributes in total.

RUMM-908 Sanitize Span and RUM Event attributes

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMCommonAsserts.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMManualInstrumentationScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMModalViewsScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMNavigationControllerScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMTabBarControllerScenarioTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Matchers/RUMSessionMatcher.swift

This is the iOS counter-part of RUMM-787 / #430.
As a reminder, it sets the `view.is_active` attribute for RUM Views to let the frontend know when a View is still in progress.
In `dd-sdk-ios`, the `RUMViewScope` was already able to handle `RUMStartViewCommand` and `RUMStopViewCommand` and it was tracking some `isActiveView`. This change makes sure a `RUMViewEvent` gets a `View` with its `isActive` property's value matching `RUMViewScope.isActiveView`'s value.
This PR also changes the behaviour of `RUMViewScope.context` by checking `isActiveView` before setting/overwriting `RUMContext.active*` properties.
Finally, it updates existing unit and integration tests to assert on the `view.isActive` based on a given navigation path.
- ✅ Feature or bugfix MUST have appropriate tests (unit, …

RUMM-786 Support RUM Explorer's indicator for active views

---

Sources/Datadog/RUM/AutoInstrumentation/Resources/URLSessionRUMResourcesHandler.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUMMonitor.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/URLFiltering/FirstPartyURLsFilter.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/URLFiltering/InternalURLsFilter.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptor.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Resources/URLSessionRUMResourcesHandlerTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/URLFiltering/FirstPartyURLsFilterTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/URLFiltering/InternalURLsFilterTests.swift

This is the counter part of [`dd-sdk-android/pull/442`](https://github.com/DataDog/dd-sdk-android/pull/442).
Note that we only set a Provider in the events for first party hosts, any other case will get a `nil` / `unknown`. Also note that the provider name is not set.
It leverages the existing `URLSessionInterceptor` mechanism and the `URLSessionAutoInstrumentation` configuration. Upstream it relies on a `FirstPartyURLsFilter` to notify interceptions with a flag, the flag will be used downstream to mark commands. The commands will be eventually consumed by a `RUMResourceScope`.
A `RUMResourceScope` will then be able to instantiate a `Provider` for first party resources as part of the Resource/Error events that need to be sent.

RUMM-722 Set a Provider for first party Resources

---

Datadog/Example/Scenarios/RUM/RUMScenarios.swift
Datadog/Example/Scenarios/TrackingConsent/TrackingConsentScenarios.swift
Datadog/Example/Scenarios/URLSession/NSURLSessionAutoInstrumentation/ObjcSendFirstPartyRequestsViewController.m
Datadog/Example/Scenarios/URLSession/NSURLSessionAutoInstrumentation/ObjcSendThirdPartyRequestsViewController.m
Datadog/Example/Scenarios/URLSession/URLSessionAutoInstrumentation/SendFirstPartyRequestsViewController.swift
Datadog/Example/Scenarios/URLSession/URLSessionAutoInstrumentation/SendThirdPartyRequestsViewController.swift
Datadog/Example/Scenarios/URLSession/URLSessionScenarios.swift
Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegate.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptor.swift
Sources/Datadog/URLSessionAutoInstrumentation/URLSessionSwizzler.swift
Sources/DatadogObjc/DatadogConfiguration+objc.swift
Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/Mocks/URLSessionAutoInstrumentationMocks.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegateTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptorTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/URLSessionSwizzlerTests.swift
Tests/DatadogTests/Helpers/XCTestCase.swift
api-surface-objc
api-surface-swift

Auto-instrumented `firstPartyHosts` were set at global level via `DatadogConfiguration`
Every `URLSession` instance had the same set of `firstPartyHosts`
Now this set can be customized per instance via `DDURLSessionDelegate`
```swift
let delegateWithCustomHosts = DDURLSessionDelegate(firstPartyHosts: ["foo.com"])
let session = URLSession(delegate: delegateWithCustomHosts)
```
`session` tracks requests made to host `foo.com` regardless of `DatadogConfiguration`
`URLSessionInterceptor` checks if `session.delegate` has its own URL filter;
1. if so, this filter is used
2. otherwise, default URL filter of `URLSessionInterceptor` is used
Next PR will bring its Objc counterpart once Swift one is approved

RUMM-954 DDURLSessionDelegate takes firstPartyHosts in init

---

Sources/Datadog/DatadogConfiguration.swift
Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift

GovCloud endpoints are moved 
* to `{feature_name}.browser-intake-ddog-gov.com`
* from `mobile-http-intake.{feature_name}.ddog-gov.com`

RUMM-1020 Govcloud endpoints changed

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/DatadogObjc/RUM/RUMDataModels+objc.swift
tools/rum-models-generator/Package.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/ObjcInterop/ObjcInteropType.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/ObjcInterop/ObjcInteropTypeReader.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/Swift/SwiftType.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Output/Printing/ObjcInteropPrinter.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Output/Printing/Printer.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Output/Printing/SwiftPrinter.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/RUMModelsGenerator.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Utilities.swift
tools/rum-models-generator/Sources/rum-models-generator/main.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Output/ObjcInteropPrinterTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/RUMModelsGeneratorTests.swift

📦 This PR updates the `rum-models-generator` tool to generate `@objc` RUM data models. This is required to further expose scrubbing API in `DatadogObjc` as it was done for Swift (#367). 
I leveraged the existing architecture of `rum-models-generator`: 
* `read → transform → print`
by implementing another `Printer`:
* `read → transform → SwiftPrinter`
* `read → transform → ObjcInteropPrinter`
The `SwiftType` schema generated and transformed for Swift code generation is now used by `ObjcInteropReader` to generate `ObjcInteropType` schema. The schema is later passed to the `ObjcInteropPrinter` for printing the actual code.
`@objc` interoperability is done by wrapping Swift `structs` in `@objc` classes and exposing Swift `enums` as `@objc enum` .
Simple example can be illustrated as:
```swift …
```

RUMM-987 Prepare code generation for RUM @objc models

---

Sources/DatadogObjc/DatadogConfiguration+objc.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift

📦 Based on RUM `@objc` models generated in #382, this PR adds Scrubbing APIs to `DatadogObjc`:
```swift
// in DDConfigurationBuilder:
@objc
public func setRUMViewEventMapper(_ mapper: @escaping (DDRUMViewEvent) -> DDRUMViewEvent?)
@objc
public func setRUMResourceEventMapper(_ mapper: @escaping (DDRUMResourceEvent) -> DDRUMResourceEvent?)
@objc
public func setRUMActionEventMapper(_ mapper: @escaping (DDRUMActionEvent) -> DDRUMActionEvent?)
@objc
public func setRUMErrorEventMapper(_ mapper: @escaping (DDRUMErrorEvent) -> DDRUMErrorEvent?)
```
As usual, `DatadogObjc` APIs bridge their calls to `Datadog` (Swift).
I also made sure those APIs are properly exposed, compile and look "nice" in Objective-c. Here, an example of redacting the `resource.url` for `POST` resources and dropping all other …

RUMM-987 Add scrubbing API to `DatadogObjc`

---

Sources/DatadogObjc/DatadogConfiguration+objc.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift
Tests/DatadogTests/DatadogObjc/DDDatadogTests.swift

`track(firstPartyHosts:)` is deprecated in favor of `trackURLSession(firstPartyHosts:)` in Swift API
The same API is used in ObjC now

RUMM-954 trackURLSession(:) is introduced in ObjC API

---

Sources/Datadog/Core/System/LaunchTimeProvider.swift
Sources/_Datadog_Private/ObjcAppLaunchHandler.m
Sources/_Datadog_Private/include/ObjcAppLaunchHandler.h

`ObjcAppLaunchHandler` is the existing mechanism that observes early steps of the [App Launch sequence](https://developer.apple.com/documentation/uikit/app_and_environment/responding_to_the_launch_of_your_app/about_the_app_launch_sequence) to provide a Launch Time for further reporting by `RUMViewScope` into `RUMActionEvent.Action` for the `start_application` event.
This currently relies on Objective-C's runtime initialisation which calls classes' `+(void)load` method as soon as they are loaded into the runtime. This happens before the `UIApplication.sharedInstance` is instantiated, and this provides an early point in time regarding the launch sequence.
The limitations are that the "earliness" is not guaranteed and depends on many factors, so it might lead to not accounting for some …

RUMM-1026 Use sysctl to gather a more accurate App Launch Time

---

Sources/Datadog/OpenTracing/OTSpan.swift
Sources/Datadog/Tracing/DDSpan.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/Tracing/DDSpanTests.swift
api-surface-swift

Currently as part of our OpenTracing integration, we provide log fields that can be set on a Span to attach an error to that Span. It's usable but we seek to provide a more convenient way to allow passing some an `Error` conforming type, an `NSError` object or some message and details to log an error using the proper log fields as described by OpenTracing.
In this PR, we add 2 convenience APIs on `OTSpan` (in Swift) to facilitate attaching an error onto the given `OTSpan` using the right field keys.
This PR introduces an extension on `OTSpan` and piggyback on the existing `log()` as well as `OTLogFields` to properly attach the provided information. It uses `DDError` to extract information out of `NSError` or any object conforming to the `Error` protocol.
It populates the …

RUMM-647 Add a Span.setError convenience API for Swift on top of Tracing

---

Sources/DatadogObjc/OpenTracing/OTSpan+objc.swift
Sources/DatadogObjc/Tracing/DDSpan+objc.swift
Tests/DatadogTests/DatadogObjc/DDTracerTests.swift
api-surface-objc

This is the objc counter part of #388 where we introduced `OTSpan.setError` convenience API.
The `DatadogObjc` `@objc protocol` and `class` merely proxy the calls that go to `Datadog.OTSpan` eventually.
Note that this PR also updates `api-surface-objc` with many changes from previous PRs so it's a bit noisy.

RUMM-647  Add the Span.setError API for Objc

---

Tests/DatadogTests/Datadog/RUM/RUMEvent/RUMEventSanitizerTests.swift

`testWhenNumberOfAttributesExceedsLimit_itDropsExtraOnes` unit test case sometimes gives false negatives
False negative case example:
`sanitized.customViewTimings.count == 49`
`sanitized.userInfoAttributes.count == 58`
We want to make sure if removals are done in the right order, this is unrelated to `count` comparisons.
Now we compute the expected item counts and `assertEqual` with them.

RUMM-908 Fix: Unit test

---

Cartfile
Cartfile.resolved
Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCrashReporting.xcscheme
Datadog/Example/ExampleAppDelegate.swift
Datadog/TargetSupport/DatadogCrashReporting/DatadogCrashReporting.h
Datadog/TargetSupport/DatadogCrashReporting/Info.plist
Datadog/TargetSupport/DatadogCrashReportingTests/DatadogCrashReportingTests.xcconfig
Datadog/TargetSupport/DatadogCrashReportingTests/Info.plist
LICENSE-3rdparty.csv
Package.swift
Sources/DatadogCrashReporting/DDCrashReportingPlugin.swift
Tests/DatadogCrashReportingTests/DatadogCrashReportingTests.swift
bitrise.yml
dependency-manager-tests/carthage/CTProject.xcodeproj/project.pbxproj
dependency-manager-tests/carthage/CTProject/ViewController.swift
dependency-manager-tests/carthage/Makefile
dependency-manager-tests/spm/SPMProject.xcodeproj.src/project.pbxproj
dependency-manager-tests/spm/SPMProject/ViewController.swift

📦 This PR starts the work no crash reporting feature by introducing `DatadogCrashReporting` module. Both SPM and Carthage support is added.
Beside the setup, I also added basic invocation of `PLCrashReporter's` code to make sure everything runs everywhere with no runtime linkage issue.
Many configuration changes of different size:
* added `DatadogCrashReporting` and `DatadogCrashReportingTests` targets,
* linked `PLCrashReporter` through `Cartfile` and `Package.swift`,
* updated `LICENSE-3rdparty.csv`,
* configured folders structure to be compatible with linter setup,
* configured `.xcconfig` for `DatadogCrashReporting` processing,
* configured `.xcconfig` for `dd-swift-testing` instrumentation and code signing,
* configured tests schema with our standard setup (TSAN, code coverage, …

RUMM-956 Create `DatadogCrashReporting` module

---

Sources/Datadog/Core/Upload/DataUploadConditions.swift
Sources/Datadog/Core/Upload/DataUploadWorker.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploadConditionsTests.swift

This is a follow-up to RUMS-132 where some troubleshooting based on the console logs was a bit hindered by the lack of details at to why upload conditions were not met.
In this PR, we expose the underlying blockers to the upload conditions. It can be the battery state/level, low power mode, the network reachability.
The following details may appear in the console:
`🐶 → 19:00:10.949 [INFO] 💡 (logging) No upload. Batch to upload: NOT CHECKED, System conditions: ❌ → 🔋 Battery: unplugged 10%; 🔌 Low Power Mode: on; 📡 Reachability: no`
In the above example all three blockers appear, but it can be any combination.
The internal `DataUploadConditions.canPerformUpload` API is changed to return an enum `Report` that is either `.go` or `.noGo`. When `Report` is `.noGo` it will come with a list of …

RUMM-892 Provide more details when upload conditions are not met in console logs

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
Datadog/Example/AppConfiguration.swift
Datadog/Example/Scenarios/CrashReporting/CrashReporting/CrashReportingScenario.storyboard
Datadog/Example/Scenarios/CrashReporting/CrashReporting/CrashReportingViewController.swift
Datadog/Example/Scenarios/CrashReporting/CrashReportingScenarios.swift
Datadog/Example/Utils/PersistenceHelper.swift

📦 This PR adds single test scenario in `Example` app to play with the Crash Reporting feature. Later (in `RUMM-960`) it will be used to send the crash report to Python server and run assertions in integration tests.
The `CrashReportingCollectOrSendScenario` scenario consists of a single View Controller with conditionally displayed UI:
If the scenario is started with no crash report file on disc, it displays the _"Crash The App"_ button. Once pressed, it issues a `fatalError()` and terminates the process.
When a crash report file is found on startup, it displays the _"Sending crash report..."_ label, meaning that it found the crash report and it expects the SDK to send it.
Once the actual `RUMError` upload is implemented in `RUMM-960`, it will be sending real data to Datadog.
To test this …

RUMM-957 Add `Example` app scenario for testing Crash Reporting feature

---

tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/JSON/JSONSchema.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/JSON/JSONSchemaToJSONTypeTransformer.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/JSON/JSONType.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/ObjcInterop/ObjcInteropType.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/ObjcInterop/SwiftToObjcInteropTypeTransformer.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/Swift/JSONToSwiftTypeTransformer.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/Swift/SwiftType.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Output/Printing/BasePrinter.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Output/Printing/ObjcInteropPrinter.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Output/Printing/SwiftPrinter.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/RUM/RUMSwiftTypeTransformer.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Input/JSONSchemaToJSONTypeTransformerTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Input/JSONToSwiftTypeTransformerTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Output/ObjcInteropPrinterTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Output/SwiftPrinterTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/RUM/RUMSwiftTypeTransformerTests.swift

We ultimately want to add support for custom timings. This was previously introduced to the schema in [rum-events-format #25](https://github.com/DataDog/rum-events-format/pull/25) relying on [JSON Schema's `additionalProperty`](https://json-schema.org/draft/2019-09/json-schema-core.html#additionalProperties).
Our Swift/Objc pipeline that generates models from a schema doesn't know how to handle `additionalProperties` at this point. To prevent from mis-generating the model for custom timings [we previously had to put a dedicated filter](https://github.com/DataDog/dd-sdk-ios/pull/393/files#diff-dd3caa4e6db960eecd95024f6d7df904948b8f53b1026c00dd19a9627317ac3e) until we add the support for `additionalProperties`.
In this PR we add the plumbing needed for a basic support of …

RUMM-1000 Add support for additional properties to the models generation pipeline

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/Scenarios/CrashReporting/CrashReportingScenarios.swift
Sources/Datadog/CrashReporting/CrashContext/CrashContext.swift
Sources/Datadog/CrashReporting/CrashContext/CrashContextProvider.swift
Sources/Datadog/CrashReporting/CrashReporter.swift
Sources/Datadog/CrashReporting/CrashReportingFeature.swift
Sources/Datadog/CrashReporting/DDCrashReportingPluginType.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingIntegration.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithLoggingIntegration.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift
Sources/Datadog/FeaturesIntegration/RUMWithCrashContextIntegration.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/DatadogCrashReporting/DDCrashReportingPlugin.swift
Sources/DatadogCrashReporting/PLCrashReporterIntegration/PLCrashReporterIntegration.swift
Sources/DatadogCrashReporting/ThirdPartyCrashReporter.swift
Tests/DatadogCrashReportingTests/DDCrashReportingPluginTests.swift
Tests/DatadogCrashReportingTests/Mocks.swift
Tests/DatadogTests/Datadog/Core/FeatureTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Writting/ConsentAwareDataWriterTests.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashContext/CrashContextProviderTests.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashReporterTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMWithCrashContextIntegrationTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/CrashReportingFeatureMocks.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift

🚚 This PR implements injection of a last `RUMViewEvent` and current `TrackingConsent` values to crash reporter, so they can be retrieved when the app restarts after crash.
Those values are necessary for:
* considering if the crash report can be send regarding the user tracking policy,
* sending the crash report as a `RUMErrorEvent` associated with the RUM session identifier from the crashed session.
`CrashContext` structure was introduced for bundling SDK state values. For now it has only two properties:
```swift
struct CrashContext: Codable {
/// Last value of `TrackingConsent`.
var lastTrackingConsent: TrackingConsent
/// Last RUM View event.
var lastRUMViewEvent: RUMViewEvent?
}
```
More will be added in `RUMM-1049` (including User Info, Network Info and Carrier Info).
The …

RUMM-957 Inject application context to crash reports

---

Sources/Datadog/Core/Utils/JSONEncoder.swift
Sources/Datadog/RUM/DataModels/RUMDataModels.swift
Sources/Datadog/RUM/RUMEvent/RUMEventBuilder.swift
Sources/Datadog/RUM/RUMEvent/RUMEventEncoder.swift
Sources/Datadog/RUM/RUMEvent/RUMEventSanitizer.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/DatadogObjc/RUM/RUMDataModels+objc.swift
Tests/DatadogBenchmarkTests/DataStorage/RUMStorageBenchmarkTests.swift
Tests/DatadogTests/Datadog/Core/Utils/JSONEncoderTests.swift
Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMEvent/RUMEventSanitizerTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUM/Scrubbing/RUMEventsMapperTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/RUM/RUMSwiftTypeTransformer.swift

[The JSON Schema for RUM Event models "custom timings" of a view](https://github.com/DataDog/rum-events-format/blob/master/schemas/view-schema.json#L108-L117) using the [`additionalProperties` keyword of the JSON Schema spec](https://json-schema.org/draft/2019-09/json-schema-core.html#additionalProperties).
This keyword was not supported until #399, and prior to that the SDK had to use a few workarounds to store the custom timings in memory until the eventual encoding into JSON.
In this PR we leverage #399 to remove the workarounds and directly encode `customTimings` from `View` models.
In this PR we:
- Remove the filter on `customTimings`423f095e
- Update the data models by running the codegen tool 8b70eabf
- Remove the few workarounds relying on RUMEvent and impact JSONDecoder d829781f

RUMM-1000 Use View.customTimings from actual schema instead of RUMEvent

---

Makefile

Update dd-sdk-testing-swift to version 0.6.0
Updated version number in Makefile

Update to dd-sdk-testing-swift version 0.6.0

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Feature.swift
Sources/Datadog/Core/Persistence/Writting/ArbitraryDataWriter.swift
Sources/Datadog/Core/Persistence/Writting/ConsentAwareDataWriter.swift
Sources/Datadog/Core/Persistence/Writting/Processing/DataProcessor.swift
Sources/Datadog/CrashReporting/CrashReporter.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingIntegration.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithLoggingIntegration.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift
Tests/DatadogTests/Datadog/Core/FeatureTests.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashReporterTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegrationTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMIntegrationsTests.swift
Tests/DatadogTests/Datadog/Mocks/CrashReportingFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/DataUploadWorkerMock.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/TracingFeatureMocks.swift

🚚 This PR sends collected crash reports as RUM Errors. 
When the app restarts after crash, we load the crash report, read its associated context and then:
* if the crash report was collected with tracking consent `.granted`,
* and the crash report was collected with RUM feature enabled,
* then the crash report is send as `RUMError` and it gets linked to the RUM Session which was interrupted.
Additionally, the `crash.count` gets updated on the last RUM View of the interrupted session.
This mostly required adding the implementation in `CrashReportingWithRUMIntegration's`:
```swift
func send(crashReport: DDCrashReport, with crashContext: CrashContext)
```
As Crash Reporting does its own consideration of `TrackingConsent`, to bypass the `ConsentAwareDataWriter`, I introduced additional …

RUMM-960 Send crash report as RUM Error

---

Package.swift

Datadog cannot be added to a Framework via SPM due to the `dynamic` property being setting in `Package.swift`
When adding Datadog using SPM as a package to a framework, the `type: .dynamic` property causes Xcode to insist on embedding the Datadog inside the framework. The Embed Framework step is automatically created and removing, causes Datadog to be removed from the project. 
Note that with LaunchDarkly, the package only appears in `Link Binary with Libraries` as desired. 
Debug builds of the project will build and run fine. However, archiving and uploading to TestFlight will succeed but the archive produced is not valid and will crash on launch as the Datadog library is missing
```Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception …
```

Swift Package Manager - Add static library variants to allow use inside frameworks

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/Scenarios/CrashReporting/CrashReportingScenarios.swift
Sources/Datadog/CrashReporting/CrashContext/CrashContext.swift
Sources/Datadog/CrashReporting/CrashContext/CrashContextProvider.swift
Sources/Datadog/CrashReporting/CrashReporter.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift
Sources/Datadog/FeaturesIntegration/RUMWithCrashContextIntegration.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashContext/CrashContextProviderTests.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashContext/CrashContextTests.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashReporterTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegrationTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMWithCrashContextIntegrationTests.swift
Tests/DatadogTests/Datadog/Mocks/CrashReportingFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

🚚 This PR makes custom RUM attributes and User Info attributes appear in RUM crash reports.
Given that:
```swift
Datadog.setUserInfo(
id: ..., 
name: ..., 
email: ..., 
extraInfo: ["key-extraUserInfo": "value-extraUserInfo"]
)
Global.rum.startView(
viewController: self, 
attributes: ["custom-attribute": "This attribute will be attached to crash report."]
)
```
All attributes will appear in RUM Error along with the crash report:
Instead of injecting the `RUMViewEvent` as the `lastRUMViewEvent` to the crash reporter, now we inject its entire envelope: `RUMView<RUMViewEvent>`. This envelope already contains `attributes` and `userInfoAttributes`.
The only challenging part was to implement deserialisation for `[String: Encodable]` in a way that ensures no information is lost. This is done by …

RUMM-1070 Send custom RUM attributes in crash reports

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/Scenarios/CrashReporting/CrashReporting/CrashReportingObjcHelpers.h
Datadog/Example/Scenarios/CrashReporting/CrashReporting/CrashReportingObjcHelpers.m
Datadog/Example/Scenarios/CrashReporting/CrashReporting/CrashReportingScenario.storyboard
Datadog/Example/Scenarios/CrashReporting/CrashReporting/CrashReportingViewController.swift
Datadog/Example/Scenarios/CrashReporting/CrashReportingScenarios.swift
Datadog/TargetSupport/Example/Example-Bridging-Header.h
Sources/Datadog/CrashReporting/DDCrashReportingPluginType.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithLoggingIntegration.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift
Sources/DatadogCrashReporting/PLCrashReporterIntegration/PLCrashReportFormatter.swift
Sources/DatadogCrashReporting/PLCrashReporterIntegration/PLCrashReporterIntegration.swift
Tests/DatadogCrashReportingTests/Mocks.swift
Tests/DatadogCrashReportingTests/PLCrashReporterIntegration/PLCrashReportFormatterTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegrationTests.swift
Tests/DatadogTests/Datadog/Mocks/CrashReportingFeatureMocks.swift

📦 This PR aims at improving `error.type` and `error.message` for Crash Reports by providing additional troubleshooting information for devs.
I've spent most of my time researching possible improvements and considering when and where they can be applied. To examine multiple variants, I updated the Crash Reporting scenario in the `Example` app with new cases:
After all, this resultant PR improves only the case where the crash originates from unhandled Objective-C exception. In such scenario, the `PLCrashReporter` records the exception info and provides it on the `PLCrashReport`, so we can consume it and pass to RUM Error.
Tapping above buttons bottom-up results with following `error.type` and `error.message` being sent:
This PR also disables on-device symbolication of crash reports. …

RUMM-1053 Improve the `error.message` for Crash Reports

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
Datadog/Example/Scenarios/RUM/RUMScenarios.swift
Datadog/Example/Scenarios/TrackingConsent/TrackingConsentScenarios.swift
Sources/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsPredicate.swift
Sources/Datadog/Utils/UIKitExtensions.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMResourcesScenarioTests.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsPredicateTests.swift
Tests/DatadogTests/Datadog/Utils/UIKitExtensionsTests.swift
Tests/DatadogTests/Helpers/CustomObjcViewController.h
Tests/DatadogTests/Helpers/CustomObjcViewController.m

🐛 When RUM Views auto instrumentation was enabled, no `UIViewController` defined in `Objc` was tracked. No matter if the SDK was configured in Objc:
```objc
[configuration trackUIKitRUMViews];
```
or swift:
```swift
.trackUIKitRUMViews()
```
The problem was caused by the filtering logic done in `DefaultUIKitRUMViewsPredicate`:
```swift
public func rumView(for viewController: UIViewController) -> RUMView? {
let canonicalClassName = NSStringFromClass(type(of: viewController))
let isCustomClass = canonicalClassName.contains(".") // custom class contains module prefix
if isCustomClass {
// ... capture the view
} else {
return nil // ignore the view
}
}
```
`isCustomClass` was meant to indicate if the `viewController` is a custom VC provided by the user app (`true`) or is a standard VC coming …

RUMM-1097 Fix `DefaultUIKitRUMViewsPredicate` for Objc view controllers

---

Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/RUM/Scrubbing/RUMEventsMapper.swift
Sources/DatadogObjc/DatadogConfiguration+objc.swift
Tests/DatadogTests/Datadog/RUM/Scrubbing/RUMEventsMapperTests.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift
api-surface-objc
api-surface-swift

My understanding is that the view event opens a parent-child relationship with the subsequent Error/Resource/Action events, and dropping a view event would cause "leaks" of Error/Resource/Action events.
Thus a solution is to forbid dropping view events while keeping the ability to redact their properties and drop "children" events.
In this PR we change the `RUMViewEventMapper` API to statically prevent from dropping `RUMViewEvent` by requiring a non-optional return type.
As this is statically enforced, we also remove a few checks in existing test cases as they would not compile nor make sense anymore.

RUMM-1077 Prevent discarding RUM View events

---

Sources/DatadogObjc/Tracing/Propagation/HTTPHeadersWriter+objc.swift
Tests/DatadogTests/DatadogObjc/DDTracerTests.swift

Create `tracePropagationHTTPHeaders` property exposed to ObjC in `DDHTTPHeadersWriter`
As per iOS Trace Collection, users of the SDK may want to manually propagate traces, rather than relying on interceptors provided by the SDK.
Trace propagation HTTP headers are not accessible via `DDHTTPHeadersWriter`, the Objective-C variant/facade class to `HTTPHeadersWriter`.
A `DDHTTPHeadersWriter`'s underlying `HTTPHeadersWriter.tracePropagationHTTPHeaders` should be accessible through a public property exposed to Objective-C.
Resolves #420. 
Create `tracePropagationHTTPHeaders` property exposed to ObjC in `DDHTTPHeadersWriter`

Make trace propagation HTTP headers available to ObjC

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Attributes/UserInfoProvider.swift
Sources/Datadog/Core/Persistence/Privacy/ConsentProvider.swift
Sources/Datadog/Core/Persistence/Writting/ConsentAwareDataWriter.swift
Sources/Datadog/Core/System/CarrierInfoProvider.swift
Sources/Datadog/Core/System/NetworkConnectionInfoProvider.swift
Sources/Datadog/Core/Utils/ValuePublisher.swift
Sources/Datadog/CrashReporting/CrashContext/CrashContext.swift
Sources/Datadog/CrashReporting/CrashContext/CrashContextProvider.swift
Sources/Datadog/CrashReporting/CrashReporter.swift
Sources/Datadog/CrashReporting/CrashReportingFeature.swift
Sources/Datadog/FeaturesIntegration/RUMWithCrashContextIntegration.swift
Tests/DatadogTests/Datadog/Core/FeatureTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Privacy/ConsentProviderTests.swift
Tests/DatadogTests/Datadog/Core/System/CarrierInfoProviderTests.swift
Tests/DatadogTests/Datadog/Core/System/NetworkConnectionInfoProviderTests.swift
Tests/DatadogTests/Datadog/Core/Utils/ValuePublisherTests.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashContext/CrashContextProviderTests.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashContext/CrashContextTests.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashReporterTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMWithCrashContextIntegrationTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/CrashReportingFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Helpers/XCTestCase.swift

🚛 This PR updates the crash context with last `UserInfo`, `NetworkConnectionInfo` and `CarrierInfo` values. Later (in `RUMM-1050`) it will be possible to read those values and associate to the `Log` containing the crash report.
There are 5 pieces of information injected to the `CrashContext` and 4 of those already had a related `*Provider`:
* last `TrackingConsent` → managed through `ConsentProvider`,
* last `RUMViewEvent`,
* last `UserInfo` → managed through `UserInfoProvider`,
* last `NetworkConnectionInfo` → managed through `NetworkConnectionInfoProvider`,
* last `CarrierInfo` → managed through `CarrierInfoProvider`.
This PRs updates those providers to work in publish / subscribe model - whenever a new value is available, all subscribed observers are notified on its change.
This PR …

RUMM-1049 Inject user, network and carrier info to Crash Reports

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
Datadog/Example/Scenarios/CrashReporting/CrashReporting/CrashReportingViewController.swift
Datadog/Example/Scenarios/CrashReporting/CrashReportingScenarios.swift
Sources/Datadog/Core/Attributes/UserInfoProvider.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithLoggingIntegration.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift
Sources/Datadog/Logger.swift
Sources/Datadog/Logging/Log/LogEncoder.swift
Sources/Datadog/Utils/InternalLoggers.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithLoggingIntegrationTests.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift

🚚 This PR sends collected crash reports as Logs. 
When the app restarts after crash, we load the crash report, read its associated context and then:
* if the Logging feature is enabled,
* and the RUM feature is disabled,
* and the crash report was collected with tracking consent `.granted`,
* then the crash report is send as `Log` with severity set to `EMERGENCY` (as we do in `dd-sdk-android`).
Example:
Everything was prepared in prior #422 and #427. This PR only adds the implementation in `CrashReportingWithLoggingIntegration` as it was previously done for `CrashReportingWithRUMIntegration`.
This PR also adds separate scenario in `Example` app, so now we can test integration with RUM and Logging separately:

RUMM-1050 Send crash report as Log

---

Sources/Datadog/Tracing/DDNoOps.swift

`OTTracer` protocol extension calls `startRootSpan` recursively by hoping the concrete type implements it
`NoOpTracer` didn't implement it and caused infinite loop/crash
`NoOpTracer` implements `startRootSpan` now

RUMM-701 NoOpTracer crash fix

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogIntegrationTests.xcscheme
Datadog/Example/Scenarios/CrashReporting/CrashReportingScenarios.swift
Datadog/TargetSupport/DatadogBenchmarkTests/DatadogBenchmarkTests.xcconfig
Datadog/TargetSupport/DatadogIntegrationTests/DatadogCrashReportingIntegrationTests.xctestplan
Datadog/TargetSupport/DatadogIntegrationTests/DatadogIntegrationTests.xcconfig
Datadog/TargetSupport/DatadogIntegrationTests/DatadogIntegrationTests.xctestplan
Datadog/TargetSupport/DatadogTests/DatadogTests.xcconfig
Datadog/TargetSupport/Example/Example.xcconfig
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift
Tests/DatadogIntegrationTests/Scenarios/CrashReporting/CrashReportingWithLoggingScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/CrashReporting/CrashReportingWithRUMScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMCommonAsserts.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMManualInstrumentationScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMModalViewsScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMNavigationControllerScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMResourcesScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMScrubbingScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMTabBarControllerScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMTapActionScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/TrackingConsent/TrackingConsentScenarioTests.swift
Tests/DatadogIntegrationTests/UITestsHelpers.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegrationTests.swift
Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift
Tests/DatadogTests/Matchers/LogMatcher.swift
bitrise.yml

🧪 This PR adds two integration tests for Crash Reporting feature. Both start with the same base scenario:
* _"launch the `Example` app → crash by tapping `fatalError()` button → launch the app again → ..."_
and differ by the assertion:
* _"... → assert that `RUMError` and `RUMView` events are sent if RUM is enabled"_,
* _"... → assert that `Log` is sent if RUM is disabled"_.
Two separate UI test cases are added. They use existing: `CrashReportingCollectOrSendWithLoggingScenario` and `CrashReportingCollectOrSendWithRUMScenario`.
To run Crash Reporting integration tests locally (from Xcode), debugger must be not attached. Otherwise, it captures the crash and interrupts the app processes.
To make it not disturbing for local test runs, I separated Crash Reporting tests from integration tests …

RUMM-1071 Add integration tests for Crash Reporting

---

Datadog/Datadog.xcodeproj/project.pbxproj
Makefile
dependency-manager-tests/carthage/CTProject.xcodeproj/project.pbxproj
dependency-manager-tests/carthage/CTProject/ViewController.swift
dependency-manager-tests/carthage/Makefile
dependency-manager-tests/carthage/tmp.xcconfig
tools/license/check-license.sh

The main thing of `carthage` is building projects for every possible arch-platform so that they don't need to be rebuilt when the developer changes the target arch-platform.
It was achieving this by `lipo`ing `BuildProducts` for different arch-platforms and giving one single `.framework` containing multiple slices.
This model stopped working as `arm64-simulator` arch-platform came along with Apple Silicon; it duplicated `arm64-ios` and `lipo` doesn't merge duplicate slices.
Apple introduced `XCFramework`s to solve this problem: this format can contain multiple `.framework`s for different arch-platforms. 
```
Example.xcframework:
- ios-arm64_armv7/Example.framework
- ios-arm64_i386_x86_64-simulator/Example.framework
- macos-arm64_x86_64/Example.framework
- tvos-arm64/Example.framework
- …
```

RUMM-1145 Carthage XCFrameworks support

---

CHANGELOG.md
Datadog/Datadog.xcodeproj/project.pbxproj
DatadogSDK.podspec
DatadogSDKAlamofireExtension.podspec
DatadogSDKObjc.podspec
Makefile
Sources/Datadog/Versioning.swift
dependency-manager-tests/carthage/CTProject.xcodeproj/project.pbxproj
dependency-manager-tests/carthage/CTProject/ViewController.swift
dependency-manager-tests/carthage/Makefile
dependency-manager-tests/carthage/tmp.xcconfig
tools/license/check-license.sh

`1.5.0` release had compilation issues with `carthage --use-xcframework` command.
`1.5.1` hotfix release should address this problem.
It cherry-picks only https://github.com/DataDog/dd-sdk-ios/pull/439 on top of `1.5.0` release.

Hotfix release 1.5.1

---

Cartfile
Cartfile.resolved
DatadogSDK.podspec
Package.swift
xcconfigs/Base.xcconfig

[`Kronos`](https://github.com/MobileNativeFoundation/Kronos) version is updated to `4.2`
`Base.xcconfig EXCLUDED_ARCHS` is also removed
With this PR, `dd-sdk-ios` can be built for `arm64-simulator` too.
That is the last obstacle before shipping proper `xcframework` binaries.

RUMM-1087 Kronos update to 4.2

---

Sources/DatadogObjc/Datadog+objc.swift
Tests/DatadogTests/DatadogObjc/DDDatadogTests.swift
api-surface-objc

🚚 This PR makes the `extraInfo` attribute visible for Objective-C in `Datadog.setUserInfo()` API.
Added missing attribute + tests.

RUMM-1197 Expose user `extraInfo` to Objc

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/TargetSupport/DatadogCrashReporting/DatadogCrashReporting.xcconfig
Makefile
Tests/DatadogBenchmarkTests/BenchmarkTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMManualInstrumentationScenarioTests.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Actions/UIApplicationSwizzlerTests.swift
dependency-manager-tests/carthage/CTProject.xcodeproj/project.pbxproj
xcconfigs/Base.xcconfig

⚙️ This PR updates the `DatadogCrashReporting` configuration so it builds well with `carthage --use-xcframeworks`.
Ideally, `carthage --use-xcframeworks` should download pre-built xcframework of [microsoft/plcrashreporter](https://github.com/microsoft/plcrashreporter), which includes `ios-arm64_i386_x86_64-simulator` slice for iOS Simulator. 
Unfortunately, pre-built xcframeworks are not yet supported in carthage (https://github.com/Carthage/Carthage/pull/3123) and it falls back to building `CrashReporter.xcframework` from source. In this case, the `arm64` architecture is not produced for `-simulator` slice (this is expected from `PLCR` [`1.8.0` release notes](https://github.com/microsoft/plcrashreporter/releases/tag/1.8.0)).
This PR updates the `DatadogCrashReporting` target to produce …

RUMM-1199 Fix `carthage --use-xcframeworks` build for DatadogCrashReporting

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/System/AppStateListener.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/Tracer.swift
Sources/Datadog/Tracing/AutoInstrumentation/URLSessionTracingHandler.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/TaskInterception.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptor.swift
Sources/Datadog/URLSessionAutoInstrumentation/URLSessionAutoInstrumentation.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Tracing/Autoinstrumentation/URLSessionTracingHandlerTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegateTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/AppStateListenerTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptorTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/URLSessionAutoInstrumentationTests.swift

We are seeing spans in APM that have duration longer than hours, even days.
We realized that those are caused by the app going background and staying there for long time.
The span finishes only once the app goes back to foreground and this can result in spans longer than hours.
The problem above happens since the app gets suspended/paused at background and picks up where it left off when it comes back to foreground.
We cannot change this behavior from our SDK, therefore we decided to provide more information so that our users can tell when their network requests take too long from when their apps stay at background for too long.
We will add `foreground_duration: TimeInterval` and `isBackground: Bool` tags/metrics to `Span`s.
1. `TaskInterception` will be responsible for adding these to …

RUMM-1064 AppStateListener added

---

Sources/Datadog/Datadog.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
tools/lint/sources.swiftlint.yml
tools/lint/tests.swiftlint.yml

🐞 This PR updates `swiftlint` configuration to `0.43.x`.
According to [`0.43.x` release notes](https://github.com/realm/SwiftLint/releases/tag/0.43.0), all paths must be relative to the `.yml` location, not to the `swiftlint` invocation dir.

RUMM-1222 Update to swiftlint `0.43.x`

---

Package.swift
dependency-manager-tests/spm/Makefile
dependency-manager-tests/spm/README.md
dependency-manager-tests/spm/SPMProject.xcodeproj.src/project.pbxproj

📦 This PR adds necessary change for linking `DatadogCrashReporting` in `Package.swift`
```diff
-            type: .dynamic,
+            type: .static,
```
This change is required to avoid following compiler errors in the apps using both `DatadogStatic` and `DatadogCrashReporting`:
```
Swift package product 'Kronos' is linked as a static library by 'SPMProject' and 'Datadog'. This will result in duplication of library code.
Swift package target '_Datadog_Private' is linked as a static library by 'SPMProject' and 'Datadog'. This will result in duplication of library code.
Swift package target 'Datadog' is linked as a static library by 'SPMProject' and 'Datadog'. This will result in duplication of library code.
```
From now on, to use Datadog crash reporting feature, apps must link …

RUMM-1206 Make `DatadogCrashReporting` static in `Package.swift`

---

Datadog/Datadog.xcodeproj/project.pbxproj

`Datadog.xcodeproj` has `Run linter` build phase.
Our SPM&cocoapods users don't see `xcodeproj` but our carthage users build the framework from it.
They don't need to lint our framework's source.
`carthage` passes `CARTHAGE=YES` flag to `xcodebuild`, our `Run linter` build phase checks this flag and it skips linting for `carthage` builds.

RUMM-1204 Linter not run for carthage builds

---

.gitignore
Makefile
bitrise.yml
tools/dogfooding/.gitignore
tools/dogfooding/dogfood.py
tools/dogfooding/src/dogfooded_commit.py
tools/dogfooding/src/package_resolved.py
tools/dogfooding/src/repository.py
tools/license/check-license.sh

🚚 This PR automates dogfooding of `dd-sdk-ios`.
With this setup, dogfooding can be started by any push to the `dogfooding` branch. Because `dogfooding` branch is _protected_, this means: by any PR merged to `dogfooding`, which gives us streamlined and simple workflow for starting, discussing and running dogfooding process.
The `make dogfood` command run on CI launches the `tools/dogfooding/dogfood.py` script, which:
* clones the dependant repository to temporary folder,
* starts a `dogfooding-<sha>` branch,
* updates the `Package.resolved` file with the last commit hash from `dd-sdk-ios/dogfooding`,
* commits and pushes the change to dependant repository,
* starts a draft PR in dependant repository to run its own automation.
I took the `dogfood.py` template from @xgouchet and updated it …

RUMM-1206 Automate dogfooding

---

Package.swift

⚙️ This PR ships an improvement to our dogfooding system. This will expose internal monitoring APIs to crash reporting module, which will be leveraged when dogfooding #457.
By compiling the `DatadogCrashReporting` module with `DD_SDK_ENABLE_INTERNAL_MONITORING`, we expose particular APIs invented for the internal monitoring feature.

RUMM-1229 δ Enable crash reporting telemetry in dogfooding

---

Sources/Datadog/DatadogConfiguration.swift
Sources/DatadogObjc/DatadogConfiguration+objc.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift

Let customer set additional configuration as a Dictionary. This will be used to configure internal settings of the SDK

RUMM-1213 Allow additional configuration when initializing the SDK

---

Sources/Datadog/Core/Persistence/Files/Directory.swift
Sources/Datadog/Core/Persistence/FilesOrchestrator.swift
Sources/Datadog/CrashReporting/CrashReporter.swift
Sources/Datadog/CrashReporting/DDCrashReportingPluginType.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift
Sources/DatadogCrashReporting/PLCrashReporterIntegration/PLCrashReporterIntegration.swift
Tests/DatadogTests/Datadog/Core/Persistence/Files/DirectoryTests.swift

📦 This PR improves internal monitoring data send to Datadog while dogfooding.
There are two things improved:
* **Got rid of _"Failed to read previously used writable file"_ false-positive warning.** It was reported each time when the last writable file is accessed after successful upload - in such case the file is missing (as it's deleted by the upload worker) which is expected behaviour and should not be reported as warning.
* **Collect Crash Reports telemetry for further analysis.** I've added some error logs in crash reporting feature and included `DEBUG` logs for shipping useful diagnostic info about the crash reports:

RUMM-1229 δ Collect internal telemetry for Crash Reporting while dogfooding

---

Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/Core/Upload/DataUploader.swift
Sources/Datadog/InternalMonitoring/InternalMonitoringFeature.swift
Sources/Datadog/Logging/LoggingFeature.swift
Sources/Datadog/RUM/RUMFeature.swift
Sources/Datadog/Tracer.swift
Sources/Datadog/Tracing/Span/SpanBuilder.swift
Sources/Datadog/Tracing/Span/SpanEncoder.swift
Tests/DatadogBenchmarkTests/DataStorage/TracingStorageBenchmarkTests.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploaderTests.swift
Tests/DatadogTests/Datadog/InternalMonitoring/InternalMonitoringFeatureTests.swift
Tests/DatadogTests/Datadog/Logging/LoggingFeatureTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/TracingFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMFeatureTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift

This is based on #456 , and let all feature use a customized `source` tag instead of the default value (`ios`).
We read the `_dd.source` tag from the `additionalConfiguration` dictionary and inject it:
- in the `ddsource()` method when uploading log-based batches (Logs, RUM, InternalLogs)
- in the `SpanBuilder` class when converting `DDSpan` to `Span` before the encoding step (APM)

RUMM-1038 add option to customize the `source` tag

---

Makefile
tools/standalone-binary-distro/make_distro_builds.sh

We need to provide our SDK as pre-build binaries to the users who don't use any package managers.
We build our SDK with `carthage --use-xcframeworks --no-skip-current` and then will upload the zipped `Carthage/Build/` folder to Github release
I tried the script in my personal fork first, you can see the output [here](https://github.com/buranmert/dd-sdk-ios/releases/tag/0.0.1)

RUMM-1087 Standalone binary distribution

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegate.swift
Sources/Datadog/URLSessionAutoInstrumentation/URLSessionSwizzler.swift
Sources/DatadogObjc/DDURLSessionDelegate+objc.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegateAsSuperclassTests.swift
Tests/DatadogTests/DatadogObjc/DDNSURLSessionDelegateTests.swift

In order to ship standalone binaries of the SDK, we need to build our targets with `BUILD_LIBRARY_FOR_DISTRIBUTION` build flag. 
Yet, `@objc open DDNSURLSessionDelegate: DDURLSessionDelegate` line was giving compiler errors: 
either we needed to remove `@objc` or superclass `DDURLSessionDelegate`
In this PR, we removed superclass of `DDNSURLSessionDelegate` and needed to make some other changes to make auto-network-tracing work.

RUMM-1234 DDNSURLSessionDelegate build errors fixed

---

Makefile

🧰 This PR fixes the recent `brew install` issues on CI.
As discussed in this [Bitrise forum thread](https://discuss.bitrise.io/t/how-to-change-brew-core-from-mirror-to-official/16033), Bitrise uses its own mirror for retrieving brew dependencies specs, so calling `brew update` without changing to the official source doesn't make sense.
We don't need to pull dependencies from official source, so using Bitrise mirror seems enough for our needs.
The issue was that with recent changes to Bitrise CI the `brew update` in our tooling was impacting brew bottles and leaving the VM's `brew` in a malformed state.

Fix `homebrew` on CI

---

DatadogSDKAlamofireExtension.podspec.src
Makefile

`make bump` wasn't bumping ` DatadogSDKAlamofireExtension.podspec` and in case the dev forgets to bump manually that leads to CI failure in release PRs.
Other `podspec` examples are followed (ie: `PodName.podspec.src` template) and this extension is included in `make bump` step.

RUMM-1172 AFExtension included in make bump

---

DatadogSDK.podspec.src

The fix was made in `DatadogSDK.podspec` but `DatadogSDK.podpspec.src` was forgotten
`DatadogSDK.podpspec.src` is fixed

RUMM-1160 make bump was breaking static pod support

---

tools/standalone-binary-distro/make_distro_builds.sh

`dependency-manager-tests` schemes can be tried by `carthage build`
We hide this folder temporarily

RUMM-1087 Test schemes are hidden from make_distro_builds

---

Datadog/Example/Scenarios/RUM/RUMScenarios.swift
Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/RUM/AutoInstrumentation/Resources/URLSessionRUMResourcesHandler.swift
Sources/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegate.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/TaskInterception.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptor.swift
Sources/Datadog/URLSessionAutoInstrumentation/URLSessionSwizzler.swift
Sources/DatadogExtensions/Alamofire/DatadogAlamofireExtension.swift
Sources/DatadogObjc/DDURLSessionDelegate+objc.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMResourcesScenarioTests.swift
Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift
Tests/DatadogTests/Datadog/Mocks/URLSessionAutoInstrumentationMocks.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Resources/URLSessionRUMResourcesHandlerTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegateTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/TaskInterceptionTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptorTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/URLSessionSwizzlerTests.swift
Tests/DatadogTests/DatadogObjc/DDNSURLSessionDelegateTests.swift
Tests/DatadogTests/Matchers/RUMSessionMatcher.swift

📦 This PR adds `rumResourceAttributesProvider` API, which makes it possible to add extra attributes to RUM Resources collected automatically:
```swift
public func setRUMResourceAttributesProvider(
_ provider: @escaping (URLRequest, URLResponse?, Data?, Error?) -> [AttributeKey: AttributeValue]?
)
```
The `provider` block is called for each `URLSessionTask` intercepted by the SDK. The implementation should look into task information and return custom attributes for RUM Resource, e.g. send redacted response headers or decode response body and send its additional context. This block is also called for RUM Errors created for resources failed on transport.
This is a counterpart of https://github.com/DataDog/dd-sdk-android/pull/520 introduced in `dd-sdk-android`.
The implementation starts with …

RUMM-1154 User can add attributes to auto instrumented RUM Resources

---

Datadog/Example/Scenarios/TrackingConsent/TrackingConsent/TSConsentSettingViewController.swift
Sources/Datadog/Utils/UIKitExtensions.swift
Tests/DatadogTests/Datadog/Core/FeatureTests.swift

📦 This PR fixes RUM Views auto-instrumentation issue for iOS 11 and fixes unit tests issues for iOS 11.x and 12.x.
**RUM Views auto-instrumentation issue for iOS 11**
Views instrumentation opts-out from tracking "bare" UIKit view controllers. This is determined by checking if the vc class is defined inside `UIKitCore.framework`. This check was failing for iOS 11, because it ships `UIKit.framework` instead of `UIKitCore.framework`.
**Tests failures for iOS 11.x and 12.x**
Several encoding-related tests were fixed for versions prior to iOS 13. They were failing due to known limitation of JSON encoder on iOS 11 and 12 - it can only encode object or array as the root type.
To mitigate this kind of regression in the future, I was trying to configure nightly job for running tests on all iOS …

RUMM-1324 Fix RUM views tracking issue for iOS 11 (and make tests green for 11.x and 12.x)

---

Sources/Datadog/Core/System/AppStateListener.swift
Sources/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsHandler.swift
Tests/DatadogTests/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsHandlerTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/AppStateListenerTests.swift

When the app goes to background, technically there is no active view. Previous behavior didn't match that.
When the app goes to background (by resigning active) `UIKitRUMViewsHandler` stops the last started RUM view and keeps a weak reference to it.
When the app comes back to foreground (IOW when it does become active) `UIKitRUMViewsHandler` re-starts that view.

RUMM-1218 App going background stops active RUM view

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/OpenTracing/OTSpan.swift
Sources/Datadog/Tracing/DDSpan.swift
Sources/DatadogObjc/Tracer+objc.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/TracingFeatureMocks.swift
Tests/DatadogTests/Datadog/OpenTracing/OTSpanTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/Tracing/Autoinstrumentation/URLSessionTracingHandlerTests.swift
Tests/DatadogTests/Datadog/Tracing/DDSpanTests.swift
Tests/DatadogTests/DatadogObjc/DDTracerTests.swift

📦 This is the final PR for `SpanEvent` scrubbing feature. It cleans things up in `DDSpan` implementation, mainly reducing the number of queue synchronisations that we were doing there.
This cleanup is possible due to refactoring done in #478 - where entire `SpanEvent` creation was moved to secondary thread.
Before #478, the `SpanBuilder` was reading span information from `DDSpan` partially:
```swift
_ = ddspan.operationName
_ = ddspan.tags
...
```
and each read [required thread synchronisation on the property getter](https://github.com/DataDog/dd-sdk-ios/blob/658dee7b6515aa296f09e43016759c4f6fa85164/Sources/Datadog/Tracing/DDSpan.swift#L22-L46).
After #478 all properties are read in bulk and no longer require thread sync. This PR removes the old property getters that are no longer used. …

RUMM-1104 Add `SpanEvent` scrubbing API - cleanup

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/Scenarios/Tracing/TracingScenarios.swift
Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/Core/System/CarrierInfoProvider.swift
Sources/Datadog/Core/System/NetworkConnectionInfoProvider.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/OpenTracing/OTSpan.swift
Sources/Datadog/Tracer.swift
Sources/Datadog/Tracing/DDSpan.swift
Sources/Datadog/Tracing/Scrubbing/SpanEventMapper.swift
Sources/Datadog/Tracing/Span/SpanEventBuilder.swift
Sources/Datadog/Tracing/Span/SpanEventEncoder.swift
Sources/DatadogObjc/Tracer+objc.swift
Tests/DatadogIntegrationTests/Scenarios/Tracing/TracingURLSessionScenarioTests.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/TracingFeatureMocks.swift
Tests/DatadogTests/Datadog/OpenTracing/OTSpanTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/Tracing/Autoinstrumentation/URLSessionTracingHandlerTests.swift
Tests/DatadogTests/Datadog/Tracing/DDSpanTests.swift
Tests/DatadogTests/Datadog/Tracing/Span/SpanEventBuilderTests.swift
Tests/DatadogTests/DatadogObjc/DDTracerTests.swift
Tests/DatadogTests/Helpers/EquatableInTests.swift
Tests/DatadogTests/Helpers/SwiftExtensions.swift

📦 This PR adds the actual implementation of `SpanEvents` scrubbing - the `SpanEvents` mapper API:
```swift
public func setSpanEventMapper(_ mapper: @escaping (SpanEvent) -> SpanEvent)
```
Similar to how RUM events mapper works, the mapper is set up from public interface and passed to the `SpanBuilder` through `FeaturesConfiguration` structure. If the mapper is configured, the builder asks it for redacted version of the `SpanEvent`.
This required making `SpanEvent` public along with some of its dependencies (notably `NetworkConnectionInfo` and `CarrierInfo`).

RUMM-1104 Add `SpanEvent` scrubbing API - implement event mapper

---

Makefile
tools/dogfooding/Makefile
tools/dogfooding/dogfood.py

⚙️ `make dogfood` stopped working on CI after recent Bitrise maintenance due to:
```shell
make: pip: No such file or directory
```
With short investigation I discovered that the result of `pip install GitPython` is now changed - once the dependency is installed, it's not seen from `python` interpreter. Aligning it to `pip3 install` and `python3` didn't help as well. Adding `--user` flag to `pip3 install` is not solving it neither.
As the use of global `pip3 install` and `python3` seems unstable in CI VMs, I switched to using [`venv`](https://docs.python.org/3.9/library/venv.html). Now, `make dogfood` creates a clean Python 3 `venv` and uses its `pip3` and `python3` to install dependencies and run scripts.

RUMM-1352 Fix pip3 issue on CI when running `dogfood.py`

---

Sources/Datadog/Core/Attributes/AttributesSanitizer.swift
Sources/Datadog/RUM/RUMEvent/RUMEventEncoder.swift
Sources/Datadog/RUM/RUMEvent/RUMEventSanitizer.swift
Tests/DatadogIntegrationTests/Scenarios/TrackingConsent/TrackingConsentScenarioTests.swift
Tests/DatadogTests/Datadog/Logging/Log/LogSanitizerTests.swift
Tests/DatadogTests/Datadog/RUM/RUMEvent/RUMEventSanitizerTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/Tracing/Span/SpanSanitizerTests.swift

To align the data with the browser SDK, and make the infos more consistent, we keep all the usr custom attributes in the root `usr` object.

RUMM-1320 Let user extra attributes use the usr prefix

---

CONTRIBUTING.md
Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/RUM/RUMVitals/VitalInfo.swift
Sources/Datadog/RUM/RUMVitals/VitalListener.swift
Sources/Datadog/RUM/RUMVitals/VitalObserver.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMVitals/VitalObserverTest.swift

Implement a way to aggregate a series of values over time. 
We create a `ValueObserver` implementation that will keep the min, max and mean value as well as a sample count.

RUMM-1272 Implement a VitalObserver

---

.gitignore
tools/dogfooding/.gitignore
tools/dogfooding/dogfood.py
tools/dogfooding/src/package_resolved.py
tools/nightly-unit-tests/.gitignore

🐶 This PR updates `dogfooding` tool to update `dd-sdk-ios` and submit PR to more products.
I updated the Python script to take dependant repository as parameter. I also added support for any number of dependencies in `dd-sdk-ios`, instead of hardcoding only `Kronos` and `PLCrashReporter`.

RUMM-1362 Automate dogfooding in more products

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/E2E.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/E2EInstrumentationTests.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/E2ETests.xcscheme
Datadog/E2E/Assets.xcassets/AccentColor.colorset/Contents.json
Datadog/E2E/Assets.xcassets/AppIcon.appiconset/Contents.json
Datadog/E2E/Assets.xcassets/Contents.json
Datadog/E2E/Base.lproj/LaunchScreen.storyboard
Datadog/E2E/E2EAppDelegate.swift
Datadog/E2E/E2EConfig.swift
Datadog/E2EInstrumentationTests/E2EInstrumentationTests.swift
Datadog/E2ETests/E2ETests.swift
Datadog/TargetSupport/E2E/E2E.xcconfig
Datadog/TargetSupport/E2E/Info.plist
Datadog/TargetSupport/E2EInstrumentationTests/E2EInstrumentationTests.xcconfig
Datadog/TargetSupport/E2EInstrumentationTests/Info.plist
Datadog/TargetSupport/E2ETests/E2ETests.xcconfig
Datadog/TargetSupport/E2ETests/Info.plist
Makefile
xcconfigs/Datadog.xcconfig

⚙️ This PR adds setup for E2E δ tests project. It will be used to monitor data and API performance when sending events to Datadog _"Mobile - Integration"_ org.
The E2E δ tests project will use our SDK and Datadog platform to test and monitor overall consistency of data sent from our SDK. It will additionally assert temporal metrics computed from measuring API performance with APM product. It will not assert deep consistency of data nor provide instant feedback for qualifying PRs before merge, hence:
* it is an extension to our existing integration tests with Python mock server, so the `Example` app and `DatadogIntegrationTests` remain unchanged and should be still maintained and updated with tests for new features;
* it will replace benchmark tests so we can call `DatadogBenchmarkTests` …

RUMM-1139 δ Create nightly E2E tests setup

---

docs/rum_collection.md

RUMM-954 changed an option, and missed an instance in the docs.
Following [the docs to implement my RUM autoinstrumentation](https://docs.datadoghq.com/real_user_monitoring/ios/?tab=cocoapods#auto-instrumentation), we hit:
> 'track(firstPartyHosts:)' is deprecated: This option is replaced by `trackURLSession(firstPartyHosts:)`. Refer to the new API comment for important details.
Seems the option was changed in [RUMM-954](https://github.com/DataDog/dd-sdk-ios/commit/2caea0b5e0ead46dc99995f499c3a25bbe655eb6#diff-43cd34cced2c4dbcc1402f5ed1e770728fcc4a107d97527a795152908711d7ee), back in January.
Docs-only.

RUMM-954: Update docs, track() option vs trackURLSession()

---

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/E2EInstrumentationTests.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/E2ETests.xcscheme
bitrise.yml

⚙️ This PR configures CI for running E2E tests (#496) nightly.
It adds `run_e2e_tests` workflow definition to `bitrise.yml`. Secrets and trigger are set up on Bitrise. After merging, I will configure necessary Bitrise schedule to run this workflow every night at a certain hour.
Additionally, I added `_notify_failure_on_slack` workflow which sends notification to our iOS Slack chanel upon certain workflow failure. It can be used to notify failure for workflows which are not asserted by GitHub PR checks (now: nightly E2E tests + dogfooding, later: release).

RUMM-1140 δ Configure CI for running E2E tests nightly

---

Sources/Datadog/Core/System/AppStateListener.swift
Sources/Datadog/Core/System/Time/DateCorrector.swift
Sources/Datadog/Core/System/Time/ServerDateProvider.swift
Sources/Datadog/CrashReporting/CrashContext/CrashContextProvider.swift
Sources/Datadog/CrashReporting/DDCrashReportingPluginType.swift
Sources/Datadog/RUM/AutoInstrumentation/Actions/UIKitRUMUserActionsHandler.swift
Sources/Datadog/RUM/AutoInstrumentation/RUMCommandSubscriber.swift
Sources/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsHandler.swift
Sources/Datadog/RUM/RUMContext/RUMContextProvider.swift
Sources/Datadog/RUM/RUMMonitor/RUMScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptor.swift
Tests/DatadogIntegrationTests/Scenarios/CrashReporting/CrashReportingWithLoggingScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/Logging/LoggingScenarioTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
tools/lint/sources.swiftlint.yml
tools/lint/tests.swiftlint.yml

📦 This PR solves warnings which pop up when compiling with Xcode 12.5.
There were 2 kinds of warnings:
* compiler: `Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead`
* linter: `Trailing Closure Violation: Trailing closure syntax should be used whenever possible`
The compiler warning is fixed by updating to recommended `AnyObject` declaration.
The linter issue is not new, but it only starter being visible after upgrading to Xcode 12.5 (see [this SwiftLint GH Issue](https://github.com/realm/SwiftLint/issues/3592)). It is only emitted from tests code (38 warnings), due to our partial mocking convention:
* e.g. this doesn't lint according to `trailing_closure` rule:
```swift
let builder: SpanEventBuilder = .mockWith(
eventsMapper: { span in
var mutableSpan …
```

RUMM-1374 Fix deprecation and lint warnings in Xcode 12.5

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScopeTests.swift

Currently if the application is not in foreground (there is no active View scope), any resource or action event will be ignored as there is no active `View` on which to attach it.
In this **PR** we are adding a change in the way we handle the received commands in the `RUMSessionScope` in order to be able to record RUM events while the application is in background.
We are introducing the concept of `RUM background View scope` which by definition is a normal View scope with predefined `name` and `url`. Once the `RUMSessionScope` needs to handle a `RUMStartAction` or `RUMStartResource` command and there is no active `RUMViewScope`, instead of ignoring the command as before it will automatically create a special `RUMViewScope` on which the received resource or action will be attached. For …

RUMM-1265 Correctly handle RUM events when app in background

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/RUM/RUMVitals/VitalMemoryReader.swift
Sources/Datadog/RUM/RUMVitals/VitalReader.swift
Tests/DatadogTests/Datadog/RUM/RUMVitals/VitalMemoryReaderTest.swift

Implement a class to read the Resident Memory used by the current application
This uses the [`task_vm_info`](https://opensource.apple.com/source/xnu/xnu-4570.41.2/osfmk/mach/task_info.h.auto.html) struct to read the relevant memory information

RUMM-1274 Implement Memory reader

---

docs/rum_collection.md

Similar to https://github.com/DataDog/dd-sdk-android/pull/615, this change specifies min OS supported version in the RUM docs.

RUMM-1384: Specify min OS supported version in the RUM docs

---

Makefile

Update to version 0.8.1 of testing framework. It solves an issue with tests that could be reported as child of another tests and were not correctly reported in the dashboard
Changed version in the makefile

Update to version 0.8.1 of testing framework

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/E2ETests/E2ETests.swift
Datadog/E2ETests/E2EUtils.swift
Datadog/E2ETests/Helpers/DatadogE2EHelpers.swift
Datadog/E2ETests/Helpers/LoggingE2EHelpers.swift
Datadog/E2ETests/Helpers/RUME2EHelpers.swift
Datadog/E2ETests/Logging/LoggerBuilderE2ETests.swift
Datadog/E2ETests/Logging/LoggerE2ETests.swift
Datadog/E2ETests/Logging/LoggingConfigurationE2ETests.swift
Datadog/E2ETests/Logging/LoggingTrackingConsentE2ETests.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

📦 This PR adds E2E tests for Logging feature.
These tests will be run in nightly CI job, sending data to _"Mobile - Integration"_ org. The org will be configured with a bunch of monitors asserting events volume, consistency and performance.
`E2ETests` is a base class for all E2E tests. It performs common things:
* starting SDK,
* measuring performance,
* stopping SDK with waiting for all data upload.
`E2EUtils` is a helper structure used to produce attributes, tags and span names expected by monitors in MI org. Most of the test-monitor contracts are laid out there, which gives a good place for documenting E2E tests system in the code.

RUMM-1376 δ Add E2E tests for Logging

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift

iOS implementation of the change done in https://github.com/DataDog/dd-sdk-android/pull/614. This allows to send custom instant (discrete) user actions even if there is an active one. Solves the issue only for the case of `addUserAction` usage, case of `startUserAction/stopUserAction` is still unsolved.

RUMM-1339: Keep custom user action even if there is active action already

---

Makefile

`DEBUG` flag is inherited from default Xcode build settings
`$(inherited)` is added to `SWIFT_ACTIVE_COMPILATION_CONDITIONS` in `Makefile`

RUMM-1381 $(inherited) is included in SWIFT_ACTIVE_COMPILATION_CONDITIONS

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/RUM/RUMVitals/VitalCPUReader.swift
Tests/DatadogTests/Datadog/RUM/RUMVitals/VitalCPUReaderTest.swift

`VitalCPUReader` is implemented in order to measure CPU utilization of the app.
`host_statistics(...)` method with `HOST_CPU_LOAD_INFO` parameter returns CPU utilization data from the kernel.
This low-level API requires working with pointers and type conversions; however
1. there is no higher level API to get such information
2. as this is the kernel, hopefully it's likely that they don't change often.

RUMM-1276 VitalCPUReader is implemented

---

Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/DatadogObjc/DatadogConfiguration+objc.swift
Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift
docs/log_collection.md
docs/rum_collection.md
docs/trace_collection.md

Update the endpoints available in the SDK and mark previous ones as deprecated.

RUMM-1397 Update Endpoints

---

Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

Use XHR by default instead of Unknown for RUM Resources
When we are unable to detect the resource type, we're going to use XHR by default instead of unknown to ensure the resource can have a backend trace attached to it.

RUMM-1421 Use XHR by default instead of Unknown for RUM Resources

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

Follow-up on https://github.com/DataDog/dd-sdk-android/pull/504 - the same sanitization of custom timings, but in iOS SDK.
This change adds sanitization of names in `custom_timings` per defined characters set.

RUMM-1057: Sanitize custom timings

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Utils/ValuePublisher.swift
Sources/Datadog/CrashReporting/CrashContext/CrashContextProvider.swift
Sources/Datadog/RUM/RUMVitals/VitalObserver.swift
Sources/Datadog/RUM/RUMVitals/VitalRefreshRateReader.swift
Tests/DatadogTests/Datadog/RUM/RUMVitals/VitalRefreshRateReaderTests.swift

We will be reading the refresh rate during app's lifetime in order to detect UI hitches.
iOS renders UI in the main run loop, this is a `RunLoop` instance. We want to be notified when a new frame is drawn.
`CADisplayLink` is a special timer type which listens to frame paints in a given run loop.
We add a `CADisplayLink` instance to `RunLoop.main` so that it calls our method every time a new frame is drawn.

RUMM-1278 Screen Refresh Rate vitals

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift

Cross platform sdks will generate the resource's span_id and trace_id on their side and forward the attributes as `_dd.span_id` and `_dd.trace_id` respectively. This PR reads those value and store them in the relevant place.

RUMM-1434 read resource span_id and trace_id from attributes

---

tools/dogfooding/dogfood.py
tools/dogfooding/src/package_resolved.py

⚙️ This PR updates dogfooding script for recent changes made in Datadog iOS app repo. Now the repo uses code-generated `.package.resolved` file, instead of one managed by Xcode.
Just changed the `paths` logic in `dogfooding.py`. Now it is able to modify multiple `Package.resolved` files as that's the setup currently used in mobile app repo.

RUMM-1467 Update dogfooding script for recent changes in other repos

---

Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/Debugging/RUMDebuggingTests.swift
Tests/DatadogTests/Datadog/RUM/RUMContext/RUMCurrentContextTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScopeTests.swift

Because tracking background event can lead to more sessions being tracked, we need to disable this feature by default and let customers enable/disable it in the configuration

RUMM-1269 Add configuration to enable/disable background RUM events

---

Sources/Datadog/Core/Upload/DataUploadWorker.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploadWorkerTests.swift

When an application is configured with an invalid Client Token, discard the batch to avoid retrying endlessly with the same invalid token.

RUMM-1439 discard batches on invalid Client Token

---

Datadog/TargetSupport/DatadogCrashReportingTests/DatadogCrashReportingTests.xcconfig

`PLCrashReporter` symbols are duplicated both in `DatadogCrashReporting` and `DatadogSDKTesting`, this was producing, apart from warnings, that `PLCR`symbols were found in the `DatadogSDKTesting` framework which made the test fail. The reason for that is because `DatadogSDKTesting` framework was being linked first, as its liking was configured in the `.xcconfig` file and the `DatadogCrashReporting` linking was added later in the Build phase.
We add the linking with the `DatadogCrashReporting` framework before the linking with `DatadogSDKTesting`, which makes the linker find its symbols as expected

Add support for DatadogSDKTesting to DatadogCrashReportingTests

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift

Mirror of the change https://github.com/DataDog/dd-sdk-android/pull/503 done for Android SDK earlier. This change add a warning if action is dropped when another action is still active in the given view scope.

RUMM-1085: Add a warning when action is dropped when another action is still active

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScopeTests.swift

Mirror of the change https://github.com/DataDog/dd-sdk-android/pull/375 done in Android SDK before: it adds a warning if there is no view scope active when any event other than events which create view scopes is received.

RUMM-728: Add a warning when event is received, but there is no active view scope

---

Sources/DatadogCrashReporting/PLCrashReporterIntegration/CrashReport.swift
Tests/DatadogCrashReportingTests/PLCrashReporterIntegration/CrashReportTests.swift

`isSystemImage` property was set by searching for `/Bundle/Application/` in the image paths.
This works well when running the app in devices where image paths can be like the followings:
```
// binaries in the App bundle:
/private/var/containers/Bundle/Application/00...00/Example.app/Example
/private/var/containers/Bundle/Application/00...00/Example.app/Frameworks/DatadogCrashReporting.framework/DatadogCrashReporting
// binaries coming from iOS
/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
/usr/lib/system/libdyld.dylib
/usr/lib/system/libsystem_kernel.dylib
/usr/lib/system/libsystem_c.dylib
```
However, this check gives wrong results when running in iOS simulator where non-system images do not have to be in the App bundle:
```
// non-system binary …
```

RUMM-1492 isSystemImage property was wrong in simulator

---

Sources/Datadog/DatadogConfiguration.swift

🧽 This PR cleans up compiler warnings which pop up when compiling the SDK:
These warnings appear to any user linking the SDK to their project. Their presence is misleading - the user is not using any deprecated API, instead we do it internally in the SDK code. Because the user can't do anything to dismiss it, I'm fixing it in this PR by removing deprecation annotation in these APIs. This operation is safe as explained below.
These warnings were introduced in https://github.com/DataDog/dd-sdk-ios/pull/523 by marking legacy cases as _deprecated_ in 3 enums:
```swift
public enum LogsEndpoint {
// ...
}
public enum TracesEndpoint {
// ...
}
public enum RUMEndpoint {
// ...
}
```
This isn't required, as those endpoints can only be used in these 3 legacy APIs which (if called) will already emit …

RUMM-1467 Remove deprecation warnings when compiling the SDK code

---

Sources/Datadog/RUM/RUMVitals/VitalRefreshRateReader.swift

`VitalRefreshRateReader` doesn't get updated while any tracking event, such as scrolling, is ongoing.
This results in reading too low FPS rates whereas UI is performing fine.
`CADisplayLink` is added to `RunLoop.main` in `.common` mode.
`.common` contains `.tracking` mode which is active while events like scrolling are ingoing.

RUMM-1544 Fix: `RefreshRateReader` doesn't read while scrolling UI

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Utils/CodableValue.swift
Sources/Datadog/Core/Utils/EncodableValue.swift
Sources/Datadog/CrashReporting/CrashContext/CrashContext.swift
Sources/Datadog/CrashReporting/CrashReporter.swift
Sources/Datadog/Logging/Log/LogEncoder.swift
Sources/Datadog/RUM/DataModels/RUMDataModels.swift
Sources/Datadog/RUM/RUMEvent/RUMEventEncoder.swift
Sources/Datadog/Tracing/Span/SpanEventBuilder.swift
Tests/DatadogTests/Datadog/Core/Utils/CodableValueTests.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashContext/CrashContextTests.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashReporterTests.swift
Tests/DatadogTests/Datadog/Mocks/AttributesMocks.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift
Tests/DatadogTests/Helpers/Encoding.swift
Tests/DatadogTests/Helpers/XCTestCase.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Output/Printing/SwiftPrinter.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Output/SwiftPrinterTests.swift

🐞 This PR fixes a bug where `CrashContext` decoding was failing if a `null` value was written in the JSON.
Because `CrashContext` is necessary for building the `RUMError` (it must be associated with `RUMView` which is encoded as part fo the `CrashContext`), the Crash Reporting feature was failing to upload crashes that include `null` value set in last view event attributes.
Swift uses `null` to represent absent optional value in JSON payload:
```swift
let absentString: String? = nil
let jsonData = try JSONEncoder().encode(absentString)
print(String(data: jsonData, encoding: .utf8)!)
// null
```
This PR improves our `Encodable` type erasure (now called `CodableValue`) to handle `null` value. When decoding `null` it stores internal `CodableNull()` value which is later used to encode `null` …

RUMM-1243 Fix crash context deserialization if it contains `null` value

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogBenchmarkTests.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCrashReporting.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogIntegrationTests.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
Makefile
Sources/Datadog/DatadogConfiguration.swift
Sources/DatadogObjc/DatadogConfiguration+objc.swift
Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift

🧽 This PR fixes compiler warnings emitted when building unit tests and changes deprecated Logs + Trace URLs to recommended values. It also elevates warnings policy to **treat them as errors on CI**.
This is to ensure that we always have `0` build-time issues and that nothing breaking can slip into project unnoticed:
First, I fixed existing warnings around using deprecated APIs in tests. This was done by referencing those APIs more dynamically - either with deprecation interface or through generic shim. Alternatively, we could remove those APIs from tests as they are meant deprecated, but I think we should still have them tested although deprecated (in fact, I spotted one missing improvement for Logs + Traces deprecated URLs thanks to having those tests).
Second, I've run recommended …

RUMM-1548 Fix compiler warnings in unit tests + fix deprecated endpoints

---

DatadogSDK.podspec
DatadogSDK.podspec.src
DatadogSDKAlamofireExtension.podspec
DatadogSDKAlamofireExtension.podspec.src
DatadogSDKCrashReporting.podspec
DatadogSDKCrashReporting.podspec.src
DatadogSDKObjc.podspec
DatadogSDKObjc.podspec.src
Makefile
dependency-manager-tests/cocoapods/CPProject.xcodeproj/project.pbxproj
dependency-manager-tests/cocoapods/CPProject/ViewController.swift
dependency-manager-tests/cocoapods/Makefile
dependency-manager-tests/cocoapods/Podfile.src
tools/distribution/push_podspecs.sh

`DatadogSDK` was using a custom `modulemap` and therefore Cocoapods was enforcing `use_frameworks!` when you have `DatadogSDK` pod.
On the other hand, `PLCrashReporter` needs to be statically linked and these 2 limitations were contradicting.
As a result, `DatadogCrashReporting` didn't support Cocoapods in the first place.
Since `DatadogSDK` doesn't require `use_frameworks!` anymore, we simply added `DatadogSDKCrashReporting.podspec` and it works.
⚠️  Please note that `PLCrashReporter` still needs to linked statically, so you can't use `use_frameworks!` with `DatadogSDKCrashReporting` pod.

DatadogSDKCrashReporting.podspec added

---

Sources/Datadog/RUM/RUMVitals/VitalInfoSampler.swift

`VitalInfoSampler` samples vital info, such as CPU, RAM and FPS, with a timer.
However, the timer is added to main `RunLoop` with `default` mode. For example, when `RunLoop` goes into `tracking` mode when the user scrolls a view then timer stops firing during the scroll.
`common` mode is used to solve this issue.
Similar to https://github.com/DataDog/dd-sdk-ios/pull/554

RUMM-1544 RunLoop is used in common mode only

---

Sources/DatadogCrashReporting/PLCrashReporterIntegration/CrashReport.swift
Tests/DatadogCrashReportingTests/PLCrashReporterIntegration/CrashReportTests.swift

`isSystemImage` is important for crash report symbolication at the backend.
However, it's a bit tricky tell system images from user images.
User images can be found in
1. `MyApp.app` bundle or
2. `DerivedData` folder (which is customizable)
System images can only be found in `Xcode.app` bundle.
System images can be found in various places, such as
1. `usr/lib/`
2. `System/Library/`
3. etc.
User images can only be found in `MyApp.app` bundle.
We implemented 2 different logic based on the platform: simulator or device.
However, we test both in our unit tests.

RUMM-1492: Fix `isSystemImage` detection

---

Sources/Datadog/Datadog.swift
Tests/DatadogTests/Datadog/DatadogTests.swift

The public interface lacks a way of checking the SDK initialized state.
A static variable `isInitialized` of the `Datadog` configuration class checks the internal `instance` availability.

RUMM-1530 Add Datadog.isInitialized variable

---

Sources/Datadog/Core/Upload/DataUploadWorker.swift
Tests/DatadogBenchmarkTests/DataStorage/LoggingStorageBenchmarkTests.swift
Tests/DatadogBenchmarkTests/DataStorage/RUMStorageBenchmarkTests.swift
Tests/DatadogBenchmarkTests/DataStorage/TracingStorageBenchmarkTests.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploadConditionsTests.swift
Tests/DatadogTests/Helpers/EquatableInTests.swift

Use preferred way of checking emptiness with `Collection`'s `isEmpty` property, as it has a complexity of O(1).
By replacing `.count == 0` checks with `.isEmpty`.

Use preferred isEmpty checks

---

Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift
Sources/Datadog/RUM/DataModels/RUMDataModels.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/DatadogObjc/RUM/RUMDataModels+objc.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegrationTests.swift
Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Matchers/RUMSessionMatcher.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/JSON/JSONSchema.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/JSON/JSONSchemaToJSONTypeTransformer.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/JSON/JSONType.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/Swift/JSONToSwiftTypeTransformer.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/Swift/SwiftType.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Output/Printing/SwiftPrinter.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Utilities.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Input/JSONSchemaReaderTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Input/JSONSchemaToJSONTypeTransformerTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Input/JSONToSwiftTypeTransformerTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Output/ObjcInteropPrinterTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Output/SwiftPrinterTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/RUM/RUMSwiftTypeTransformerTests.swift

📦 This PR adds billing information to RUM events - all must use plan `1`. It updates `RUMDataModels` (both Swift and Objc)  to recent schemas and configures `.plan1` value for all events send from the SDK.
Billing information was [earlier added to rum-events schema](https://github.com/DataDog/rum-events-format/blob/2ea84b56a4e0670b2d6e3e0c6a5fd27774ce4a3d/schemas/_common-schema.json#L171-L182):
```json
"session": {
"type": "object",
"description": "Session-related internal properties",
"required": ["plan"],
"properties": {
"plan": {
"type": "number",
"description": "Session plan: 1 is the 'lite' plan, 2 is the 'replay' plan",
"enum": [1, 2]
}
}
}
```
It uses a new semantic: _enum with numeric values_, so I had to update the `rum-models-generator` to support it. It was quite simple, as …

RUMM-1527 Add billing attribute to all RUM events

---

Sources/Datadog/Tracing/Propagation/HTTPHeadersWriter.swift
Sources/Datadog/Tracing/Propagation/TracingHTTPHeaders.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptor.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMResourcesScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/Tracing/TracingURLSessionScenarioTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptorTests.swift
Tests/DatadogTests/DatadogObjc/DDTracerTests.swift

🐞 This PR aligns our trace propagation logic with [_"How are RUM resources linked to traces?"_](https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?tab=browserrum#how-are-rum-resources-linked-to-traces) doc by adding two more headers to instrumented requests:
```
x-datadog-sampling-priority: 1 
x-datadog-sampled: 1
```
As reported in #572, lack of these headers may lead to not connecting mobile and backend trace in distributed tracing. The issue is hard to reproduce in our own infra, as we seem to overwrite sampling rules. In this fix I'm basing on docs, customer observation and my research on other DD SDKs implementation (including `browser-sdk` that respects those headers).
This PR targets the `1.7.0-beta4` branch made for next release. Once merged, I will raise …

RUMM-1579 Inject sampling headers to instrumented requests

---

Sources/Datadog/RUM/DataModels/RUMDataModels.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/Swift/JSONToSwiftTypeTransformer.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/Swift/SwiftType.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Output/Printing/ObjcInteropPrinter.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Output/Printing/SwiftPrinter.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Input/JSONToSwiftTypeTransformerTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Input/SwiftTypeTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Output/ObjcInteropPrinterTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Output/SwiftPrinterTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/RUM/RUMSwiftTypeTransformerTests.swift

As part of applying new RUM event schema, we need to add internal mutation capabilities to rum event models in order to sanitise custom attributes. The `rum-models-generator` tool was creating immutable models which prevented from sanitising the `usr` and `context` additional properties. 
The `rum-models-generator` now support 3 levels of property mutability:
```swift
enum Mutability: Int {
case immutable
case mutableInternally
case mutable
}
```
The `mutableInternally`  will be applied to read-only models with `additionalProperties` set to `true`. The generated models will then have an accessor level of `public internal(set) var` in a transitive way.

RUMM-1420 Set internal(set) accessor to readonly additionalProperties

---

Sources/Datadog/RUM/DataModels/RUMDataModels.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/ObjcInterop/ObjcInteropType.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/ObjcInterop/SwiftToObjcInteropTypeTransformer.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/Swift/JSONToSwiftTypeTransformer.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/Swift/SwiftType.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Output/Printing/ObjcInteropPrinter.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Output/Printing/SwiftPrinter.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Input/JSONToSwiftTypeTransformerTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Output/ObjcInteropPrinterTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Output/SwiftPrinterTests.swift

RUM models additional properties needs to be set as `[String: Encodable]` to match the public API definition.
The codegen `rum-models-generator` now adds addition properties with type `[String: Encodable]`.
A new protocol `SwiftPrimitiveNoObjcInteropType` has been added to prevent the objc interface from being generated, both `SwiftCodable` and `SwiftEncodable` now complies to the protocol.

RUMM-1420  `additionalProperties` as [String: Encodable]

---

Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/Core/Upload/HTTPClient.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/DatadogObjc/DatadogConfiguration+objc.swift
Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift
Tests/DatadogTests/Datadog/Core/Upload/HTTPClientTests.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift
docs/rum_collection/advanced_configuration.md

Let a customer setup a custom Proxy for data intake. 
A new method let's the customer provide the proxy configuration dictionary that will be forwarded to the HttpClient to create the `URLSession`.

RUMM-1350 let customer set up a Proxy for data upload

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/DatadogCrashReporting/PLCrashReporterIntegration/PLCrashReporterIntegration.swift
Tests/DatadogCrashReportingTests/PLCrashReporterIntegration/DDCrashReportExporterTests.swift

🛡️ All is good, but this PR adds two more unit tests to `DatadogCrashReporting` to ensure that the arithmetic behind our unsymbolicated stack trace computation produces same results as in [`PLCrashReportTextFormatter`](https://github.com/microsoft/plcrashreporter/blob/b6a0696d2add340999c6a03fcd10cbffdfc2a73d/Source/PLCrashReportTextFormatter.m#L47-L50).
This is to further ensure reliability of our crash reports and prevent future regressions.
Two unit tests are added. Both compare values from `DDCrashReport` to values appearing in raw crash report exported from `PLCR` (to its free-form text format). I leveraged `PLCR's` `.generateLiveReportAndReturnError()` API which produces a snapshot of running process (like it would crash, but without actual crashing).

RUMM-1597 Add tests for matching our crash report format with PLCR text format

---

Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/RUM/RUMFeature.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/RUMMonitor.swift
Sources/DatadogObjc/DatadogConfiguration+objc.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/DatadogObjc/ObjcAPITests/DDConfiguration+apiTests.m
api-surface-objc
api-surface-swift

Adds an optional `onSessionStart` callback to `RUMApplicationScope` to be called when a new session starts. The callback takes 2 arguments: the newly started Session ID and a boolean indicating whether or not the session is discarded by the sampling rate (when `true` it means no event in this session will be kept).
Fix #526

RUMM-1455 Add Session Start Callback

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog.xcscheme
Sources/Datadog/Core/PerformancePreset.swift
Sources/Datadog/Core/Swizzling/MethodSwizzler.swift
Sources/Datadog/Core/Upload/DataUploadDelay.swift
Tests/DatadogTests/Datadog/Core/PerformancePresetTests.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploadDelayTests.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploadWorkerTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMIntegrationsTests.swift
Tests/DatadogTests/Datadog/GlobalTests.swift
Tests/DatadogTests/Datadog/LoggerBuilderTests.swift
Tests/DatadogTests/Datadog/Logging/LoggingFeatureTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/ServerMock.swift
Tests/DatadogTests/Datadog/RUM/RUMFeatureTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMVitals/VitalMemoryReaderTests.swift
Tests/DatadogTests/Datadog/RUMMonitorConfigurationTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/TracerConfigurationTests.swift
Tests/DatadogTests/Datadog/Tracing/TracingFeatureTests.swift
Tests/DatadogTests/DatadogObjc/ObjcAPITests/DDRUMMonitor+apiTests.m
Tests/DatadogTests/Helpers/TestsDirectory.swift
Tests/DatadogTests/TestsObserver/DatadogTestsObserver.swift
Tests/DatadogTests/TestsObserver/DatadogTestsObserverLoader.m
tools/nightly-unit-tests/bitrise.yml.src

⚙️ This PR solves flakiness in unit tests. It should make both **PRs integration** and **nightly unit test** more stable.
As some of the flakiness came from not managing the global state properly, I also added a new component: `DatadogTestsObserver`. It runs integrity check after each test, ensuring that known aspects of global state are met. This tool was already helpful in spotting several issues fixed in this PR. It should also help contributing to the SDK codebase as no more known issues will get into the main branch unnoticed in code review.
**Note:** This PR doesn't solve UI tests flakiness (integration tests). This can be a next goal in the backlog.
I addressed all top 10 failures (`346`) reported to CI App from `master` branch in last 1 month:
* …

RUMM-1373 Fix flaky unit tests

---

Cartfile
Cartfile.resolved
DatadogSDKCrashReporting.podspec
DatadogSDKCrashReporting.podspec.src
Package.swift

📦 This PR upgrades PLCR dependency version to `1.10.0`.
The `1.10.0` version was very much awaited, as it is meant to solve our problem with `DDCR.podspec` distribution.
Upgraded PLCR version in `Package.swift` (for SPM), `Cartfile` (for Carthage) and `DDCR.podspec` (for Cocoapods).
I also tested that `DDCR.podspec` passes `pod spec lint`:
```
$ pod spec lint --allow-warnings --verbose DatadogSDKCrashReporting.podspec
DatadogSDKCrashReporting.podspec passed validation.
```
Later I will check if `DDCR` compiles on M1 laptop.

RUMM-1614 Upgrade PLCR to `1.10.0`

---

Tests/DatadogTests/TestsObserver/DatadogTestsObserver.swift

📦 This PR adds small, but convenient improvement to `DatadogTestsObserver` introduced in #592. Now, it will run integrity checks only if the test succeeds. 
Running checks for failed tests, might result with making the failure information unreadable, whereas it is more important than the integrity check result.  Given this test:
```swift
func testFoo() {
RUMFeature.instance = .mockNoOp() // breaking integrity rule, as it is never reset to `nil`
XCTAssertEqual(2, 3)
}
```
the outcome was:
```
error: -[DatadogTests.GlobalTests testFoo] : XCTAssertEqual failed: ("2") is not equal to ("3")
Fatal error: 🐶✋ `DatadogTests` integrity check failure.
`DatadogTestsObserver` found that `-[FooTests testFoo]` breaks 1 integrity rule(s) which
must be fulfilled before and after each unit test:
⚠️ ---- …
```

RUMM-1373 Do not run `DatadogTests` integrity checks if test fails

---

tools/nightly-unit-tests/bitrise.yml.src

📦 As flakiness was finally addressed in our unit tests (#592), we can relax the observability of nightly jobs. With this change, successful jobs will be notified to utility channel and only failures will be reported to the main one.
Using [`channel_on_error`](https://github.com/bitrise-steplib/steps-slack-message/blob/fed002637189e15384c61e71a9dcd71b75200b4a/step.yml#L93) option.
~- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)~
~- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference~

Send nithgly unit tests Slack notification to different channels

---

Sources/Datadog/Core/Upload/HTTPClient.swift
Tests/DatadogTests/Datadog/Core/Upload/HTTPClientTests.swift

URLSession does not set the `Proxy-Authorization` header automatically when using a proxy configuration. We have to manually set the HTTP basic authentication header.

RUMM-1575 Set `Proxy-Authorization` header with proxy configuration

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/AppConfiguration.swift
Datadog/Example/Base.lproj/Main.storyboard
Datadog/Example/Debugging/DebugCrashReportingWithRUMViewController.swift

🚚 This PR adds debug screen to `Example` app for testing Crash Reporting. It comes handy for debugging two situations:
* crashing the app in existing RUM session;
* crashing the app without starting any view (no RUM session).
Basic screen with two buttons and utility for creating RUM session (taken from RUM debug screen):

RUMM-1599 Add debug screen for testing Crash Reporting

---

Datadog/E2ETests/E2ETests.swift
Datadog/E2ETests/Logging/LoggerBuilderE2ETests.swift
Datadog/E2ETests/Logging/LoggerE2ETests.swift
Datadog/E2ETests/Logging/LoggingConfigurationE2ETests.swift
Datadog/E2ETests/Logging/LoggingTrackingConsentE2ETests.swift
tools/nightly-e2e-tests/monitors-gen/templates/monitor-apm.tf.src
tools/nightly-e2e-tests/monitors-gen/templates/monitor-logs.tf.src
tools/nightly-e2e-tests/src/main_tf_renderer.py
tools/nightly-e2e-tests/src/test_file_parser.py
tools/nightly-e2e-tests/tests/test_parsing_test_file.py
tools/nightly-e2e-tests/tests/test_rendering_monitor_template.py

⚙️ This PR updates our E2E test monitors to new format:
* it adds `feature` tag (`logs` | `trace` | `rum` | `core`) to each monitor;
* it adds `monitor:behavior` tag to all monitors asserting data;
* it adds `monitor:performance` tag to all monitors asserting performance;
* from now on, all performance spans use `"perf_measure"` span with test method sent as a resource name.
It also adds a bonus for troubleshooting, now each monitor renders its corresponding E2E test code in monitor UI, e.g.:
This helps understanding each monitor, especially if it expects "data" or "no data".
* I added `${{feature}}` variable to monitors template - it has no default value, so linter will emit an error if not specified.
* Both `monitor:behaviour` and `monitor:performance` tags are hardcoded in each …

RUMM-1588 + RUMM-1610 Update E2E test monitors to new metric format

---

dependency-manager-tests/carthage/Cartfile.src
dependency-manager-tests/carthage/Makefile
dependency-manager-tests/cocoapods/Makefile
dependency-manager-tests/cocoapods/Podfile.src
dependency-manager-tests/spm/Makefile
dependency-manager-tests/spm/SPMProject.xcodeproj.src/project.pbxproj

As an open-source project, we sometimes receive PRs from other forks.
We'd like to run our CI for those contributions in the same way as we do for regular PRs.
Our `dependency-manager-tests` had their repo URL hardcoded, now this value comes from Bitrise, [`$BITRISEIO_PULL_REQUEST_REPOSITORY_URL`](https://devcenter.bitrise.io/builds/available-environment-variables/).

RUMM-1469 Fix: CI for fork PRs

---

Sources/Datadog/RUMMonitor.swift
Sources/DatadogObjc/RUMMonitor+objc.swift
Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/DatadogObjc/DDRUMMonitorTests.swift
Tests/DatadogTests/DatadogObjc/ObjcAPITests/DDRUMMonitor+apiTests.m

Use `native` resource type instead of `xhr`. The latter was used as a legacy based on the Browser RUM SDK, but we need something more relevant for mobile apps.

RUMM-1605 Use Native resource type instead of XHR

---

tools/nightly-unit-tests/generate_bitrise_yml.py
tools/nightly-unit-tests/src/semver.py
tools/nightly-unit-tests/src/test_plan.py
tools/nightly-unit-tests/tests/test_semver.py

🐞 This PR fixes an issue in nightly tests automation, where sometimes it was trying to run unit tests on `iOS 10.x`.
Our nightly tests automation looks at all installed and available for installation Simulators in host environment (CI machine). Then it picks few Simulators (randomly) and runs tests (if Simulator is pre-installed) or installs the Simulator and then runs tests. Because `iOS 10.x` simulator can be installed on macOS Catalina, it was sometimes picked by our automation.
I added `MIN_SUPPORTED_IOS_VERSION` variable to filter out unsupported versions from test plan.
Also, I added `dump_environment()` function to print more information about the Simulators, Runtimes and Devices when automation fails. This should be handy for debugging issues like [iOS 15.0 Simulator not being …

RUMM-1625 Do not run nightly tests below iOS 11.0.0

---

Sources/Datadog/RUM/RUMVitals/VitalInfoSampler.swift
Tests/DatadogTests/Datadog/RUM/RUMVitals/VitalInfoSamplerTests.swift

`RefreshRate` is shown as a mobile vital in Datadog UI.
It needs to be normalized as different devices can have different maximum FPS rates.
It was normalized to 0...1, this was not consistent with other platforms.
Now it is normalized to 0...60 range, as browser and Android SDKs do.

RUMM-1278 RefreshRate is normalized to 0...60

---

LICENSE

For now the License is not recognised by Github License detection, nor the Swift Package Index [page](https://swiftpackageindex.com/DataDog/dd-sdk-ios)

Update License to be recognised by Github 

---

Sources/Datadog/Core/System/Time/DateCorrector.swift
Sources/Datadog/Core/System/Time/ServerDateProvider.swift
Tests/DatadogTests/Datadog/Core/System/Time/DateCorrectionTests.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift

The Kronos `Clock.now` property is not thread safe and should always be invoked from the main thread, this change would have a large impact on our codebase. As an alternative, we can rely on the server time offset we get from `Clock.sync`: The `Clock.now` is in fact used by `DateCorrector` to actually compute the server offset.
Below a quick benchmark of the computed offset previously used and the server offset applied by this PR:
|Previous Computed Offset|Server Offset|
|---|---|
|**0.0537**11891174316406|**0.0537**5981330871582|
|**0.0476**3531684875488|**0.0476**7334461212158|
|**0.0457**2319984436035|**0.0457**66234397888184|
|**0.081**27260208129883|**0.081**31551742553711|
|**0.051**30136013031006|**0.051**299452781677246|
|**0.0388**5924816131592|**0.0388**74030113220215|
> Note …

RUMM-1609 Use NTP server offset

---

docs/rum_collection/advanced_configuration.md
docs/rum_collection/data_collected.md

Update code snippets in doc and fix few attributes keys.

RUMM-1091 Harmonize code snippet in documentation

---

Sources/Datadog/FeaturesIntegration/RUMIntegrations.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMIntegrationsTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift

Add User Action id to shared context with Logs and Traces.
Based on [browser-sdk/#352](https://github.com/DataDog/browser-sdk/pull/352), the shared context with Logs and Traces integration now includes the `user_action.id` if an active User Action ID is present.

RUMM-1668 Associate Logs and Traces with RUM Action

---

Datadog/TargetSupport/DatadogCrashReporting/DatadogCrashReporting.xcconfig
Makefile

📦 This PR removes workaround added in early development of `DatadogCrashReporting` when `PLCR's` xcframework (`1.8.0`) was missing the `arm64-simulator` slice.
The recent version of `PLCR's` xcframework (`1.10.0`) includes the missing slice, so this workaround is not needed anymore. It also means that now all targets in `Datadog.xcworkspace` can be compiled on Apple Silicon.
Made necessary updates in `xcconfigs`.

RUMM-1200 Remove Carthage workaround for missing `arm64` slice in PLCR's xcframework

---

Sources/Datadog/Core/System/MobileDevice.swift

As described in #609, iOS 15 has introduced a race condition around `ProcessInfo.isLowPowerModeEnabled`:
The conditions under which this can occur are:
1. Register to observer: `NSProcessInfoPowerStateDidChangeNotification`
2. In the observation block, query `ProcessInfo.isLowPowerModeEnabled`
3. Later on another piece of code calls `ProcessInfo.isLowPowerModeEnabled`
4. _Sometimes_ that will trigger a change in the power state which will be broadcast to observers before returning
5. The code in (2) is called which re-enters `isLowPowerModeEnabled`
6. Thread deadlock over an `os_unfair_lock` occurs and the app crashes
We introduce a `LowPowerModeMonitor` which:
1. Listens to `NSProcessInfoPowerStateDidChangeNotification`
2. On any updates it queries `ProcessInfo.isLowPowerModeEnabled` and …

Prevent iOS 15 crashes by not polling isLowPowerModeEnabled

---

Sources/Datadog/Core/System/MobileDevice.swift
Tests/DatadogTests/Datadog/Core/System/MobileDeviceTests.swift

📦 This PR adds tests to changing "Low Power Mode" setting.
This is to add coverage and prevent regression in fix merged in #613.
I changed existing test to update `BatteryStatus.isLowPowerModeEnabled` on notification, instead of pulling it from `ProcessInfo`.

RUMM-1688 Add tests to "Low Power Mode" setting changes

---

Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegateTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/URLSessionSwizzlerTests.swift
Tests/DatadogTests/Helpers/SwiftExtensions.swift
Tests/DatadogTests/Helpers/XCTestCase.swift

📦 This PR adds a bit more verbosity to errors which we capture in flaky tests. 
Looking at last `7d`, we got 11 failures in nightly tests:
Unfortunately, the error messages are not handy in troubleshooting:
As I couldn't reproduce these failures locally (in exactly the same OS + simulator setup and with `dd-swift-testing` instrumentation enabled), I propose to first add more verbosity in this PR, and collect more data in CI App.
I improved the way we compare two task instances. Instead of:
```swift
XCTAssertTrue(actualTask === expectedTask)
```
now it uses a helper method:
```swift
AssertURLSessionTasksIdentical(actualTask, expectedTask)
```
which dumps additional information about the `lhs` and `rhs` tasks if they are not identical, e.g:

RUMM-1394 Add more verbosity to flaky test errors

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/E2ETests/Tracing/SpanE2ETests.swift
Datadog/E2ETests/Tracing/TracerE2ETests.swift
Datadog/E2ETests/Tracing/TracingConfigurationE2ETests.swift
tools/nightly-e2e-tests/monitors-gen/templates/monitor-logs.tf.src
tools/nightly-e2e-tests/src/lint.py

📦 This PR adds E2E tests and their monitor definitions for Tracing product.
Added tests with their monitors (`terraform plan` works fine). I haven't yet updated monitors in Mobile Integration org - that needs to be done after merge otherwise they will have no data.
I also added two changes to E2E tests linter:
* it now checks if `$feature` variable is one of allowed values (`core`, `logs`, `trace`, `rum`, `crash`),
* it no longer checks if `$monitor_query` contains the test method name (the way we set up some monitors was not compatible with this rule).

RUMM-1377 Add E2E tests for Tracing APIs

---

Datadog/Example/Base.lproj/Main.storyboard
Datadog/Example/Debugging/DebugLoggingViewController.swift
Sources/Datadog/Core/System/CarrierInfoProvider.swift
Sources/Datadog/Core/System/NetworkConnectionInfoProvider.swift
Tests/DatadogTests/Datadog/Core/System/CarrierInfoProviderTests.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashContext/CrashContextProviderTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/CoreTelephonyMocks.swift

📦 This PR updates the way we retrieve `CarrierInfo` information on iOS 12+. It's an educated guess to mitigate infrequent (2 impacted users) crashes reported in #623 and #619. Instead of pulling `CTTelephonyNetworkInfo` for each collected event to create `CarrierInfo`, now we only listen to `CTTelephonyNetworkInfo` changes to update `CarrierInfo` when necessary.
We use `CTTelephonyNetworkInfo` (from `CoreTelephony` framework) to read carrier information:
A loop of investigation, research and debugging, lead me to following conclusions:
* C1. Reported crashes are very infrequent (one report on iOS 14.8 and one on iOS 14.6),
* C2. I observed is that `CTTelephonyNetworkInfo` only changes when swapping SIM card to another one (it does not change when removing SIM card - the last known info is …

RUMM-1691 Reduce utilization of `CTTelephonyNetworkInfo` to mitigate `CarrierInfoProvider` crash

---

tools/distribution/src/assets/gh_asset.py

Pre-built binaries should be compatible with newer Xcode versions. 
Currently they are incompatible, this may lead to such errors:
```
Module compiled with Swift 5.3.2 cannot be imported by the Swift 5.5 compiler: /foo/bar/DerivedData/Build/Products/Debug-iphonesimulator/Datadog.framework/Modules/Datadog.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
```
`BUILD_LIBRARY_FOR_DISTRIBUTION = YES` is set while building

RUMM-1667: Fix distribution tool

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/DatadogObjc/ObjcIntercompatibility/AnyEncodable.swift
Sources/DatadogObjc/RUM/RUMDataModels+objc.swift
Sources/DatadogObjc/RUMMonitor+objc.swift
Tests/DatadogTests/DatadogObjc/DDRUMMonitorTests.swift
Tests/DatadogTests/DatadogObjc/RUM/RUMDataModels+objcTests.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Output/Printing/ObjcInteropPrinter.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Output/ObjcInteropPrinterTests.swift

📦 This PR fixes `DatadogObjc` issue with retrieving back attribute values in public APIs.
It was not possible to obtain the value of `Any` attribute, i.e. this would fail:
```swift
let view = DDRUMView(name: "name", attributes: ["foo": "bar"])
XCTAssertEqual(view.attributes["foo"] as? String, "bar") // 🐞 fail
```
It would fail because `"bar"` is wrapped into `AnyEncodable(value: "bar")` type erasure as part of our Objective-C <> Swift interoperability (Swift SDK represents attributes as `Encodable`). `AnyEncodable` is `internal` type to `DatadogObjc` so it was not even possible to read the attribute value back in any other way.
I introduced `func castAttributesToObjectiveC(_ attributes: [String: Encodable]) -> [String: Any]` function to unpack `AnyEncodable` values before they are passed …

RUMM-1583 Fix attributes reading in Objective-C

---

bitrise.yml
tools/nightly-unit-tests/bitrise.yml.src
tools/nightly-unit-tests/src/bitrise_yml_writter.py

Bitrise's `xcode-test` step deprecates `should_retry_test_on_fail` input in favor of `test_repetition_mode: 'retry_on_failure`
Our main `bitrise.yml` uses the new input parameter.
`nightly-unit-tests` tool sets the input parameter accordingly.

RUMM-1770 test_repetition_mode is added for Xcode 13 stack

---

Sources/Datadog/Core/Attributes/Attributes.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/RUMCommandTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift

Fatal errors from RN (and future cross plateform sdks)  are reported with a custom attribute `_dd.error.is_crash`. 
The value of `_dd.error.is_crash` will map to RUM Error’s `error.is_crash`.

RUMM-1763 Read `_dd.error.is_crash` crossplatform attribute

---

Sources/DatadogCrashReporting/PLCrashReporterIntegration/CrashReport.swift
Sources/DatadogCrashReporting/PLCrashReporterIntegration/CrashReportMinifier.swift
Sources/DatadogCrashReporting/PLCrashReporterIntegration/DDCrashReportExporter.swift
Tests/DatadogCrashReportingTests/Mocks.swift
Tests/DatadogCrashReportingTests/PLCrashReporterIntegration/CrashReportMinifierTests.swift

⚙️🐞 This PR fixes bug discovered by recent upgrade to Xcode 13.1 on CI.
With Xcode 13.1 and iOS Simulator some paths to binary images may include illegal characters (e.g. spaces) which return `nil` for `URL(string:)`:
```swift
let path = "/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 13.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation"
//                                                                ^ 🤨
print(URL(string: path)) // nil
```
We shouldn't use `URL(string:)` for path processing, so I'm replacing it with `URL(fileURLWithPath:)` to fix the issue. The improvement is that now it returns `URL`, not `URL?` so I also managed to simplify the code a little bit.
🛡 Tested on real device as well.

RUMM-1386 Fix `BinaryImage.imageName` resolution on iOS Simulator with Xcode 13.1

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/Base.lproj/Main.storyboard
Datadog/Example/Debugging/DebugRUMSessionViewController.swift
Datadog/Example/Debugging/Helpers/SwiftUI.swift

📦 As part of `RUMM-1758` work (proposing RFC to reduce number of view updates), I made a simple tool to debug RUM session. I think we can leverage it on a longer run, so I'm adding it to our existing debug toolset.
Unlike existing "Debug RUM" tool, this new "Debug RUM session" utility allows for sending RUM session composed from different events (actions, errors, resources). Additionally, resources can be controlled by their "start" and "stop", so it is possible to debug sequences like:
* start view A
* start resource R1
* start resource R2
* stop resource R1
* start view B
* stop resource R2
It's also all made in SwiftUI, so adding new features / utils could be easier.
~- [] Feature or bugfix MUST have appropriate tests (unit, integration)~

RUMM-1758 Add RUM Session debug utility

---

Sources/Datadog/Core/Persistence/Files/Directory.swift

Closes https://github.com/DataDog/dd-sdk-ios/issues/653
`try? FileManager.default.removeItem(at: tempDirectory.url)` is called as an extra safety measure.
It throws most of the time, for example at the app launch it typically throws 3 times: once per feature.
When `Swift Error Breakpoint` is enabled, that causes debugger to halt multiple times.
`try? FileManager.default.removeItem(at: tempDirectory.url)` should only be called if `FileManager.default.replaceItemAt(url, withItemAt: tempDirectory.url)` fails.
Now this method call is wrapped with a `do-catch` and `removeItem` is called only if an error is caught.

RUMM-1780 Prevent FileManager from throwing

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogBenchmarkTests.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCrashReporting.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogIntegrationTests.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/E2E.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/E2EInstrumentationTests.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/E2ETests.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
Datadog/Example/Debugging/DebugRUMSessionViewController.swift

🐞⚙️ This PR fixes `Example` compilation problem in Xcode 12 (used in nightly tests). 
The issue was introduced in `SwiftUI` code added in #669, where we use a construct not available for Xcode 12.
Just replacing:
```diff
- .listStyle(.plain)
+ .listStyle(PlainListStyle())
```
and not shadowing class fields with local variables:
```diff
- let viewKey = viewKey
+ let key = viewKey
```
I also migrated our xcworkspace by dismissing recommended changes for Xcode 13.1 (none of them was applicable in our setup).

RUMM-1758 Fix Example app compilation in Xcode 12

---

Datadog/Datadog.xcodeproj/project.pbxproj

🐞⚙️ This PR fixes the runtime issue appearing in nightly tests for iOS 11 and 12:
```
dyld: Library not loaded: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
Referenced from: /Users/vagrant/Library/Developer/CoreSimulator/Devices/7795F4B9-88DD-4620-B70C-CECE75CF3516/data/Containers/Bundle/Application/F5F467F7-4D89-4EB2-9504-0773865DB814/Example.app/Example
Reason: image not found
```
The issue was introduced in #669, where `SwiftUI` code was added to `Example` app. The solution is to add a weak reference to `SwiftUI.framework` in this target:
~- [] Feature or bugfix MUST have appropriate tests (unit, integration)~

RUMM-1758 Fix 'Library not loaded: SwiftUI' runtime crash in nightly tests (iOS 11 and 12)

---

Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

📦 This is the first PR on _application launch events tracking_. It implements the base logic of starting "ApplicationLaunch" view if any RUM event is received before tracking the first view:
It was known that this feature will collide with existing [Background Events Tracking](https://github.com/DataDog/dd-sdk-ios/blob/b28016175691665c9c2e1d3d867e90d6f4437ab2/Sources/Datadog/DatadogConfiguration.swift#L678-L690) option, which creates "Background" view for capturing off-view events. Most of the effort in this PR is focused on decoupling both and implementing a clear separation of following cases:
* when event is received and existing session didn't yet track any view → start "ApplicationLaunch" view;
* when event is received and existing session has tracked some view → start "Background" …

RUMM-1765 Collect RUM events during application launch - part 1

---

.gitignore
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/Core/System/MobileDevice.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogConfiguration.swift
Tests/DatadogBenchmarkTests/BenchmarkMocks.swift
Tests/DatadogTests/Datadog/Core/System/MobileDeviceTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift

Adds two launch arguments:
DD_DEBUG sets sampling to 100%, verbosity to debug, and upload frequency to frequent
DD_DEBUG_RUM enables Datadog.debugRUM
All of these settings are changed during initialization to override whatever configuration the user set

🚩RUM-1755 Add config overrides for debug launch arguments

---

Tests/DatadogIntegrationTests/Scenarios/RUM/RUMManualInstrumentationScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMMobileVitalsScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMModalViewsScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMNavigationControllerScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMResourcesScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMScrubbingScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMSwiftUIScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMTabBarControllerScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMTapActionScenarioTests.swift
Tests/DatadogIntegrationTests/UITestsHelpers.swift
Tests/DatadogTests/Matchers/RUMSessionMatcher.swift

⚙️🐞 This PR fixes two issues in `RUMResourcesScenarioTests` which causes recent flakiness.
Frequent problem (> 10 CI failures in last `15d`):
Rare problem (2 CI failures in last `15d`):
The **frequent problem** was caused by sending requests to these 3rd party URLs:
```diff
-let thirdPartyGETResourceURL = URL(string: "https://bitrise.io")!
-let thirdPartyPOSTResourceURL = URL(string: "https://bitrise.io/about")!
```
For some reason, when running this in Bitrise container the SSL and DNS phases were sometimes skipped. I don't know the exact reason (it might be related to Bitrise infra), but changing these to proper `GET` and `POST` endpoints (external) seems to improve situation. I ran these tests successfully 20 times in a CI loop.
```diff
+let thirdPartyGETResourceURL = URL(string: …
```

RUMM-1821 Fix flakiness in `RUMResourcesScenarioTests`

---

Sources/Datadog/DDRUMMonitor.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

The current error reporting of Datadog didn't result in the best results for us:
As you can see, these 3 errors are the same, but they aren't seen as the same since they differ due to the associated value.
We've implemented our own custom error parsing locally which uses mirroring to get the enum case and associated values separately:
```swift
// A wrapper around tracked errors to convert into Datadog suitable error messages.
struct DatadogError {
let underlyingError: Error
let type: String
let message: String
let attributes: [String: Encodable]
let file: StaticString
let line: UInt
init(trackedError: TrackedError) {
let caseName = trackedError.error.caseName
let associatedValues = trackedError.error.associatedValues
let errorDescription = (trackedError.error as? …
```

Allow passing in a type for errors sent with a message

---

Makefile

Update to version 1.0.3-beta.1 of testing framework. It fixes test network instrumentation when running using `DD_DISABLE_SDKIOS_INTEGRATION` configuration
Updated version on Makefile

Update to version 1.0.3-beta.1 of testing framework

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift

Targeting 🐶 Dogfooding.
Log MetricKit payloads through internal monitoring.
Subscribe to `MXMetricManager` when sending `ApplicationStart` event to internal logs.
The logs will include the Application Launch Time measured by the SDK to later compare with values reported by `MetricKit`.
MetricKit payloads are transformed into logs attributes with the help of a modified version of [AnyEncodable](https://github.com/DataDog/dd-sdk-ios/pull/688/commits/dfd0d30abb3ccdefec92c04c598f3b2158b92bf3#diff-7e73bbe23d9ad1b6da3e7d82fdb3d85f13b0d077b56366fa5affcf76942a2a8eR566-R613).
[Here a sample of a log](https://app.datadoghq.com/logs?query=service%3Add-sdk-ios%20env%3Aprod&cols=host%2Cservice&event=AQAAAX291bHEpvAnaQAAAABBWDI5MWRzUkFBQ2poaDZJQlotc213QUE&index=&messageDisplay=inline&stream_sort=desc&fr …

RUMM-1803 Monitor MetricKit through internal monitoring

---

Sources/Datadog/Core/Feature.swift
Sources/Datadog/Core/System/AppStateListener.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/RUM/RUMFeature.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUMMonitor.swift
Sources/Datadog/URLSessionAutoInstrumentation/URLSessionAutoInstrumentation.swift
Tests/DatadogBenchmarkTests/BenchmarkMocks.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/Debugging/RUMDebuggingTests.swift
Tests/DatadogTests/Datadog/RUM/RUMContext/RUMCurrentContextTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/Tracing/Autoinstrumentation/URLSessionTracingHandlerTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/AppStateListenerTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptorTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/URLSessionAutoInstrumentationTests.swift

📦 This PR limits _application launch events tracking_ feature to only consider events received while app is in foreground. It adds necessary implementation to not start "ApplicationLaunch" view if app is not in `active` state.
When app launches in background, its events can still be tracked if [Background Events Tracking](https://github.com/DataDog/dd-sdk-ios/blob/b28016175691665c9c2e1d3d867e90d6f4437ab2/Sources/Datadog/DatadogConfiguration.swift#L678-L690) feature is enabled. This makes a clear separation of "ApplicationLaunch" and "Background" activities.
Determining app state is done using existing `AppStateListener` - it is now injected to RUM feature as well. It is used to check the app state and consider starting either:
* "ApplicationLaunch" view - if app receives off-view events …

RUMM-1765 Do not start "ApplicationLaunch" view when app launches in background - part 2

---

Sources/_Datadog_Private/ObjcAppLaunchHandler.m

Fixes a memory leak in `AppLaunchHandler`.
The token generated by `NSNotificationCenter` was not released.

RUMM-1839 Fix Application Launch Handler Memory Leak

---

Cartfile
Cartfile.resolved
Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/Utils/PersistenceHelper.swift
DatadogSDKCrashReporting.podspec.src
Sources/DatadogCrashReporting/PLCrashReporterIntegration/PLCrashReporterIntegration.swift
Tests/DatadogCrashReportingTests/PLCrashReporterIntegration/DDCrashReportExporterTests.swift
Tests/DatadogCrashReportingTests/PLCrashReporterIntegration/PLCrashReporterIntegrationTests.swift

Configure `PLCrashReporter` with a custom storage location to `/Library/Caches/com.datadoghq.crash-reporting/v1`.
By setting a custom path, we allow other instances of `PLCrashReporter` to work alongside the SDK without altering the reports.
Sets the `basePath` property of the [PLCrashReporterConfig](https://github.com/microsoft/plcrashreporter/blob/master/Source/PLCrashReporterConfig.h#L185).
The `PLCrashReporter` version has been incremented to `1.10.1` to use the `[PLCrashReporter crashReportPath]` in tests.

RUMM-1805 Set `PLCrashReporter` custom path

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/System/AppStateListener.swift
Sources/Datadog/CrashReporting/CrashContext/CrashContext.swift
Sources/Datadog/CrashReporting/CrashContext/CrashContextProvider.swift
Sources/Datadog/CrashReporting/CrashReporter.swift
Sources/Datadog/CrashReporting/CrashReportingFeature.swift
Sources/Datadog/FeaturesIntegration/RUMWithCrashContextIntegration.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMOffViewEventsHandlingRule.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUM/UUIDs/RUMUUID.swift
Sources/Datadog/RUMMonitor.swift
Sources/Datadog/Utils/SwiftExtensions.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashContext/CrashContextProviderTests.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashContext/CrashContextTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMWithCrashContextIntegrationTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/CrashReportingFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMOffViewEventsHandlingRuleTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/Utils/SwiftExtensionsTests.swift

📦 This PR prepares `CrashContext` to handle crashes during application launch. This is necessary to decide:
* if the crash should be send in "ApplicationLaunch" view (when app crashed during foreground launch);
* if the crash should be send in "Background" view (when app crashed during background launch);
* if the crash should be dropped (e.g. when app crashed during background launch, but Background Events Tracking is disabled OR when crashed session was rejected by sampler).
First, I isolated the code deciding on "ApplicationLaunch" x "Background" x "no" view to `RUMOffViewEventsHandlingRule`. This logic is quite complex but very important (for customer billing 💸) so it's definitely worth having it separate as it will be used by both RUM and Crash Reporting to take similar decision on …

RUMM-1765 Update `CrashContext` with necessary info for handling App Launch crashes - part 3

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/Core/Utils/Sampler.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift
Sources/Datadog/FeaturesIntegration/RUMWithCrashContextIntegration.swift
Sources/Datadog/RUM/RUMEvent/RUMConnectivityInfoProvider.swift
Sources/Datadog/RUM/RUMEvent/RUMUserInfoProvider.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift
Tests/DatadogTests/Datadog/Core/Utils/SamplerTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegrationTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMIntegrationsTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMWithCrashContextIntegrationTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/Debugging/RUMDebuggingTests.swift
Tests/DatadogTests/Datadog/RUM/RUMContext/RUMCurrentContextTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScopeTests.swift
Tests/DatadogTests/Datadog/RUMMonitorConfigurationTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Helpers/EquatableInTests.swift
Tests/DatadogTests/Helpers/SwiftExtensions.swift

📦 This PR adds the actual handling of _application launch crashes_. When app crashes **before** starting the RUM session, the crash is uploaded in a new, artificial session indicated either by "ApplicationLaunch" or "Background" view, depending on the app state during crash.
The `RUMOffViewEventsHandlingRule` introduced in #690 is now reused in `CrashReportingWithRUMIntegration` to decided on how to send the crash. The overall logic of processing crashes in RUM looks this:
To make it work as described in the original RFC, I had to inject sampling logic into `CrashReportingWithRUMIntegration`. To reuse existing code, I isolated it into single `Sampler` component (defined in "core").

RUMM-1765 Handle App Launch crashes - part 4

---

Datadog/Example/Debugging/BackgroundEvents/BackgroundLocationMonitor.swift
Datadog/Example/Debugging/BackgroundEvents/DebugBackgroundEventsViewController.swift
Sources/Datadog/Core/System/AppStateListener.swift
Sources/Datadog/CrashReporting/CrashContext/CrashContextProvider.swift
Sources/Datadog/RUM/Instrumentation/Views/RUMViewsHandler.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/Tracing/AutoInstrumentation/URLSessionTracingHandler.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashContext/CrashContextProviderTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/UIKitMocks.swift
Tests/DatadogTests/Datadog/Tracing/Autoinstrumentation/URLSessionTracingHandlerTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/AppStateListenerTests.swift

📦 This is the final PR closing topic of _tracking app launch events (and crashes)_. While testing it (with new options added to debug UI 👇), I found a bug 🐞 in `AppStateListener`, which I'm solving in this PR.
Problem was that [`AppStateListener` was only considering `UIApplication.State.active` as "foreground" application state](https://github.com/DataDog/dd-sdk-ios/blob/ad16182bba3f757406834044bf0d9d1fdcdd3dea/Sources/Datadog/Core/System/AppStateListener.swift#L103), whereas app lifecycle is more complex than that and it can be also in "foreground" while in `.inactive` state:
> [**`applicationState`**](https://developer.apple.com/documentation/uikit/uiapplication/1623003-applicationstate)
> The app is **inactive at launch**, and then is generally in either an active or background state. …

RUMM-1765 Fix foreground app state reporting in `AppStateListener` - part 5 🏁

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Matchers/RUMSessionMatcher.swift

Backend stop processing view updates when one view reports `is_active: false`. 
Only send the attribute `is_active: false` after ongoing resources are consumed.

RUMM-1779 Keep view active until all resources are consumed

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/FeaturesIntegration/WebView/WKUserContentController+Datadog.swift
Sources/Datadog/FeaturesIntegration/WebView/WebEventBridge.swift
Sources/Datadog/FeaturesIntegration/WebView/WebLogEventConsumer.swift
Sources/Datadog/FeaturesIntegration/WebView/WebRUMEventConsumer.swift
Sources/Datadog/Logging/Log/LogEventEncoder.swift
Tests/DatadogTests/Datadog/RUM/WebView/WKUserContentController+DatadogTests.swift
Tests/DatadogTests/Datadog/RUM/WebView/WebEventBridgeTests.swift
Tests/DatadogTests/Datadog/RUM/WebView/WebLogEventConsumerTests.swift
Tests/DatadogTests/Datadog/RUM/WebView/WebRUMEventConsumerTests.swift

Datadog `browser-sdk` integration will send log and RUM events to the native SDK and these events will be decorated with the contextual information of the native app.
That way any app with web view can display its users' session in the same timeline, native + webview.
Once the message is passed from `browser-sdk`, a JS script will catch it and pass it to either `WebLogEventConsumer` or `WebRUMEventConsumer`.
Then they will add information to events and persist them in the filesystem where they wait to be uploaded to Datadog.

RUMM-1791 WebEventConsumers added

---

tools/distribution/release.py
tools/distribution/src/assets/gh_asset.py
tools/distribution/src/directory_matcher.py
tools/distribution/src/semver.py
tools/distribution/tests/test_directory_matcher.py
tools/distribution/tests/test_semver.py

📦 This PR updates our release automation so it can conditionally include/exclude certain `XCFrameworks` from GitHub release asset validation (`.*zip`). This is required as starting from `1.9.0` SDK will no longer depend on `Kronos.xcframework` (#701), but when (re)building historical tags, we want it to be included.
I extracted the code for validating each `XCFramework` and used OCP to make it configurable for a certain range of `Version`.

RUMM-1744 Update release tool to conditionally validate `Kronos.xcframework`

---

docs/rum_collection/crash_reporting.md

Updates documentation to clarify Swift Package Manager linking, as linking both `Datadog` and `DatadogCrashReporting` libraries will result in duplicated symbols.

RUMM-1799 Clarify Linking Crash Reporting Using SPM

---

Sources/Datadog/FeaturesIntegration/WebView/WKUserContentController+Datadog.swift
Sources/Datadog/FeaturesIntegration/WebView/WebRUMEventConsumer.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Tests/DatadogTests/Datadog/RUM/WebView/WebRUMEventConsumerTests.swift

With `browser-sdk` integration, iOS SDK can receive RUM events from the web views. Yet, these events don't pass through the same pipeline that regular RUM events pass. This may result in expired sessions while receiving events from the web views.
`RUMWebViewCommand` is an empty command that keeps the session alive and it is sent every time `WebRUMEventConsumer` receives an event.

RUMM-1793 WebView events fire RUMWebViewCommand

---

Sources/Datadog/Core/System/Time/DateCorrector.swift
Sources/Datadog/Core/System/Time/ServerDateProvider.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashContext/CrashContextProviderTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewIdentityTests.swift
Tests/DatadogTests/Datadog/RUM/RUMVitals/VitalRefreshRateReaderTests.swift
Tests/DatadogTests/Helpers/XCTestCase.swift

🔬 This PR addresses tests flakiness from last month - collected from 189K test runs on the main branch:
* green - reproduced and fixed;
* orange - cannot reproduce, added more verbosity;
* other - too little data;
Each case explained in PR comments. There's no general conclusion.

RUMM-1890 Fix tests flakiness

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/E2ETests/NTP/KronosE2ETests.swift
Sources/Datadog/Core/System/Time/ServerDateProvider.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/InternalMonitoring/Kronos/KronosMonitor.swift
Sources/Datadog/Kronos/KronosClock.swift
Sources/Datadog/Kronos/KronosNTPClient.swift
Tests/DatadogTests/Datadog/InternalMonitoring/Kronos/KronosMonitorTests.swift

📦🔬 This PR adds `KronosMonitor` for collecting internal telemetry on Kronos execution (NTP sync). This is to gather more data and have more observability on #647.
**Note:** this additional telemetry will only  be collected in apps that enable our Internal Monitoring feature, which means our own dogfood 🐶 projects. It won't be collected from customer apps.
`KronosMonitor` traces 3 phases of Kronos execution: 
* overall clock sync, 
* DNS resolution,
* UDP connection to each resolved IP.
```swift
internal protocol KronosMonitor {
// MARK: - Clock sync
func notifySyncStart(from pool: String)
func notifySyncEnd(serverOffset: TimeInterval?)
// MARK: - DNS resolution
func notifyResolveDNS(to addresses: [KronosInternetAddress])
// MARK: - IP querying
func notifyStartQuerying(ip address: …
```

RUMM-1744 Collect Kronos telemetry in Internal Monitoring

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift

Targeting 🐶 Dogfooding.
Log `ActivePrewarm` process variable while monitoring `MetricKit` with internal monitoring. This attribute will help us in deciding how we can leverage this value when reporting Application Launch Time.

RUMM-1803 Add internal monitoring to 'ActivePrewarm' process variable

---

Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift
Sources/Datadog/RUM/DataModels/RUMDataModels.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/DatadogObjc/RUM/RUMDataModels+objc.swift
Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift

Adds support for flutter error source (RUMM-1900)
Ran the Schema generator

RUMM-1900/1904 Update RUM Schema

---

Sources/Datadog/FeaturesIntegration/WebView/WebRUMEventConsumer.swift
Tests/DatadogTests/Datadog/RUM/WebView/WebRUMEventConsumerTests.swift

`WebRUMEvent` dates were being corrected with time offsets in nanoseconds.
That resulted in dropped events as the date format is in milliseconds.
Time offsets format is changed to milliseconds, now the events are visible in Datadog UI.

RUMM-1649 Fix: WebRUMEvent date offset in Ms

---

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogBenchmarkTests.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCrashReporting.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc.xcscheme
Datadog/TargetSupport/DatadogIntegrationTests/DatadogIntegrationTests.xctestplan
Makefile

Update to version 1.1.0 of testing framework 
Update the version in Makefile
Update test targets so they keep the previous behaviour (Stdout and Stderr capturing must be explicitly activated now)

Update to version 1.1.0 of testing framework

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
Datadog/Example/Debugging/DebugWebviewViewController.swift
Datadog/Example/Scenarios/WebView/WebViewScenarios.swift
Datadog/Example/Scenarios/WebView/WebViewTrackingFixtureViewController.swift
Datadog/Example/Scenarios/WebView/WebViewTrackingScenario.storyboard
Datadog/TargetSupport/DatadogIntegrationTests/DatadogCrashReportingIntegrationTests.xctestplan
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMCommonAsserts.swift
Tests/DatadogIntegrationTests/Scenarios/WebView/WebViewScenarioTest.swift
Tests/DatadogTests/Matchers/RUMEventMatcher.swift
Tests/DatadogTests/Matchers/RUMSessionMatcher.swift

Adding integration test to WebView tracking feature.
In this new test, the app opens a WebView which loads Browser SDK instrumented content. The iOS SDK should transport all RUM events and Logs received from Browser SDK.

RUMM-1649 WebViewTracking integration test added

---

Datadog/Example/Debugging/DebugWebviewViewController.swift
Sources/Datadog/FeaturesIntegration/WebView/WebLogEventConsumer.swift
Tests/DatadogTests/Datadog/RUM/WebView/WebLogEventConsumerTests.swift

🐞 This PR fixes bug with WebView logs processing. Due to wrong date correction, WebView logs were rejected by BE.
Correction logic was using `ns`, instead of `ms`.

RUMM-1924 Fix bug with WebView logs not appearing in Logs Explorer

---

Sources/DatadogCrashReporting/PLCrashReporterIntegration/CrashReport.swift
Sources/DatadogCrashReporting/PLCrashReporterIntegration/DDCrashReportExporter.swift
Tests/DatadogCrashReportingTests/Mocks.swift
Tests/DatadogCrashReportingTests/PLCrashReporterIntegration/DDCrashReportExporterTests.swift

Stack frames in crash report could be reported as `???` if PLCR could not find the image or if the image's UUID is missing. To identify the root cause, we should keep reporting binary images without UUID.
- Set `StackFrame.libraryName` even for binary image with no UUID
- Allow optional `uuid` in `BinaryImageInfo`

RUMM-1883 Report binary image with no UUID

---

Datadog/Example/Debugging/DebugWebviewViewController.swift
Datadog/Example/Scenarios/WebView/WebViewTrackingFixtureViewController.swift
Makefile
Sources/Datadog/FeaturesIntegration/WebView/WKUserContentController+Datadog.swift
Tests/DatadogIntegrationTests/Scenarios/WebView/WebViewScenarioTest.swift
Tests/DatadogTests/Datadog/RUM/WebView/WKUserContentController+DatadogTests.swift
Tests/DatadogTests/Datadog/RUM/WebView/WebRUMEventConsumerTests.swift

📦 This PR adds last changes to `hybrid-application` branch to prepare it for dogfooding.
* Adjusted public API naming, added docs string comments;
* Resolved obsolete `TODOs`;
Additionally, it hides the entry code to WebView tracking behind `DD_SDK_ENABLE_EXPERIMENTAL_APIS` compiler flag. We used this feature flag successfully to disable Crash Reporting in #487. This will let us safely merge `hybrid-application` to `master` and further to `dogfooding`. This flag is defined in [`dogfooding/Package.swift`](https://github.com/DataDog/dd-sdk-ios/blob/ab6796174f8b9a80ea205b335430d1afe911fef5/Package.swift#L54) so the feature will be visible in dogfood projects.
⚠️ This will require adding `DD_SDK_ENABLE_EXPERIMENTAL_APIS` to `Base.local.xcconfig` for local development. This is automated as …

RUMM-1911 Prepare WebView tracking for dogfooding

---

Sources/Datadog/FeaturesIntegration/WebView/WebEventBridge.swift

📦 This PR fixes compiler issue in nightly tests (Xcode 12.4 x macOS Catalina):
```
▸ Compiling WebEventBridge.swift
❌  /Users/vagrant/git/Sources/Datadog/FeaturesIntegration/WebView/WebEventBridge.swift:44:80: variable declared in 'guard' condition is not usable in its body
throw WebEventError.invalidMessage(description: String(describing: message))
^
```
I just renamed this parameter to make it distinct in guard's scope.

RUMM-1911 Fix compilation issue in nightly tests (macOS Catalina)

---

Sources/Datadog/Tracing/AutoInstrumentation/URLSessionTracingHandler.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift
Tests/DatadogTests/Datadog/Tracing/Autoinstrumentation/URLSessionTracingHandlerTests.swift

Spans have a limited number of unique resource values. Removing query parameters ensure we don't use too many unique slots, and aligns the iOS SDK with android and other APM implementations.

RUMM-1910 Strip query parameters from span resource

---

tools/distribution/release.py
tools/distribution/src/assets/gh_asset.py
tools/distribution/src/utils.py

📦 This PR adds an option to our distribution tool for including the Xcode version in produced GH assets. This is required as due to a 🐞 bug in Swift compiler (https://bugs.swift.org/browse/SR-14195) we can't produce truly portable XCFrameworks - the `.swiftinterface` emitted for [Module Stability](https://www.swift.org/blog/abi-stability-and-more/) of `Datadog.xcframework` is ambiguous (more on this in `RUMM-1934` JIRA).
The idea is to use this flag and produce multiple GH Assets for each release:
* `Datadog-x.y.z.zip` - built with recent version of Xcode;
* `Datadog-x.y.z-Xcode-a.b.c.zip` - built with previous version of Xcode;
* `...` - same for reasonable number of previous Xcode versions.
The existing `--overwrite-github` option in `release.py` will allow us to overwrite existing …

RUMM-1934 Add option for including Xcode version in produced GH asset

---

Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift
Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift
Tests/DatadogTests/Datadog/RUM/Scrubbing/RUMEventsMapperTests.swift

Add test coverage for `RUMCrashEvent` scrubbing introduced in #734.
> Using `rum-model-generator` to support local schema that extend `error-schema.jon` requires non-trivial changes that will be tracked in RUMM-1949.

RUMM-1584 Test crash event scrubbing

---

docs/log_collection.md
docs/rum_collection/_index.md
docs/rum_collection/advanced_configuration.md
docs/trace_collection.md

Add Objective-C version to all snippets when applicable.

RUMM-1769 Add Objective-C documentation snippets

---

Sources/Datadog/FeaturesIntegration/WebView/WKUserContentController+Datadog.swift
Tests/DatadogTests/Datadog/RUM/WebView/WKUserContentController+DatadogTests.swift

If `trackDatadogEvents` method is called multiple times, it crashes the app.
The reason is that calling `WKUserContentController.add(messageHandler:, name:)` multiple times with the same `name` crashes the app.
`trackDatadogEvents` method removes already-added components before adding them.

RUMM-1955 Multiple calls to trackDatadogEvents handled

---

docs/README.md
docs/rum_collection/_index.md
docs/rum_collection/advanced_configuration.md
docs/rum_collection/crash_reporting.md
docs/rum_collection/data_collected.md
docs/rum_collection/troubleshooting.md

Implements absolute URLs for the doc site and copy nits.

DOCS-3052 iOS Monitoring Edits

---

Datadog/Example/Scenarios/WebView/WebViewTrackingFixtureViewController.swift
Sources/Datadog/FeaturesIntegration/WebView/WKUserContentController+Datadog.swift
Tests/DatadogTests/Datadog/RUM/WebView/WKUserContentController+DatadogTests.swift

Without removing `WKScriptMessageHandlers` explicitly, they stay alive in memory even after deallocation of the webview
By calling `stopTrackingDatadogEvents`, our users can remove Datadog components from their `WKWebViewConfiguration` instances so that `DatadogMessageHandler` can be deallocated.

RUMM-1931 stopTrackingDatadogEvents added to avoid memory leaks

---

Datadog/Example/AppConfiguration.swift
Datadog/Example/Environment.swift
Datadog/TargetSupport/Example/Info.plist
xcconfigs/Datadog.xcconfig

This PR is only for making it easier to switch between production and staging environments during development.
`Custom Logs/RUM URL`s are read from local `xcconfig` files, which are gitignored.
```
/// Datadog.local.xcconfig
// prod
CUSTOM_LOGS_URL=my.production.url
...
// staging
CUSTOM_LOGS_URL=my.staging.url
...
```
Now you can comment out the section you'd like and switch your development environment.

RUMM-1806 Custom Logs/RUM endpoints are read from xcconfig

---

Datadog/Example/Scenarios/URLSession/URLSessionScenarios.swift

⚙️ In #750 we added syntax to `Example` target which is not compatible with Xcode 12.x compiler:
```
❌  /Users/vagrant/git/Datadog/Example/Scenarios/URLSession/URLSessionScenarios.swift:92:34: cannot infer contextual base in reference to member 'allCases'
instrumentationMethod = .allCases.randomElement()!
~^~~~~~~~
```
It makes our nightly tests for iOS 11.x-13.x fail to compile, as these require Xcode 12.x.
```diff
-        instrumentationMethod = .allCases.randomElement()!
+        instrumentationMethod = InstrumentationMethod.allCases.randomElement()!
```
I made sure everything else compiles in Xcode 12.x.

RUMS-481 Fix nightly tests compilation issue in Xcode 12.x

---

docs/log_collection.md
docs/rum_collection/data_collected.md
docs/trace_collection.md

Document cleartext data storage in cache directory.

RUMM-1939 Document data storage regarding encryption

---

Tests/DatadogIntegrationTests/Scenarios/CrashReporting/CrashReportingWithLoggingScenarioTests.swift

Fix `CrashReportingWithLoggingScenarioTests.testCrashReportingCollectOrSendWithLoggingScenario` flakiness.

Fix integration test flakiness

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog iOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCrashReporting iOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogIntegrationTests.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc iOS.xcscheme
Makefile
bitrise.yml
tools/nightly-unit-tests/bitrise.yml.src
xcconfigs/Base.xcconfig

Add `iOS` suffix to iOS targets to prepare addition of `tvOS` targets.

RUMM-2033 Rename iOS targets

---

Sources/Datadog/Core/Upload/RequestBuilder.swift
Tests/DatadogTests/Datadog/Core/Upload/RequestBuilderTests.swift

Prevent any non alpha numeric character from app name when building the user agent

RUMM-2010 Sanitize app name in User Agent

---

Tests/DatadogTests/Datadog/InternalMonitoring/InternalMonitoringFeatureTests.swift
Tests/DatadogTests/Datadog/Logging/LoggingFeatureTests.swift
Tests/DatadogTests/Datadog/RUM/RUMFeatureTests.swift
Tests/DatadogTests/Datadog/Tracing/TracingFeatureTests.swift

⚙️ This PR fixes user agent header tests flakiness.
In #769 we added sanitisation for the "app name" component in UA header. This change wasn't reflected in dependant HTTP message tests, which assert the value of UA header. The random input generated for these tests was allowing whitespaces, now sanitised in upstream logic.
Because we test random input sanitisation separately (in UA sanitisation tests), to fix the problem here, I only adjusted characters range for the input used in HTTP message tests.

RUMM-2010 Fix User-Agent tests flakiness

---

tools/distribution/update_upstream_sdks.py

The Flutter package moved and got renamed in the dd-sdk-flutter repository. This will point it to the correct location.

Fix update_upstream script for new Flutter plugin location

---

Sources/Datadog/RUM/DataModels/RUMDataModels.swift
Sources/DatadogObjc/RUM/RUMDataModels+objc.swift
tools/rum-models-generator/Package.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/JSON/JSONSchema.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/JSON/JSONSchemaReader.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/RUMModelsGenerator.swift
tools/rum-models-generator/Sources/rum-models-generator/main.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Fixtures/fixture-json-schema-to-json-type-transformer.json
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Fixtures/fixture-json-schema-to-json-type-transformer/main.json
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Fixtures/fixture-json-schema-to-json-type-transformer/schema-1.json
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Fixtures/fixture-json-schema-to-json-type-transformer/schema-2.json
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Fixtures/fixture-reading-schema-with-additional-properties-with-no-type.json
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Fixtures/fixture-reading-schema-with-typed-additional-properties.json
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Input/JSONSchemaReaderTests.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Input/JSONSchemaToJSONTypeTransformerTests.swift
tools/rum-models-generator/run.sh

The `rum-models-generator` cli is too opinionated on the schema files tree, with recent changes in [rum-events-format](https://github.com/DataDog/rum-events-format) and the addition of telemetry events, the generator needs to be updated to digest the events formats from the root definition defined in [rum-events-format](https://github.com/DataDog/rum-events-format/blob/master/rum-events-format.json).
The `rum-models-generator` now takes the `rum-events-format.json` file path as an argument and is able to transverse schemas by navigating in the directories based on the `oneOf` references. This is possible because `$ref` value is always the relative path to the referred schema.
[`RUMDataModels.swift`](https://github.com/DataDog/dd-sdk-ios/compare/maxep/RUMM-2020/telemetry-schema?expand=1#dif …

RUMM-2020 Generate models from root schema file

---

docs/rum_collection/crash_reporting.md

Updates iOS Crash Reporting and Error Tracking page with improved information architecture and copy.
Thanks @ncreated for the insights and suggestions!
DOCS-2567

DOCS-2567 iOS Crash Reporting and Error Tracking Edits

---

CHANGELOG.md
Sources/Datadog/Core/System/LaunchTimeProvider.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/_Datadog_Private/ObjcAppLaunchHandler.m
Sources/_Datadog_Private/include/ObjcAppLaunchHandler.h
Tests/DatadogTests/Datadog/Core/System/LaunchTimeProviderTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift

Don't report launch time for pre-warmed process.
[RFC 2353430547](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/2353430547)
```objective-c
// isActivePrewarm = [NSProcessInfo.processInfo.environment[@"ActivePrewarm"] isEqualToString:@"1"];
BOOL __dd_private_isActivePrewarm() {
if (isActivePrewarm) return isActivePrewarm;
CFTimeInterval time = __dd_private_AppLaunchTime();
return time > ValidAppLaunchTimeThreshold;
}
```

RUMM-1803 Stop reporting pre-warmed application launch time

---

tools/distribution/release.py
tools/distribution/src/release/assets/gh_asset.py
tools/distribution/src/release/semver.py

Build and validate XCFrameworks with tvOS slices for sdk versions greater or equal to `1.10.0`.
`carthage build --platform iOS,tvOS --use-xcframeworks`

RUMM-2054 Build xcframework with tvos slices

---

CHANGELOG.md
Sources/DatadogCrashReporting/PLCrashReporterIntegration/DDCrashReportExporter.swift
Tests/DatadogCrashReportingTests/PLCrashReporterIntegration/DDCrashReportExporterTests.swift

📦 This PR aims at improving the symbolicated `error.stack` by removing trailing `???` frame (if present). 
Going from this:
to this:
The root cause of `???` is lack of library base address resolved for the frame. This makes its symbolication impossible. This line describes the very entry point to the code execution (even before `main`), so nothing actionable. To keep the symbolicated stack clean and avoid false positive symbolication errors, we truncate it.
Only the last frame is dropped and only if it couldn't be symbolicated.

RUMM-2025 Filter out unrecognized trailing stack frame in `error.stack`

---

CHANGELOG.md
Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Feature.swift
Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/Core/Persistence/DataEncryption.swift
Sources/Datadog/Core/Persistence/DataFormat.swift
Sources/Datadog/Core/Persistence/Reading/FileReader.swift
Sources/Datadog/Core/Persistence/Writing/FileWriter.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/DatadogObjc/DatadogConfiguration+objc.swift
Tests/DatadogBenchmarkTests/BenchmarkMocks.swift
Tests/DatadogTests/Datadog/Core/Persistence/Reading/FileReaderTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Writing/FileWriterTests.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/Datadog/InternalMonitoring/InternalMonitoringFeatureTests.swift
Tests/DatadogTests/Datadog/Logging/LoggingFeatureTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMFeatureTests.swift
Tests/DatadogTests/Datadog/Tracing/TracingFeatureTests.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift
Tests/DatadogTests/DatadogObjc/ObjcAPITests/DDConfiguration+apiTests.m

Allow users to set custom encryption routines for on-disk data storage.
Expect an implementation of the following protocol:
```swift 
/// Interface that allows storing data in encrypted format. Encryption/decryption round should
/// return exactly the same data as it given for the encryption originally (even if decryption
/// happens in another process/app launch).
public protocol DataEncryption {
/// Encrypts given `Data` with user-chosen encryption.
///
/// - Parameter data: Data to encrypt.
/// - Returns: The encrypted data.
func encrypt(data: Data) throws -> Data
/// Decrypts given `Data` with user-chosen encryption.
///
/// Beware that data to decrypt could be encrypted in a previous
/// app launch, so implementation should be aware of the case when decryption could
/// fail (for …
```

RUMM-1870 Add data encryption interface

---

tools/distribution/dogfood.py
tools/distribution/src/dogfood/package_resolved.py
tools/distribution/tests/dogfood/test_package_resolved.py

⚙️ This PR fixes the problem of the recent dogfooding automation [failure](https://github.com/DataDog/dd-sdk-ios/runs/5816985836):
```
❌ Failed to dogfood: .package.resolved uses version 2 but `package_resolved.py` supports version 1. Update `package_resolved.py` to new format.
```
https://github.com/apple/swift-package-manager/pull/3717 introduced a new format of `package.resolved` in Swfit 5.6 toolchain ([CHANGELOG](https://github.com/apple/swift-package-manager/pull/3717)). Before, both `dd-sdk-ios` and its dependant projects (Shopist iOS and Datadog iOS app) were using `package.resolved` in `version: 1`. Recently, Datadog iOS app's build was upgraded to new toolchain and it uses `version: 2`.
This PR enhances `dogfood` script to support both formats, so we can freely use different …

Update `dogfood` tool to support new format of `package.resolved`

---

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog tvOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCrashReporting tvOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc tvOS.xcscheme
Makefile

Fix CI Visiblity testing. 
FRAMEWORK_SEARCH_PATHS and LD_RUNPATH_SEARCH_PATHS were not properly set 
Expand test environment variables in tvOS targets 

Fix CI Visiblity testing

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift

Prevent sending negative `view.time_spent`.
Report `time_spent` with a minimal value of 1 nano second.
- [ ] ~~Add CHANGELOG entry for user facing change.~~

RUMM-2079 `time_spent` can't be lower than 1ns

---

docs/rum_collection/crash_reporting.md

this is a really small nitpicky PR. the pronoun `it` in the previous version had an unclear antecedent, which was flagged by transifex. i've rewritten this sentence for better syntactical clarity.

clarifying a sentence in crash reporting doc

---

docs/rum_collection/_index.md
docs/rum_collection/crash_reporting.md

Updates the iOS Monitoring doc page announcing that the SDK now supports tvOS and iOS.
Slack convo with Maxime.

DOCS-3269 tvOS and iOS Support in iOS Monitoring Documentation

---

Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/Example/AppConfiguration.swift
Datadog/Example/Environment.swift
Datadog/Example/Utils/MessagePortChannel.swift
Datadog/Example/Utils/RUMSessionEndView.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMCommonAsserts.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMManualInstrumentationScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMMobileVitalsScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMModalViewsScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMNavigationControllerScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMResourcesScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMScrubbingScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMSwiftUIScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMTabBarControllerScenarioTests.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMTapActionScenarioTests.swift
Tests/DatadogIntegrationTests/UITestsHelpers.swift

📦 This PR updates our integration tests so they no longer depend on the number of `RUMViewEvents` sent during each RUM scenario. This is a preliminary enhancement for _"RUMM-2029 Reduce number of view updates"_ coming in next PR.
The old approach of awaiting for certain `view.resource.count` or `view.action.count` in integration tests was too fragile as it strictly depends on the number of view events we send. In upcoming `RUMM-2029` work we can't guarantee presence of every "intermediate" update, so in case of last view being not stopped, we will miss some events in integration tests:
In upcoming `RUMM-2029` work we will reduce the number of "intermediate" updates, but keep the "initial" and "terminal" ones. With that in mind, and knowing the RUM principle of _"starting a new view stops …

RUMM-2029 Make integration tests not depend on the number of view updates

---

CHANGELOG.md

⚙️🧰 This PR fixes the `CHANGELOG.md` after:
* #814 
It was altered by the git conflict resolution strategy we define in [`.gitattributes`](https://github.com/DataDog/dd-sdk-ios/blob/develop/%20.gitattributes):
```
CHANGELOG.md merge=union
```
Reviewed all entries manually and fixed them to reflect released / unreleased items.
- [ ] ~Make sure each commit and the PR mention the Issue number or JIRA reference~
- [ ] ~Add CHANGELOG entry for user facing change.~

Fix `CHANGELOG.md` after `1.10.0` release

---

docs/rum_collection/web_view_tracking.md

Adds iOS Web View Tracking documentation.
DOCS-3019
Preview link in Documentation PR: https://docs-staging.datadoghq.com/alai97/single-sourcing-web-view-tracking-docs/real_user_monitoring/ios/web_view_tracking/.

DOCS-3019 Adds iOS Web View Tracking Documentation

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Telemetry.swift
Sources/Datadog/DDRUMMonitor.swift
Sources/Datadog/RUM/RUMContext/RUMCurrentContext.swift
Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
Sources/Datadog/RUM/RUMTelemetry.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMTelemetryTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift

Isolate RUM Telemetry apis for cross feature usage.
Creates a `Telemetry` protocol to be used across features and in core layer of the SDK. RUM then complies to the protocol through `RUMTelemetry` to send debug and error messages as RUM Telemetry events.
- [ ] ~~Add CHANGELOG entry for user facing change.~~

RUMM-2024 Isolate telemetry apis

---

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog iOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog tvOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogBenchmarkTests.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCrashReporting iOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCrashReporting tvOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc iOS.xcscheme
Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc tvOS.xcscheme
Datadog/TargetSupport/DatadogIntegrationTests/DatadogIntegrationTests.xctestplan
Makefile

Update to version 2.0.0 of the testing framework
Update DD_SDK_SWIFT_TESTING_VERSION to 2.0.0 in Makefile
Use DD_API_KEY instead of DATADOG_CLIENT_TOKEN

Update to version 2.0.0 of the testing framework

---

.github/PULL_REQUEST_TEMPLATE.md
bitrise.yml
tools/ci/Makefile
tools/ci/choose_workflows.py
tools/ci/src/ci_context.py
tools/ci/src/utils.py
tools/license/check-license.sh

⚙️🔨  This PR proposes an improvement to our CI pipelines configuration. The goal is to reduce the duration of CI builds for different triggers. Recently this duration crossed the bar of 60 minutes, which clearly becomes a bottleneck in our workflow.
Average build duration (p95) for last 60 days (by "phases"):
Significant phases are:
* "setup" (~3 minutes) - preparing CI environment (installing PLCR, `dd-swift-testing` and CLIs),
* "unit tests" (~12.5 minutes) - running unit tests for iOS and tvOS (all products),
* "integration tests" (~18 minutes) - running integration tests for all products,
* "smoke tests" (~30 minutes) - testing SDK compatibility with Cocoapods, Carthage and SPM.
**Before**, these phases were always ran one after another for every pull request. Even if the PR was only …

RUMM-2110 Improve CI performance

---

CHANGELOG.md
Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Kronos/KronosDNSResolver.swift
Sources/Datadog/Kronos/KronosInternetAddress.swift
Tests/DatadogTests/Datadog/Kronos/KronosInternetAddressTests.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift

🐞 This PR aims at fixing https://github.com/DataDog/dd-sdk-ios/issues/647. As explained in https://github.com/DataDog/dd-sdk-ios/issues/647#issuecomment-1108489161 we found an evidence (in our internal telemetry) that in some circumstances Kronos (NTP) logic can try to query private IP and hence bring up the _"Local Network Permission"_ alert. 
This happens very rarely, and except a single hit in our logs we couldn't manage to reproduce it.
Our telemetry shows a clear attempt on querying `192.168.1.250`. To avoid this, in this PR we apply additional filtering in `KronosDNSResolver` to ensure that private IPs are never used for NTP sync.
If all resolved IPs are filtered out, Kronos will fail silently and fallback to previous known time correction (stored in user defaults). In case of fresh …

RUMM-2153 Prevent Kronos logic from querying private IPs

---

Datadog/Datadog.xcodeproj/project.pbxproj

Pre-iOS 13 simulators crash due to dyld issues at runtime during our nightly tests
[Apple's recommended way is implemented](https://developer.apple.com/forums/thread/126506)

RUMM-2152 SwiftUI linked weakly

---

Sources/Datadog/Datadog.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift
Sources/Datadog/RUM/DataModels/RUMDataModelsMapping.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMScopeDependencies.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUM/RUMTelemetry.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegrationTests.swift
Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMTelemetryTests.swift

The React Native and Flutter SDKs set the `_dd.source` additional property to have that change the `source` property of events. However, all of the RUM events were still only even using `ios` as the source. This should fix it so that, if a value is provided to the the `_dd.source` attribute map, that source is sent to RUMM 
Fixes RUMM-2162

Fix RUM events to support sending correctly configured `source` value

---

Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUM/RUMTelemetry.swift

⚙️ Fixes recent nightly tests failure (on Xcode 12.x stack):
```
❌ /Users/vagrant/git/Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift:198:22: value of optional type 'RUMResourceEvent.Source?' must be unwrapped to a value of type 'RUMResourceEvent.Source'
source: .init(rawValue: dependencies.source) ?? .ios,
```
Xcode 12.x compiler wasn't yet smart enough to infer type in such expressions:
```diff
- source: .init(rawValue: dependencies.source) ?? .ios,
```
I had to add the type information by hand:
```diff
+ source: RUMResourceEvent.Source(rawValue: dependencies.source) ?? .ios,
```

RUMM-2162 Fix compilation issue in Xcode 12.x

---

Datadog/E2ETests/Helpers/DatadogE2EHelpers.swift
Datadog/Example/AppConfiguration.swift
Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/Core/Telemetry.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/RUM/RUMFeature.swift
Sources/Datadog/RUM/RUMTelemetry.swift
Sources/Datadog/RUM/RUMVitals/VitalCPUReader.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMTelemetryTests.swift
Tests/DatadogTests/Matchers/RUMEventMatcher.swift

Add RUM telemetry event sampling, discard duplicates, and report up to 100 events per sessions.
`RUMTelemetry` class now takes a sampler parameter and implement a log validation before recording the telemetry event.

RUMM-2027 Add RUM Telemetry sampling

---

Datadog/TargetSupport/DatadogIntegrationTests/DatadogCrashReportingIntegrationTests.xctestplan

In order to avoid collision (both `DatadogSDKTesting` and our SDK have their own crash reporters) `DatadogCrashReportingIntegrationTests.xctestplan` disables `DatadogSDKTesting` by leaving env vars blank
Now `DatadogCrashReportingIntegrationTests.xctestplan` enables `DatadogSDKTesting` by feeding the correct env vars, on top of them it has `DD_DISABLE_CRASH_HANDLER` env var to disable `DatadogSDKTesting`'s crash reporter

RUMM-1227 DatadogSDKTesting is enabled for Crash tests

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Feature.swift
Sources/Datadog/Core/Persistence/DataBlock.swift
Sources/Datadog/Core/Persistence/Reading/FileReader.swift
Sources/Datadog/Core/Persistence/Writing/FileWriter.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/Logging/Log/LogEventSanitizer.swift
Sources/Datadog/Logging/LoggingFeature.swift
Sources/Datadog/RUM/RUMFeature.swift
Sources/Datadog/Tracing/TracingFeature.swift
Tests/DatadogTests/Datadog/Core/Persistence/DataBlockTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Reading/FileReaderTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Writing/FileWriterTests.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploadWorkerTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/Logging/LogOutputs/LogFileOutputTests.swift
Tests/DatadogTests/Datadog/RUM/RUMEventOutputs/RUMEventFileOutputTests.swift
Tests/DatadogTests/Datadog/Tracing/SpanOutputs/SpanFileOutputTests.swift

Write event to files in TLV format. This change prepares the introduction of event metadata to batches.
All events will be serialised in TLV format using the following byte alignment:
```
+-  2 bytes -+-   4 bytes   -+- n bytes -|
| block type | data size (n) |    data   |
+------------+---------------+-----------+
```
This `block type` is a 2 bytes value describing how to decode the data. In this PR, only code `0x00` identifying an event is used.
The `data size` is written in 4 bytes so we are more flexible in term of size limit.
By using TLV, the format differs from the RFC so we are more resilient to header (metadata) decoding failure.
Batches will be written in `v2` folders, this PR does not remove any `v1` folder, it will be dealt in another PR.

RUMM-2134 Write events to files in TLV format

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Feature.swift
Sources/Datadog/Core/Persistence/Migrating/DataMigrator.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/Logging/LoggingFeature.swift
Sources/Datadog/RUM/RUMFeature.swift
Sources/Datadog/Tracing/TracingFeature.swift
Tests/DatadogTests/Datadog/Core/Persistence/Migrating/DataMigratorTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/Mocks/FeatureDirectoriesMock.swift

Remove v1 feature folders when migrating to v2 storage.
Any `deprecated` directories defined in `FeatureDirectories` will be removed as part of the initial migration step.

RUMM-2134 Remove deprecated feature directories

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/DatadogCore/DatadogCore.swift
Sources/Datadog/DatadogInternal/DatadogCoreProtocol.swift
Tests/DatadogTests/Datadog/Mocks/DatadogCoreMock.swift

Creates a v1 feature registry in `DatadogCore` to use while migrating to v2 architecture.
`DatadogCoreProtocol` now expect 2 methods specific to v1 features registering.

RUMM-2133 Add v1 feature registry

---

Sources/Datadog/Core/Persistence/Files/Directory.swift
Sources/Datadog/CrashReporting/CrashReporter.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogCore/DatadogCore.swift
Sources/Datadog/FeaturesIntegration/WebView/WKUserContentController+Datadog.swift
Sources/Datadog/Logger.swift
Sources/Datadog/Logging/LoggingFeature.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashReporterTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/LoggerBuilderTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Logging/LoggingFeatureTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogCoreMock.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/WebView/WKUserContentController+DatadogTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/DatadogObjc/DDDatadogTests.swift
Tests/DatadogTests/DatadogObjc/DDLoggerTests.swift
Tests/DatadogTests/DatadogObjc/DDTracerTests.swift
Tests/DatadogTests/TestsObserver/DatadogTestsObserver.swift

Register Logs v1 in `DatadogCore`.
Remove `LoggingFeature.instance` singleton and other static access and expect a `DatadogCoreProtocol` complying instance when creating a `Logger`, `defaultDatadogCore` is used by default.

RUMM-2133 Register Logs v1 in `DatadogCore`

---

instrumented-tests/http-server-mock/Sources/HTTPServerMock/ServerMock.swift
instrumented-tests/http-server-mock/Sources/HTTPServerMock/ServerProcessRunner.swift
instrumented-tests/http-server-mock/Tests/HTTPServerMockTests/HTTPServerMockTests.swift
instrumented-tests/http-server-mock/python/server_address.py
instrumented-tests/http-server-mock/python/start_mock_server.py

`http-server-mock` was the last script still in py 2.
`BaseHTTPRequestHandler` now write `bytes` instead of `string` to fd.

Migrate http-server-mock to python3

---

tools/distribution/src/dogfood/repository.py
tools/distribution/update_upstream_sdks.py

⚙️🧰 This PR fixes the `update_upstream_sdks` tool to properly upgrade iOS SDK dependency in Flutter SDK.
Now it works: https://github.com/DataDog/dd-sdk-flutter/pull/127.
The problem was bad handling of the [`datadog_flutter_plugin.podspec`](https://github.com/DataDog/dd-sdk-flutter/blob/develop/packages/datadog_flutter_plugin/ios/datadog_flutter_plugin.podspec) modification. The script was not truncating the file before performing write operation, so after write the last line was still remaining:
🎁 As a bonus I fixed the problem of no author being reported for automated commits.

Fix `update_upstream_sdks` CI job

---

Sources/Datadog/Datadog.swift
Sources/Datadog/Logger.swift
Sources/Datadog/Tracer.swift
Sources/Datadog/Tracing/TracingFeature.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/LoggerBuilderTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogCoreMock.swift
Tests/DatadogTests/Datadog/Mocks/TracingFeatureMocks.swift
Tests/DatadogTests/Datadog/TracerConfigurationTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/Tracing/TracingFeatureTests.swift
Tests/DatadogTests/DatadogObjc/DDDatadogTests.swift
Tests/DatadogTests/DatadogObjc/DDGlobalTests.swift
Tests/DatadogTests/DatadogObjc/DDTracerTests.swift
Tests/DatadogTests/TestsObserver/DatadogTestsObserver.swift

Register Tracing v1 in `DatadogCore`.
Remove `TracingFeature.instance` singleton and other static access and expect a `DatadogCoreProtocol` complying instance when creating a `Tracer`, `defaultDatadogCore` is used by default.

RUMM-2133 Register Tracing v1 in `DatadogCore`

---

tools/distribution/update_upstream_sdks.py

Now that the Flutter plugin is split into multiple packages, we need to make sure to run `pod update` in all the sub-examples and integration test apps to make sure they all update their Podfile.lock files. This runs through all the packages in `packages` and updates all of them (including the main plugin).
This is based on #862 and needs to go in after it.

Fix update_upstream to run pod update in all sub-packages

---

docs/rum_collection/web_view_tracking.md

Adds RUM services information to introduce Unified Service Tagging.
DOCS-2277
https://docs-staging.datadoghq.com/alai97/rum-services-doc-updates/real_user_monitoring/ios/web_view_tracking/

DOCS-2277 iOS Web View Tracking Edits

---

Sources/Datadog/CrashReporting/CrashReportingFeature.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/FeaturesIntegration/RUMWithCrashContextIntegration.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMScopeDependencies.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMWithCrashContextIntegrationTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/DatadogObjc/DDRUMMonitorTests.swift
Tests/DatadogTests/TestsObserver/DatadogTestsObserver.swift

Register Crash Reporting v1 in `DatadogCore`.
Remove `CrashReportingFeature.instance` singleton and other static access.

RUMM-2133 Register Crash Reporting v1 in `DatadogCore`

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Feature.swift
Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/Core/Persistence/Files/Directory.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogCore/DatadogCore.swift
Sources/Datadog/DatadogInternal/DatadogCoreProtocol.swift
Sources/Datadog/DatadogInternal/DatadogV1Context.swift
Sources/Datadog/Logging/LoggingFeature.swift
Sources/Datadog/Logging/LoggingV2Configuration.swift
Sources/Datadog/RUM/RUMFeature.swift
Sources/Datadog/Tracing/TracingFeature.swift
Tests/DatadogBenchmarkTests/DataStorage/LoggingStorageBenchmarkTests.swift
Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift
Tests/DatadogTests/Datadog/Core/Persistence/Files/DirectoryTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/LoggerBuilderTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Logging/LoggingFeatureTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/DatadogCoreMock.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMFeatureTests.swift
Tests/DatadogTests/Datadog/RUM/WebView/WKUserContentController+DatadogTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/Tracing/TracingFeatureTests.swift
Tests/DatadogTests/DatadogObjc/DDDatadogTests.swift
Tests/DatadogTests/DatadogObjc/DDLoggerTests.swift
Tests/DatadogTests/DatadogObjc/DDTracerTests.swift
Tests/DatadogTests/Helpers/TestsDirectory.swift

⚙️🧰 This PR makes necessary refactoring to create V1 `LoggingFeature` from V2's storage and upload configurations.
Feature initialisation is now generic and can happen in `DatadogCore` with:
```swift
func create<Feature: V1Feature>(
storageConfiguration: FeatureStorageConfiguration,
uploadConfiguration: FeatureUploadConfiguration,
featureSpecificConfiguration: Feature.Configuration
) throws -> Feature 
```
The `featureSpecificConfiguration` is used to avoid impactful refactoring. It holds the feature-specific part of the config ([`FeaturesConfiguration.Logging`](https://github.com/DataDog/dd-sdk-ios/blob/b1c10dceeca16ab6e8f6a0f0314cedcf0b13dd61/Sources/Datadog/Core/FeaturesConfiguration.swift#L28-L32)). It will be removed as the last step after migrating other features to this setup.
I …

RUMM-2169 Initialise V1 Logging with V2 configuration

---

Tests/DatadogIntegrationTests/Scenarios/WebView/WebViewScenarioTest.swift

Browser SDK support action id as string or as array of strings as defined in schema:
https://github.com/DataDog/rum-events-format/blob/master/schemas/rum/_action-child-schema.json#L15L31
This is not yet supported by the Swift schema generator, as a workaround we pick the first id when
we encounter an array.

Patch Browser Action Events with array of ids

---

Sources/Datadog/Datadog.swift
Sources/Datadog/RUMMonitor.swift
Sources/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegate.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptor.swift
Sources/Datadog/URLSessionAutoInstrumentation/URLSessionAutoInstrumentation.swift
Sources/Datadog/URLSessionAutoInstrumentation/URLSessionSwizzler.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogCoreMock.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegateTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/URLSessionAutoInstrumentationTests.swift
Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/URLSessionSwizzlerTests.swift
Tests/DatadogTests/DatadogObjc/DDDatadogTests.swift
Tests/DatadogTests/DatadogObjc/DDNSURLSessionDelegateTests.swift
Tests/DatadogTests/TestsObserver/DatadogTestsObserver.swift

Register `URLSession` instrumentation v1 in `DatadogCore`.
Remove `URLSessionAutoInstrumentation.instance` singleton and other static access and expect a `DatadogCoreProtocol` complying instance when creating a `DDURLSessionDelegate`, `defaultDatadogCore` is used by default.

RUMM-2133 Register `URLSession` Instrumentation v1 in `DatadogCore`

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogCore/DatadogCore.swift
Sources/Datadog/Logging/LoggingFeature.swift
Sources/Datadog/RUM/RUMFeature.swift
Sources/Datadog/RUM/RUMV2Configuration.swift
Tests/DatadogBenchmarkTests/DataStorage/RUMStorageBenchmarkTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMIntegrationsTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMFeatureTests.swift
Tests/DatadogTests/Datadog/RUM/RUMTelemetryTests.swift
Tests/DatadogTests/Datadog/RUM/WebView/WKUserContentController+DatadogTests.swift
Tests/DatadogTests/Datadog/RUMMonitorConfigurationTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/DatadogObjc/DDRUMMonitorTests.swift

⚙️🧰 This PR makes necessary refactoring to create V1 `RUMFeature` from V2's storage and upload configurations.
Based on the refactoring done in #866 for `LoggingFeature`, this PR applies similar configuration to RUM.

RUMM-2169 Initialise V1 RUM with V2 configuration 

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogCore/DatadogCore.swift
Sources/Datadog/DatadogInternal/DatadogCoreProtocol.swift
Sources/Datadog/DatadogInternal/DatadogV1CoreProtocol.swift
Sources/Datadog/FeaturesIntegration/WebView/WKUserContentController+Datadog.swift
Sources/Datadog/Logger.swift
Sources/Datadog/RUM/Instrumentation/Views/SwiftUI/SwiftUIViewModifier.swift
Sources/Datadog/RUM/RUMTelemetry.swift
Sources/Datadog/RUMMonitor.swift
Sources/Datadog/Tracer.swift
Sources/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegate.swift
Sources/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptor.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/LoggerBuilderTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogCoreMock.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/TracingFeatureMocks.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/TracerConfigurationTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/DatadogObjc/DDDatadogTests.swift
Tests/DatadogTests/DatadogObjc/DDGlobalTests.swift
Tests/DatadogTests/DatadogObjc/DDLoggerTests.swift
Tests/DatadogTests/DatadogObjc/DDRUMMonitorTests.swift
Tests/DatadogTests/TestsObserver/DatadogTestsObserver.swift

SDK V1 implementation defines multiple `internal` objects that need to stay hidden from the public interface while we migrate to v2 core module and configuration. The PR is a proposal to segregate v1 from v2 interfaces to be able to keep all v1 apis `internal`.
The `DatadogCoreProtocol` will internally expose a `v1` extension to access all v1 apis needed to register and retrieve features.
``` swift
extension DatadogCoreProtocol {
// Upcast `DatadogCoreProtocol` instance to `DatadogV1CoreProtocol`
// to access v1 related implementation.
// If upcasting fails, a `NOOPDatadogCore` instance is returned.
var v1: DatadogV1CoreProtocol {
self as? DatadogV1CoreProtocol ?? NOOPDatadogCore()
}
}
```

RUMM-2171 V1 Interface Segregation

---

Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/CrashReporting/CrashReporter.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogCore/DatadogCore.swift
Sources/Datadog/DatadogInternal/DatadogV1Context.swift
Sources/Datadog/DatadogInternal/DatadogV1CoreProtocol.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithLoggingIntegration.swift
Sources/Datadog/FeaturesIntegration/TracingWithLoggingIntegration.swift
Sources/Datadog/FeaturesIntegration/WebView/WKUserContentController+Datadog.swift
Sources/Datadog/Logger.swift
Sources/Datadog/Logging/LoggingFeature.swift
Sources/Datadog/Tracer.swift
Tests/DatadogTests/Datadog/CrashReporting/CrashReporterTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithLoggingIntegrationTests.swift
Tests/DatadogTests/Datadog/LoggerBuilderTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Logging/LoggingFeatureTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/DatadogCoreMock.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/WebView/WKUserContentController+DatadogTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/DatadogObjc/DDDatadogTests.swift
Tests/DatadogTests/DatadogObjc/DDLoggerTests.swift
Tests/DatadogTests/DatadogObjc/DDTracerTests.swift

🔨🧰 This PR makes `LoggingFeature` no longer depend on `CoreConfiguration` and `CoreDependencies`.
This refactoring is required to better isolate Feature modules from Core implementation. It prepares the codebase for further introduction of SDK context in V2.
There are two main changes and everything else is mainly their consequence:
* Common configuration is now removed from `FeaturesConfiguration.Logging`
```diff
struct Logging {
-   let common: Common
let uploadURL: URL
let logEventMapper: LogEventMapper?
}
```
* Common dependencies are now removed from `LoggingFeature` interface
```diff
internal final class LoggingFeature: V1FeatureInitializable {
// ...
-   // MARK: - Dependencies
- 
-   let dateProvider: DateProvider
-   let dateCorrector: DateCorrectorType
-   let userInfoProvider: …
```

RUMM-2169 Isolate Logging feature from Core's configuration and dependencies

---

Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/CrashReporting/CrashReporter.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogInternal/DatadogV1Context.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithLoggingIntegration.swift
Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift
Sources/Datadog/FeaturesIntegration/WebView/WKUserContentController+Datadog.swift
Sources/Datadog/RUM/RUMFeature.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMScopeDependencies.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegrationTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMIntegrationsTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Logging/LoggingFeatureTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMFeatureTests.swift
Tests/DatadogTests/Datadog/RUM/WebView/WKUserContentController+DatadogTests.swift
Tests/DatadogTests/Datadog/RUMMonitorConfigurationTests.swift
Tests/DatadogTests/Datadog/RUMMonitorTests.swift
Tests/DatadogTests/Datadog/Tracing/TracingFeatureTests.swift
Tests/DatadogTests/DatadogObjc/DDRUMMonitorTests.swift

🔨🧰 A counterpart of https://github.com/DataDog/dd-sdk-ios/pull/877 but for the `RUMFeature`.
> This refactoring is required to better isolate Feature modules from Core implementation. It prepares the codebase for further introduction of SDK context in V2.
Common configuration is now removed from `FeaturesConfiguration.RUM`:
```diff
struct RUM {
// ...
-   let common: Common
let uploadURL: URL
let applicationID: String
let sessionSampler: Sampler
// ...
}
```
Common dependencies are now removed from `RUMFeature` interface:
```diff
internal final class RUMFeature: V1FeatureInitializable {
// ...
-   // MARK: - Dependencies
-   let sdkInitDate: Date
-   let dateProvider: DateProvider
-   let dateCorrector: DateCorrectorType
-   let appStateListener: AppStateListening
-   let …
```

RUMM-2169 Isolate RUM feature from Core's configuration and dependencies

---

CHANGELOG.md
Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/RUM/RUMFeature.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMScopeDependencies.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUM/RUMVitals/VitalInfoSampler.swift
Sources/DatadogObjc/DatadogConfiguration+objc.swift
Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMIntegrationsTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMVitals/VitalInfoSamplerTests.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift
Tests/DatadogTests/DatadogObjc/ObjcAPITests/DDConfiguration+apiTests.m
docs/rum_collection/advanced_configuration.md

Customers can set the desired delay between Mobile Vitals update (CPU/RAM) as follows:
- FREQUENT - every 100ms 
- AVERAGE - 500 ms 
- RARE - 1000ms
- NEVER - don’t provide vitals data
`VitalInfoSampler` will start the sample timer only if `frequency` parameter is available.

RUMM-2077 Vitals Frequency Configuration

---

CHANGELOG.md
Sources/Datadog/Core/System/CarrierInfoProvider.swift
bitrise.yml

🐞 Solves #892 revealing Mac Catalyst compatibility broken in `1.11.0`.
It was broken incidentally  in https://github.com/DataDog/dd-sdk-ios/pull/764 and because we lost observability on it in smoke tests, the problem was not alerted.
First, I fixed the Mac Catalyst compatibility **smoke test** in `bitrise.yml`. This test started failing silently (we don't know when). Because it was based on 3rd-party [`cbf1/bitrise-step-xcodebuild`](https://github.com/cbf1/bitrise-step-xcodebuild) instead of tracing the problem, I replace it with plain 1st-party [`script`](https://github.com/bitrise-steplib/steps-script). We now run `xcodebuild` directly with `-euxo pipefail` flags to fail the job on any issues.
Second, I fixed the actual **implementation** by bringing back `#if …

RUMM-2256 Fix Mac Catalyst compatibility in `1.11.0`

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Directories.swift
Sources/Datadog/Core/Feature.swift
Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/Core/Utils/Cryptography.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/DatadogCore/DatadogCore.swift
Sources/Datadog/DatadogInternal/DatadogCoreProtocol.swift
Sources/Datadog/DatadogInternal/DatadogV1Context.swift
Sources/Datadog/Logging/LoggingV2Configuration.swift
Sources/Datadog/RUM/RUMV2Configuration.swift
Sources/Datadog/Tracing/TracingV2Configuration.swift
Tests/DatadogTests/Datadog/Core/DirectoriesTests.swift
Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift
Tests/DatadogTests/Datadog/Core/Utils/CryptographyTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/Logging/LoggingFeatureTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/DirectoriesMock.swift
Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMFeatureTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/Utils/RUMViewIdentityTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/Tracing/TracingFeatureTests.swift
Tests/DatadogTests/Helpers/TestsDirectory.swift
Tests/DatadogTests/TestsObserver/DatadogTestsObserver.swift

📦 With this PR, each instance of `DatadogCore` will use a different directory for managing its data.
This is a step forward towards V2 architecture, where we're going to support multiple SDK instances. Each instance of the SDK needs to persist data in different locations.
This is the content of `/Library/Caches/` when using two instances of `DatadogCore`:
Each `DatadogCore` now accepts a "core directory". I introduced a separate `CoreDirectory` type that wraps [`Directory`](https://github.com/DataDog/dd-sdk-ios/blob/ef343b1781218392790bd7085fad4b27628ea44b/Sources/Datadog/Core/Persistence/Files/Directory.swift#L10) - this is to enforce type safety at configuration level and to avoid passing wrong directory by mistake.
The `CoreDirectory` creates the folder structure for SDK and its …

RUMM-2203 Use unique data directory for each instance of the SDK

---

bitrise.yml
session-replay/.gitignore
session-replay/Package.swift
session-replay/README.md
session-replay/Sources/DatadogSessionReplay/Drafts/SessionReplayFeature.swift
session-replay/Tests/DatadogSessionReplayTests/SessionReplayFeatureTests.swift
tools/ci/choose_workflows.py
tools/ci/src/ci_context.py
tools/lint/sources.swiftlint.yml
tools/lint/tests.swiftlint.yml
tools/xcode-templates/Datadog/Swift File.xctemplate/TemplateInfo.plist
tools/xcode-templates/Datadog/Unit Test Case Class.xctemplate/TemplateInfo.plist

📦 This PR starts the Session Replay module 🥳. It will be an ongoing work, so it targets `feature/session-replay` branch. 
Initially, Session Replay module won't require any code from the main SDK, so it is created as a stand-alone and self-contained SPM package (under `session-replay/` folder). This will guarantee no conflicts with `develop` code and still enable code reuse through `.xcworkspace` if necessary.
Very likely, we will change the structure of `DatadogSessionReplay` package when extracting V2 modules.
* Created `DatadogSessionReplay` module with tests target;
* Updated linter to include `session-replay/` path;
* Updated CI to run unit tests for Session Replay conditionally (using existing `choose_workflows.py`, it will skip tests for other code if only `session-replay/*` paths …

RUMM-2264 Set up Session Replay module

---

Datadog/E2ETests/Helpers/LoggingE2EHelpers.swift

⛑ Fixes the problem in nightly E2E tests, were deprecated `Logger` APIs were still used:
```
❌  /Users/vagrant/git/Datadog/E2ETests/Helpers/LoggingE2EHelpers.swift:34:14: 'jsonWith(prefix:)' is deprecated: JSON format is no longer supported for console logs and this API will be removed in future versions
.jsonWith(prefix: .mockRandom()),
```
In #923 we deprecated two `Logger.Builder.ConsoleLogFormat` APIs: `.json` and `.jsonWith(prefix:)`, but we missed their use in E2E tests. Because CI builds are run with [_"Treat warnings as errors"_](https://github.com/DataDog/dd-sdk-ios/blob/7359006be4194184f7d506c3013dbf6da15e2981/Makefile#L32-L33), it caused a failure in recent nightly build.
Removed use of deprecated APIs from nightly tests.

RUMM-2239 Remove use of deprecated log format APIs in E2E tests

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Attributes/UserInfoProvider.swift
Sources/Datadog/DatadogCore/Context/UserInfoPublisher.swift
Sources/Datadog/DatadogInternal/Context/DatadogContext.swift
Sources/Datadog/DatadogInternal/Context/UserInfo.swift
Tests/DatadogTests/Datadog/DatadogCore/UserInfoPublisherTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogInternal/DatadogContextMock.swift

Publish user info to Datadog Context.
Implement a `UserInfoPublisher` that complies to `ContextValuePublisher` and provide `UserInfo` to the context. Setting the `current` user info property of the publisher will publish the value to the subscriber.

RUMM-2299 Core Context User Info Publisher

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/DatadogCore/Context/LaunchTimeReader.swift
Sources/Datadog/DatadogInternal/Context/DatadogContext.swift
Sources/Datadog/DatadogInternal/Context/LaunchTime.swift
Tests/DatadogTests/Datadog/Core/System/LaunchTimeProviderTests.swift
Tests/DatadogTests/Datadog/DatadogCore/LaunchTimeReaderTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogInternal/DatadogContextMock.swift

Provide Launch Time through Datadog Context.
Implement a `LaunchTimeReader` that complies to `ContextValueReader` and provide `LaunchTime` to the context.
The reader uses the objc `AppLaunchHandler` like the previous `LaunchTimeProvider`

RUMM-2299 Core Context Launch Time Reader

---

tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/JSON/JSONSchema.swift
tools/rum-models-generator/Sources/RUMModelsGeneratorCore/Input/Swift/JSONToSwiftTypeTransformer.swift
tools/rum-models-generator/Tests/rum-models-generator-coreTests/Input/JSONToSwiftTypeTransformerTests.swift

📦 This PR fixes 2 problems discovered when running models generation for Session Replay schemas. With this fix, the generator makes successful run on [session-replay-mobile-events-format.json](https://github.com/DataDog/rum-events-format/blob/master/session-replay-mobile-events-format.json) and prints Swift code.
This PR **doesn't yet**:
* Decorate SR models code appropriately. Similar to RUM, there are several things we may want to adjust in produced code (e.g. naming, or reusing common types) to make it more convenient to work with.
* Restructure `rum-models-generator` package to include separate generation tracks for RUM and SR.
Both elements will be delivered in next PRs.
First, I enhanced JSON schema reader with inferring `type` if it is not explicitly defined. This is the case of …

RUMM-2266 Enable Session Replay models generation

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/DatadogCore/Context/BatteryStatusReader.swift
Sources/Datadog/DatadogCore/Context/LowPowerModePublisher.swift
Sources/Datadog/DatadogCore/Upload/BatteryStatusV1.swift
Sources/Datadog/DatadogCore/Upload/DataUploadConditions.swift
Sources/Datadog/DatadogInternal/Context/BatteryStatus.swift
Sources/Datadog/DatadogInternal/Context/DatadogContext.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploadConditionsTests.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploadWorkerTests.swift
Tests/DatadogTests/Datadog/DatadogCore/BatteryStatusReaderTests.swift
Tests/DatadogTests/Datadog/DatadogCore/LowPowerModePublisherTests.swift
Tests/DatadogTests/Datadog/DatadogInternal/Context/BatteryStatusV1Tests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/DatadogInternal/DatadogContextMock.swift

Provide battery status and low battery mode through core context.
Introduce `BatteryStatusReader` and `LowPowerModePublisher` for providing the core context. The values have been split to reflect their respective data source and providing methods: reader vs. publisher.
Previous battery status is renamed to `BatteryStatusV1` but will be removed once the uploader is based on the v2 context.

RUMM-2207 Battery Status Reader and Low Battery Mode Publisher

---

bitrise.yml

🧪 In last 1 month, 16 out of 30 CI failures on `develop` came from Crash Reporting integration tests:
This PR is trying to address and solve this problem.
I suspect the issue comes from Apple Crash Reporter intercepting app crashes in Simulator. As a fix, I disable Apple's CR before running our CR integration tests:
```
launchctl unload -w /System/Library/LaunchAgents/com.apple.ReportCrash.plist
```
To test it, I ran CR integration tests 10x with this fix (20 tests in total), all green:

Fix CR integration tests flakiness 🤞

---

Sources/Datadog/DatadogInternal/Context/DeviceInfo.swift
Sources/Datadog/RUM/DataModels/RUMDataModels.swift
Sources/Datadog/RUM/RUMEvent/RUMDeviceInfo.swift
Sources/DatadogObjc/RUM/RUMDataModels+objc.swift
Tests/DatadogIntegrationTests/Scenarios/RUM/RUMManualInstrumentationScenarioTests.swift
Tests/DatadogTests/Datadog/DatadogInternal/Context/DeviceInfoTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMEvent/RUMDeviceInfoTests.swift

Flutter / Dart needs architecture in order to select the proper symbol file to process.  Currently, only add architecture if UIKit is imported
Add architecture when creating the DeviceInfo. I've added a few checks on the Integration tests to make sure that the architecture is present and is an expected value.

Add processor architecture to RUMDeviceInfo

---

docs/rum_collection/crash_reporting.md

Keeping the front matter for the Crash Reporting doc page in the `pull_config.yaml` file instead.
Will merge this PR in first, and then https://github.com/DataDog/documentation/pull/14702!

Removes Duplicate Front Matter

---

CHANGELOG.md
Package.swift

This package is the only one that cannot be used if our own project uses SwiftUI Previews in our own packages (ie. Xcode Project links a single SPM package that links all our other dependencies, though I'd tried other arrangements unsuccessfully). This is because all library products in this package explicitly specify either `.static` or `.dynamic`, which does not play well with Xcode's build system when it needs to wiggle things around for previews.
Specifically, when importing the static variant, previews fail with:
```
HumanReadableSwiftError
SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x00006000069648d0):'DatadogStatic'>)
```
and when it's dynamic:
```
PotentialCrashError: Update failed
XCPreviewAgent may have crashed. Check …
```

Can't compile for SwiftUI Previews

---

CHANGELOG.md
Datadog/Datadog.xcodeproj/project.pbxproj
Datadog/E2ETests/NTP/KronosE2ETests.swift
Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/Core/System/Time/DatadogNTPDateProvider.swift
Sources/Datadog/Core/System/Time/ServerDateCorrector.swift
Sources/Datadog/Core/System/Time/ServerDateProvider.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/Kronos/KronosClock.swift
Sources/DatadogObjc/DatadogConfiguration+objc.swift
Tests/DatadogTests/Datadog/Core/System/Time/DateCorrectionTests.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/Datadog/DatadogTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift

Expose clock synchronisation interface to allow custom implementation.
`ServerDateProvider` has now `public` access level and a custom provider can be injected at configuration. The list of Datadog NTP pools are also expose if needed.

RUMM-2341 Expose server date provider interface

---

Datadog/E2ETests/NTP/KronosE2ETests.swift

🐞 This PR fixes E2E tests build. It got broken yesterday with merge to `develop` (#950) and all our monitors failed at night.
Updates the use of an API that was changed from `internal` to `public`. Lack of this caused compiler error on CI:
```
❌  /Users/vagrant/git/Datadog/E2ETests/NTP/KronosE2ETests.swift:86:32: type 'DatadogNTPDateProvider' has no member 'datadogNTPServers'
DatadogNTPDateProvider.datadogNTPServers.forEach { ddNTPPool in
~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~
```
To avoid this situation in the future, I added `RUMM-2394 Add smoke test for E2E build on feature-branch` to our backlog.

Fix E2E tests build

---

Sources/Datadog/DatadogInternal/_InternalProxy.swift
Sources/Datadog/RUM/_RUMInternalProxy.swift

Add `public` to all the Internal Proxy methods as they need to be public to be useful.
Just add `public` in front.

Add public visibility to Internal Proxy methods.

---

docs/rum_collection/data_collected.md

Removes the `view.loading_time` metric.
#rum-docs, #support-rum Slack

iOS Monitoring Doc Edit

---

Sources/Datadog/RUM/DataModels/RUMDataModels.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/DatadogObjc/RUM/RUMDataModels+objc.swift
Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScopeTests.swift

Add the `error_tap` frustration signal when a Tap action leads to one or more errors
Update models and add frustration type `error_tap` to action event when the action scope has one or more error.

RUMM-2350 Detect error tap furstration

---

CHANGELOG.md
Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Core/Attributes/Attributes.swift
Sources/Datadog/Core/FeaturesConfiguration.swift
Sources/Datadog/Core/System/AppVersionProvider.swift
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogCore/DatadogCore.swift
Sources/Datadog/DatadogInternal/DatadogV1Context.swift
Sources/Datadog/DatadogInternal/_InternalProxy.swift
Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift
Tests/DatadogTests/Datadog/Core/System/AppVersionProviderTests.swift
Tests/DatadogTests/Datadog/DatadogInternal/_InternalProxyTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithLoggingIntegrationTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Logging/LoggingFeatureTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/DatadogInternal/DatadogCoreMock.swift
Tests/DatadogTests/Datadog/RUM/RUMFeatureTests.swift
Tests/DatadogTests/Datadog/RUM/WebView/WKUserContentController+DatadogTests.swift
Tests/DatadogTests/Datadog/RUMMonitorConfigurationTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/Tracing/TracingFeatureTests.swift
Tests/DatadogTests/DatadogObjc/DDLoggerTests.swift

📦 This PR adds `set(customVersion:)` API to internal proxy available in cross-platform SDKs. This is to unlock OTA use cases in RN, where `version` can change without restarting the app.
I added `AppVersionProvider`, which reads initial `version` from configuration (supporting `_dd.version ` override) and accepts its updates through `_InternalProxy.configuration` proxy.
Cross-platform SDKs can now customize `version` in 2 ways:
* on SDK init, by passing `"_dd.version"` in `additionalConfiguration`;
* later at runtime by using `Datadog._internal._configuration.set(customVersion:)`.
Aware of architectural changes made in https://github.com/DataDog/dd-sdk-ios/pull/947, notably the removal of `FeatureCommonDependencies` container, this new provider is added directly to `DatadogCore` - in the …

RUMM-2381 Add internal proxy API for customising app `version`

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/DatadogCore/DatadogCore.swift
Sources/Datadog/DatadogInternal/DatadogCoreProtocol.swift
Sources/Datadog/DatadogInternal/DatadogFeatureConfiguration.swift
Sources/Datadog/DatadogInternal/MessageBus/FeatureMessage.swift
Sources/Datadog/DatadogInternal/MessageBus/FeatureMessageAttributes.swift
Sources/Datadog/DatadogInternal/MessageBus/FeatureMessageReceiver.swift
Sources/Datadog/FeaturesIntegration/LoggingWithRUMIntegration.swift
Sources/Datadog/FeaturesIntegration/RUMIntegrations.swift
Sources/Datadog/Logger.swift
Sources/Datadog/Logging/RemoteLogger.swift
Sources/Datadog/RUM/RUMV2Configuration.swift
Sources/Datadog/RUMMonitor.swift
Tests/DatadogTests/Datadog/DatadogCore/MessageBusTests.swift
Tests/DatadogTests/Datadog/DatadogInternal/Context/FeatureMessageAttributesTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/RUMIntegrationsTests.swift
Tests/DatadogTests/Datadog/LoggerBuilderTests.swift
Tests/DatadogTests/Datadog/Mocks/DatadogInternal/DatadogCoreMock.swift
Tests/DatadogTests/Datadog/Mocks/DatadogInternal/MessageBusMock.swift
Tests/DatadogTests/Datadog/Mocks/DatadogInternal/PassthroughCoreMock.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMessageReceiverTests.swift

Send Log error to RUM through the message bus.
- Creates a `RUMMessageReceiver` that can receive `.error` messages. 
- The `RemoteLogger` now sends error log as message through `core`. The `LoggingWithRUMErrorsIntegration` has been removed.
The `FeatureMessageAttributes` has been added as a wrapper around `[String: Any]` for message attributes. This object allow reading attributes by their keys and types which greatly facilitate reading messages on the bus. It supports 2 ways of accessing attributes: The classic `subscript` and the [`@dynamicMemberLookup`](https://github.com/apple/swift-evolution/blob/f55963fb0abd77aae643882ca3fc8939b1f969f2/proposals/0195-dynamic-member-lookup.md)
```swift
var attributes: FeatureMessageAttributes = [
"key1": 1,
"key2": "value 2",
"key3": 3.0
]
let one = …
```

RUMM-2332 Log Error to RUM through message bus

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogInternal/Extensions/DatadogExtended.swift
Sources/Datadog/DatadogInternal/Extensions/Foundation+Datadog.swift
Sources/Datadog/Logging/Log/LogEventBuilder.swift
Sources/Datadog/Logging/LoggingV2Configuration.swift
Sources/Datadog/Logging/RemoteLogger.swift
Sources/Datadog/Tracer.swift
Sources/Datadog/Tracing/DDSpan.swift
Sources/Datadog/Tracing/Integrations/TracingWithLoggingIntegration.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/TracingWithLoggingIntegrationTests.swift
Tests/DatadogTests/Datadog/Logging/LoggingFeatureTests.swift
Tests/DatadogTests/Datadog/Logging/LoggingMessageReceiverTests.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Datadog/Mocks/TracingFeatureMocks.swift
Tests/DatadogTests/Datadog/TracerConfigurationTests.swift
Tests/DatadogTests/Datadog/TracerTests.swift
Tests/DatadogTests/Datadog/Tracing/Autoinstrumentation/URLSessionTracingHandlerTests.swift
Tests/DatadogTests/Datadog/Tracing/DDSpanTests.swift

Send Span log to Logs through the message bus.
`TracingWithLoggingIntegration` no longer write a `LogEvent` on the Logs event write, but build and send a message instead.
This PR introduces `DatadogExtension` and `DatadogExtended` which is a pattern from [Alamofire](https://github.com/Alamofire/Alamofire/blob/master/Source/AlamofireExtended.swift). This pattern allows to expose external libraries extensions hided behind a `dd` property (instance or static). It can be useful when sharing type extension through `DatadogInternal`. Here, it expose the extended property `name` of type `Foundation.Thread`
```swift
Thread.current.dd.name // returns the current thread name extended by Datadog
```

RUMM-2332 Span to Log through message bus

---

session-replay/Sources/DatadogSessionReplay/Processor/Flattening/NodesFlattener.swift
session-replay/Sources/DatadogSessionReplay/Processor/Processor.swift
session-replay/Sources/DatadogSessionReplay/Processor/SRDataModelsBuilder/RecordsBuilder.swift
session-replay/Sources/DatadogSessionReplay/Processor/SRDataModelsBuilder/WireframesBuilder.swift
session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/NodeRecorders/NodeRecorder.swift
session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/NodeRecorders/UILabelRecorder.swift
session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/NodeRecorders/UIViewRecorder.swift
session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/ViewTreeSnapshot.swift
session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/ViewTreeSnapshotBuilder.swift
session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotProducer/WindowSnapshotProducer.swift
session-replay/Sources/DatadogSessionReplay/Utilities/Colors.swift
session-replay/Tests/DatadogSessionReplayTests/Mocks/CoreGraphicsMocks.swift
session-replay/Tests/DatadogSessionReplayTests/Mocks/FoundationMocks.swift
session-replay/Tests/DatadogSessionReplayTests/Mocks/RecorderMocks.swift
session-replay/Tests/DatadogSessionReplayTests/Mocks/UIKitMocks.swift
session-replay/Tests/DatadogSessionReplayTests/Mocks/Utilities/XCTestCase+Extensions.swift
session-replay/Tests/DatadogSessionReplayTests/Recorder/SnapshotBuilder/NodeRecorders/UILabelRecorderTests.swift
session-replay/Tests/DatadogSessionReplayTests/Recorder/SnapshotBuilder/NodeRecorders/UIViewRecorderTests.swift
session-replay/Tests/DatadogSessionReplayTests/Recorder/SnapshotBuilder/ViewTreeSnapshotBuilderTests.swift
session-replay/Tests/DatadogSessionReplayTests/Recorder/SnapshotBuilder/ViewTreeSnapshotTests.swift
session-replay/Tests/DatadogSessionReplayTests/Utilities/ColorsTests.swift

📦 This PR enhances Session Replay with recognising certain node semantics for `UIViews` and `UILabels`. For both, the recorder now captures more information on the native view and puts it into the JSON prepared for SR player. 
The `Recorder` now captures:
* appearance information on each `UIView`:
* background color
* border style (color + width)
* corner radius
* alpha
* text information on each `UILabel`:
* the text displayed
* the actual frame of the test (including paddings)
* text color
* font
Proposed implementation introduces a small framework prepared for capturing semantics of other nodes in extensible way promoting OCP (`UITextField`, `UIImageView`, `UISwitch` will come in next PR).
Each view traversed by `ViewTreeSnapshotBuilder` gets queried by a sequence of `NodeRecorders`: …

RUMM-2429 [SR] Capture `UIViews` and `UILabels` semantics

---

session-replay/Sources/DatadogSessionReplay/Processor/Flattening/NodesFlattener.swift
session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/NodeRecorders/UIImageViewRecorder.swift
session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/NodeRecorders/UISwitchRecorder.swift
session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/NodeRecorders/UITextFieldRecorder.swift
session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/ViewTreeSnapshot.swift
session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/ViewTreeSnapshotBuilder.swift
session-replay/Tests/DatadogSessionReplayTests/Mocks/RecorderMocks.swift
session-replay/Tests/DatadogSessionReplayTests/Mocks/UIKitMocks.swift
session-replay/Tests/DatadogSessionReplayTests/Recorder/SnapshotBuilder/NodeRecorders/UIImageViewRecorderTests.swift
session-replay/Tests/DatadogSessionReplayTests/Recorder/SnapshotBuilder/NodeRecorders/UISwitchRecorderTests.swift
session-replay/Tests/DatadogSessionReplayTests/Recorder/SnapshotBuilder/NodeRecorders/UITextFieldRecorderTests.swift
session-replay/Tests/DatadogSessionReplayTests/Recorder/SnapshotBuilder/ViewTreeSnapshotBuilderTests.swift
session-replay/Tests/DatadogSessionReplayTests/Recorder/SnapshotBuilder/ViewTreeSnapshotTests.swift

📦 Supplementing #985, this PR adds 3 more semantics to session replay:
* `UITextField`
* `UIImageView`
* `UISwitch`
I leverated the `NodeRecorder` + `NodeSemantics` framework introduced in #985 by adding 3 specialised node recorders: `UITextFieldRecorder`, `UIImageViewRecorder` and `UISwitchRecorder`.
It required some adjustments to `NodeSemantics.importance` to ensure that new node semantics are resolved consistently by `ViewTreeSnapshotBuilder`. More explanation in inline comment.

RUMM-2429 [SR] Add TextField, ImageView and UISwitch semantics

---

tools/nightly-unit-tests/bitrise-nightly-unit-tests.yml
tools/nightly-unit-tests/bitrise.yml.src
tools/nightly-unit-tests/src/bitrise_yml_writter.py

💉📦 This PR fixes recent issues in nightly tests.
Nightly tests are key to our iOS version coverage - they run unit tests on all iOS Simulator versions available in macOS Monterey + Xcode 13.4.1 (dozens of iOS versions from 12.4 up). Especially critical in testing OS version-specific code (swizzlings, `@available(...)`, I/O APIs, ...).
CI job was having a problem with `xcode-test` Bitrise step:
```
ERRO[02:23:30] Step (Run unit tests for given platform) failed: Failed to prepare the step for execution through the required toolkit (go), error: Failed to install package, error: command `/usr/local/bin/go "build" "-o" "/Users/vagrant/.bitrise/toolkits/go/cache/https___github.com_bitrise-io_bitrise-steplib.git-xcode-test-2.4.5" "github.com/bitrise-steplib/steps-xcode-test"` failed: exit status …
```

Fix nightly tests build

---

CHANGELOG.md
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScopeTests.swift

A user action should be sent if a new view start shortly after.

RUMM-2508 Fix manual User Action dropped if a new view start

---

Makefile

Update to new version of the tracer, it includes support for the Intelligent Test runner configuration through:
CI -> Settings->Test Service Settings
But as it needs admin rights for configuring I have kept the environment variables with the configuration (that overrides those of the settings)
Uopdated the version of the Makefile

Update to version 2.2.0-beta.8 of testing framework

---

Sources/Datadog/RUM/RUMMonitor/DDNoopRUMMonitor.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/DDNoopRUMMonitorTests.swift

This PR resolves the baseline request in #978 by calling `warn()` when any method vended by `DDRUMMonitor` is called on an instance of `DDNoopRUMMonitor`.
This change will make it more obvious when a `DDNoopRUMMonitor` has been captured and is being utilized accidentally.
I copied over all methods from `DDRUMMonitor` into `DDNoopRUMMonitor`, replaced `public` with `override`, and called `warn()` within each method body.

Warn when DDNoopRUMMonitor is sent any DDRUMMonitor methods

---

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift

Fill `frustration.count` field in view event with frustrations from actions.

RUMM-2354 Report Frustration Count in View

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/DatadogCore/DatadogCore.swift
Sources/Datadog/DatadogCore/Storage/Writing/Writer.swift
Sources/Datadog/DatadogInternal/DatadogCoreProtocol.swift
Sources/Datadog/DatadogInternal/DatadogFeature.swift
Sources/Datadog/DatadogInternal/DatadogV1CoreProtocol.swift
Sources/Datadog/DatadogInternal/MessageBus/FeatureMessageReceiver.swift
Sources/Datadog/DatadogInternal/Upload/FeatureRequestBuilder.swift
Tests/DatadogTests/Datadog/Mocks/DatadogInternal/DatadogCoreMock.swift
Tests/DatadogTests/Datadog/Mocks/DatadogInternal/PassthroughCoreMock.swift

Provide interfaces for registering v2 Features and Integrations.
A Feature or an Integration must comply to the following protocols so they can be registered in a `core` instance:
```swift
public protocol DatadogFeature {
/// The feature name.
var name: String { get }
/// The URL request builder for uploading data in this Feature.
///
/// This builder currently use the v1 context, but will be soon migrated to v2
var requestBuilder: FeatureRequestBuilder { get }
/// The message bus receiver.
///
/// The `FeatureMessageReceiver` defines an interface for Feature to receive any message
/// from a bus that is shared between Features registered in a core.
var messageReceiver: FeatureMessageReceiver { get }
}
public protocol DatadogFeatureIntegration {
/// The feature name.
var name: String { …
```

RUMM-2603 Create V2 Registration Interfaces

---

session-replay/Sources/DatadogSessionReplay/Drafts/SessionReplayFeature.swift
session-replay/Sources/DatadogSessionReplay/Processor/Privacy/TextObfuscator.swift
session-replay/Sources/DatadogSessionReplay/Recorder/Recorder.swift
session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/NodeRecorders/UILabelRecorder.swift
session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/NodeRecorders/UITextFieldRecorder.swift
session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/ViewTreeSnapshotBuilder.swift
session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotProducer/ViewTreeSnapshotProducer.swift
session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotProducer/WindowSnapshotProducer.swift
session-replay/Tests/DatadogSessionReplayTests/Mocks/RecorderMocks.swift
session-replay/Tests/DatadogSessionReplayTests/Mocks/SnapshotProducerMock.swift
session-replay/Tests/DatadogSessionReplayTests/Processor/Privacy/TextObfuscatorTests.swift
session-replay/Tests/DatadogSessionReplayTests/Recorder/RecorderTests.swift
session-replay/Tests/DatadogSessionReplayTests/Recorder/SnapshotBuilder/NodeRecorders/UILabelRecorderTests.swift
session-replay/Tests/DatadogSessionReplayTests/Recorder/SnapshotBuilder/NodeRecorders/UITextFieldRecorderTests.swift
session-replay/Tests/DatadogSessionReplayTests/Recorder/SnapshotBuilder/ViewTreeSnapshotBuilderTests.swift

🚚🔒 This PR adds "mask all" and "allow all" privacy rules to Session Replay.
With "mask all" (default setting), no text will be recorded in traversed `UILabels` and `UITextFields`. Instead, visible characters will be replaced by `"x"` (except whitespaces and newlines).
The public API added in this PR is still a draft (we will work on the actual one when integrating with V2 SDK).
The actual masking is done by basic iteration over `String` with replacing certain characters. To make it performant:
* It uses [`String.UnicodeScalarView.Iterator`](https://developer.apple.com/documentation/swift/string/unicodescalarview/iterator) which gives good performance and encapsulates Unicode complexity. I measured this to be 10x faster than RegExp (with 40K characters-long string and 1K repeats, it was …

RUMM-2503 [SR] Add "mask all" privacy rule

---

Makefile

Update to version 2.2.0-rc.2 of testing framework, previous rc.1 version was not skipping tests as it should
Updating the makefile

Update to version 2.2.0-rc.2 of testing framework

---

CHANGELOG.md
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift

Fix vitals presets and align with Android.
- Default Vitals Frequency: `average` (every 500ms)
- Frozen Frame Threshold: **700ms**

Fix Vitals Default Presets

---

CHANGELOG.md
DatadogSDK.podspec
DatadogSDKAlamofireExtension.podspec
DatadogSDKCrashReporting.podspec
DatadogSDKObjc.podspec
Sources/Datadog/DatadogConfiguration.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/Versioning.swift
Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift
Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift

git-flow: counterpart of #1041

Merge `release/1.13.0` to `develop`

---

Sources/Datadog/DatadogCore/Upload/DataUploadWorker.swift
Sources/Datadog/DatadogCore/Upload/DataUploader.swift
Sources/Datadog/DatadogInternal/Context/DatadogContext.swift
Sources/Datadog/DatadogInternal/Context/DeviceInfo.swift
Sources/Datadog/DatadogInternal/DatadogFeature.swift
Sources/Datadog/DatadogInternal/DatadogV1Context.swift
Sources/Datadog/DatadogInternal/Upload/FeatureRequestBuilder.swift
Sources/Datadog/DatadogInternal/Upload/URLRequestBuilder.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploadWorkerTests.swift
Tests/DatadogTests/Datadog/Core/Upload/DataUploaderTests.swift
Tests/DatadogTests/Datadog/Core/Upload/RequestBuilderTests.swift
Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift
Tests/DatadogTests/Datadog/Mocks/DatadogInternal/UploadMock.swift
session-replay/Sources/DatadogSessionReplay/DatadogCoreIntegration/RequestBuilder/JSON/EnrichedRecordJSON.swift
session-replay/Sources/DatadogSessionReplay/DatadogCoreIntegration/RequestBuilder/JSON/SegmentJSON.swift
session-replay/Sources/DatadogSessionReplay/DatadogCoreIntegration/RequestBuilder/JSON/SegmentJSONBuilder.swift
session-replay/Sources/DatadogSessionReplay/DatadogCoreIntegration/RequestBuilder/Multipart/MultipartFormData.swift
session-replay/Sources/DatadogSessionReplay/DatadogCoreIntegration/RequestBuilder/RequestBuilder.swift
session-replay/Sources/DatadogSessionReplay/DatadogCoreIntegration/RequestBuilder/Uploader.swift
session-replay/Sources/DatadogSessionReplay/Drafts/SessionReplay.swift
session-replay/Sources/DatadogSessionReplay/Drafts/SessionReplayConfiguration.swift
session-replay/Sources/DatadogSessionReplay/Drafts/SessionReplayFeature.swift
session-replay/Sources/DatadogSessionReplay/Writer/Models/EnrichedRecord.swift
session-replay/Tests/DatadogSessionReplayTests/DatadogCoreIntegration/RequestBuilder/JSON/EnrichedRecordJSONTests.swift
session-replay/Tests/DatadogSessionReplayTests/DatadogCoreIntegration/RequestBuilder/JSON/SegmentJSONBuilderTests.swift
session-replay/Tests/DatadogSessionReplayTests/DatadogCoreIntegration/RequestBuilder/Multipart/MultipartFormDataTests.swift
session-replay/Tests/DatadogSessionReplayTests/DatadogCoreIntegration/RequestBuilder/RequestBuilderTests.swift
session-replay/Tests/DatadogSessionReplayTests/Mocks/FoundationMocks.swift
session-replay/Tests/DatadogSessionReplayTests/Mocks/SessionReplayMocks.swift

📦 This PR implements Session Replay data uploads. SR records previously (#1044) written to `DatadogCore` are now read back and mapped into `URLRequests` sent to SR Intake.
✋ Because `DatadogCore` only supports `[Data] -> URLRequest` mapping (not yet `[Data] -> [URLRequest]`), I had to implement a temporary workaround. The first request is sent through `DatadogCore` (🏅), but other are passed to arbitrary (and temporary) uploader managed by SR.
Another problem I had to solve in this PR relates to decoding [`[SRRecord]`](https://github.com/DataDog/dd-sdk-ios/blob/253deba65b9c5da89875e2fce7a698930e5910df/session-replay/Sources/DatadogSessionReplay/Writer/SRDataModels.swift#L775) from events `[Data]` received from core. Even though our …

RUMM-2662 [SR] Upload Session Replay records (batched into segments)

---

Datadog/Datadog.xcodeproj/project.pbxproj
Sources/Datadog/CrashReporting/Integrations/CrashReportingWithRUMIntegration.swift
Sources/Datadog/DatadogInternal/Context/DatadogContext.swift
Sources/Datadog/DatadogInternal/DatadogCoreProtocol.swift
Sources/Datadog/RUM/DatadogCoreIntegration/SessionReplayDependency.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift
Sources/Datadog/RUM/RUMMonitor/Scopes/Utils/RUMOffViewEventsHandlingRule.swift
Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift
Tests/DatadogTests/Datadog/RUM/DatadogCoreIntegration/SessionReplayDependencyTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/Utils/RUMOffViewEventsHandlingRuleTests.swift
session-replay/Sources/DatadogSessionReplay/DatadogCoreIntegration/RUMContextReceiver.swift
session-replay/Sources/DatadogSessionReplay/DatadogCoreIntegration/RUMDependency.swift
session-replay/Sources/DatadogSessionReplay/DatadogCoreIntegration/SRContextPublisher.swift
session-replay/Sources/DatadogSessionReplay/Drafts/SessionReplay.swift
session-replay/Sources/DatadogSessionReplay/Drafts/SessionReplayFeature.swift
session-replay/Tests/DatadogSessionReplayTests/DatadogCoreIntegration/SRContextPublisherTests.swift

📦 This PR delivers the last 🧩 element of Session Replay upload pipeline. It integrates SR data with RUM: If any RUM event is collected while SR module is enabled, it will have `hasReplay` flag set accordingly to the recording state (`true` | `false`).
This flag is crucial for RUM <> SR correlation, i.a.: thanks to this value we can display ▶️ button next to events that can be referenced from SR replays. Clicking on it will jump directly to this event within recording:
When recorder's state changes, SR updates its `FeatureBaggage` in `DatadogContext`. This baggage is read by RUM when events are created.
For clarity, and to continue convention started with [`RUMDependency`](https://github.com/DataDog/dd-sdk-ios/blob/feature/session-replay/session-replay/Sources/DatadogSessionReplay/DatadogCo …

RUMM-2662 [SR] Set `hasReplay` flag on RUM events

---

CHANGELOG.md
Sources/Datadog/Logger.swift
Sources/Datadog/Logging/ConsoleLogger.swift
Sources/Datadog/Logging/RemoteLogger.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Logging/ConsoleLoggerTests.swift

Adding methods to loggers so we can pass in error information (kind, message, and stack trace) as Strings instead of relying on the `Error` type from Swift.
This is mostly for Cross Platform SDKs that need to send in serialized error information.

Add methods to pass error info to logs as decomposed strings

---

Sources/Datadog/CrashReporting/Integrations/CrashReportingWithLoggingIntegration.swift
Sources/Datadog/Logging/Log/LogEventBuilder.swift
Sources/Datadog/Logging/Log/LogEventEncoder.swift
Tests/DatadogBenchmarkTests/DataStorage/LoggingStorageBenchmarkTests.swift
Tests/DatadogIntegrationTests/Scenarios/Logging/LoggingScenarioTests.swift
Tests/DatadogTests/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithLoggingIntegrationTests.swift
Tests/DatadogTests/Datadog/LoggerTests.swift
Tests/DatadogTests/Datadog/Logging/Log/LogEventBuilderTests.swift
Tests/DatadogTests/Datadog/Mocks/LoggingFeatureMocks.swift
Tests/DatadogTests/Matchers/LogMatcher.swift

Add an `architecture` attribute to logs, under a new `_dd` structure for reserved attributes.
The method for encoding this is a bit different than the rest of the logs, and closer to what Android is doing. Instead of encoding nested properties with `.` keys, it encodes with the full JSON object.

Add architecture to logs

---

CONTRIBUTING.md
tools/lint/run-linter.sh

This allows running our linting script with `--fix` flag enabled. Particularly useful for people who are still aligning with the code-style.
I updated the bash script to take `--fix` into account. Also made a hint in the contribution guide.

RUMM-2725 Add --fix flag to linter script

---

Sources/Datadog/DDRUMMonitor+Internal.swift
Tests/DatadogTests/Datadog/RUM/RUMInternalProxyTests.swift

Change `updatePerformanceMetrics` to take a time as its first parameter, so it can cast to `RUMCommandSubscriber` instead of `RUMMonitor` (because we eliminate the dependency on dateProvider)
This is mostly to make updatePerformanceMetrics more testable in cross-platform libraries.

Change updatePerformanceMetrics to take a time

---

Sources/Datadog/Logging/Log/LogEventEncoder.swift

Allow error info to be modifiable on LogEvents. This allows clients to modify that information in the LogEventMapper and scrub potentially sensitive data.

Allow error info to be modifiable on LogEvents

---

Makefile

`DatadogSDKTesting` 2.2.0-rc.4 makes the unit tests pipeline to hang when launching the app runner.
CI passes when using 2.1.3, so lets downgrade on `develop` and investigate further the issue.

Downgrade to version 2.1.3 of testing framework 

---

session-replay/Sources/DatadogSessionReplay/Processor/Processor.swift
session-replay/Sources/DatadogSessionReplay/Processor/SRDataModelsBuilder/RecordsBuilder.swift
session-replay/Sources/DatadogSessionReplay/Recorder/TouchSnapshotProducer/TouchSnapshot/TouchIdentifierGenerator.swift
session-replay/Sources/DatadogSessionReplay/Recorder/TouchSnapshotProducer/TouchSnapshot/TouchSnapshot.swift
session-replay/Sources/DatadogSessionReplay/Recorder/TouchSnapshotProducer/WindowTouchSnapshotProducer.swift
session-replay/Tests/DatadogSessionReplayTests/Mocks/RecorderMocks.swift
session-replay/Tests/DatadogSessionReplayTests/Mocks/SRDataModelsMocks.swift
session-replay/Tests/DatadogSessionReplayTests/Processor/ProcessorTests.swift

📦 This PR switches from using deprecated `TouchData` to a new `PointerInteractionData` for sending touches in SR.
The new `PointerInteractionData` includes information of the touch "phase" and uses "one-to-one" relationship with "incremental records" (one record = one touch position). Both make it easier for the player to seek the replay to certain position - the player doesn't need to lookup previous or next records to know if there is a touch information to render. 
Visually, new touches are rendered with a fancy animation because we know the touch phase.
This change was relatively small in current architecture. It only required recording of the touch phase and changing the events emitted to the batch.
**Before**, the `Processor` was writing one "incremental record" for a batch of touch …

RUMM-2784 [SR] Migrate to `PointerInteractionData` for sending touch information

---

Sources/Datadog/Datadog.swift
Sources/Datadog/DatadogCore/Context/DatadogContextProvider.swift

When running E2E tests, we invoke `flushAndDeinitialize` to send all events to the intake. But after introducing the Core Context Provider, some work items could still be waiting on its queue after flushing. We should for wait all execution when flushing.
Perform a `sync` on the context provider queue.

RUMM-2782 Flush Context Queue
