DataDog/dd-sdk-ios

Datadog.podspec, DatadogObjc.podspec, Sources/Datadog/Datadog.swift
📦 This PR bumps the SDK version to `1.0.0-beta2`.
* `sdkVersion` in code ↗️,
* `s.version` in podspecs ↗️.
=> RUMM-313 Update SDK version to `1.0.0-beta2`

Datadog.podspec, DatadogObjc.podspec
New beta version to do dogfooding: `1.0.0-beta3`
`podspec`s are bumped to `1.0.0-beta3`
=> RUMM-342 Mark 1.0.0-beta3 release 

.github/CODEOWNERS, docs/README.md, docs/log_collection.md
=> RUMM-139 Add documentation for logging

README.md, docs/README.md
📦 Before pushing `1.0.0` tag we have to fix this few last things that I spotted.
* short update in `README.md`;
* fix for broken link in `docs/`.
=> RUMM-291 Update README and broken link in `docs/`

DatadogSDK.podspec, DatadogSDKObjc.podspec, Sources/Datadog/Datadog.swift
New version: `1.0.1`
* bump podspec version;
* bump `sdkVersion`;
=> RUMM-367 Mark 1.0.1 release

DatadogSDK.podspec, DatadogSDKObjc.podspec, Sources/Datadog/Datadog.swift
* #80 : `missing required module` fix
* #65 : Syncing logs time with server
=> Version bump to 1.1.0

DatadogSDK.podspec, DatadogSDKObjc.podspec, Sources/Datadog/Datadog.swift
🚀 Preparing for `1.2.0` release.
=> RUMM-460 Version bump to 1.2.0

docs/log_collection.md
📦 As we added new property to the public API, this PR updates the online docs accordingly.
I also went through the other content in there and:
* made attributes naming correct;
* unified some method names to industry-way of documenting Swift code.
=> RUMM-409 Update public docs with the new, `environment` setting

DatadogSDK.podspec, DatadogSDKObjc.podspec, Sources/Datadog/Datadog.swift, Sources/Datadog/Tracing/Propagation/HTTPHeadersWriter.swift, Tests/DatadogTests/Datadog/TracerTests.swift, docs/trace_collection.md
📦 This PR does necessary changes to release `1.3.0-beta2`.
* bump `sdkVersion`,
* update documentation snippets,
* remove `DD` prefix from public `HTTPHeadersWriter` API.
=> RUMM-545 Prepare `-beta2` release

Datadog/Datadog.xcodeproj/project.pbxproj, Datadog/Datadog.xcodeproj/xcshareddata/xcbaselines/61441C6724619FE4003D8BB8.xcbaseline/FE5A2FAD-6AE2-410D-A9A1-1E5F56CC9C52.plist, Datadog/Datadog.xcodeproj/xcshareddata/xcbaselines/61441C6724619FE4003D8BB8.xcbaseline/Info.plist, Tests/DatadogBenchmarkTests/TracingBenchmarkTests.swift, Tests/DatadogBenchmarkTests/TracingStorageBenchmarkTests.swift
Add benchmarks for Tracing
Simple one span benchmarks added
Added baselines for mi device
=> RUMM 564 - Add benchmarks for Tracing

.github/workflows/all-platform-tests.yml
📦 This PR adds a GitHub workflow to manually trigger the `all-platform-tests` CI job on Bitrise.
A 3rd party [pull-request-comment-trigger](https://github.com/Khan/pull-request-comment-trigger) action is used to [trigger the build on Bitrise](https://devcenter.bitrise.io/api/build-trigger/#triggering-a-new-build) if **`@test-all-platform`** keyword is given in PR description or in PR comment.
As this is a 3rd party code, I pin its version to a specific commit, so we can run the security audit before using it.
Before getting the security approval I don't pass the real GH nor Bitrise tokens through `secrets.` in this PR. Instead, a set of `DUMMY_*` repository secrets was defined, to only demonstrate how this is managed to work.
Although [passing secrets to command-line is …
=> RUMM-486 Run all platform tests on manual trigger

DatadogSDK.podspec, DatadogSDKObjc.podspec, Sources/Datadog/Versioning.swift
Bumping SDK version to 1.3.0 Beta 3
This version contains auto-instrumentation for Tracing 🚀 
_NOTE:_ Once this PR is merged, we will rename `next-version` milestone to `1.3.0-beta3` and create a new `next-version`
=> RUMM-566 Tracing Beta-3

Datadog/Datadog.xcodeproj/project.pbxproj, Datadog/Example/Base.lproj/Main.storyboard, Datadog/Example/IntegrationTestFixtures/SendRUMFixture2ViewController.swift, Datadog/Example/IntegrationTestFixtures/SendRUMFixture3ViewController.swift, Sources/Datadog/RUM/RUMEvent/RUMEventBuilder.swift, Sources/Datadog/RUM/RUMEvent/RUMEventEncoder.swift, Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift, Sources/Datadog/RUM/RUMMonitor/RUMContext.swift, Sources/Datadog/RUM/RUMMonitor/RUMScope.swift, Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift, Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift, Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift, Sources/Datadog/RUM/UUIDs/RUMUUID.swift, Sources/Datadog/RUM/UUIDs/RUMUUIDGenerator.swift, Sources/Datadog/RUMMonitor.swift, Tests/DatadogIntegrationTests/RUMIntegrationTests.swift, Tests/DatadogIntegrationTests/UITestsHelpers.swift, Tests/DatadogTests/Datadog/Mocks/CoreMocks.swift, Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift, Tests/DatadogTests/Datadog/RUM/RUMEventOutputs/RUMEventFileOutputTests.swift, Tests/DatadogTests/Datadog/RUM/RUMMonitor/RUMScopeTests.swift, Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScopeTests.swift, Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScopeTests.swift, Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift, Tests/DatadogTests/Datadog/RUM/UUIDs/DefaultRUMUUIDGeneratorTests.swift, Tests/DatadogTests/Datadog/RUMMonitorTests.swift, Tests/DatadogTests/Helpers/SwiftExtensions.swift, Tests/DatadogTests/Matchers/RUMEventMatcher.swift
📦 This PR adds RUM Views monitoring.
Two public APIs are exposed on `RUMMonitor`:
```swift
/// Notifies that the View starts being presented to the user.
/// - Parameters:
///   - viewController: the instance of `UIViewController` representing this View.
///   - attributes: custom attributes to attach to the View.
public func start(viewController: UIViewController, attributes: [AttributeKey: AttributeValue]? = nil) {
start(view: viewController, attributes: attributes)
}
/// Notifies that the View stops being presented to the user.
/// - Parameters:
///   - viewController: the instance of `UIViewController` representing this View.
///   - attributes: custom attributes to attach to the View.
public func stop(viewController: UIViewController, attributes: [AttributeKey: AttributeValue]? = …
```
=> RUMM-519 Add Views monitoring

DatadogSDK.podspec, DatadogSDKObjc.podspec, README.md, Sources/Datadog/Versioning.swift, api-surface-swift, docs/trace_collection.md
📦 This PR prepares the release branch for `1.3.0` release.
Version bump, docs + api-surface updates.
@test-all-platforms
=> RUMM-621 Release 1.3.0

Shopist/Shopist.xcodeproj/project.pbxproj, Shopist/Shopist/Scenes/ProductDetailViewController.swift, Shopist/Shopist/Scenes/ProductDetailViewController.xib, Shopist/Shopist/Scenes/ProductsViewController.swift
We need an example, Shopist app to generate demo RUM data
This PR implements product detail page in Shopist app
=> RUMM-601 Shopist: Product Detail page added

Shopist/Shopist.xcodeproj/project.pbxproj, Shopist/Shopist/API.swift, Shopist/Shopist/Cart.swift, Shopist/Shopist/Extensions/UIViewController+NavBar.swift, Shopist/Shopist/Scenes/CartViewController.swift, Shopist/Shopist/Scenes/ListViewController.swift, Shopist/Shopist/Scenes/ProductDetailViewController.swift, Shopist/Shopist/Views/TableViewCells.swift
We need Shopist app to generate RUM data for demos
We added Cart page to add items and then check them out
=> RUMM-602 Shopist: Cart added

Shopist/Shopist/API.swift, Shopist/Shopist/Extensions/UIView+Autolayout.swift, Shopist/Shopist/Scenes/CartViewController.swift
Shopist: an app to generate demo RUM data
Checkout is implemented
You can also input any discount code in Cart page
If checkout succeeds, the app goes back to homepage/categories
If checkout fails, the app presents an alert with the error
I copied `randomFail()` from android, %5 of the chance we present an error without making the request
=> RUMM-602 Shopist: Checkout implemented

Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift, Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScopeTests.swift
Active user actions were being discarded when their view is stopped
We should stop/finalize those user actions in that case
`UserActionScope` handles `StopView` command and sends the corresponding RUM event
This PR also limits `action.loadingTime` to hardcoded max duration values (0.1 sec for discrete actions, 10 for continuous actions)
=> RUMM-660 Active user actions stopped with stopView

docs/trace_collection.md
📖 This PR adds auto instrumentation note to tracing docs.
~- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)~
=> RUMM-621 Update Tracing docs with auto instrumentation info

docs/trace_collection.md
📦 This PR adds the public beta notice to the tracing docs.
=> RUMM-663 Add the public beta notice to tracing docs

Sources/Datadog/Tracing/DDSpan.swift, Tests/DatadogTests/Datadog/TracerTests.swift
`Span` used non-thread-safe methods for setting tags and adding logs
The issue was that setting a value via subscript is not thread-safe
We wrapped those set operations with `queue.a/sync { ... }` calls
=> RUMM-685: Fix - Span is made thread safe

Tests/DatadogTests/Datadog/RUMMonitorTests.swift
🧪 This PR adds test to assert the RUM global attributes behaviour.
As discussed, while the RUM View is active, attributes can be added or updated but not removed, so:
```swift
func testWhenViewIsStarted_attributesCanBeAddedOrUpdatedButNotRemoved() {
// ...
}
```
test case was added.
=> RUMM-706 Add test for RUM global attributes behaviour

Sources/Datadog/Tracing/Propagation/HTTPHeadersWriter.swift, api-surface-objc, api-surface-swift
✏️ This PR updates public api comments in Tracing.
Updated the comment. I also updated the API surface files to include the new stuff we added for RUM.
=> RUMM-386 Update public api comments in Tracing

DatadogSDK.podspec, DatadogSDKObjc.podspec, Sources/Datadog/Versioning.swift, api-surface-objc, api-surface-swift
🚀 This PR bumps the SDK version to `1.4.0-beta1` to prepare it for the release.
Did `make bump` and `make api-surface`.
Once approved, I will create pre-release tag and push both podspecs to CP.
=> RUMM-814 Release 1.4.0-beta1

docs/rum_collection.md
🗒️ This PR adds `rum_collection.md` guide explaining to users how to use RUM.
For now, the guide has 3 sections:
* Setup SDK for RUM,
* RUM Auto Instrumentation,
* RUM Manual Instrumentation.
I also made sure this `.md` renders well on documentation website (locally), so we can easily deploy it when we want:
=> RUMM-811 Add `rum_collection.md` guide

Shopist/Shopist/API.swift, Shopist/Shopist/AppDelegate.swift, Shopist/Shopist/Extensions/UIImageView+Network.swift, Shopist/Shopist/Extensions/UIViewController+NavBar.swift, Shopist/Shopist/Scenes/CatalogViewController.swift, Shopist/Shopist/Scenes/CheckoutViewController.swift, Shopist/Shopist/Scenes/HomeViewController.swift, Shopist/Shopist/Scenes/ListViewController.swift, Shopist/Shopist/Scenes/ProductViewController.swift
We test RUM autoinstrumentation in Shopist app
What is autoinstrumented:
1. network requests
2. `tap` user actions
3. views
What is to be autoinstrumented later
1. custom and swipe user actions
=> RUMM-812 Shopist: RUM Autoinstrumentation

Shopist/Shopist/AppDelegate.swift
This request came from those who use Shopist demo data
Instead of randomizing, now user is selected based on `UserDefaults` value
=> RUMM-868 Shopist users are selected deterministically

Sources/Datadog/DDRUMMonitor.swift, Sources/Datadog/DatadogConfiguration.swift, Sources/Datadog/RUM/AutoInstrumentation/Views/UIKitRUMViewsPredicate.swift, Sources/Datadog/RUMMonitor.swift, Sources/Datadog/URLSessionAutoInstrumentation/DDURLSessionDelegate.swift, docs/trace_collection.md
✏️ This PR updates RUM public APIs docs.
I went through all RUM public APIs, making sure their comments are up-to-date.
I updated the `trace_collection.md` doc to include the new requirement on using `DDURLSessionDelegate`.
Also, I cleaned up the `RUMMonitor's` interface from default parameter values left in some places. All defaults are provided by its superclass: `DDRUMMonitor`. (FTR: [Swift forum: Allow default parameter overrides](https://forums.swift.org/t/pitch-allow-default-parameter-overrides/10673))
=> RUMM-607 Review public APIs and docs

Shopist/Shopist.xcodeproj/project.pbxproj, Shopist/Shopist/AppDelegate.swift, Shopist/Shopist/User.swift
We'd like to populate our dashboards with data from all over the world.
_Fake_ Shopist users of the world, unite! ✊
=> RUMM-674 Shopist randomizes IP addresses

CHANGELOG.md
✏️ This PR updates the changelog with `1.4.0` release notes.
Add entries + run `pimpmychangelog`.
=> Update CHANGELOG with 1.4.0 release notes

docs/rum_collection.md
this sentence was missing kind of an important component
=> finish out incomplete sentence

api-surface-swift, docs/rum_collection.md
✏️ This PR adds updates to `rum_collection.md` docs, to keep it up to date with `1.4.0` GA.
~- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)~
~- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference~
=> RUMM-931 Update docs for 1.4.0

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog.xcscheme, Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogBenchmarkTests.xcscheme, Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogIntegrationTests.xcscheme, Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc.xcscheme, Makefile
Update testing sdk to version 0.5.1
Updated version number
Added Environment variables for Bitrise commit information
=> Update testing sdk to version 0.5.1

Tests/DatadogTests/DatadogObjc/DDRUMMonitorTests.swift
🧑‍🚒 This PR fixes unit tests compilation on `master`.
I updated tests introduced in #350 with new RUM models generated in #351.
=> RUMM-917 Fix unit tests on `master`

DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKObjc.podspec, Sources/Datadog/Versioning.swift
We need this alpha version for other internal projects until public release.
After approval, `make ship` will be run
=> Bumped version to 1.5.0-alpha2

DatadogSDK.podspec, DatadogSDK.podspec.src, DatadogSDKAlamofireExtension.podspec, DatadogSDKObjc.podspec, DatadogSDKObjc.podspec.src, Sources/Datadog/Versioning.swift, api-surface-objc, api-surface-swift
📦 This PR prepares `1.5.0-beta1` release.
Updated SDK version and `*.podspec` files.
`DatadogSDK.podspec` and `DatadogSDKObjc.podspec` will be pushed 👍 to pod specs repo.
`DatadogAlamofireExtension.podspec` will not yet be pushed 👎 - it waits for `1.5.0` GA.
=> RUMM-1037 Release `1.5.0-beta1`

dogfood.py, tools/dogfooding/dogfood.py
This creates a Python script that can be ran to generate a PR on a target dependency project, to ensure fast and automated dogfooding.
The script will pull the target project in a temp folder, update the relevant file to reference the provided SDK version, then commit, push a branch and generate a PR. 
```shell
python3 dogfood.py -v "<VERSION_NAME>" -t app
```
=> RUMM-1018 Create a dogfooding script

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog.xcscheme, Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogBenchmarkTests.xcscheme, Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogIntegrationTests.xcscheme, Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc.xcscheme, Makefile
Update to version 0.7.0 of testing framework
Update value of `DD_SDK_SWIFT_TESTING_VERSION` to 0.7.0
Modify environment variables for this version: add `SRCROOT` and remove Bitrise Git variables since are not needed anymore
=> Update to version 0.7.0 of testing framework

docs/mobile_data_collected.md
=> Fixed broken tables

docs/rum_collection.md
Update headings to match [docs contributing guidelines](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#headers)
N/A
=> Lint headings for Docs

Makefile
Update to version 0.8.0 of testing framework
modifying the version in the makefile
=> Update to version 0.8.0 of testing framework

CHANGELOG.md, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKObjc.podspec, Sources/Datadog/Versioning.swift
🏁 This PR prepares `1.6.0` submission.
Branched from `1.6.0-alpha1` tag and updated `CHANGELOG`.
=> Release `1.6.0`

Makefile
Update to version 0.8.2 of testing framework
Changed version in Makefile
=> Update to version 0.8.2 of testing framework

Makefile
Update to version 0.9.0 of testing framework
Updated version on makefile
=> Update to version 0.9.0 of testing framework

docs/trace_collection.md
Fixes a typo because it makes the it easier to read
deleted a `t` character in three places.
=> Correct `headersWritter` -> `headersWriter` typo

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog.xcscheme, Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogBenchmarkTests.xcscheme, Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc.xcscheme, Datadog/TargetSupport/DatadogIntegrationTests/DatadogIntegrationTests.xctestplan, Makefile
Update to version 0.9.2 of testing framework
Also use recommended environment variables for testing configuration:
* Replace `BITRISE_APP_TITLE` with `BITRISE_TRIGGERED_WORKFLOW_ID`
* Add `BITRISE_BUILD_SLUG`
* Remove environment variables that only needed when running tests on physical devices
=> Update to version 0.9.2 of testing framework

docs/rum_collection/_index.md
Removed italics (for product landing pages), spelling fixes, and fixing a link.
=> Doc Updates to Real User Monitoring > iOS Monitoring

DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, Sources/Datadog/Versioning.swift
What and why?
This PR prepares `1.7.0-beta3` submission.
- New crash report format
- Crash Reporting supports for all package managers
- Mobile vitals are added
- Fixes and improvements
Once this PR is approved, I will add a pre-release tag.
=> Release `1.7.0-beta3`

Makefile
Update to version 0.9.3 of testing framework
Changing version number in Makefile
=> Update to version 0.9.3 of testing framework

Makefile
Update to version 0.9.4 of testing framework
Changing the version in the Makefile
=> Update to version 0.9.4 of testing framework

DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, Sources/Datadog/RUM/RUMVitals/VitalInfoSampler.swift, Sources/Datadog/Tracing/Propagation/HTTPHeadersWriter.swift, Sources/Datadog/Tracing/Propagation/TracingHTTPHeaders.swift, Sources/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptor.swift, Sources/Datadog/Versioning.swift, Tests/DatadogIntegrationTests/Scenarios/RUM/RUMResourcesScenarioTests.swift, Tests/DatadogIntegrationTests/Scenarios/Tracing/TracingURLSessionScenarioTests.swift, Tests/DatadogTests/Datadog/TracerTests.swift, Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/URLSessionInterceptorTests.swift, Tests/DatadogTests/DatadogObjc/DDTracerTests.swift
⚙️ This is purely technical PR to update `master` branch with things merged as a hotfix to `1.7.0-beta4`.
Just updating `master` with `1.7.0-beta4` without deleting the source branch.
=> Update `master` with `1.7.0-beta4` fixes

Datadog/Datadog.xcodeproj/project.pbxproj, Sources/DatadogObjc/Datadog+objc.swift, Sources/DatadogObjc/RUMMonitor+objc.swift, Tests/DatadogTests/DatadogObjc/ObjcAPITests/DDConfiguration+apiTests.m, Tests/DatadogTests/DatadogObjc/ObjcAPITests/DDDatadog+apiTests.m, Tests/DatadogTests/DatadogObjc/ObjcAPITests/DDGlobal+apiTests.m, Tests/DatadogTests/DatadogObjc/ObjcAPITests/DDNSURLSessionDelegate+apiTests.m, Tests/DatadogTests/DatadogObjc/ObjcAPITests/DDRUMMonitor+apiTests.m
🐞 As noticed in https://github.com/DataDog/dd-sdk-ios/issues/577#issuecomment-908500889, `DDRUMView` and `DDRUMAction` were not properly exposed to Objective-C interface.
This PR targets the `1.7.0-beta4` branch, as IMO this is no-risk but high impact fix that can be shipped in `1.7.0`.
Swift definitions of `DDRUMView` and `DDRUMAction` were missing `@objc` annotation in their `public init()`. Definition for `DDRUMView` was there, but it was accidentally removed in [this refactoring](https://github.com/DataDog/dd-sdk-ios/commit/d705147efa91415009cd57f97017b154958b9f43#diff-9cfc39ecf2272240473cb67d32dd88a47848e360c5a6aea3cf8ee0a6a3fce8d6).
Because unexposed or broken Objective-C APIs are recurring problem (https://github.com/DataDog/dd-sdk-ios/pull/359, …
=> RUMM-1582 Fix `DDRUMView` and `DDRUMAction` APIs for Objective-C

Sources/Datadog/DatadogConfiguration.swift, Sources/DatadogObjc/DatadogConfiguration+objc.swift, Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift, Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift, Tests/DatadogTests/DatadogObjc/ObjcAPITests/DDConfiguration+apiTests.m
=> RUMM-1487 Add support to US5 servers

Makefile
Update to version 0.9.5 of testing framework
Changed the version in the makefile
=> Update to version 0.9.5 of testing framework

README.md, Sources/Datadog/Tracing/DDNoOps.swift, Sources/DatadogExtensions/Alamofire/README.md, Tests/DatadogTests/Datadog/Tracing/DDNoopTracerTests.swift
Use Trace Collection [documentation destination path](https://github.com/DataDog/documentation/blob/master/local/bin/py/build/configurations/pull_config.yaml#L511).
=> RUMM-1006 Update Trace Collection documentation link

DatadogSDK.podspec, DatadogSDK.podspec.src, DatadogSDKAlamofireExtension.podspec, DatadogSDKAlamofireExtension.podspec.src, DatadogSDKCrashReporting.podspec, DatadogSDKCrashReporting.podspec.src, DatadogSDKObjc.podspec, DatadogSDKObjc.podspec.src, Sources/Datadog/Versioning.swift
Prepare `1.8.0-beta1` version.
Update podspecs src.
`make bump`
=> RUMM-1632 Release 1.8.0-beta1

Makefile
Update to version 1.0.1 of testing framework
Updated the Makefile version
=> Update to version 1.0.1 of testing framework

Tests/DatadogTests/Datadog/DatadogTests.swift
⚙️ This PR fixes flaky test added with `Datadog.clearAllData()` in #644.
It caused 64 failures among all branches during last 1 month:
In this test:
* we initialise the SDK;
* then we write 1 file to both directories (`.pending` and `.granted`) for each of 4 features (so 8 files in total);
* then we call `Datadog.clearAllData()`;
* and then we expect no data in all directories.
This initial assertion in `// Given` block was failing:
```swift
// Given
XCTAssertEqual(numberOfFiles, 8, "Each feature stores 2 files - one authorised and one unauthorised")
```
The problem was caused by data migration performed on SDK start-up. When SDK starts, [it instantiates `ConsentAwareDataWriter` for each feature](https://github.com/DataDog/dd-sdk-ios/blob/eef82d8cd5bbb0764e2e1f4d13a324ff17f4509c/Sources/Da …
=> RUMM-640 Fix flaky test in `DatadogTests`

Makefile
Update to version 1.0.2 of testing framework
Changed the version in the Makefile
=> Update to version 1.0.2 of testing framework

Sources/Datadog/CrashReporting/CrashReporter.swift, Sources/Datadog/Datadog.swift, Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift
Add logs to crash reporting.
Inject user and internal logger to crash reporting plugin.
=> RUMM-1796 Crash Reporting Logging

Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift, Sources/Datadog/RUM/DataModels/RUMDataModels.swift, Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift, Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift, Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift, Sources/DatadogObjc/RUM/RUMDataModels+objc.swift, Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift, Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift, Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScopeTests.swift, Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift
⚙️ Purely technical PR to update `hybrid-application` branch with the content of main branch.
`master` → `hybrid-application` merge.
=> RUMM-1649 Update `hybrid-application` branch with `master`

docs/log_collection.md
This section is rendered as code when using tabs.
=> RUMM-1769 Fix logs doc rendering

docs/log_collection.md, docs/rum_collection/_index.md, docs/trace_collection.md
All current regions (US1, US3, US5, US1_FED, EU1)  are documented in the setup instructions.
This PR also fix tracing indentation and RUM setup for eu1.
=> RUMM-1956 Document all regions in setup instruction

docs/rum_collection/advanced_configuration.md
Adds a link to the source code for the `DDRUMMonitor` class + addresses copy nits.
DOCS-3099
=> DOCS-3099 iOS Advanced Configuration Edits

Makefile
Update to version 1.1.1 of testing framework
Updated makefile version
=> Update to version 1.1.1 of testing framework

docs/log_collection.md, docs/trace_collection.md
Fix doc rendering for logs and tracing:
- https://docs.datadoghq.com/logs/log_collection/ios
- https://docs.datadoghq.com/tracing/setup_overview/setup/ios
=> RUMM-2013 Remove tabs in doc

Sources/Datadog/Core/Persistence/Files/File.swift, Sources/Datadog/Core/System/CarrierInfoProvider.swift, Sources/Datadog/Core/System/MobileDevice.swift, Sources/Datadog/Core/System/NetworkConnectionInfoProvider.swift, Sources/Datadog/Core/Utils/JSONEncoder.swift, Sources/Datadog/FeaturesIntegration/WebView/WKUserContentController+Datadog.swift, Sources/Datadog/InternalMonitoring/Kronos/KronosMonitor.swift, Sources/Datadog/RUM/Debugging/RUMDebugging.swift, Sources/Datadog/RUM/Instrumentation/Actions/SwiftUI/SwiftUIActionModifier.swift, Sources/Datadog/RUM/Instrumentation/Views/SwiftUI/SwiftUIViewModifier.swift, Sources/Datadog/URLSessionAutoInstrumentation/Interception/TaskInterception.swift, Sources/Datadog/Utils/SwiftUIExtensions.swift, Tests/DatadogCrashReportingTests/PLCrashReporterIntegration/DDCrashReportBuilderTests.swift, Tests/DatadogTests/Datadog/Core/System/CarrierInfoProviderTests.swift, Tests/DatadogTests/Datadog/Core/System/LaunchTimeProviderTests.swift, Tests/DatadogTests/Datadog/Core/System/MobileDeviceTests.swift, Tests/DatadogTests/Datadog/Core/System/NetworkConnectionInfoProviderTests.swift, Tests/DatadogTests/Datadog/CrashReporting/CrashContext/CrashContextProviderTests.swift, Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/CoreTelephonyMocks.swift, Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/UIKitMocks.swift, Tests/DatadogTests/Datadog/RUM/Debugging/RUMDebuggingTests.swift, Tests/DatadogTests/Datadog/RUM/Instrumentation/Actions/UIKit/UIApplicationSwizzlerTests.swift, Tests/DatadogTests/Datadog/RUM/Instrumentation/Actions/UIKit/UIKitRUMUserActionsHandlerTests.swift, Tests/DatadogTests/Datadog/RUM/Instrumentation/Views/UIKit/UIKitRUMViewsPredicateTests.swift, Tests/DatadogTests/Datadog/RUM/WebView/WKUserContentController+DatadogTests.swift, Tests/DatadogTests/Datadog/URLSessionAutoInstrumentation/Interception/TaskInterceptionTests.swift, Tests/DatadogTests/Datadog/Utils/SwiftUIExtensionsTests.swift
Add compilation and runtime flags for tvOS.
This PR only focuses on making codebase compatible with tvOS. Targets definition will come next.
=> RUMM-2033 tvOS Compatibility

docs/log_collection.md, docs/rum_collection/data_collected.md, docs/trace_collection.md
Add a link to Apple's app sandbox documentation
=> RUMM-1939 add link to Apple's sandbox documentation

Datadog/Datadog.xcodeproj/project.pbxproj, Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog tvOS.xcscheme, Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCrashReporting tvOS.xcscheme, Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc tvOS.xcscheme, Makefile, bitrise.yml
Adds tvOS framework and unit tests targets and schemes.
=> RUMM-2033 Add tvOS Targets

DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, Sources/Datadog/FeaturesIntegration/WebView/WKUserContentController+Datadog.swift, Sources/Datadog/Versioning.swift, Tests/DatadogIntegrationTests/Scenarios/Logging/LoggingCommonAsserts.swift, Tests/DatadogIntegrationTests/Scenarios/RUM/RUMCommonAsserts.swift, Tests/DatadogIntegrationTests/Scenarios/Tracing/TracingCommonAsserts.swift, docs/log_collection.md, docs/rum_collection/data_collected.md, docs/trace_collection.md
Merge latest changes from `release/1.10.1-beta1` to `develop`
=> Merge 1.10.0-beta1 to `develop`

docs/rum_collection/crash_reporting.md
=> General availability of iOS crash reporting

README.md
Updates iOS SDK GitHub Readme with tvOS support.
Slack convo with Maxime.
=> DOCS-3269 tvOS and iOS Support in the README

tools/distribution/update_upstream_sdks.py
This updates the version table in the documentation when performing other updates, so it doesn't have to be done manually.
=> Update version in documentation when updating the Flutter SDK

Tests/DatadogTests/Datadog/RUM/RUMVitals/VitalRefreshRateReaderTests.swift
Main thread overhead test is flaky when measuring refresh rate.
Allow sample count to be higher than target.
Improve test failure description for future investigation.
=> Mitigate refresh rate test flakiness

CHANGELOG.md, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, Sources/Datadog/Versioning.swift
📦 Merging `release/1.11.0-beta1` to `develop`.
Version bump + `CHANGELOG.md` update.
=> Merge `1.11.0-beta1` to `develop`

docs/rum_collection/data_collected.md
Removes the `country_subdivision_iso_code` facet.
RUM Docs Slack
=> DOCS-3465 iOS Data Collected Edit

CHANGELOG.md, Datadog/Datadog.xcodeproj/project.pbxproj, Datadog/TargetSupport/DatadogIntegrationTests/DatadogCrashReportingIntegrationTests.xctestplan, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, Sources/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegration.swift, Sources/Datadog/Kronos/KronosDNSResolver.swift, Sources/Datadog/Kronos/KronosInternetAddress.swift, Sources/Datadog/RUM/DataModels/RUMDataModelsMapping.swift, Sources/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScope.swift, Sources/Datadog/RUM/RUMMonitor/Scopes/RUMScopeDependencies.swift, Sources/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScope.swift, Sources/Datadog/RUM/RUMMonitor/Scopes/RUMViewScope.swift, Sources/Datadog/RUM/RUMTelemetry.swift, Sources/Datadog/Versioning.swift, Tests/DatadogTests/Datadog/FeaturesIntegration/CrashReporting/CrashReportingWithRUMIntegrationTests.swift, Tests/DatadogTests/Datadog/Kronos/KronosInternetAddressTests.swift, Tests/DatadogTests/Datadog/Mocks/RUMDataModelMocks.swift, Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift, Tests/DatadogTests/Datadog/Mocks/SystemFrameworks/FoundationMocks.swift, Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMResourceScopeTests.swift, Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMUserActionScopeTests.swift, Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMViewScopeTests.swift, Tests/DatadogTests/Datadog/RUM/RUMTelemetryTests.swift, tools/distribution/src/release/assets/gh_asset.py
Merge `release/1.11.0-beta2` to `develop` 🚀
=> Merge `1.11.0-beta2` to `develop`

Tests/DatadogBenchmarkTests/DataStorage/LoggingStorageBenchmarkTests.swift, Tests/DatadogBenchmarkTests/DataStorage/RUMStorageBenchmarkTests.swift, Tests/DatadogBenchmarkTests/DataStorage/TracingStorageBenchmarkTests.swift
=> RUMM-2134 Fix benchmark tests

docs/rum_collection/_index.md
=> DOCS-3301 add background event tracking documentation

Makefile
Update to version 2.0.1 of testing framework
Updated version number in makefile
=> Update to version 2.0.1 of testing framework

docs/README.md, docs/rum_collection/_index.md
Updates the Docs README + doc page with information about UST.
Unified Service Tagging Doc Updates
=> iOS Monitoring + README Edits

docs/rum_collection/advanced_configuration.md
Fix deprecated action tracking configuration in doc.
=> Fix UIKit actions tracking documentation

docs/rum_collection/_index.md
Adds tvOS to the index page title.
#rum-docs Slack
=> Updates Index Page Title for iOS Monitoring

Sources/Datadog/RUM/RUMMonitor/RUMCommand.swift, Sources/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScope.swift, Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift, Tests/DatadogTests/Datadog/RUM/RUMMonitor/Scopes/RUMSessionScopeTests.swift
This ensures that the timeout for sessions take into account the interactive vs non interactive events.
=> RUMM-2233 Fix session management rule

Sources/Datadog/Logging/Log/LogEventEncoder.swift, Tests/DatadogTests/Datadog/LoggerTests.swift, Tests/DatadogTests/DatadogObjc/DDLoggerTests.swift
Out of consistency with Android, we add an automatic tag to each log with the version of the host application
=> RUMM-2254 Add a version tag to all logs

.gitignore
⚙️ This PR updates `.gitignore` for easy changing between `feature/session-replay` and other branches.
Because we use Swift Package project on `feature/session-replay` branch, I'm adding `.swiftpm` to `.gitignore`, so it is possible to smoothly jump between branches, without deleting git stage.
=> RUMM-2264 Update `.gitignore` to enable smooth branch changes

.github/CODEOWNERS
Tags me as a secondary reviewer on doc-related pull requests, hopefully leading to faster approvals.
=> Adds Secondary Doc Reviewer

Makefile
Update to version 2.1.0 of testing framework
Updated makefile with new version
=> Update to version 2.1.0 of testing framework

Datadog/Datadog.xcodeproj/project.pbxproj
Fix project misconfiguration introduced by `develop` merge.
=> Fix develop merge

docs/rum_collection/data_collected.md
Adds long tasks to the types of event list. 
=> Add long task to the event types

CHANGELOG.md, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, Sources/Datadog/Versioning.swift
=> Release 1.12.0-beta3

Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog iOS.xcscheme, Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/Datadog tvOS.xcscheme, Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCrashReporting iOS.xcscheme, Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogCrashReporting tvOS.xcscheme, Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc iOS.xcscheme, Datadog/Datadog.xcodeproj/xcshareddata/xcschemes/DatadogObjc tvOS.xcscheme, Datadog/TargetSupport/DatadogIntegrationTests/DatadogCrashReportingIntegrationTests.xctestplan, Datadog/TargetSupport/DatadogIntegrationTests/DatadogIntegrationTests.xctestplan, Makefile
Configure targets to use ITR, excluding benchmark module.
Also configured to run in all branches except develop.
Updated to version 2.2.0-beta.1 of the testing framework
Added some needed environment variables for each module (not added to benchmark module because it could add some benchmark noise, but can be tested if it works well also for it)
Excluded develop branch, more branches can be added (comma separeted)
=> Enable Intelligent Test Runner for project

docs/rum_collection/data_collected.md
Addresses a copy nit.
DOCS-4037
=> iOS Monitoring Data Collected Edit

Makefile
Update to version 2.2.0-beta.6 of testing framework.
It includes some small fixes and tags modules when ITR skipped tests
Changed Makefile
=> Update to version 2.2.0-beta.6 of testing framework

docs/rum_collection/_index.md
Fixes a broken link
Was missing a 'g'.
=> Typo in link

session-replay/Sources/DatadogSessionReplay/Processor/Processor.swift, session-replay/Sources/DatadogSessionReplay/Processor/SRDataModelsBuilder/RecordsBuilder.swift, session-replay/Sources/DatadogSessionReplay/Processor/SRDataModelsBuilder/SegmentBuilder.swift, session-replay/Sources/DatadogSessionReplay/Processor/SRDataModelsBuilder/WireframesBuilder.swift, session-replay/Sources/DatadogSessionReplay/Writer/SRDataModels.swift, tools/rum-models-generator/Sources/CodeDecoration/SRCodeDecorator.swift, tools/rum-models-generator/run.py
📦 This PR updates auto-generated SR data models so they are more convenient for use.
This is to enable code reuse and shape simpler control flows. Mainly achieved by sharing common type definitions.
Resolved all TODOs annotated with `RUMM-2440`. To do this, I updated `SRCodeDecorator` in `rum-models-generator` → then recreated all models → then updated SR code.
=> RUMM-2440 [SR] Make SR models more convenient to work with

docs/rum_collection/advanced_configuration.md
`setAttribute` doesn't exist, should be `addAttribute`
=> Replace 'setAttribute' in docs

session-replay/Sources/DatadogSessionReplay/Processor/SRDataModelsBuilder/WireframesBuilder.swift, session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/ViewTreeSnapshotBuilder.swift, session-replay/Sources/DatadogSessionReplay/Writer/SRDataModels.swift, session-replay/Tests/DatadogSessionReplayTests/Mocks/FoundationMocks.swift, session-replay/Tests/DatadogSessionReplayTests/Mocks/SRDataModelsMocks.swift, tools/rum-models-generator/Sources/CodeDecoration/SRCodeDecorator.swift
📦 Preparing for bigger _"`RUMM-2464` [SR] Support incremental updates"_, this PR isolates changes in auto-generated code.
I updated SR data models for acting more convenient in incremental snapshots by extracting few types to the root level (making it reusable). This is done by updating `SRCodeDecorator` and re-generating.
I also added few handy `SRDataModel` mocks (any + random), which will be leveraged in upcoming PR.
=> RUMM-2464 [SR] Update SR models for more convenience in incremental updates

CHANGELOG.md, Cartfile, Cartfile.resolved, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKCrashReporting.podspec.src, DatadogSDKObjc.podspec, Package.swift, Sources/Datadog/Versioning.swift
Upgrade to `PLCrashReporter` 1.11.0 and fix Xcode 14 support.
=> Hotfix 1.12.1

session-replay/Sources/DatadogSessionReplay/Processor/Diffing/Diff+SRWireframes.swift, session-replay/Sources/DatadogSessionReplay/Processor/Diffing/Diff.swift, session-replay/Sources/DatadogSessionReplay/Processor/Processor.swift, session-replay/Sources/DatadogSessionReplay/Processor/SRDataModelsBuilder/RecordsBuilder.swift, session-replay/Sources/DatadogSessionReplay/Processor/SRDataModelsBuilder/SegmentBuilder.swift, session-replay/Sources/DatadogSessionReplay/Processor/SRDataModelsBuilder/WireframesBuilder.swift, session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/NodeIDGenerator.swift, session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/NodeRecorders/UIImageViewRecorder.swift, session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/NodeRecorders/UILabelRecorder.swift, session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/NodeRecorders/UISwitchRecorder.swift, session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/NodeRecorders/UITextFieldRecorder.swift, session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/NodeRecorders/UIViewRecorder.swift, session-replay/Sources/DatadogSessionReplay/Recorder/SnapshotBuilder/ViewTreeSnapshotBuilder.swift, session-replay/Tests/DatadogSessionReplayTests/Mocks/RecorderMocks.swift, session-replay/Tests/DatadogSessionReplayTests/Processor/Diffing/Diff+SRWireframesTests.swift, session-replay/Tests/DatadogSessionReplayTests/Processor/Diffing/DiffTests.swift, session-replay/Tests/DatadogSessionReplayTests/Recorder/SnapshotBuilder/NodeIDGeneratorTests.swift
📦 This PR adds support to incremental updates in SR segments.
This will vastly reduce the size of SR payloads. Instead of sending all wireframes each time ("full snapshot"), now we only send their differences from previous frame ("incremental snapshot").
This work is composed of two main parts:
* wireframe IDs generation,
* diff algorithm.
I introduced `NodeIDGenerator` which generates unique and stable IDs (`NodeID`) for each `UIView` instance:
* **`NodeIDs` are unique**, so each instance of `UIView` has different ID(s);
* **`NodeIDs` are stable**, meaning that one instance of `UIView` has the same ID for its entire lifespan.
`NodeIDs` are generated by `Recorded` (UI thread) and used as `WireframeID` in `Processor` (background thread). They are keys to determine incremental changes from …
=> RUMM-2464 [SR] Support incremental updates

Makefile
Update to version 2.2.0-rc.1 of testing framework
Updated makefile
=> Update to version 2.2.0-rc.1 of testing framework

Datadog/Datadog.xcodeproj/project.pbxproj, Sources/Datadog/Core/Attributes/Attributes.swift, Sources/Datadog/Core/FeaturesConfiguration.swift, Sources/Datadog/Datadog.swift, Sources/Datadog/DatadogCore/Context/ApplicationVersionPublisher.swift, Sources/Datadog/DatadogCore/DatadogCore.swift, Sources/Datadog/DatadogInternal/Context/DatadogContext.swift, Sources/Datadog/DatadogInternal/_InternalProxy.swift, Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift, Tests/DatadogTests/Datadog/DatadogCore/ApplicationVersionPublisherTests.swift, Tests/DatadogTests/Datadog/DatadogCore/FeatureContextTests.swift, Tests/DatadogTests/Datadog/DatadogCore/MessageBusTests.swift, Tests/DatadogTests/Datadog/DatadogInternal/_InternalProxyTests.swift, Tests/DatadogTests/Datadog/Logging/LoggingFeatureTests.swift, Tests/DatadogTests/Datadog/RUM/RUMFeatureTests.swift, Tests/DatadogTests/Datadog/Tracing/TracingFeatureTests.swift
Apply #973 on v2.
Create a `ApplicationVersionPublisher` to replace `AppVersionProvider`.
=> RUMM-2381 Add internal proxy API for customising app version

Makefile
Update to version 2.2.0-rc.3 of testing framework
Updated Makefile
=> Update to version 2.2.0-rc.3 of testing framework

Sources/Datadog/DDRUMMonitor+Internal.swift, Sources/Datadog/DDRUMMonitor.swift, Sources/Datadog/DatadogConfiguration.swift, Sources/Datadog/Logging/Log/LogEventBuilder.swift, Sources/Datadog/RUM/RUMMonitor/DDNoopRUMMonitor.swift, Sources/Datadog/RUMMonitor.swift, Tests/DatadogTests/Datadog/Logging/Log/LogEventBuilderTests.swift, Tests/DatadogTests/Datadog/RUM/RUMInternalProxyTests.swift, Tests/DatadogTests/Datadog/RUMMonitorTests.swift
This PR includes 2 improvements for cross-platform SDKs:
- move `updatePerformanceMetric` to internal proxy
- make the `VitalsFrequency` enum extend String for easier initialization
=> Improve internals for cross-platform SDKS

tools/distribution/requirements.txt
Update of requirements for distribution tools due to: https://github.com/DataDog/dd-sdk-ios/security/dependabot/1
=> RUMM-2829 Update requirements

api-surface-objc, api-surface-swift
I wanted to see what we have in the public API, but it seems `api-surface-[swift,objc]` files were not updated for more than 1 year. So this PR does the necessary update.
`make api-surface` didn't work out of the box, because it is not supporting Apple Silicon. These are the changes I had to make to be able to run it, but since I am not quite sure that these changes are enough/best way to make it work, I won't add these changes to the PR and just show the diff:
```diff
diff --git a/Makefile b/Makefile
index 73645bc9..2f5b4fc4 100644
--- a/Makefile
+++ b/Makefile
@@ -122,9 +122,9 @@ sr-models-verify:
api-surface:
@cd tools/api-surface/ && swift build --configuration release
@echo "Generating api-surface-swift"
-               ./tools/api-surface/.build/x86_64-apple-macosx/release/api-surfac …
```
=> Update public API surface

session-replay/Sources/DatadogSessionReplay/Processor/SRDataModelsBuilder/WireframesBuilder.swift, session-replay/Sources/DatadogSessionReplay/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UINavigationBarRecorder.swift, session-replay/Sources/DatadogSessionReplay/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITabBarRecorder.swift, session-replay/Sources/DatadogSessionReplay/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextViewRecorder.swift, session-replay/Sources/DatadogSessionReplay/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotBuilder.swift, session-replay/Tests/DatadogSessionReplayTests/Mocks/Utilities/FuzzyHelpers.swift, session-replay/Tests/DatadogSessionReplayTests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UINavigationBarRecorderTests.swift, session-replay/Tests/DatadogSessionReplayTests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITabBarRecorderTests.swift, session-replay/Tests/DatadogSessionReplayTests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextViewRecorderTests.swift
Adds support for UITextView
It's done by using clipping and intersection of actual view placement and it's content view.
=> RUMM-2681 [SR] Add support for UITextView

docs/rum_collection/advanced_configuration.md
Fix broken link in documentation.
=> Fix link to setup facets and measures

docs/trace_collection.md
Fixes a markdown tagging mistake
=> iOS trace collection docs fix formatting

docs/trace_collection.md
=> [git-flow] #1117 to `develop`

Makefile
Update to version 2.2.0 of testing framework
Updated version in the Makefile
=> Update to version 2.2.0 of testing framework

Sources/Datadog/DatadogCore/Storage/DataBlock.swift
=> RUMM-2819 Fix Xcode 13 build

Tests/DatadogBenchmarkTests/DataStorage/LoggingStorageBenchmarkTests.swift, Tests/DatadogBenchmarkTests/DataStorage/RUMStorageBenchmarkTests.swift, Tests/DatadogBenchmarkTests/DataStorage/TracingStorageBenchmarkTests.swift
Fixing benchmarks target build, broken after last sequence of rebase & merges.
Adding missing `forceNewBatch:` parameter.
=> RUMM-2821 Fix bencharks build

Sources/Datadog/DatadogCore/Storage/DataBlock.swift, Tests/DatadogTests/Datadog/Core/Persistence/DataBlockTests.swift, Tests/DatadogTests/Datadog/Core/Persistence/Writing/FileWriterTests.swift
Add more context to TLV errors for telemetry.
Add more info to `DataBlockError`.
=> RUMM 2817 TLV Telemetry

CHANGELOG.md, Datadog/Datadog.xcodeproj/project.pbxproj, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSDKSessionReplay.podspec, Makefile, Sources/Datadog/RUM/Integrations/CrashReportReceiver.swift, Sources/Datadog/Versioning.swift, Tests/DatadogTests/Datadog/RUM/Integrations/CrashReportReceiverTests.swift
=> [git-flow] `release/1.15.0` to `develop`

DatadogSessionReplay/Tests/DatadogSessionReplayTests/Mocks/CoreGraphicsMocks.swift, DatadogSessionReplay/Tests/DatadogSessionReplayTests/Mocks/RecorderMocks.swift, DatadogSessionReplay/Tests/DatadogSessionReplayTests/Processor/Flattening/NodesFlattenerTests.swift, DatadogSessionReplay/Tests/DatadogSessionReplayTests/Processor/ProcessorTests.swift, DatadogSessionReplay/Tests/DatadogSessionReplayTests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewRecorderTests.swift, DatadogSessionReplay/Tests/DatadogSessionReplayTests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UILabelRecorderTests.swift, DatadogSessionReplay/Tests/DatadogSessionReplayTests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UISwitchRecorderTests.swift, DatadogSessionReplay/Tests/DatadogSessionReplayTests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextFieldRecorderTests.swift, DatadogSessionReplay/Tests/DatadogSessionReplayTests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextViewRecorderTests.swift, DatadogSessionReplay/Tests/DatadogSessionReplayTests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIViewRecorderTests.swift, DatadogSessionReplay/Tests/DatadogSessionReplayTests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotBuilderTests.swift
Add mocks and basic tests for the nodes flattener.
=> Nodes flattener tests

CHANGELOG.md, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSDKSessionReplay.podspec, Sources/Datadog/Versioning.swift
git-flow: counterpart of #1186
=> Merge `release/1.16.0` to `develop`

Makefile
Update to version 2.2.3 of testing framework
Updated version in the Makefile
=> Update to version 2.2.3 of testing framework

docs/rum_collection/data_collected.md
Adds a note about how to change data collection settings for IP addresses.
[DOCS-4984](https://datadoghq.atlassian.net/browse/DOCS-4984)
[DOCS-4984]: https://datadoghq.atlassian.net/browse/DOCS-4984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> stop data collection note

docs/rum_collection/data_collected.md
Adds a note about how to stop collecting geo-location data.
[DOCS-4984](https://datadoghq.atlassian.net/browse/DOCS-4984)
[DOCS-4984]: https://datadoghq.atlassian.net/browse/DOCS-4984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Note about how to stop collecting geolocation data

docs/rum_collection/_index.md
Updates the screenshot for new iOS applications. The previous one was not rendering.
Replaces the previous image.
=> Updated privacy controls in application setup

Makefile
Update to version 2.2.4 of testing framework
Updated version in Makefile
=> Update to version 2.2.4 of testing framework

CHANGELOG.md, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSDKSessionReplay.podspec, Sources/Datadog/Versioning.swift
git-flow: counterpart of #1222
=> Merge `release/1.17.0` to `develop` 

docs/log_collection.md
Adds a tab for the AP1 site region.
DOCS-5147
https://docs-staging.datadoghq.com/alai97/log-collection-small-ap1-doc-update/logs/log_collection/ios
=> DOCS-5147 iOS Log Collection Edit

CHANGELOG.md, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSDKSessionReplay.podspec, Sources/Datadog/Versioning.swift, tools/lint/sources.swiftlint.yml, tools/lint/tests.swiftlint.yml
git-flow: counterpart of: #1254
=> Merge `release/1.18.0` to `develop`

DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/Basic.storyboard, DatadogSessionReplay/Sources/Processor/SRDataModelsBuilder/WireframesBuilder.swift, DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UILabelRecorder.swift, DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIPickerViewRecorder.swift, DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextFieldRecorder.swift, DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UITextViewRecorder.swift, DatadogSessionReplay/Sources/Writer/Models/SRDataModels+UIKit.swift
Adds support for text alignment.
Adds unified initialiser for UIKit->SR mapping and makes sure it's used across the board.
One snapshot test was updated with right and center alignment.
It removes logic for calculating vertical position using padding. Now it all takes whole frame of the view and achieves correct display by using text alignment.
=> REPLAY-1523 Text alignment

CHANGELOG.md, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSDKSessionReplay.podspec, Sources/Datadog/Versioning.swift, Tests/DatadogBenchmarkTests/DataStorage/TracingStorageBenchmarkTests.swift
git-flow: counterpart of #1267
=> Merge `release/1.19.0` to `develop`

DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/UnsupportedViews.storyboard, DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UnsupportedViewRecorder.swift, DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UnsupportedViewRecorderTests.swift
We should remove any reference to a UIWebView since it's officially deprecated by Apple.
=> RUMM-3307 Remove UIWebView

CHANGELOG.md, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSDKSessionReplay.podspec, Sources/Datadog/Versioning.swift
git-flow: counterpart of #1294
=> Merge `release/1.20.0` to `develop`

CHANGELOG.md, DatadogInternal.podspec, DatadogLogs.podspec, DatadogRUM.podspec, DatadogRUM/Sources/RUMMonitor.swift, DatadogRUM/Sources/RUMMonitor/RUMCommand.swift, DatadogRUM/Sources/RUMMonitor/Scopes/RUMApplicationScope.swift, DatadogRUM/Sources/RUMVitals/VitalInfoSampler.swift, DatadogRUM/Tests/Integrations/ErrorMessageReceiverTests.swift, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSDKSessionReplay.podspec, DatadogSessionReplay/SRSnapshotTests/SRHost/Fixtures/UnsupportedViews.storyboard, DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UnsupportedViewRecorder.swift, DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UnsupportedViewRecorderTests.swift, DatadogTrace.podspec, DatadogWebViewTracking.podspec, Sources/Datadog/Versioning.swift, TestUtilities.podspec, Tests/DatadogTests/Datadog/LoggerTests.swift, Tests/DatadogTests/Datadog/RUM/RUMMonitorTests.swift, Tests/DatadogTests/Datadog/TracerTests.swift, tools/nightly-unit-tests/bitrise.yml.src
Keep `develop` and `feature/v2` in sync.
Resolve conflicts with:
- #1278
=> Update `feature/v2` with `develop` 

Datadog/Datadog.xcodeproj/project.pbxproj, Datadog/Example/Debugging/DebugWebviewViewController.swift, DatadogCrashReporting/Sources/DatadogCrashReporter.swift, DatadogInternal/Sources/CoreRegistry.swift, DatadogInternal/Sources/DatadogCoreProtocol.swift, DatadogInternal/Sources/NetworkInstrumentation/URLSession/DatadogURLSessionDelegate.swift, DatadogInternal/Sources/NetworkInstrumentation/URLSession/URLSessionInterceptor.swift, DatadogInternal/Tests/CoreRegistryTest.swift, DatadogInternal/Tests/NetworkInstrumentation/NetworkInstrumentationFeatureTests.swift, DatadogLogs/Sources/Builder.swift, DatadogLogs/Sources/DatadogLogger.swift, DatadogRUM/Sources/Instrumentation/Actions/SwiftUI/SwiftUIActionModifier.swift, DatadogRUM/Sources/Instrumentation/Views/SwiftUI/SwiftUIViewModifier.swift, DatadogRUM/Sources/RUMMonitor.swift, DatadogSessionReplay/Sources/Drafts/SessionReplay.swift, DatadogTrace/Sources/DatadogTracer.swift, Sources/Datadog/Datadog+Internal.swift, Sources/Datadog/Datadog.swift, Tests/DatadogTests/Datadog/Core/_InternalProxyTests.swift, Tests/DatadogTests/Datadog/DatadogCore/MessageBusTests.swift, Tests/DatadogTests/Datadog/DatadogTests.swift, Tests/DatadogTests/Datadog/RUM/RUMMonitorTests.swift, Tests/DatadogTests/DatadogObjc/DDDatadogTests.swift, Tests/DatadogTests/DatadogObjc/DDGlobalTests.swift, Tests/DatadogTests/DatadogObjc/DDLoggerTests.swift, Tests/DatadogTests/DatadogObjc/DDTracerTests.swift, Tests/DatadogTests/TestsObserver/DatadogTestsObserver.swift
Create a registry of SDK instances to support multiple core.
Thread-safety of the registery is ensured by a read-write lock.
=> RUMM-2985 Create Core Registry

Datadog/Example/ExampleAppDelegate.swift, DatadogRUM/Sources/DDRUMMonitor.swift, DatadogRUM/Sources/RUMConfiguration.swift, DatadogRUM/Sources/RUMMonitor.swift, IntegrationTests/Runner/ExampleAppDelegate.swift, Sources/Datadog/Datadog.swift, Tests/DatadogTests/Datadog/DatadogTests.swift, Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift, Tests/DatadogTests/Datadog/RUM/RUMMonitorTests.swift
Remove Debug RUM from core module
Move logic to RUM Monitor
=> Remove Debug RUM from Core

Datadog.xcworkspace/contents.xcworkspacedata, Datadog/Datadog.xcodeproj/project.pbxproj
=> Fix benchmark tests

DatadogInternal/Sources/CoreRegistry.swift, DatadogWebViewTracking/Sources/WKUserContentController+Datadog.swift, IntegrationTests/Runner/Scenarios/WebView/WebViewTrackingFixtureViewController.swift, Sources/Datadog/Datadog.swift
Follow up on #1306 
Use core registry in `Datadog` API.
=> Use core registry in Datadog interface

.spi.yml
An attempt to make docs generation working at https://swiftpackageindex.com/DataDog/dd-sdk-ios
Verification per https://github.com/SwiftPackageIndex/SPIManifest/blob/main/Sources/validate-spi-manifest/Validator.swift
```
validate-spi-manifest .spi.yml
✅ The file is valid.
```
=> docs: add spi configuration

DatadogLogs/Sources/Log/LogEventSanitizer.swift, DatadogLogs/Sources/Scrubbing/LogEventMapper.swift, DatadogObjc/Sources/RUM+objc.swift, DatadogRUM/Sources/Instrumentation/Actions/UIKit/UIKitRUMUserActionsHandler.swift, DatadogRUM/Sources/Instrumentation/Actions/UIKit/UIKitRUMUserActionsPredicate.swift, DatadogRUM/Sources/Instrumentation/RUMInstrumentation.swift, DatadogRUM/Sources/RUMConfiguration.swift, DatadogRUM/Tests/Instrumentation/Actions/UIKitRUMUserActionsHandlerTests.swift, DatadogRUM/Tests/Instrumentation/RUMInstrumentationTests.swift, DatadogRUM/Tests/Mocks/RUMFeatureMocks.swift, DatadogRUM/Tests/RUMTests.swift, DatadogWebViewTracking/Sources/WebViewTracking.swift, DatadogWebViewTracking/Sources/WebViewTrackingMessage.swift, IntegrationTests/Runner/Scenarios/RUM/RUMScenarios.swift, IntegrationTests/Runner/Scenarios/TrackingConsent/TrackingConsentScenarios.swift, Tests/DatadogTests/Datadog/Mocks/RUMFeatureMocks.swift, Tests/DatadogTests/DatadogObjc/ObjcAPITests/DDTrace+apiTests.m, api-surface-swift
📦 In this PR I do an overall run over all products, performing cleanup and incorporating last changes to their public API.
3 main things (in commits):
* `DatadogRUM`: renamed `*RUMUserAction*` → `*RUMAction*` in predicates API, to make it consistent with RUMMonitor API from https://github.com/DataDog/dd-sdk-ios/pull/1310
* `DatadogLogs`: cleaned up unnecessary public symbols
* `WebViewTracking`: cleaned up unnecessary public symbols
=> RUMM-3295 Consolidate 2.x public API

DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, Makefile, TestUtilities.podspec
Prepare SDK version for dogfooding
=> Bumped version to 2.0.0-alpha1

DatadogSessionReplay/SRSnapshotTests/SRSnapshotTests/Utils/ImageRendering.swift, DatadogSessionReplay/Sources/Processor/Diffing/Diff+SRWireframes.swift, DatadogSessionReplay/Sources/Processor/SRDataModelsBuilder/WireframesBuilder.swift, DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewRecorder.swift, DatadogSessionReplay/Sources/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UnsupportedViewRecorder.swift, DatadogSessionReplay/Sources/Writer/Models/SRDataModels.swift, DatadogSessionReplay/Tests/Mocks/SRDataModelsMocks.swift, DatadogSessionReplay/Tests/Processor/Diffing/Diff+SRWireframesTests.swift, DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewWireframesBuilderTests.swift, tools/rum-models-generator/README.md, tools/rum-models-generator/Sources/CodeDecoration/SRCodeDecorator.swift, tools/rum-models-generator/run.py
Adds and utilises new type of wireframe that represents placeholders.
=> REPLAY-1805 Player side placeholder

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, Package.swift, TestUtilities.podspec, dependency-manager-tests/spm/App/ViewController.swift, dependency-manager-tests/spm/SPMProject.xcodeproj.src/project.pbxproj
=> Pre-release `2.0.0-beta1`

MIGRATION.md
=> RUMM-3404 Create MIGRATION.md

DatadogSDK.podspec, tools/distribution/src/release/assets/gh_asset.py
- Fix xcframework validation of v2 modules.
- Fix `DatadgSDK.podspec`
=> Fix v2 assets validation

Datadog/Datadog.xcodeproj/project.pbxproj, Datadog/Example/Debugging/DebugRUMSessionViewController.swift, Datadog/Example/ExampleAppDelegate.swift, DatadogCore/Tests/Datadog/LoggerTests.swift, DatadogCore/Tests/Datadog/TracerTests.swift, DatadogLogs/Sources/Feature/MessageReceivers.swift, DatadogLogs/Sources/Feature/RUMContextMapping.swift, DatadogLogs/Sources/RemoteLogger.swift, DatadogRUM/Sources/Integrations/RUMContextAttributes.swift, DatadogRUM/Tests/RUMTests.swift, DatadogSessionReplay/Sources/Feature/RUMContextReceiver.swift, DatadogSessionReplay/Sources/Feature/RUMDependency.swift, DatadogSessionReplay/Tests/Feature/RUMContextReceiverTests.swift, DatadogTrace/Sources/Feature/MessageReceivers.swift, DatadogTrace/Sources/Feature/RUMContextMapping.swift, DatadogTrace/Tests/ContextMessageReceiverTests.swift
🐞 Porting #1355 bugfix for V2.
See #1355.
=> RUMM-3320 fix: [V2] Fix APM local spans not correlating with RUM views

Package.swift, dependency-manager-tests/spm/App/ViewController.swift, dependency-manager-tests/spm/SPMProject.xcodeproj.src/project.pbxproj
📦 Enabling SR in `Package.swift`, to fix the recent dogfooding PRs.
Updated `Package.swift` and SPM smoke tests.
First merging to `develop`, then I'll merge `develop` → `dogfooding`.
=> RUMM-1869 Enable SR in `Package.swift`

DatadogInternal/Tests/NetworkInstrumentation/URLSessionSwizzlerTests.swift
Fix `URLSessionSwizzlerTests` on pre iOS13.
Test was missing `firstPartyHosts` for the modified URL.
=> Fix URLSession test on pre iOS13

DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
=> Merge `release/2.1.0` to `develop`

DatadogCore/Sources/Core/Context/CarrierInfoPublisher.swift, DatadogCore/Sources/Core/DatadogCore.swift, DatadogRUM/Sources/Debugging/RUMDebugging.swift, DatadogRUM/Sources/RUMVitals/VitalInfoSampler.swift, DatadogRUM/Sources/RUMVitals/VitalRefreshRateReader.swift
Reverts DataDog/dd-sdk-ios#1420
Need to revert due to CI issues. Needs deeper investigation.
=> Revert "Add visionOS support"

Datadog/IntegrationUnitTests/Public/TelemetryCoreIntegrationTests.swift, DatadogCore/Sources/Core/DatadogCore.swift, DatadogCore/Sources/Datadog+Internal.swift, DatadogCore/Sources/Datadog.swift, DatadogCore/Tests/Datadog/RUM/TelemetryReceiverTests.swift, DatadogCrashReporting/Sources/CrashReporting.swift, DatadogInternal/Sources/Telemetry/Telemetry.swift, DatadogInternal/Tests/Telemetry/TelemetryTests.swift, DatadogLogs/Sources/Logs.swift, DatadogRUM/Sources/Feature/RUMFeature.swift, DatadogRUM/Sources/RUMMonitor/Scopes/RUMScopeDependencies.swift, DatadogRUM/Tests/Integrations/TelemetryReceiverTests.swift, DatadogSessionReplay/Sources/Feature/SessionReplayFeature.swift, DatadogTrace/Sources/Feature/TraceFeature.swift
Facilitate telemetry report by exposing a `core.telemetry` endpoint.
=> RUM-384 Add convenient `core.telemetry` endpoint

CHANGELOG.md, Datadog/Datadog.xcodeproj/project.pbxproj
=> fix: do not embed DatadogInternal while building Trace and RUM xcframeworks

CHANGELOG.md, Datadog/Datadog.xcodeproj/project.pbxproj, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
git-flow: counterpart of https://github.com/DataDog/dd-sdk-ios/pull/1445
=> Merge hotfix/2.1.1 to develop

DatadogTrace/Sources/DDSpan.swift
It won't speed up so much as using this class over OTSpan protocol in most cases.
Anyway, making this class `final` gets maintainability, and improves performance of using static-dispatch potentially.
=> Make DDSpan final class

DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, Package.swift, SUPPORTED-VERSIONS.md, TestUtilities.podspec, TestUtilities/Package.swift, instrumented-tests/http-server-mock/Package.swift, tools/api-surface/Fixtures/Package.swift, tools/api-surface/Package.swift, tools/rum-models-generator/Package.swift, tools/sr-snapshots/Package.swift
This PR aims to update all the versions and describe the full picture in a new markdown file `SUPPORTED-VERSIONS.md` available in the root of the repo.
=> RUMM-3209 Supported versions documentation

instrumented-tests/http-server-mock/Package.swift
=> Fix Nightly: Lower http-server-mock version

CHANGELOG.md, Datadog/Datadog.xcodeproj/project.pbxproj, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCore/Tests/DatadogObjc/DDUIKitRUMActionsPredicateTests.swift, DatadogCore/Tests/DatadogObjc/DDUIKitRUMViewsPredicateTests.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogObjc/Sources/RUM/RUM+objc.swift, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
=> Release 2.2.1

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
counterpart to https://github.com/DataDog/dd-sdk-ios/pull/1460
=> Bump for release 2.2.0

bitrise.yml, tools/distribution/requirements.txt, tools/license/check-license.sh
🧰 This PR enables `tools/distribution/*` package tests on CI.
Same as other tests conditioned by `DD_RUN_TOOLS_TESTS`, this suite will be run for PRs that alter any file under `tools/*` path.
Enabling `pytest` configuration to run existing tests.
=> chore: Enable CI tests for distribution tools

DatadogCore/Sources/PerformancePreset.swift, DatadogCore/Tests/Datadog/Core/Persistence/FilesOrchestratorTests.swift, DatadogCore/Tests/Datadog/DatadogCore/DatadogCoreTests.swift, DatadogInternal/Sources/Extensions/FixedWidthInteger+Convenience.swift, DatadogSessionReplay/Sources/Feature/SessionReplayFeature.swift, DatadogSessionReplay/Sources/Utilities/Cache.swift
Adds general minor improvements that were side effect of working on Shopist update.
=> Minor improvments after shopist

DatadogCore/Tests/Datadog/LoggerTests.swift, DatadogObjc/Sources/RUM/RUMDataModels+objc.swift, DatadogRUM/Sources/DataModels/RUMDataModels.swift
=> RUM-1096 Fix test for os name

SUPPORTED-VERSIONS.md, tools/ci/choose_workflows.py
Tests weren't correctly running on PRs automatically.
This PR updates paths in the choose_workflow script.
=> Fix choose workflows

IntegrationTests/Runner/Scenarios/RUM/StopSessionScenario/KioskSendEventsViewController.swift
Increase simulate loading time to keep the view active
=> fix: Flakiness in `IntegrationScenarios / RUMStopSessionScenarioTests`

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
=> Merge `release/2.4.0` to `develop`

CHANGELOG.md
Merge issue.
move URLSession changelog to unreleased
=> docs: move URLSession changelog to unreleased

DatadogRUM/Sources/RUMConfiguration.swift, DatadogTrace/Sources/TraceConfiguration.swift
Docs were not obsolete 
Updated docs to suggest using URLSessionInstrumentation
=> RUM-717 docs: update urlSessionTracking to suggest using URLSessionInstrumentation

.github/CODEOWNERS
This PR includes the `rum-mobile-ios` team as a code owning team in order to ensure we have at least 1 iOS Engineer reviewing every merged PR. 
=> Include rum-mobile-ios team as codeowner

DatadogInternal/Sources/NetworkInstrumentation/NetworkInstrumentationFeature.swift
Potentially a retain cycle from the crash.
double weakify.
=> fix: double weakify self in nested closures

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift, DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
* [BUGFIX] https://github.com/DataDog/dd-sdk-ios/pull/1596
=> Hotfix `2.5.1`

DatadogCore/Sources/Core/Upload/DataUploadStatus.swift, DatadogCrashReporting/Sources/PLCrashReporterIntegration/CrashReport.swift, DatadogInternal/Sources/Utils/SwiftExtensions.swift, DatadogRUM/Sources/Integrations/CrashReportReceiver.swift, DatadogRUM/Sources/RUMMonitor/Scopes/RUMUserActionScope.swift
❌ occured
✅ occurred
https://dictionary.cambridge.org/dictionary/english/occurred
=> Fix occurred typos

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift, DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
git-flow counterpart of https://github.com/DataDog/dd-sdk-ios/pull/1598
I had to use separate `-merge-into-develop` branch due to git conflicts in `CHANGELOG.md`. When doing merge locally it went with no problem 🤔💭.
=> Merge `hotfix/2.5.1` to `develop`

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/compilation_issue.md, .github/ISSUE_TEMPLATE/crash_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/other.md
Included bug report and feature request templates.
=> chore: Update issue templates

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
git-flow: counterpart of #1622
=> Merge `release/2.6.0` to `develop`

DatadogCore/Tests/Datadog/Mocks/RUMDataModelMocks.swift, DatadogObjc/Sources/RUM/RUMDataModels+objc.swift, DatadogRUM/Sources/DataModels/RUMDataModels.swift, DatadogRUM/Sources/DataModels/RUMDataModelsMapping.swift, DatadogRUM/Sources/Integrations/TelemetryReceiver.swift, DatadogRUM/Tests/Mocks/RUMDataModelMocks.swift
Updated the RUM schema to latest (just RUM not SR).
Needed to switch the source to `unity` in that SDK.
refs: RUM-2662
=> chore: Update RUM model schema to latest version

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Resources/PrivacyInfo.xcprivacy, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec, dependency-manager-tests/carthage/App/PrivacyInfo.xcprivacy, dependency-manager-tests/carthage/App/ViewController.swift, dependency-manager-tests/carthage/CTProject.xcodeproj/project.pbxproj, dependency-manager-tests/cocoapods/App/PrivacyInfo.xcprivacy, dependency-manager-tests/cocoapods/App/ViewController.swift, dependency-manager-tests/cocoapods/CPProject.xcodeproj/project.pbxproj, dependency-manager-tests/spm/App/PrivacyInfo.xcprivacy, dependency-manager-tests/spm/App/ViewController.swift, dependency-manager-tests/spm/SPMProject.xcodeproj.src/project.pbxproj, dependency-manager-tests/xcframeworks/App/PrivacyInfo.xcprivacy, dependency-manager-tests/xcframeworks/App/ViewController.swift, dependency-manager-tests/xcframeworks/XCProject.xcodeproj/project.pbxproj
=> Release 2.7.1

DatadogCore/Tests/Matchers/SRRequestMatcher.swift, IntegrationTests/IntegrationScenarios/Scenarios/Core/StopCoreScenarioTests.swift, IntegrationTests/IntegrationScenarios/Scenarios/SessionReplay/SRMultipleViewsRecordingScenarioTests.swift, IntegrationTests/IntegrationTests.xcodeproj/project.pbxproj
- Fix Session Replay by ignoring Resource request payload
- Fix Stop Core Scenario (iOS 17) by waiting for all actions
=> Fix integration tests

DatadogCore/Sources/Core/Context/CarrierInfoPublisher.swift, DatadogCore/Sources/Core/DatadogCore.swift, DatadogCore/Sources/Datadog.swift, DatadogRUM/Sources/Debugging/RUMDebugging.swift, DatadogRUM/Sources/RUMVitals/VitalInfoSampler.swift, DatadogRUM/Sources/RUMVitals/VitalRefreshRateReader.swift, SUPPORTED-VERSIONS.md
Provides build time issue mitigations to enable compilation on VisionOS.
*This PR is not adding official VisionOS support - just resolves compilation issues in multi target environments.*
=> RUM-1958 Enable SDK compilation on VisionOS

DatadogCore/Tests/Datadog/Mocks/RUMDataModelMocks.swift, DatadogObjc/Sources/RUM/RUMDataModels+objc.swift, DatadogRUM/Sources/DataModels/RUMDataModels.swift, DatadogRUM/Sources/Integrations/CrashReportReceiver.swift, DatadogRUM/Sources/RUMMonitor/Scopes/RUMResourceScope.swift, DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift, DatadogRUM/Tests/Mocks/RUMDataModelMocks.swift
Includes changes for Errors (BinaryImages, Threads, new SourceTypes), new RUMVital object.
=> chore: Update RUM schema to most recent version

DatadogInternal/Tests/NetworkInstrumentation/NetworkInstrumentationFeatureTests.swift
=> Fix flakyness attempt

CHANGELOG.md
Adds missing change log for Resource Enpoint.
=> Add resource endpoint info in the `CHANGELOG.md`

DatadogObjc/Sources/RUM/RUMDataModels+objc.swift, DatadogRUM/Sources/DataModels/RUMDataModels.swift
Update RUM schema. This specifically updates the telemetry schema to add Unity version.
=> RUM-3237 Update RUM schema

CONTRIBUTING.md
📦 As we require all commits to be signed, this PR updates `CONTRIBUTING.md` with this note.
Updated `CONTRIBUTING.md`.
=> chore: Add signed commits requirement to CONTRIBUTING.md

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
git-flow: counterpart of #1732 
Fix `CHANGELOG`
=> Merge `release/2.8.0` to `develop`

CHANGELOG.md
Add PR links for the error mapping changes made.
=> doc: Add pull request links in CHANGELOG

CHANGELOG.md
Changelog entry was missed.
Added changelog.
=> RUM-1828 feat! (128 bit trace id) update changelog

Datadog/Example/Base.lproj/Main iOS.storyboard, Datadog/Example/Debugging/DebugOTelTracingViewController.swift, DatadogInternal/Sources/Upload/Event.swift
Just some manual testing
Add a button that sends span link.
Also, conformed Event to CustomDebugStringConvertible for some LLDB convenience.
=> feat(otel-tracer): add send span links in example app

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
=> Merge `release/2.10.0` to `develop` 

api-surface-objc, api-surface-swift
This PR updates API surface files for Swift and Objective-C, it wasn't done for a long time.
=> Update API surface files for Swift and Objective-C

CHANGELOG.md, Datadog/IntegrationUnitTests/Trace/HeadBasedSamplingTests.swift, DatadogCore/Tests/Datadog/TracerTests.swift, DatadogCore/Tests/Datadog/Tracing/TracingURLSessionHandlerTests.swift, DatadogCore/Tests/DatadogObjc/DDTracerTests.swift, DatadogInternal/Sources/NetworkInstrumentation/Datadog/HTTPHeadersReader.swift, DatadogInternal/Sources/NetworkInstrumentation/Datadog/HTTPHeadersWriter.swift, DatadogRUM/Tests/Instrumentation/Resources/URLSessionRUMResourcesHandlerTests.swift, DatadogTrace/Tests/TracingURLSessionHandlerTests.swift, IntegrationTests/IntegrationScenarios/Scenarios/RUM/RUMResourcesScenarioTests.swift, IntegrationTests/IntegrationScenarios/Scenarios/Tracing/TracingURLSessionScenarioTests.swift
Cherrypick https://github.com/DataDog/dd-sdk-ios/pull/1807
=> Cherrypick #1807 to 2.10.1

CHANGELOG.md, Datadog/IntegrationUnitTests/Trace/HeadBasedSamplingTests.swift, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCore/Tests/Datadog/TracerTests.swift, DatadogCore/Tests/Datadog/Tracing/TracingURLSessionHandlerTests.swift, DatadogCore/Tests/DatadogObjc/DDTracerTests.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogInternal/Sources/NetworkInstrumentation/Datadog/HTTPHeadersReader.swift, DatadogInternal/Sources/NetworkInstrumentation/Datadog/HTTPHeadersWriter.swift, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogRUM/Tests/Instrumentation/Resources/URLSessionRUMResourcesHandlerTests.swift, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogTrace/Tests/TracingURLSessionHandlerTests.swift, DatadogWebViewTracking.podspec, IntegrationTests/IntegrationScenarios/Scenarios/RUM/RUMResourcesScenarioTests.swift, IntegrationTests/IntegrationScenarios/Scenarios/Tracing/TracingURLSessionScenarioTests.swift, TestUtilities.podspec
- https://github.com/DataDog/dd-sdk-ios/pull/1810
=> Release 2.10.1

CHANGELOG.md, Datadog/IntegrationUnitTests/Trace/HeadBasedSamplingTests.swift, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
The develop branch went out of sync because the way we did the hotfix.
The timeline was
- hotfix merged to develop
- hotfix cherrypicked on top of 2.10.0 and 2.10.1 released by merging to master
- because develop already had the change, no merge was performed to develop
merge master to develop.
=> Merge 'master' into develop #1818

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCore/Tests/Datadog/Core/Upload/DataUploadWorkerTests.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
=> Merge `release/2.11.0` to `develop`

DatadogRUM/Sources/RUMMonitor/Monitor.swift
5.7 build failed in SPI https://swiftpackageindex.com/DataDog/dd-sdk-ios/builds
Scope correctly when weakifying self.
=> chore: fix Swift 5.7 issue with scoping

DatadogCore/Sources/Core/Upload/URLSessionClient.swift, DatadogCore/Sources/Kronos/KronosNTPClient.swift, DatadogCore/Tests/Datadog/RUM/RUMMonitorTests.swift, DatadogRUM/Sources/Integrations/WebViewEventReceiver.swift
⬆️ This PR updates our code for `swiftlint` 0.55.1.
Few rules trigger when using `0.55.1`, so I did necessary code changes.
=> chore: Update code for `swiftlint` 0.55.1

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
=> Merge `release/2.12.0` to `develop`

E2ETests/E2ETests.xcodeproj/project.pbxproj, E2ETests/Runner/Scenarios/SessionReplayWebView/SessionReplayWebView.storyboard, E2ETests/Runner/Scenarios/SessionReplayWebView/SessionReplayWebViewController.swift, E2ETests/Runner/Scenarios/SessionReplayWebView/SessionReplayWebViewScenario.swift
Complexify the Session Replay WebView scenario by defining navigation between webviews, both using a tabs and navigation-stack.
=> RUM-2814 E2E Scenario: Navigate through WebViews

Datadog/IntegrationUnitTests/Public/CoreTelemetryIntegrationTests.swift, DatadogCore/Tests/Datadog/Mocks/RUMDataModelMocks.swift, DatadogInternal/Sources/SDKMetrics/MethodCalledMetric.swift, DatadogObjc/Sources/RUM/RUMDataModels+objc.swift, DatadogRUM/Sources/DataModels/RUMDataModels.swift, DatadogRUM/Sources/FatalErrorBuilder.swift, DatadogRUM/Sources/Integrations/CrashReportReceiver.swift, DatadogRUM/Sources/Integrations/TelemetryReceiver.swift, DatadogRUM/Sources/RUMMonitor/Scopes/RUMViewScope.swift, DatadogRUM/Tests/Integrations/TelemetryReceiverTests.swift, DatadogRUM/Tests/Mocks/RUMDataModelMocks.swift
=> RUM-4133 Propagate device and os info to all metrics

DatadogInternal/Sources/Context/DeviceInfo.swift
Refactor of Sysctl broke the build and we don't have any mechanism to test in PRs, it was missed.
Fixed the build but we still don't have a good way to test in CI.
We can technically use 
```
xcodebuild build -scheme Datadog-Package -destination generic/platform=macOS | xcbeautify
```
or in short
```
make build-spm PLATFORM=macOS
```
to build for macOS but DatadogRUM is not supported for macOS for UIKit dependency and it fails, we need to find a better way to build for macOS without building RUM.
=> fix: macOS build broken due to refactoring of Sysctl

bitrise.yml
📦 🧰 Fixes dogfooding automation in Bitrise. It was broken in pending GitLab migration.
`make` become `make clean install` for dogfooding package.
=> chore: Fix dogfooding automation in Bitrise

CHANGELOG.md, DatadogObjc/Sources/RUM/RUMDataModels+objc.swift, DatadogRUM/Sources/DataModels/RUMDataModels.swift, DatadogRUM/Sources/DataModels/RUMDataModelsMapping.swift, TestUtilities/Mocks/DatadogContextMock.swift, api-surface-objc, api-surface-swift
Follow-up for https://github.com/DataDog/rum-events-format/pull/214: update RUM and telemetry schema.
=> RUM-5111: Update RUM and Telemetry models with KMP source

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
=> Merge release `2.14.0` to `develop`

CHANGELOG.md
https://github.com/DataDog/dd-sdk-ios/pull/1968 was merged with no changelog update
=> chore: Add missing CHANGELOG entry for #1968

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
git-flow counterpart of https://github.com/DataDog/dd-sdk-ios/pull/1971
=> Merge release `2.15.0` to `develop`

BenchmarkTests/Benchmarks/Sources/Benchmarks.swift, BenchmarkTests/Benchmarks/Sources/Metrics.swift, BenchmarkTests/Runner/AppDelegate.swift, BenchmarkTests/Runner/Scenarios/SyntheticScenario.swift
Collect CPU metrics during benchmarks.
=> RUM-5555 Benchmarks: Collect CPU Metric

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSDK.podspec, DatadogSDKAlamofireExtension.podspec, DatadogSDKCrashReporting.podspec, DatadogSDKObjc.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
=> Merge `release/2.16.0` to develop

CHANGELOG.md, DatadogCore/Sources/Core/Upload/DataUploadConditions.swift
Skip `networkReachability` check for uploading on watchOS.
ext contribution: #2005
=> fix: Always assume device is online on Apple Watch

DatadogInternal/Sources/NetworkInstrumentation/TraceID.swift
Fixes #2032 
Updated docs to match the trace id generation
=> gh-2032 chore: update TraceID docs to reflect the generation implementation

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
=> Merge release 2.17.0 to develop

CHANGELOG.md
Changelog wasn't super clear.
- make it clear that API is experimental
- make it clear the new required param is breaking change
=> Update CHANGELOG.md for view loading time API

BenchmarkTests/BenchmarkTests.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, BenchmarkTests/Runner/AppDelegate.swift, BenchmarkTests/Runner/Scenarios/SyntheticScenario.swift
Allow running benchmark scenario without measures so we can debug and define s8s tests without collecting data.
=> Benchmark: Allow run without measure

DatadogSessionReplay/Sources/Models/SRDataModels.swift, api-surface-objc, api-surface-swift
This PR brings schema change made in https://github.com/DataDog/rum-events-format/pull/223.
API surface was updated as well.
=> Update Session Replay schema with a Kotlin Multiplatform source for Mobile segment

docs/sdk_performance.md
We've measured performance and impact in the early stage of SDK v2, but unlike [Android](https://github.com/DataDog/dd-sdk-android/blob/develop/docs/sdk_performance.md), we never shared the report.
=> Add Performance Report

DatadogSessionReplay/Tests/Mocks/UIKitMocks.swift, DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/ViewTreeSnapshotTests.swift
Fix test flakiness introduced in #2083
Revert to previous fuzzy fixture.
=> chore: Fix test flakiness

tools/dogfooding/dogfood.sh
Redo: #2106
Update dependency in `/Tuist/Package.resolved`
=> chore: Fix dogfooding in mobile app

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
git-flow: counterpart of #2109
=> Merge `release/2.20.0` to `develop`

Datadog/Datadog.xcodeproj/project.pbxproj, DatadogInternal/Sources/NetworkInstrumentation/TracePropagationHeadersWriter.swift, DatadogInternal/Sources/Utils/Sampler.swift, DatadogInternal/Tests/Utils/DeterministicSamplerTests.swift
Implement an id based deterministic sampling. Next PR will make use of it for our tracing decisiong, allowing a more consistent APM implementation with other platform agents
=> RUM-6867 Implement id based deterministic sampling

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
=> Merge `release/2.21.0` to `develop`

DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDSessionReplay+apiTests.m, DatadogSessionReplay/Sources/SessionReplay+objc.swift, DatadogSessionReplay/Sources/SessionReplayConfiguration.swift, api-surface-objc, api-surface-swift
=> RUM-7316 Expose Session Replay SwiftUI Feature Flag to Objc

BenchmarkTests/SwiftUICatalog/Views/Sections/View Modifiers/EffectsModifiersView.swift
Silence console error, no impact on benchmarks
=> [Benchmarks] fix: Wrong bundle in SwiftUI scenario

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
=> Merge `release/2.23.0` to `develop`

BenchmarkTests/README.md
Updates the `README.md` of the Benchmark application to include the commands necessary to launch it.
=> RUM-8637 Update README of Benchmark application

BenchmarkTests/BenchmarkTests.xcodeproj/project.pbxproj, BenchmarkTests/BenchmarkTests.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, BenchmarkTests/Runner/AppConfiguration.swift, BenchmarkTests/Runner/Scenarios/Logs/LogsCustomScenario.swift, BenchmarkTests/Runner/Scenarios/Logs/LogsHeavyTrafficScenario.swift, BenchmarkTests/Runner/Scenarios/Logs/UI/LogsCustomContentView.swift, BenchmarkTests/Runner/Scenarios/Logs/UI/LogsHeavyTrafficContentView.swift, BenchmarkTests/Runner/Scenarios/Logs/UI/LogsUtils.swift, BenchmarkTests/Runner/Scenarios/SyntheticScenario.swift
To ensure our SDKs maintain optimal performance and do not introduce regressions, we will establish a robust benchmarking and testing framework. This will include performance benchmarks and end-to-end tests that run for every new release. This PR introduces new scenarios and UI to test the Logs feature.
Introduction of different scenarios that allows us to simulate logging in a real application.
A configurable scenario that allows to manually adjust parameters (log level, message, logs per batch, and payload size, ect) and trigger logging events on demand. This lets us test different configurations.
A scrolling scenario where each list item displays a heavy image (fetched from the Picsum API) and triggers logging events as it appears. This simulates a high-load environment where a stream …
=> RUM-8834 Logs Benchmark Scenario

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
git-flow: counterpart of #2220
=> Merge `release/2.24.0` to `develop`

DatadogInternal/Sources/NetworkInstrumentation/HostsSanitizer.swift, DatadogInternal/Tests/NetworkInstrumentation/HostsSanitizerTests.swift
Simplifes host sanitizing logic to include edge cases like `customprotocol://name`, which is valid swift `URL`.
Simplified regex and updated tests.
=> RUM-8931 Simplify host sanitizer logic

.gitlab-ci.yml, IntegrationTests/IntegrationScenarios/Scenarios/RUM/RUMTapActionScenarioTests.swift
=> RUM-7564 Update CI to Xcode 16.2

tools/license/check-license.sh
Fix License check failure introduced by #2247
=> fix: License check failure

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
=> Merge release/2.25.0 to develop

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
=> Merge `release/2.26.0` to `develop`

CHANGELOG.md, DatadogAlamofireExtension.podspec, DatadogCore.podspec, DatadogCore/Sources/Versioning.swift, DatadogCrashReporting.podspec, DatadogInternal.podspec, DatadogLogs.podspec, DatadogObjc.podspec, DatadogRUM.podspec, DatadogSessionReplay.podspec, DatadogTrace.podspec, DatadogWebViewTracking.podspec, TestUtilities.podspec
git-flow counterpart of: #2282
=> Merge `release/2.27.0` to `develop`

BenchmarkTests/Runner/AppConfiguration.swift
Fix build issue introduced by #2304 where `AnyDecoder` has been removed.
=> RUM-9461 Fix Benchmark build

CHANGELOG.md, DatadogRUM/Sources/RUMVitals/VitalMemoryReader.swift
This PR improves the collected value of the memory used by the application. 
The implementation collects the memory information from `phys_footprint`. 
This logic is in line with the suggestion shared on the public [thread](https://developer.apple.com/forums/thread/105088).
=> RUM-9493: Improve how Memory vital is collected

CHANGELOG.md, DatadogCore/Tests/Datadog/Core/DirectoriesTests.swift, DatadogCore/Tests/DatadogObjc/DDConfigurationTests.swift, DatadogInternal/Sources/Context/DatadogSite.swift, DatadogObjc/Sources/DatadogConfiguration+objc.swift, DatadogRUM/Tests/Feature/RequestBuilderTests.swift, DatadogSessionReplay/Tests/Feature/RequestBuilder/ResourceRequestBuilderTests.swift, DatadogSessionReplay/Tests/Feature/RequestBuilder/SegmentRequestBuilderTests.swift, TestUtilities/Sources/Mocks/DatadogInternal/DatadogContextMock.swift
Add support to AP2 DC
Add AP2 endpoints and tests
=> [RUM-10315] AP2 DC Support

DatadogInternal/Tests/NetworkInstrumentation/NetworkInstrumentationFeatureTests.swift
📦 ❄️ The test `testGivenURLSessionWithCustomDelegate_whenUsingCombineDataFromURL_itNotifiesInterceptor()` was occasionally failing due to the Combine subscription being deallocated too early. This caused the network interception callbacks to not be triggered consistently, resulting in flaky test behavior.
Stored the `sink` subscription in a local variable (`cancellable`) to ensure the Combine pipeline remains alive for the duration of the test. This guarantees that the interception lifecycle events are reliably triggered before expectations are asserted.
Tested with 100+ test reps in local ✅.
=> chore: Fix flakiness in Combine-based `NetworkInstrumentation` test

.gitlab-ci.yml
Add missing `id_tokens` to dogfooding jobs
=> RUM-10225 Fix Dogfooding token

.gitlab-ci.yml, DatadogRUM/Sources/Feature/RUMFeature.swift, DatadogRUM/Sources/RUMConfiguration.swift, DatadogRUM/Sources/RUMMonitor/Scopes/RUMScopeDependencies.swift, DatadogRUM/Tests/RUMMonitor/Scopes/RUMUserActionScopeTests.swift, DatadogRUM/Tests/RUMMonitor/Scopes/RUMViewScopeTests.swift, TestUtilities/Sources/Mocks/DatadogRUM/RUMFeatureMocks.swift
=> Merge `develop` to `feature/v3`

.github/workflows/stale.yml
Forgot to change the second label in #2393
=> Fix label in Stale Github Action

DatadogInternal/Sources/Models/RUM/RUMDataModels.swift, DatadogObjc/Sources/RUM/RUMDataModels+objc.swift
Updating RUM models to include latest schema changes, including a new type of Vital for User Stories.
`make rum-models-generate`
=> RUM-11031 Update RUM models with new Vital type and properties

tools/clean.sh
Fix typo preventing CI from cleaning Xcode derived-data.
=> Fix clean.sh

.github/dependabot.yml, .github/workflows/issue_notification.yml, .gitlab-ci.yml, Makefile, tools/issue_handler/.gitignore, tools/issue_handler/README.md, tools/issue_handler/integration_tests/test_analysis.py, tools/issue_handler/integration_tests/test_real_issue.py, tools/issue_handler/pytest.ini, tools/issue_handler/requirements.txt, tools/issue_handler/run_tests.sh, tools/issue_handler/setup_env.sh, tools/issue_handler/src/__init__.py, tools/issue_handler/src/analyze_issue.py, tools/issue_handler/src/github_handler.py, tools/issue_handler/src/openai_handler.py, tools/issue_handler/src/slack_handler.py, tools/issue_handler/test_local.py, tools/issue_handler/test_slack_webhook.py, tools/issue_handler/tests/test_analysis.py, tools/issue_handler/tests/test_github_handler.py, tools/issue_handler/tests/test_openai_handler.py, tools/issue_handler/tests/test_real_issue.py, tools/issue_handler/tests/test_slack_handler.py, tools/runner-setup.sh, tools/tools-test.sh
This PR introduces an automated GitHub issue handler that fetches issue details and posts notifications to Slack. This helps streamline issue triage and provides immediate visibility when new issues are opened. See [this doc](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/5134614893/Interruption+Handler+Assistant) (internal) for more.
- GitHub Action workflow (`.github/workflows/issue_notification.yml`) triggers on new issues and runs the analysis pipeline
- Python-based issue handler (`tools/issue_handler/`) with modular architecture:
-  `github_handler.py` - GitHub API integration for fetching issue details
-  `openai_handler.py` - Issue analysis
-  `slack_handler.py` - Webhook-based Slack posting
- Comprehensive testing with unit tests, integration tests, and local development …
=> Add workflow for Github issue notifications to Slack

DatadogCore/Tests/Datadog/RUM/TelemetryReceiverTests.swift, DatadogRUM/Tests/SDKMetrics/SessionEndedMetricControllerTests.swift, DatadogTrace/Tests/TraceTests.swift
Cherry-pick #2478 for `feature/profiling` to unlock builds
=> Update swiftlint 0.61.0 on `feature/profiling`

IntegrationTests/IntegrationScenarios/Scenarios/RUM/RUMFeatureOperationsScenarioTests.swift, IntegrationTests/IntegrationTests.xcodeproj/project.pbxproj, IntegrationTests/IntegrationTests.xcodeproj/xcshareddata/xcschemes/Runner iOS.xcscheme, IntegrationTests/Runner/Scenarios/RUM/Feature Operations/NextScreenViewController.swift, IntegrationTests/Runner/Scenarios/RUM/Feature Operations/RUMFeatureOperationsScenario.storyboard, IntegrationTests/Runner/Scenarios/RUM/Feature Operations/RUMFeatureOperationsViewController.swift, IntegrationTests/Runner/Scenarios/RUM/RUMScenarios.swift, IntegrationTests/xctestplans/RUM.xctestplan, TestUtilities/Sources/Matchers/RUMSessionMatcher.swift
This PR adds integration tests for Feature Operations. Scenarios tested:
- basic start & stop operations
- parallel instances
- failure scenarios
- cross-view operations
- Added a new `RUMFeatureOperationsScenario`
- Extended `RUMSessionMatcher` to include vital events
| Main screen | 2nd screen |
|--------|--------|
| <img width="1206" height="2622" alt="Simulator Screenshot - iPhone 16 Pro - 2025-09-19 at 14 34 22" src="https://github.com/user-attachments/assets/3a58d7cf-efc4-49c9-abe5-1234287fe357" /> | <img width="1206" height="2622" alt="Simulator Screenshot - iPhone 16 Pro - 2025-09-19 at 14 34 27" src="https://github.com/user-attachments/assets/8f277de2-90d1-4b7f-b278-6f2350aa7c14" /> |
=> RUM-11034 FO Add integration tests
